### ISSUE TITLE
[Feature Request] Update Gradle version to 6.6

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-android#1028]
# Feature Request

## Motivation Behind Feature

The Gradle 6.6 has been released, it is good to implement this new version to Cordova Android.

## Feature Description

This release introduces a major performance optimization as an experimental opt-in. Configuration caching allows Gradle to skip the configuration phase of the build and start executing tasks as soon as possible.

Other improvements in this release include conventions for handling user-provided credentials, support for Java compilation --release flag, and a number of other improvements and bug fixes.

**Comment by breautek** [comment]
In general, it's always nice to keep up to date with the latest patch so I give my :+1: and I'll support a PR that upgrades gradle to 6.5.1 but a couple of notes:

Cordova generally doesn't support experimental features, so I don't foresee us interfacing with this feature at this time. Of course, this doesn't mean that the end-user cannot enable the feature themselves once 6.5.1 is used.

The security fix mentioned in 6.5.1 actually landed in 6.5, which you can see if you click on the link for more details at https://docs.gradle.org/6.5.1/release-notes.html#security or by viewing the actual [CVE](https://github.com/gradle/gradle/security/advisories/GHSA-ww7h-4fx5-8c2j), so `cordova-android@9` is already using the patched gradle version.

**Comment by mosabab** [comment]
> In general, it's always nice to keep up to date with the latest patch so I give my 👍 and I'll support a PR that upgrades gradle to 6.5.1 but a couple of notes:
> 
> Cordova generally doesn't support experimental features, so I don't foresee us interfacing with this feature at this time. Of course, this doesn't mean that the end-user cannot enable the feature themselves once 6.5.1 is used.
> 
> The security fix mentioned in 6.5.1 actually landed in 6.5, which you can see if you click on the link for more details at https://docs.gradle.org/6.5.1/release-notes.html#security or by viewing the actual [CVE](https://github.com/gradle/gradle/security/advisories/GHSA-ww7h-4fx5-8c2j), so `cordova-android@9` is already using the patched gradle version.

Thanks for reply,

I don't foresee from cordova developers to Add Gradle 6.5.1 to Cordova Android for now.

Recently I found that Gradle has a new version, so, I just open this request to let All Cordova-Android Developers know to keep cordova-android updated to latest features of any required tools that needed to build Android Apps.

Regards

**Comment by alexhaller** [comment]
Gradle 6.6 is out! Are you checking updating to this version?

**Comment by mosabab** [comment]
> Gradle 6.6 is out! Are you checking updating to this version?

I will change the title of this to 6.6
