### ISSUE TITLE
angular cordova application html5 video tag does not play on android

### ISSUE THREAD

**Issue by rajendrarama** [apache/cordova-android#1029]
I have an angular cordova application which has got the html video tag that plays on IOS but not on Android. Play button does not show on android.

html tag is as below:

```
<video width="320" height="240" controls="controls">
<source src="samplevideolink" type="video/mp4" />
</video>
```

config.xml of Cordova is as below:
```

<content src="index.cordova.html" />
<plugin name="cordova-plugin-whitelist" spec="1" />
<access origin="*...." />
<allow-intent href="...." />
<allow-intent href="..." />
<platform name="android">
<allow-intent href="market:*" />
<icon src="assets/android/ldpi.png" density="ldpi" />
<icon src="assets/android/mdpi.png" density="mdpi" />
<icon src="assets/android/hdpi.png" density="hdpi" />
<icon src="assets/android/xhdpi.png" density="xhdpi" />
<icon src="assets/android/xxhdpi.png" density="xxhdpi" />
<icon src="assets/android/xxxhdpi.png" density="xxxhdpi" />
</platform>
<platform name="ios">
....
<preference name="webviewbounce" value="false" />
<preference name="UIWebViewBounce" value="false" />
<preference name="DisallowOverscroll" value="true" />
<preference name="android-minSdkVersion" value="23" />
<preference name="BackupWebStorage" value="none" />
```

Not sure if there is a problem withany configuration specific to Android in Cordova. Is there any plugin specific to Android Cordova need to be installed

Really appreciate your help.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
