### ISSUE TITLE
Apk parsing error while using cordova build -release 

### ISSUE THREAD

**Issue by sreenumalae** [apache/cordova-android#1030]
Hello Everyone,

In my moodle project when I use 
`cordova build android`

The debug apk builds perfectly and it works as expected 

when it comes to 
`cordova build android --release`

It builds release unsigned apk successfully but when I'm trying to install. I'm getting an error
**Could not parse error string**

**Comment by breautek** [comment]
You cannot install unsigned apks (the android sdk signs debug builds for you, which is by debug builds work).

You have to sign release builds yourself. Start [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#signing-an-app) to learn how to sign APKs.

If you require more assistance, [slack](http://slack.cordova.io/) is a more appropriate place for questions such as this. We use GitHub issues is for tracking bugs.
