### ISSUE TITLE
redirections from the app redirects to browser

### ISSUE THREAD

**Issue by ctaque** [apache/cordova-android#1032]
Hello,
My apps consits in a redirection to a website.
In previous apps I did, when I did the redirection it opened the website in the app, not in the browser.
To do the last one I upgraded cordova, gradle and android-studio.

Which version do I need to open the website in the app ?

Thanks in advance

**Comment by breautek** [comment]
You should use the [in-app browser](https://github.com/apache/cordova-plugin-inappbrowser) plugin if you want to view a website in your app.

Redirecting the main app webview to load an external website is not recommended and produces a security risk for your users. See our [security notes](https://cordova.apache.org/docs/en/latest/guide/appdev/security/index.html#use-inappbrowser-for-outside-links) for more info.
