### ISSUE TITLE
Android building broken: Unable to open asset URL: file:///android_asset/www/cordova_plugins.js

### ISSUE THREAD

**Issue by brunoPert** [apache/cordova-android#1033]
# Bug Report

## Problem
While  building and running my cordova app inside  emulator (also in phone), the apk is successfully installed but breaks when oppening, returning only a wide screen:

### What is expected to happen?

The app should open in the first view. 

### What does actually happen?

A white screen appears, plus the following message in android studio logcat:

![Captura de Pantalla 2020-07-22 a la(s) 12 34 25](https://user-images.githubusercontent.com/49445815/88196608-c8005300-cc17-11ea-951b-98da5eee72cc.png)

### Environment, Platform, Device

Im trying this in mac os and in linux mint too, with same result in both. 

What are relevant versions you are using?

cordova version: 9.0.0 (cordova-lib@9.0.1)
"cordova-android": "8.1.0",

**Comment by jkaw** [comment]
This happened to me as well. It seems that when Cordova Android 9.0.0 is installed, the plugins are not added properly. Thus, the cordova-plugins.js file is not created on the Cordova add android@9.0.0 command. If you check your platforms/android/platform_www folder, it will be missing the Cordova-plugins.js file and the plugins folder. I had to re add all my plugins manually (Cordova plugin rm/add) to get those files to generate.

**Comment by jkaw** [comment]
I should add that I did a 'cordova platform rm android' and 'cordova platform add android@9.0.0' multiple times, and each time there was no cordova-plugins.js file or plugins folder created in my platform_www folder.

**Comment by brunoPert** [comment]
Thanks! It did the trick. After adding all plugins plus removing and adding android plaform, could build again.

**Comment by awexfwex** [comment]
The above isn't a fix, its a workaround. Manually removing and re-adding all the plugins each time isn't ideal. Any chance we could re-open this?

**Comment by breautek** [comment]
> The above isn't a fix, its a workaround. Manually removing and re-adding all the plugins each time isn't ideal. Any chance we could re-open this?
> 
> Another workaround would be to rm -rf plugins directory as part of a clean build step

Are you reproducing this using `cordova@10` / `cordova-android@9` ?? If so, I think this does warrant a reopen.

**Comment by awexfwex** [comment]
> Are you reproducing this using `cordova@10` / `cordova-android@9` ?? If so, I think this does warrant a reopen.

No, this is using cordova@9. I'll try reproing on cordova@10 once i've got the next release out and it's safe to tinker with it
