### ISSUE TITLE
After upgrading to cordova-android@9.0.0, FileReader.readAsArrayBuffer stopped working

### ISSUE THREAD

**Issue by maxymczech** [apache/cordova-android#1034]
# Bug Report

### What is expected to happen?

I expect this code to read my file, it worked fine in `cordova-android@8.1.0`:

```
const reader = new FileReader();
reader.onloadend = function() {
  ...
}
reader.readAsArrayBuffer(file);
```

### What does actually happen?

Read fails with `ERROR_CODE: 1`

## Information
I run application on Samsung A90, running Android 10

### Command or Code
```
const reader = new FileReader();
reader.onloadend = function() {
  ...
}
reader.readAsArrayBuffer(file);
```

### Environment, Platform, Device
I run application on Samsung A90, running Android 10

### Version information
`cordova-android@9.0.0`

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
how does the file path looks like?

On Android 10 there are certain paths that are no longer accessible, but only happens if the app targets SDK 29, which cordova-android 9 does, so that could be the issue.

**Comment by maxymczech** [comment]
I think starts with `cdvfile://localhost/persistent/`

**Comment by jcesarmobile** [comment]
I was expecting a file:// url, not a cdvfile:// url. Can you share your code?

**Comment by breautek** [comment]
Closing as stale.
