### ISSUE TITLE
'@netflix/nerror@^1.1.3' is not in the npm registry.

### ISSUE THREAD

**Issue by feiandytan** [apache/cordova-android#1039]
# Bug Report

## Problem
I am trying to add platform android@9.0.0, but failed with the error: '@netflix/nerror@^1.1.3' is not in the npm registry.

### Command or Code

```
cordova create test1
cd test1
cordova platform add android@9.0.0
```
Running above command will get following output:
```
Using cordova-fetch for cordova-android@9.0.0
Failed to fetch platform cordova-android@9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@netflix%2fnerror - Not found
npm ERR! 404
npm ERR! 404  '@netflix/nerror@^1.1.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'cordova-common'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\i062893\AppData\Roaming\npm-cache\_logs\2020-08-06T10_01_47_909Z-debug.log
```

### Version information

OS: Windows10
cordova: 9.0.0 (cordova-lib@9.0.1)
node: v12.18.3

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
Duplicate: https://github.com/apache/cordova-common/issues/149

NPM is currently having an issue. https://status.npmjs.org/

**Comment by erisu** [comment]
Sorry correction, the duplicate linked issue is not exactly a complete duplicate but the ticket contains a response to the actual  current issue you have reported here.

Link to exact reponse:
https://github.com/apache/cordova-common/issues/149#issuecomment-669816061

In the mean time, please monitor the npmjs registry status and try again after they have resolved the issue.
