### ISSUE TITLE
unable to load platformApi from platform when adding android platform v9.0.0

### ISSUE THREAD

**Issue by yuanzuo** [apache/cordova-android#1067]
cordova version: 

>cordova -v
9.0.0 (cordova-lib@9.0.1)

Error: 
>cordova platform add android@9.0.0
Using cordova-fetch for cordova-android@9.0.0
Adding android project...
Unable to load PlatformApi from platform. SyntaxError: Unexpected token {
Unhandled "error" event. (The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.)

Is there any prerequisite to add cordova-android 9.0.0? Anyone has same issue as I got? 
How to fix this?

Thanks!

**Comment by breautek** [comment]
> Unable to load PlatformApi from platform. SyntaxError: Unexpected token {

This suggests you're using an incompatible NodeJS version. The minimum supported version of Node is 10, but 12 is recommended as it's the current LTS release.

With any major version of node, it is also recommended to use the latest patch available, which for Node 12, is currently Node 12.18.3.

**Comment by yuanzuo** [comment]
this issue can be closed. I am able to add cordova-android v9 after upgrading node.js to v12.8.4
