### ISSUE TITLE
cordova android v9 - build failure - unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by yuanzuo** [apache/cordova-android#1075]
# Bug Report
upgraded my project to cordova-android 9.0 from android 8.
Upgraded CLI to Cordova 10.
upgraded node.js to v12.18.4
upgraded java 8 to patch 261

## Problem
android build failed the error: unable to find valid certification path to requested target

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.72.

### What is expected to happen?
Build Should be successful.

### What does actually happen?
build failed the error: unable to find valid certification path to requested target

## Information

see above.
I got this error in command line and in Android Studio (v3.1.4)

### Command or Code

>cordova build android

### Environment, Platform, Device

Windows 10. Cordova v10. Gradle 6.5. Cordova-android v9.0

### Version information
Windows 10. Cordova v10. Gradle 6.5. Cordova-android v9.0

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by timbru31** [comment]
This looks like some network hiccups or proxy issues. Can you test it again or with another/different network?

**Comment by yuanzuo** [comment]
Initially I thought it is caused by company network VPN. But it still fails if it was run outside company network. 
I also tried using another wifi than home wifi, no luck.

**Comment by timbru31** [comment]
Very weird, but sadly not an issue we can solve given the fact that gradle itself has problems to reach a specific URL.

Your antivirus program might be the culprit, too, some install custom SSL certificates and try to intercept SSL traffic. Your Java installation might be too old, too and does not trust the GeoTrust RSA CA 2018 which Bintray uses.
