### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by videmort** [apache/cordova-android#1087]
# Bug Report
In master version the icon of the app is not showing.

## Problem
Icon of app not showing (shows cordova default)

### What is expected to happen?
Show icon declared in the config.xml

## Information
cordova-android master version (nightly)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
