### ISSUE TITLE
Cordova is not building application

### ISSUE THREAD

**Issue by yegender124001** [apache/cordova-android#1096]
## Description
I am making an Android application and new to here. I have installed Visual Studio Code 2017. When I tried to install in my device there are most of the error came. My Output is the below:
`
1>------ Build started: Project: LernoCode, Configuration: Debug Android ------
Cordova 6.3.1
------ Platform android already exists
------ Copying native files from C:\Users\yegen\source\repos\LernoCode\LernoCode\res\native\android to C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android
------ Done copying native files to C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android
------ Preparing platform: android
  ____              _                                                       
 / ___|___  _ __ __| | _____   ____ _   _ __  _ __ ___ _ __   __ _ _ __ ___ 
|  |   / _ \| '__/ _` |/ _ \ \ / / _` | | '_ \| '__/ _ \ '_ \ / _` | '__/ _ \
|  |__| (_) | | | (_| | (_) \ V / (_| | | |_) | | |  __/ |_) | (_| | | |  __/
 \____\___/|_|  \__,_|\___/ \_/ \__,_| | .__/|_|  \___| .__/ \__,_|_|  \___|
                                       |_|            |_|                   
-----------------------------------------------------------------------------
Running Cordova prepare on the project
-----------------------------------------------------------------------------

You have been opted out of telemetry. To change this, run: cordova telemetry on.
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml for saved platforms that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\res\xml\config.xml
Merging project's config.xml into platform-specific android config.xml
Found "merges/android" folder. Copying its contents into the android project.
Merging and updating files from [www, platforms\android\platform_www, merges\android] to platforms\android\assets\www
  delete platforms\android\assets\www\VSBuildInfo.xml (no source)
Wrote out android application name "LernoCode" to C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\res\values\strings.xml
Wrote out Android package name "io.cordova.myapp5c9f4c" to C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\src\io\cordova\myapp5c9f4c\MainActivity.java
Updating icons at platforms\android\res
Updating splash screens at platforms\android\res
Prepared android project successfully
No scripts found for hook "after_prepare".
Checking config.xml for saved plugins that haven't been added to the project
------ Building platform: android
------ Build configuration options:  --debug --

You have been opted out of telemetry. To change this, run: cordova telemetry on.
No scripts found for hook "before_compile".
ANDROID_HOME=C:\ProgramData\Microsoft\AndroidSDK\25
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_261
Reading build config file: C:\Users\yegen\source\repos\LernoCode\LernoCode\build.json
Running command: cmd "/s /c "C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true""
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M
Downloading http://services.gradle.org/distributions/gradle-2.13-all.zip

Command finished with error code 1: cmd /s /c "C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\yegen\source\repos\LernoCode\LernoCode\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
1>MSBUILD : cordova-build error : Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.13-all.zip
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install.createDist(Install.java:47)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
1>MSBUILD : cordova-build error : Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.13-all.zip
1>MSBUILD : cordova-build error :  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
1>MSBUILD : cordova-build error :  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Download.download(Download.java:45)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install$1.call(Install.java:60)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install$1.call(Install.java:47)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
1>MSBUILD : cordova-build error :  ... 3 more
1>MSBUILD : cordova-build error : Error: cmd: Command failed with exit code 1 Error output:
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M
1>MSBUILD : cordova-build error : Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.13-all.zip
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install.createDist(Install.java:47)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
1>MSBUILD : cordova-build error : Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.13-all.zip
1>MSBUILD : cordova-build error :  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
1>MSBUILD : cordova-build error :  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Download.download(Download.java:45)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install$1.call(Install.java:60)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.Install$1.call(Install.java:47)
1>MSBUILD : cordova-build error :  at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
1>MSBUILD : cordova-build error :  ... 3 more
1>Done building project "LernoCode.jsproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

`

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by breautek** [comment]
> Cordova 6.3.1

Additionally, the OP is running an unsupported version of cordova-android & cordova-cli.

> HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.13-all.zip

I don't remember which cordova-android version used gradle 2 but it would be ancient.
