### ISSUE TITLE
After change the bundle identifier I get an error

### ISSUE THREAD

**Issue by JosefJezek** [apache/cordova-android#1109]
# Bug Report

### What is expected to happen?

```
cordova platform rm android
cordova platform add android
```
I change bundle identifier in config.xml from `com.example` to `com.example.dev`
```
cordova prepare android
cordova-plugin-androidx-adapter: Processed 14 Java source files in 329ms
cordova-plugin-androidx: Updated gradle.properties to enable AndroidX

cordova prepare android
cordova-plugin-androidx-adapter: Processed 14 Java source files in 329ms
cordova-plugin-androidx: Updated gradle.properties to enable AndroidX
```

### What does actually happen?

```
cordova platform rm android
cordova platform add android
```
I change bundle identifier in config.xml from `com.example` to `com.example.dev`
```
cordova prepare android
cordova-plugin-androidx-adapter: Processed 14 Java source files in 329ms
cordova-plugin-androidx: Updated gradle.properties to enable AndroidX

cordova prepare android
No Java files found that extend CordovaActivity.
```

### Version information

```
Ubuntu 20.04.1 
"cordova": "^10.0.0",
"cordova-android": "^9.0.0",
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Currently If you want to change the bundle id, you must remove the platform and then re-add it.

I think this should be documented and better error feedback should be provided, so I'll leave this open. Or better, make Cordova tooling just handle bundle id changes, but I think that is an easier said than done kind of action, especially with other platforms.

**Comment by JosefJezek** [comment]
ok, please add the handler to Cordova CLI...

**Comment by cmartinezv** [comment]
Which version I have to use to don't have this error anymore ?. Seems it deletes de MainActivity.java when the bundle id is different.

**Comment by lucasdavila** [comment]
This started happening to me too, after I upgrades to cordova cli 10.0.0

**Comment by 13sergy** [comment]
Me too... after I upgraded to cordova cli 10.0.0 this started happening. I have 5 diferent bundle id working perfectly in cordova 8

MainActivity.java is deleted and cordva is not able to create in the new path parsed from my new bundle. 

Solution... I have to delete platform and add it again.

### Version information

```
Windows 10
"cordova": "^10.0.0",
"cordova-android": "^9.0.0",
```

**Comment by yaciine01** [comment]
Any solutions pls ??

**Comment by wedgberto** [comment]
> Which version I have to use to don't have this error anymore ?. Seems it deletes de MainActivity.java when the bundle id is different. It should update or create the correct MainActivity according to the bundle id.

cordova-android@8.1.0 does not have this bug - see my comments in the commit that broke this https://github.com/apache/cordova-android/commit/3712619f5cd3de5055336e87bfade2bc2407900d#r43030914

**Comment by Fourie-r** [comment]
@cmartinezv This was working properly on android version 8.1.0 for me it broke after updating to v9.1.0 and apparently has been push forward to v10.0

**Comment by breautek** [comment]
Duplicate: https://github.com/apache/cordova-android/issues/1139
