### ISSUE TITLE
resource mipmap/con (aka com.company name.phone word:mipmap/icon) not found.

### ISSUE THREAD

**Issue by svitalij1983** [apache/cordova-android#1110]
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.phoneword" android:installLocation="auto">
  <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="26" />
  <uses-permission android:name="android.permission.CALL_PHONE" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <application android:label="Phoneword.Android" android:theme="@style/MainTheme" android:icon="@mipmap/launcher_foreground" android:name="android.app.Application" android:allowBackup="true" android:debuggable="true">
    <activity android:configChanges="orientation|screenSize" android:icon="@mipmap/con" android:label="PhoneWord" android:theme="@style/MainTheme" android:name="crc64bc4bc45b5b32d53b.MainActivity">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by erisu** [comment]
Closing Ticket as Incomplete
