### ISSUE TITLE
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-android#1115]
# Bug Report
There's a warning when building android project for a long time now:
`Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
## Problem
This warning might not be true as the date passed, but there's no real reason it should be there I guess...
### What is expected to happen?
There's shouldn't be a warning.

### What does actually happen?
Nothing really, everything is working, but still, a warning is a warning and I think it should be removed if possible...

## Information
Build the following project for example:
https://github.com/IsraelHikingMap/Site/tree/master/IsraelHiking.Web

### Command or Code
`cordova run android`

### Environment, Platform, Device
Windows 10 pro, any android device.

### Version information
both on cordova 9 and cordova-android 8.1
and cordova 10 and conrdova-android 9

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
`cordova-android` don't use `compile`.

I cloned your repo so that I could scan your project and found that it's caused by [@mauron85/cordova-plugin-background-geolocation](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/android/dependencies.gradle) plugin.

**Comment by HarelM** [comment]
@breautek thanks for the info!
I have a fork of this unmaintained repo, I'll fix it there.
https://github.com/HarelM/cordova-plugin-background-geolocation
I'm guessing that the file that is causing the violation is the following, right?
https://github.com/HarelM/cordova-plugin-background-geolocation/blob/master/android/dependencies.gradle
I'm not sure how to fix this.
The following article suggests to simply replace compile with implementation, is this the right solution?
https://tomgregory.com/gradle-implementation-vs-compile-dependencies/#:~:text=The%20compile%20dependency%20configuration%20is,the%20same%20functionality%20as%20compile.&text=You%20should%20always%20use%20implementation,as%20compile%20is%20now%20deprecated.

**Comment by breautek** [comment]
In most cases I think changing `compile` to `implementation` will work.

ie: `implementation 'com.github.tony19:logback-android:1.1.1-9'`

**Comment by HarelM** [comment]
@breautek thanks! I'll give it a try.
