### ISSUE TITLE
Cordova app can not be launched in Android 11

### ISSUE THREAD

**Issue by nilecherry** [apache/cordova-android#1116]
# Bug Report
Cordova app can not be launched in Android 11
## Problem
It occurs NoClassDefFoundError: Failed resolution of: Lorg/apache/cordova/CordovaActivity and the app can not be launched.

**Comment by nilecherry** [comment]
![Uploading a11.png…]()

**Comment by timbru31** [comment]
Please actually fill out the issue template. With such little information we can't help you.

**Comment by PeterHdd** [comment]
Hi, 

Does cordova-android 9.0.0 support android 11?

**Comment by breautek** [comment]
> Does cordova-android 9.0.0 support android 11?

`cordova-android@9` technically supports up to API 29 (Android 10). You can use target SDK 29 (the default target when using `cordova-android@9`) and still run apps on Android 11.

You can _probably_ target API 30 but mileage may vary depending on plugins.
