### ISSUE TITLE
Loading images (src)

### ISSUE THREAD

**Issue by phoenixVS** [apache/cordova-android#1119]
# Bug Report

## Problem
When bundling with create-react-app, <img /> tags with src from import (ES6 Modules), the image doesn't load in cordova build on every platform :(

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
