### ISSUE TITLE
How to include the setting to change storage location?

### ISSUE THREAD

**Issue by andreszs** [apache/cordova-android#1121]
Starting with Android 7 or 8, certain apps include a button to change the app's **storage location** from Internal to SD, as follows:

![image](https://user-images.githubusercontent.com/10298071/98820149-8edd3000-240c-11eb-95b7-705a3c91cc71.png)

Our Cordova 9.0.0 apps do not feature this **Change** button, is there some `config.xml` setting, or plugin to enable this option?

**Comment by breautek** [comment]
There's no explicit option to enable it, but [<edit-config>](https://cordova.apache.org/docs/en/12.x/plugin_ref/spec.html#edit-config) (docs are for `plugin.xml`, but `edit-config` can also be used in `config.xml`) directive can modify the manifest to allow external installation. The android default is to use internal storage only, and for most apps that would be preferable.

You can read https://developer.android.com/guide/topics/data/install-location for the caveats of external-storage installed apps.
