### ISSUE TITLE
Cordova build failing with Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.1.error

### ISSUE THREAD

**Issue by SupriyaLakamsani** [apache/cordova-android#1122]
When I try to build cordova apk it is failing with below error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all artifacts for configuration ':CordovaLib:classpath'.
   > Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.1.
     Required by:
         project :CordovaLib
      > Could not resolve com.github.dcendents:android-maven-gradle-plugin:2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/github/dcendents/android-maven-gradle-plugin/2.1/android-maven-gradle-plugin-2.1.pom'.
            > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/com/github/dcendents/android-maven-gradle-plugin/2.1/android-maven-gradle-plugin-2.1.pom?referrer'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Command failed with exit code 1: C:\My_Files\MobileApps\EmployeeApp\platforms\android\gradlew clean -b C:\My_Files\MobileApps\EmployeeApp\platforms\android\build.gradle

**Comment by timbru31** [comment]
Please make sure your client trusts the Amazon Root CA 1 - this is not an issue with Cordova but your machine. Visiting https://repo.jfrog.org/artifactory/libs-release-bintray/com/github/dcendents/android-maven-gradle-plugin/2.1/ in the browser might yield more useful information for you.

It's recommended to upgrade to the latest available JDK8 release (currently update 8u271, too, as this might be culprit, too.
