### ISSUE TITLE
Failed to fetch platform cordova-android@^9.0.0 Probably this is either a connection problem, or platform spec is incorrect.

### ISSUE THREAD

**Issue by Vulisha** [apache/cordova-android#1131]
Hi, 
This stopped working for some reason, tried to update nodeJs and it did not help:
```
cordova platform add android
Using cordova-fetch for cordova-android@^9.0.0
Failed to fetch platform cordova-android@^9.0.0
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
CordovaError: TypeError: Cannot assign to read only property 'valueOf' of object '[object Object]'

```
I googled whole of internet and no solution helps. It works perfectly on other PC. I have connection to npm. 

cordova platform list
Installed platforms:

Available platforms:
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  windows ^7.0.0

Tried with nodejs 12 and 14, does not help. Tried npm cache clean --force, does not help. I have absolutely no more idea what is wrong as error details are pretty scarce with error...

**Comment by vamsiinspace** [comment]
its a permission issue on mac os.
Use :sudo cordova platform add android

**Comment by Vulisha** [comment]
Hi, 

thanks on a tip, but unfortunately it is Windows 10 PC and everything was working 2 weeks ago, and then probably some updates happened? And I have no more Idea what to check anymore.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by breautek** [comment]
Reinstall cordova. See https://github.com/apache/cordova-cli/issues/543 for why.
