### ISSUE TITLE
Implement 'WebViewAssetLoader'

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-android#1135]
We could consider loading the web content with `WebViewAssetLoader` as an alternative to the `file:` protocol.

I tried to implement this in a webview plugin and it worked quite good. Further testing needs to be done.

See https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/629

**Comment by haslinghuis** [comment]
As long there are no better alternatives it's ok. Also see https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/629
