### ISSUE TITLE
Cordova is returning an error when trying to build android even if I changed nothing

### ISSUE THREAD

**Issue by fabrizio03** [apache/cordova-android#1144]
I am writing a small app in cordova and everything was working fine until yesterday when I tried to run `cordova build android --release`
Since then I always get this when I try to build for android:

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\android\Sdk (recommended setting)
ANDROID_HOME=C:\android\Sdk (DEPRECATED)
Using Android SDK: C:\android\Sdk
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: failed writing to 'C:\Users\Inspiron 15\Desktop\project\platforms\android\app\build\intermediates\runtime_symbol_list\debug\R.txt': Invalid Data. (13).



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
26 actionable tasks: 26 executed
Command failed with exit code 1: C:\Users\Inspiron 15\Desktop\project\platforms\android\gradlew cdvBuildDebug -b C:\Users\Inspiron 15\Desktop\project\platforms\android\build.gradle
```

I am on windows 10, using cordova 10.0.0.
The only plugins for the moment are:
  cordova-plugin-file
  cordova-plugin-whitelist

I have tried to uninstall and reinstall gradle (trying both 6.1.1 and 6.5), to remove and add again android platform and I also started a new project but nothing changed.

Update:

android version: 9.0.0
latest build-tools installed (in ANDROID_HOME/build-tools/): 30.0.2

**Comment by breautek** [comment]
Try running `cordova clean android` 

This will delete your intermediates. Then you can try rebuilding. If it doesn't work -- I'll need a bit more information.

- I'll need your `cordova-android` version (obtainable via `cordova platform ls`)
- The build tools version you're using (Should be in your `PATH` somewhere.. e.g: `%ANDROID_HOME%/build-tools/<version>/`
- - If not in your path, then you can check the android SDK Manager for what build tools versions is installed.

**Comment by fabrizio03** [comment]
I updated my question, the latest build-tools version installed is 30.0.2, but I also have some older versions in `%ANDROID_HOME%/build-tools/` (28.0.2, 29.0.2, 30.0.0)

**Comment by breautek** [comment]
> I updated my question, the latest build-tools version installed is 30.0.2, but I also have some older versions in `%ANDROID_HOME%/build-tools/` (28.0.2, 29.0.2, 30.0.0)

I would try to remove the older versions from your path, you should really only have one build-tools version in your path. Depending on the order, you may be using an older version which might be incompatible with modern versions.  `cordova-android@9` is tested and expects `29.0.2` but in my experience `30` still works.

**Comment by fabrizio03** [comment]
I removed all the older versions but nothing changed.

**Comment by breautek** [comment]
Can you paste me the results of `C:\Users\Inspiron 15\Desktop\project\platforms\android\app\build\intermediates\runtime_symbol_list\debug\R.txt` ?

I've reproduced your setup and it builds fine for me on a newly created app. This is the contents of my `R.txt` file:

```
int drawable screen 0x7f010000
int mipmap ic_launcher 0x7f020000
int mipmap ic_launcher_background 0x7f020001
int mipmap ic_launcher_foreground 0x7f020002
int string activity_name 0x7f030000
int string app_name 0x7f030001
int string launcher_name 0x7f030002
int xml config 0x7f040000
```

**Comment by fabrizio03** [comment]
I believe that the file R.txt isn't even created in my case

**Comment by fabrizio03** [comment]
I finally found out what happened: Avast was blocking R.txt creation and editing and of course I received no notification... I solved my problem by temporarily disabling Avast.

**Comment by ZAHHAR-ISMAIL** [comment]
I solve it by uninstalling the antivirus.

**Comment by ZAHHAR-ISMAIL** [comment]
I solve it by uninstalling the antivirus.
