### ISSUE TITLE
Press the backbutton at first and the 'backbutton' event is not fired ?

### ISSUE THREAD

**Issue by 75341704** [apache/cordova-android#1146]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x ] Support Question

## Description
I use the code about 'backbutton' hereunder
https://cordova.apache.org/docs/en/latest/cordova/events/events.html

Hereunder is operation sequence.
The app is loaded and there is no further interaction in the app.
And then the backbutton is pressed at first. 
The 'backbutton' event is not fired and the app is exited.

But after the app is loaded and some interaction is done , the 'backbutton' event is fired and listener is working.

Please kindly check whether it is ok or not.

## Information

<!DOCTYPE html>
<html>
    <head>
    <title>Device Ready Example</title>
    <script type="text/javascript" charset="utf-8" src="cordova.js"></script>
    <script type="text/javascript" charset="utf-8" src="example.js"></script>
    </head>
    <body onload="onLoad()">
    </body>
</html>
// example.js file
// Wait for device API libraries to load
//
function onLoad() {
    document.addEventListener("deviceready", onDeviceReady, false);
}

// device APIs are available
function onDeviceReady() {
    document.addEventListener("backbutton",onBackButton, false);
    // Add similar listeners for other events
}

function onBackButton() {
    // Handle the pause event
}
## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
