### ISSUE TITLE
Android bundle package could not be produced using cordova build android --release

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-android#1151]
# Bug Report

### What is expected to happen?
It should generate android bundle package without any problems.

### What does actually happen?
It generate error code after run `cordova build android --release`
![Untitled-1](https://user-images.githubusercontent.com/47486787/104928295-2467e380-59ab-11eb-96e1-82a05b651b5d.jpg)

## Information

![Untitled-1](https://user-images.githubusercontent.com/47486787/104928253-1619c780-59ab-11eb-916c-7e8343f86d93.jpg)

### Command or Code

command line code: `cordova build android --release`

`build.json file:`

`{
    "android": {
        "debug": {
            "keystore": "../android.keystore",
            "storePassword": "android",
            "alias": "mykey1",
            "password" : "password",
            "keystoreType": "",
            "packageType": "apk"
        },
        "release": {
            "keystore": "../android.keystore",
            "storePassword": "",
            "alias": "mykey2",
            "password" : "password",
            "keystoreType": "",
            "packageType": "bundle"
        }
    }
}`

### Version information

cordova-android 9.1.0-dev (master)
Cordova cli 10.0.0
Android studio 4.1.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Confirmed issue on nightly on a plain fresh cordova project, via `cordova build android -- --packageType=bundle`.

This does work on `cordova-android@9.0.0`

I believe the regression happened somewheres within these commits:

7428bd3a (HEAD -> master, origin/master, origin/HEAD, apache/master) Features/webp support for splashscreen (#1113)
55feadff fix(prepare): mapImageResources always returning [] (#1136)
97e2d156 test(java): remove duplicate code in BackButtonMultipageTest (#1129)
b2453375 refactor(ProjectBuilder): clean up output file collection code (#1099)
bb7d733c refactor: unify installation on devices & emulators (#1123)
aa679ea1 feat(Adb): list devices _and_ emulators in one go (#1125)
0e8234ab refactor(check_reqs): cleanup default Java location detection on Windows (#1102)
d5b9029a Android - allow changing min sdk version (#1117)
671e1fd1 refactor: remove copied Adb.install from emulator.install (#1108)
c144c081 fix(android): allow file access for existing behavior (#1111)
aada3e81 refactor: do not kill adb on UNIX-like systems (#1103)
335b0f25 test: fix unit test failures for certain random orders (#1094)
b1f01d7a test: ensure single top-level describe block in test file (#1094)
3b56160d chore(asf): Update GitHub repo metadata
39e31562 fix: Reflect minimum required NodeJS (#1045)
e125ab1b refactor(retry): simplify retryPromise using modern JS (#1086)
5d3591b8 refactor(utils): reduce number of utils (#1085)
20623889 fix(prepare): fix pattern used to collect image resources (#1084)
33476b47 [Frequent Updates] Gradle 6.6.1 & Android Gradle Plugin 4.0.1 & com.jfrog.bintray.gradle 1.8.5 (#1079)
2c888f41 chore(pkg): remove deprecated no-op field "engineStrict" (#1081)
565106fc refactor: Stop suppressing un-needed TruelyRandom lints (#1046)
a45217e6 ci: Added Node 14.x (#975)
d7790ca8 chore: remove unused emulator.create_image and its dependencies (#1019)
8ef8d994 fix(pluginHandlers): properly check if path is inside another (#1014)
80ad6353 test(pluginHandlers/common): better setup & teardown (#1013)
ec944cf0 fix: gradle ignore properties (#1018)
ba5781c3 refactor: save ProjectBuilder instance in Api instance (#1016)
d86cb99d Remove unnecessary stuff (#1015)
3204b980 test(java): fix, improve and move clean script (#1017)
ce735256 test: fix missing stack traces in jasmine output (#1012)
cccf8124 Set package-lock.json to 9.1.0-dev
f7e19796 Update JS snapshot to version 9.1.0-dev (via coho)
49fc5da2 Set VERSION to 9.1.0-dev (via coho)

**Comment by breautek** [comment]
It appears https://github.com/apache/cordova-android/commit/7428bd3a7fff2b95e5885429acc2a50a95e1dfbc is the offending commit.

Building bundles works on https://github.com/apache/cordova-android/commit/55feadff0519fa294be34c22ff6fbb913efd1b48

**Comment by breautek** [comment]
I think I'm pointing the blame at the wrong PR, but I have a fix PR incoming.

**Comment by mosabab** [comment]
Thanks for fix the issue
