### ISSUE TITLE
Migrate away from JFrog Bintray / JCenter

### ISSUE THREAD

**Issue by kklyoon** [apache/cordova-android#1160]
Here is jfrog Notice

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

should be updated about it. 

Thanks.

**Comment by breautek** [comment]
We are aware, but we don't know what we are going to do about it yet. If you have any recommendations, please do share.

**Comment by brodybits** [comment]
I took the liberty to rewrite the title. As stated in PR #1160, it seems to be blocked by this issue: https://youtrack.jetbrains.com/issue/IDEA-261387

It looks to me like JCenter will continue serving packages until February 1, 2022.

**Comment by breautek** [comment]
cordova-android@9.1 (currently not released, but planned to be released soon...) will contain https://github.com/apache/cordova-android/pull/1179

While this in itself doesn't remove `jcenter`, it should allow you to override the repositories used so that you can use an alternate source, for as long as the repository contains the dependencies that cordova requires. This should serve as a stopgap measure at the very least I think...

**Comment by th-jtullgren** [comment]
Hi,

We need the framework binary to extend some apis in the CordovaInterface. I see the binary in JCenter but nothing in maven central. Is it possible to publish the framework binary to maven central?

Thanks

**Comment by erisu** [comment]
This should have been resolved in Cordova-Android 10.

**Comment by th-jtullgren** [comment]
@erisu Since you have closed this issue, where can I track the progress for uploading the framework to maven central?  Thanks!

**Comment by th-jtullgren** [comment]
@erisu is there an update on this?  Jcenter deadline is approaching.

**Comment by erisu** [comment]
What do you mean?

It has already been completed. We removed the usage and been uploading to maven central.

**Comment by th-jtullgren** [comment]
@erisu I apologize. I just searched for cordova on maven central and it was not showing up. I put the full coordinate and I have found it. Thank you!

**Comment by erisu** [comment]
Awesome! No Problem.

I will go ahead and share the link here so if in case anyone else comes across this ticket and looking for it.

* https://mvnrepository.com/artifact/org.apache.cordova/framework
* https://search.maven.org/artifact/org.apache.cordova/framework
