### ISSUE TITLE
cordova platform add android not working for 9.0.0.0 version

### ISSUE THREAD

**Issue by mabreu14** [apache/cordova-android#1162]
# Bug Report

## Problem
* command 'cordova platform add android' is not working 
* The issue started happening after Feb 03 2021
* Its falling trying to get platform API on line https://github.com/apache/cordova-lib/blob/master/src/cordova/util.js#L59 when pkgJsonPath is node_modules/cordova-android/bin/templates/cordova/Api.js

### What is expected to happen?
android platform should be added 

### What does actually happen?
error Unable to load PlatformApi from platform. ReferenceError: globalThis is not defined

## Information
Error happens with version cordova-android@9.0.0
If I downgrade to 8 it works 

### Command or Code
phonegap platform add android

### Version information
current dependencies
"babel-core": "^6.3.26",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-polyfill": "^6.3.14",
    "bluebird": "^2.9.33",
    "classnames": "^2.1.3",
    "cordova": "^8.0.0",
    "cordova-android": "9.0.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-app-icon-changer": "1.0.0",
    "cordova-plugin-calendar": "5.1.5",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-dialogs": "2.0.1",
    "cordova-plugin-enable-multidex": "0.1.3",
    "cordova-plugin-file": "6.0.1",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-geolocation": "3.0.0",
    "cordova-plugin-inappbrowser": "3.2.0",
    "cordova-plugin-network-information": "2.0.1",
    "cordova-plugin-passbook": "0.2.1",
    "cordova-plugin-safariviewcontroller": "1.6.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-vibration": "3.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-support-google-services": "^1.1.0",
    "cordova-plugin-screen-orientation": "3.0.2",
    "currency.js": "^0.4.4",
    "fastclick": "^1.0.6",
    "geolib": "^2.0.17",
    "glob": "^6.0.1",
    "hammerjs": "^2.0.4",
    "jquery": "^2.1.4",
    "jsbarcode": "^3.11.0",
    "lodash.groupby": "^3.1.1",
    "lodash.isequal": "^4.2.0",
    "merge-stream": "^1.0.0",
    "moment": "^2.10.3",
    "mx-ui": "git+ssh://git@bitbucket.org/daxko/mx-ui.git",
    "node-uuid": "^1.4.7",
    "node-version-compare": "^1.0.2",
    "phonegap": "^8.0.0",
    "phonegap-plugin-barcodescanner": "8.0.0",
    "plist": "^1.2.0",
    "react": "^15.2.1",
    "react-addons-css-transition-group": "^15.2.1",
    "react-addons-shallow-compare": "^15.2.1",
    "react-auto-text": "^1.0.0",
    "react-dom": "^15.2.1",
    "react-router": "^2.7.0",
    "react-svg": "^7.2.6",
    "rewire": "^2.3.4",
    "seed-random": "^2.2.0",
    "universal-ga": "^1.0.0"

## Checklist

- [x ] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
> "cordova": "^8.0.0",

Can you try version 10?

**Comment by mabreu14** [comment]
I updated to 10 and got the same error but from a different line 
ReferenceError: globalThis is not defined
cordova/node_modules/queue-microtask/index.js:5
? queueMicrotask.bind(globalThis)

**Comment by dpogue** [comment]
What version of nodeJS do you have installed? `node -v` should tell you

**Comment by mabreu14** [comment]
11.10

**Comment by breautek** [comment]
We support Node 12+ LTS versions.

Non-LTS versions are not supported (although will probably still work). Recommended version to use is the latest release of Node 14.

**Comment by mabreu14** [comment]
downgrading to v10 sold the issue
