### ISSUE TITLE
How to configure Apache Cordova with OData?

### ISSUE THREAD

**Issue by younussenn** [apache/cordova-android#1168]
Hello there,

I'll develop an application with Apache cordova but I don't know much about this. To start, I have to do this. **I will use OData** as the protocol. With the Apache cordova mobile application, I want to write data somewhere(sqlite, mongodb etc.) and print the data I wrote on the screen.

Is there any document or video I can use on this subject? Can you help me?

Thank you.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however this channel is for bug and feature requests, not for support. 😊  
You can try asking on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova) or in our [Slack community](http://slack.cordova.io).
