### ISSUE TITLE
cordova-android pdf-file-upload ionic 6.13.0 , Cordova 10.0.0 is not working 

### ISSUE THREAD

**Issue by karimmahrouskamil** [apache/cordova-android#1169]
# Bug Report

## Problem
pdf-file-upload ionic 6.13.0 , Cordova 10.0.0 is not working 
### What is expected to happen?
resolve the native path from the filechooser plugin

### What does actually happen?

 after it resolve uriFromFileChooser parameter the error happen on step "2" callback error  it returns an error with **"uri"** on step 2 or

## Information

I have added permissions using Android permissions plugin 
```
 permissionsArr = [
    this.androidPermissions.PERMISSION.READ_EXTERNAL_STORAGE,
    this.androidPermissions.PERMISSION.WRITE_EXTERNAL_STORAGE,
    this.androidPermissions.PERMISSION.MANAGE_DOCUMENTS
  ]

```
using the function below
```
 RequestPermissions() {

    this.androidPermissions.requestPermissions(this.permissionsArr).then((value: AndroidPermissionResponse) => {

      console.log(value);
      // console.log(value.hasPermission);


    },
      (error) => {
        console.log(error);

      });
  }
```
### Command or Code

   ```
 //1 File Chooser
    this.fileChooser.open().then((uriFromFileChooser) => {

      console.log("SUCCESS - open method -1" + uriFromFileChooser);
      //2 FilePath
      this.filePath.resolveNativePath(uriFromFileChooser).then((nativePathResolvedFromFilePath) => {
        console.log("SUCCESS  - resolve native -2" + nativePathResolvedFromFilePath);

        // 3 
        this.base64.encodeFile(nativePathResolvedFromFilePath).then((base64File: string) => {
          console.log("SUCCESS  - encode to base 64 -3" + JSON.stringify(base64File));

          //4  send to backend API 
    

        }, (err) => {
          console.log("error from base 64  method - 3" + JSON.stringify(err));
        });

      }, (error) => {
        console.log("error from resolve native path method - 2" + JSON.stringify(error));
      })

    }, (err) => {
      console.log("error from open method - 1" + JSON.stringify(err));

    })
```

### Environment, Platform, Device

 ionic 6.13.0 , Cordova 10.0.0 

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
File Chooser is not part of the Cordova codebase, so we cannot resolve any bugs related to this plugin.

Related links:
https://ionicframework.com/docs/native/file-chooser
https://github.com/ihadeed/cordova-filechooser
