### ISSUE TITLE
Will Chrome 90 Update to Stop 3rd Party Cookies affect my App

### ISSUE THREAD

**Issue by FIELDPOINT** [apache/cordova-android#1187]
**Background**
My Cordova app has a login Page which relies on ASP.Net Session SetCookie Response from the server (https://XYZ.com) to set the session cookie and then uses that information to maintain session to stay logged in. 

**Question**
My question is will this change from Chrome - https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html that's due to come out in April 2021 affect my setup in anyway? 

I have tried googling this for hours now without any concrete answers. Any help will be appreciated.

UPDATE
I found you could set the setAcceptThirdPartyCookies to true or false in the SystemCookieManager class. I tried setting this to false thinking it would mimic the Chrome 90 change and sure enough my cordova app stopped working. So I guess my question now becomes - Will this chrome 90 change the behaviour of setAcceptThirdPartyCookies method and render it useless or honor the value that it sets?

**Comment by breautek** [comment]
Not sure if chrome 90 is available in the Prerelease channels yet, but perhaps https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/prerelease.md may help

**Comment by breautek** [comment]
Webviews on API 31 / Android 12 will enforce [SameSite](https://web.dev/samesite-cookies-explained/) cookie policies. Cordova cannot override this policy. It will likely require some changes on the server side to handle this change.

The `setAcceptThirdPartyCookies` is for accepting third-party cookies which Cordova has always had enabled, but is a different policy than `SameSite`.

[Google](https://developer.android.com/about/versions/12/behavior-changes-12#test_samesite_behaviors_in_your_app) provides tips on how you can test SameSite cookie policies.

Closing as won't fix as cookie behaviour is outside of Cordova's control.
