### ISSUE TITLE
Cannot use Java 11 (or any Java >10)

### ISSUE THREAD

**Issue by witekkij** [apache/cordova-android#1195]
We recently moved from Java 8 to 11 with our backend, but although Android SDK Command line tools now supports Java 11 (legacy SDK Tools didn't) I still cannot build my frontend apps when Java 8 is not in path

This was addressed but not resolved in 
https://github.com/apache/cordova-android/pull/446

**Comment by timbru31** [comment]
See https://github.com/apache/cordova-android/pull/928#issuecomment-655503129 for the reason.

**Comment by timbru31** [comment]
If the newer SDK CLI tools now properly support Java 11, please link the documentation/changelog that highlights this change.

**Comment by breautek** [comment]
Java 11 support will be coming with Android Gradle Plugin 7.0, which isn't released yet. It's available in the preview.

https://developer.android.com/studio/preview/features#agp-7-0-jdk-11

Not only it is supported, it will be required. We have plans to make this change in `cordova-android@10`, **IF** AGP 7 is released early enough.
