### ISSUE TITLE
Bluetooth pairing no longer working on Android 11 since Feb 1/21 Google security update, multiple plugins effected

### ISSUE THREAD

**Issue by anywherecommerce-kim** [apache/cordova-android#1215]
# Bug Report
Bluetooth pairing no longer working on Android 11 since Feb 1/21 Google security update, multiple plugins effected

Google released a security update to devices running Android 11 on Feb 1, 2012.  Part of this update effects bluetooth, and applications using Web View.   Since applying the update,  plugins supporting Bluetooth or BLE ceased functioning.  Tested on Samsung Note 20, Pixel 5, reports of others.

Both BT Classic and BLE appear to be effected.

## Problem

It appears that the OS bluetooth pairing/confirmation popup is being blocked.   Users are unable to respond with an OK, and the bluetooth pairing eventually times out. 

Have writen plugin wrapping aar file that works fine with known good devices on Android 11.   The calls work fine in Android native.  The exact same aar file with a plugin wrapper that worked on Android 11 PRIOR to the Feb 1, 2021 update no longer prompts user for pairing. 

Have also tested cordova-plugin-bluetoothle and various other plugins.  All have same behavior.  Android 11 prior to update - works,  after update - corodva apps or plugins no longer appear to be able to display bluetooth confirmation dialogs, breaking pairing.

### What is expected to happen?

I would like to be able to see behavior similar to what was available prior to the Android 11 Feb update.   Bluetooth pairing attempts should trigger the OS confirmation dialog to come up.

### What does actually happen?

It appears that the confirmation dialog is being blocked from display or some other underlaying issue

## Information

I strongly suspect that this has to do with a webview update required by the security update.   Something appears to have changed.,

### Command or Code

Try cordova-plugin-bluetoothble for a sample of the issue.   I am running a vendor specific plugin that I cannot release code for, but the ble plugin has a similar structure.   Works on Android 11, pre-patch, fails after patch.

### Environment, Platform, Device

Tested on Samsung Note 20, Pixel 5, reports of others.

### Version information

Tested building with:
Cordova 10,  Cordova 9, Cordova 8, on each of Linux, macOS Catalina and Windows 10

Issue isolated to Android handsets running Android 11 with Feb 1, 2021 patch from google.

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
I fail to see a link between cordova-android and the issues that appear to be issues in the bluetooth plugins. Have you isolated a particular plugin call to the cordova framework that isn't working properly? If not, then I'd suggest raising the issues with the bluetooth plugin authors first.

**Comment by breautek** [comment]
Closing as stale.
