### ISSUE TITLE
Application does not initialize correctly on 10.x nightly/dev master

### ISSUE THREAD

**Issue by breautek** [apache/cordova-android#1217]
# Bug Report

### What is expected to happen?

Application to start correctly

### What does actually happen?

Application fails to initialize probably (deviceReady not fired).

## Information

This is a regression from a newly added feature https://github.com/apache/cordova-android/pull/1137

With the default configuration, plugins will fail to initialise because they do not pass the whitelist checks. This occurs when you have at least one plugin installed.

The default `<content src="index.html" />` seems to produce a white list pattern where `index.html` is the `host`, instead of the `path`, so when comparing against the `https://localhost` origin, it returns false.

![Screenshot from 2021-04-24 12-36-24](https://user-images.githubusercontent.com/11200662/115964218-bf67e080-a4f9-11eb-992d-2cf565e9ffa9.png)

### Command or Code

```
cordova create test
cd test
cordova platform add android@nightly
cordova plugin add cordova-plugin-file
cordova run android
```

These steps will produce the hello world cordova app that stays on "connecting" because `deviceReady` never fires.

### Environment, Platform, Device

`cordova-android@nightly`
And one other plugin

## Workaround

Setting `<content src="https://localhost/index.html" />` will correct the problem, but the framework should perhaps figure out this out so that `<content src="index.html" />` continues to work properly.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
It also works if you add `<allow-navigation href="https://localhost/*" />`, but yeah, it should work without the need of adding it or changing the content url.
I think the proper place to put it is inside the AllowList plugin, once it gets merged https://github.com/apache/cordova-android/pull/1138
there is the check that allows the content src url

**Comment by NiklasMerz** [comment]
Looks like we need to change this: https://github.com/apache/cordova-android/blob/53d60dd70719220a655b1bedb09b20280d92b0d3/framework/src/org/apache/cordova/AllowListPlugin.java#L81
