### ISSUE TITLE
Can't distinguish between aab signed and unsigned

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-android#1234]
# Bug Report

## Problem
When failing to sign an aab file the file name is `app-release.aab`

### What is expected to happen?
When signing fails or has incorrect parameters I expect the filename to be `app-release-unsigned.aab` much like what happens with the apk file.

### What does actually happen?
When singing fails or has incorrect parameters the file name does not change and remains the same for when signing is successful

## Information
I'm using my repository to migrate from apk to aab, and when I tested this locally I get the following output:
```
npx cordova build android --release -- --keystore=my.jks --storePassword=mykspass --password=mypass --packageType=bundle
Removing unneeded permissions: RECORD_AUDIO, MODIFY_AUDIO_SETTINGS, RECEIVE_BOOT_COMPLETED, READ_PHONE_STATE
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/Users/harel/Library/Android/sdk/ (DEPRECATED)
Using Android SDK: /Users/harel/Library/Android/sdk
'keystore' and 'alias' need to be specified to generate a signed archive. // this is the important warning saying I did something wrong...
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :CordovaLib
[Cordova] cdvMinSdkVersion is overridden, try it at your own risk.

> Task :app:stripReleaseDebugSymbols
WARNING: Compatible side by side NDK version was not found. Default is 21.0.6113669.
Compatible side by side NDK version was not found. Default is 21.0.6113669.
Unable to strip the following libraries, packaging them as they are: libsqlc-native-driver.so.

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 36s
45 actionable tasks: 45 executed
Built the following bundle(s): 
	.../platforms/android/app/build/outputs/bundle/release/app-release.aab

```
### Command or Code
See above

### Environment, Platform, Device
MacOs but I don't think it's OS specific...

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by kzimny** [comment]
You can open the aab file with zip or TotalCommander. Signed bundles contains META-INF folder with RSA, SF and MF files.

**Comment by HarelM** [comment]
Please re-read what I wrote. It's not about how to sign, but rather about the file name when signing fails...

**Comment by erisu** [comment]
@HarelM you might want to make that request with Google. Our code is not customizing the default file name.

APK, for example, is outputed like how you are describing by default and is not something we are doing.

**Comment by HarelM** [comment]
I didn't know that. Thanks for looking into it!
Feel free to close this issue...

**Comment by breautek** [comment]
Yah I thought that was the case, just wasn't 100% sure and didn't had the time to double check. I'll close this issue.
