### ISSUE TITLE
Kotlin gradle version does not change with respect to GradlePluginKotlinVersion variable

### ISSUE THREAD

**Issue by ebhsgit** [apache/cordova-android#1235]
# Bug Report

## Problem
Using cordova 9.0.0, when I set `GradlePluginKotlinVersion` to 1.4.31
I get compilation error "Expecting a parameter declaration" due to trailing comma.

----

Kotlin allowed trailing comma in 1.3.70

https://youtrack.jetbrains.com/issue/KT-34743

### What is expected to happen?

Compile without error

### What does actually happen?

Unable to compile.
Error "Expecting a parameter declaration" pointing to the trailing comma

## Information

```
data class Test(
    val test1: String,
    val test2: String,
) {
    fun test(
        t1: String,
        t2: String,
    ) {

    }
}
```

This code when compiled will result in error

------

After investigating, I notice that `kotlin-android-extensions-runtime` did not respect the `GradlePluginKotlinVersion` variable.
It was set to 1.3.50.

This is due to `org.jetbrains.kotlin:kotlin-gradle-plugin` being hardcoded to version 1.3.50 in `bin\templates\project\build.gradle` 

## Checklist

- [ x ] I searched for existing GitHub issues
- [ x ] I updated all Cordova tooling to most recent version
- [ x ] I included all the necessary information above

**Comment by erisu** [comment]
This should have been resolved in Cordova-Android 10.
