### ISSUE TITLE
Running emulator adds allow-navigation to localhost and it causes an Application Error

### ISSUE THREAD

**Issue by ilprima** [apache/cordova-android#1240]
Every time I run:
` ionic cordova run android -l —prod
`or
`ionic cordova run android -l
`or
`ionic cordova emulate android -l
`
It adds a row in the config.xml

`    <allow-navigation href="http://localhost:8100" sessionid="1c2ab341" />
`
That causes a popup with this text:

<img width="464" alt="Schermata 2021-06-10 alle 11 49 45" src="https://user-images.githubusercontent.com/18414951/121504663-78b74280-c9e2-11eb-86d7-1f5339b39ca0.png">

I use Ionic, my versions in:
```

Ionic:

   Ionic CLI                     : 6.11.8 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.3
   @angular-devkit/build-angular : 0.901.9
   @angular-devkit/schematics    : 9.1.15
   @angular/cli                  : 9.1.15
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android broken, browser 5.0.4, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.2.1, (and 22 other plugins)

Utility:

   cordova-res                          : 0.15.3
   native-run (update available: 1.4.0) : 1.3.0

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v12.18.3 (/usr/local/bin/node)
   npm        : 6.14.6
   OS         : macOS Catalina
   Xcode      : Xcode 11.7 Build version 11E801a



```

**Comment by jcesarmobile** [comment]
> Cordova Platforms : android broken

looks like you android platform is in a bad state, try removing the platform and adding it again
