### ISSUE TITLE
Cordova does not start AVD

### ISSUE THREAD

**Issue by pcwSlide** [apache/cordova-android#1242]
# Bug Report

## Problem
cordova run android/emulator does not start the AVD - it seems to loop endlessly.

This has been the same for me for a year now. I know I can run the AVD first - that is not the issue. 

### What is expected to happen?
I expect the software to negotiate with the adb and start the default instance - AVD

### What does actually happen?
loops endlessly - it seems cordova can't start an emulator.. It used to..

>>Using Android SDK: C:\Users\Phil.DESKTOP-TK224C9\AppData\Local\Android\Sdk
>>No target specified and no devices found, deploying to emulator
>>No emulator specified, defaulting to Galaxy_Nexus_API_29_Android_10
>>Waiting for emulator to start...

## Information

>> cordova run android --emulator --verbose
>> Output
>>No emulator specified, defaulting to Galaxy_Nexus_API_29_Android_10
Found available port: 5584
Waiting for emulator to start...
Running adb shell command "getprop dev.bootcomplete" on target emulator-5584...

### Command or Code

cordova run android --emulator
cordova run android 

### Environment, Platform, Device

Really just a straight setup
Win 10 | Cordova 10  CLI | Gradle 6.1 | Latest Android Studio Updates | Pixel/Samsung AVD's

### Version information

Really just a straight setup
Win 10 | Cordova 10  CLI | Gradle 6.1 | Latest Android Studio Updates

## Checklist

>> - closed but not solved
'cordova run android --emulator' command line tool stuck at 'Waiting for emulator to start...' apache/cordova-plugin-camera#698

- [ X] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

Thanks

**Comment by PieterVanPoyer** [comment]
I did transfer the issue from the cordova-plugin-camera repo, it has nothing todo with the camera in my opinion.

**Comment by breautek** [comment]
This issue shuld have been resolved by https://github.com/apache/cordova-android/pull/978 which was included in the `cordova-android@9.0` release.

Can you confirm that you're using `cordova-android@9` platform or later?

**Comment by PieterVanPoyer** [comment]
It doesn't work on my system either. 
But my setup/system is not a reference setup, so I don't complain about it. 
Btw, I use ``cordova-android@9.1`` now.

@pcwSlide which cordova-android version do you use?

**Comment by PieterVanPoyer** [comment]
@pcwSlide there seems to be something wrong with the windows setup .
https://cordova.apache.org/docs/en/10.x/guide/platforms/android/index.html#windows

When you look at the guidelines, there are some environment variables to set.
![image](https://user-images.githubusercontent.com/33040889/121754789-c97b8800-cb15-11eb-90ac-53d269f1eb13.png)

You could try to change the latest ``...\Android\sdk\tools`` to ``...\Android\sdk\emulator`` 

Make sure to restart your computer .

I am not sure if there are any side effects .

But could you test this.

**Comment by pcwSlide** [comment]
> 
> 
> It doesn't work on my system either.
> But my setup/system is not a reference setup, so I don't complain about it.
> Btw, I use `cordova-android@9.1` now.
> 
> When I start with verbose logging I see this repeated
> 
> ```
> Running adb shell command "getprop dev.bootcomplete" on target emulator-5584...
> ```
> 
> I did put some extra logging in the wait_for_emulator function.
> 
> ```
> Failed to execute shell command "getprop,dev.bootcomplete" on device: Error: Command failed with exit code 1: adb -s emulator-5584 shell getprop dev.bootcomplete\nadb.exe: device \'emulator-5584\' not found
> ```
> 
> Did some deeper digging. The JavaScript in `emulator.js` does
> 
> ```
> var args = ['-avd', emulatorId, '-port', port];
>             // Don't wait for it to finish, since the emulator will probably keep running for a long time.
>             execa('emulator', args, { stdio: 'inherit', detached: true, cwd: emulator_dir })
>                 .unref();
> ```
> 
> When I run this command just in a command prompt I've got next output.
> 
> ```
> C:\Users\myusername\AppData\Local\Android\sdk\tools>emulator -avd "Galaxy_Nexus_API_29" -port 5584 -verbose
> emulator:Android emulator version 26.0.3.0 (build_id 3965150)
> emulator:Found AVD name 'Galaxy_Nexus_API_29'
> emulator:Found AVD target architecture: x86
> emulator:argv[0]: 'emulator'; program directory: 'C:\Users\myusername\AppData\Local\Android\sdk\tools'
> emulator:  Found directory: C:\Users\myusername\AppData\Local\Android\sdk\system-images\android-29\google_apis\x86\
> 
> emulator:Probing for C:\Users\myusername\AppData\Local\Android\sdk\system-images\android-29\google_apis\x86\/kernel-ranchu: file missing
> emulator:Auto-config: -engine classic (based on configuration)
> emulator:  Found directory: C:\Users\myusername\AppData\Local\Android\sdk\system-images\android-29\google_apis\x86\
> 
> emulator:try dir C:\Users\myusername\AppData\Local\Android\sdk\tools
> emulator:Looking for emulator-x86 to emulate 'x86' CPU
> emulator:Probing program: C:\Users\myusername\AppData\Local\Android\sdk\tools/emulator-x86.exe
> PANIC: Missing emulator engine program for 'x86' CPU.
> ```
> 
> Okay, so I have an Android/sdk/tools folder with an emulator.exe in it.
> 
> And I have an Android/sdk/emulator folder with an emulator.exe in it. This one should be started.
> 
> @pcwSlide which cordova-android version do you use?

**Comment by pcwSlide** [comment]
Ok I will try that.. I am using cordova 10 – So you are saying that the CLI 10 is ok but we just explicitly fetch the cordava-android9 platform?

 

Will we have to do this always or will the version 9 settle into a standard platform add android?

 

Phil

**Comment by breautek** [comment]
>Will we have to do this always or will the version 9 settle into a standard platform add android?

Each CLI version is tied to a major version, and is only really tested against that major version, generally speaking. So if you were starting fresh, CLI 10 install by default the latest version of cordova-android@9. However, if you were upgrading an existing project which may still had cordova-android@8, then you'll need to manually upgrade by removing and re-adding the platform.

@PieterVanPoyer has reproduced your issue though on the latest cordova versions. Currently the cordova docs will recommend you to set old/deprecated android tooling in your path, and if you follow these recommendations, it will produce the issue you have reported. You can see Pieter's comments for a workaround until a patch can be landed and released.

**Comment by pcwSlide** [comment]
Ok - I will check mine with a new platform asap.

Can I say however that openeng the emulator with the CLI run command to an emulator has not work for a very long time - for me. This thread was closed but the issue not resolved I believe - from my very poor memory. 

I hope it can be corrected long term. Thanks

Phil
PS: This is my effort in supporting the great job you guys do and not - "a compliant".

**Comment by breautek** [comment]
This can be left open for now until we determine if code change is required or a doc change os required. Like I said earlier, pieter was able to reproduce the issue on windows.

And no worries, this isn't treated as a complaint :)

**Comment by PieterVanPoyer** [comment]
@pcwSlide we need you to test this.

You should check your Windows PATH environment variables.
https://cordova.apache.org/docs/en/10.x/guide/platforms/android/index.html#windows

You should have 2 entries (necassary for Cordova).
```
C:\Users\[your user]\AppData\Local\Android\Sdk\platform-tools
C:\Users\[your user]\AppData\Local\Android\Sdk\tools
```

We think the last one is incorrect. You should change that last one to.
```
C:\Users\[your user]\AppData\Local\Android\Sdk\emulator
```
So change ``C:\Users\[your user]\AppData\Local\Android\Sdk\tools`` to ``C:\Users\[your user]\AppData\Local\Android\Sdk\emulator`` in your windows PATH environment variables.

Make sure to restart your computer .

Then you should test if the  ``cordova run android --emulator`` starts the emulator, and give some feedback about your test.

@breautek later we should check if the cordova build command still works without the ``\Sdk\tools`` entry.

**Comment by pcwSlide** [comment]
Ok - so with a new Cordova project it does pick the emulator up with the changed env. However first time through it spawns a command box with the text below the line.
Points:
1. If this is correct then the documentation should be changed.
2. I feel this is a work around and this thread should be open until a straight cordova download with platform add works out of the box.
3. My Android Emulator seems up to date 30.6.5 - Studio does not show an update required.  Studio confims I am up to date.
4. When changing an env variable you don't have to restart your PC - just open another cmd.

Thanks for your help - I will test further and look forward to Cordova 10.

Cheers
Phil




--------------------------------------------------------------------------
emulator: Requested console port 5584: Inferring adb port 5585.
handleCpuAcceleration: feature check for hvf
added library vulkan-1.dll
Failed to open /qemu.conf, err: 2
HAX is working and emulator runs in fast virt mode.
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"

Warning: restoring GLES1 context from snapshot. App may need reloading.

**Comment by albertidimentico** [comment]
Hello, placing the environment variables corrects the problem, although it does not automatically start the emulator.

Environment Variables:
C:\Users\[your user]\AppData\Local\Android\Sdk\platform-tools
C:\Users\[your user]\AppData\Local\Android\Sdk\cmdline-tools\latest\bin
C:\Users\[your user]\AppData\Local\Android\Sdk\tools\emulator


`BUILD SUCCESSFUL in 17s
50 actionable tasks: 50 up-to-date
Built the following apk(s):
        C:\Users\alberto\Desktop\alberto\prueba\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_HOME=C:\Users\alberto\AppData\Local\Android\Sdk (recommended setting)
ANDROID_SDK_ROOT=C:\Users\alberto\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: C:\Users\alberto\AppData\Local\Android\Sdk
Waiting for emulator to start...`
