### ISSUE TITLE
edit-config for Androidmanifest.xml doesn't work with <queries> (for API30 new permissions)

### ISSUE THREAD

**Issue by Stephane84** [apache/cordova-android#1245]
# Bug Report

Hello, I need to add in my AndroidManifest.xml `<queries>` with package name of app i interact with, to make it works with Android API 30 app builded on Android 11 devices (see : https://developer.android.com/training/package-visibility/declaring)

## Problem

i need to use edit-config in my config.xml to do it, like this but it doesn't work :

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest" xmlns:android="http://schemas.android.com/apk/res/android">
  <queries>
    <package android:name="my.package.name"/>
  </queries>
</edit-config>
```

### What is expected to happen?
When running the command cordova prepare android with this edit config, it should add in AndroidManifest.xml the queries elements :

```
<queries>
    <package android:name="my.package.name" />
</queries>
```

### What does actually happen?

using edit-config with mode="merge" mode="overwrite" or no mode doesn't add the queries tags in AndroidManifest.xml

Oddly, when i put anything wrong in the mode attribute, it's work ... I can't understand why ???
Like this exemple, with mode="magic" . See : 

```
<edit-config file="app/src/main/AndroidManifest.xml" mode="magic" target="/manifest" xmlns:android="http://schemas.android.com/apk/res/android">
  <queries>
    <package android:name="my.package.name"/>
  </queries>
</edit-config>
```

Then, here, my queries is added in AndroidManifest.xml

## Information

I tried with cordova-android 9.0.0, 9.1.0 and 10.0.0-nightly.2021.6.6.6d803e2f
Nothing works

Maybe, it's not an issue of cordova-android, but cordova-cli ? If i need to change the issue to other repo, please let me know.

### Environment, Platform, Device
Windows

### Version information
    Node : 14.16.1
    Npm : 6.14.12
    cordova cli : 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Personally I don't like how `edit-config` works, but `edit-config` works only if there is actually something to edit. i.e. You can't use it to add something that is missing, only to modify something that already exists.

If we want to add a new node to `AndroidManifest.xml`, you must use [config-file](https://cordova.apache.org/docs/en/10.x/plugin_ref/spec.html#config-file) directive instead. The usage is very similar to `edit-config`, but `config-file` won't have a `mode` attribute.

Let me know how this works for you.

**Comment by Stephane84** [comment]
Well, it was so easy, and i missed it !
Thanks, config-file did the job

```
<config-file target="AndroidManifest.xml" parent="/manifest" xmlns:android="http://schemas.android.com/apk/res/android">
    <queries>
        <package android:name="my.package.name1"/>
        <package android:name="my.package.name2"/>
    </queries>
</config-file>
```
