### ISSUE TITLE
Unrecognized option: --illegal-access=permit

### ISSUE THREAD

**Issue by Fowlet** [apache/cordova-android#1248]
# Bug Report

### What is expected to happen?

I'm trying to build an Android Ionic app using Cordova, package versions below.

### What does actually happen?

 I run `ionic cordova run android` and am met with:

```
> cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/home/ethan/Android/Sdk (DEPRECATED)
Using Android SDK: /usr/lib/android-sdk
Subproject Path: CordovaLib
Subproject Path: app
Unrecognized option: --illegal-access=permit
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

## Information
It looks like something is trying to use the `illegal-access` argument, which doesn't exist on Java 1.8 (and later versions are incompatible with Cordova).

### Command or Code
`ionic cordova run android`

### Environment, Platform, Device
Ubuntu 21.04 64-bit
Node Fermium

### Version information
```
"dependencies": {
    "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@ionic/angular": "^5.5.2",
    "cordova-android": "9.1.0",
    "rxjs": "~6.6.0",
    "tone": "^14.7.77",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/compiler-cli": "~12.0.1",
    "@angular/language-service": "~12.0.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  }
```

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Fowlet** [comment]
Looks like something added that flag in the `gradlew` file of the project. Not sure what, but removing it allows the build to start. Any insights into where that might be coming from?

**Comment by breautek** [comment]
I would try scanning the plugins/ folder for illegal-access text.

Chances are this is coming from one of your installed plugins, probably in a form of a hook.

**Comment by pvharmo** [comment]
I'm getting the same error when I create a new project.

When I follow the getting started (but replacing browser by android)
- `cordova create MyApp`
- `cd MyApp`
- `cordova platform add android`
- `cordova run`

then I get the same error

**Comment by PieterVanPoyer** [comment]
Can anyone add more information to this ticket.
- The generated gradlew file?
- Run the build with the --verbose flag, and attach the output?

**Comment by daedeloth** [comment]
Sure, here you go:

[build verbose.txt](https://github.com/apache/cordova-android/files/6771178/build.verbose.txt)

[gradlew.txt](https://github.com/apache/cordova-android/files/6771190/gradlew.txt)

**Comment by PieterVanPoyer** [comment]
Indeed, there it is probably
![image](https://user-images.githubusercontent.com/33040889/124647245-01b48300-de96-11eb-9d05-b11eee731852.png)

If you manually remove the `--illegal-access=permit` from the gradlew file, does it work?

@breautek can you check your gradlew file ?

**Comment by breautek** [comment]
> @breautek can you check your gradlew file ?

My gradlew file definitely doesn't have `--illegal-access`

**Comment by daedeloth** [comment]
Well i seem to be running a different version of gradle :) Also I don't really know what gradle does, so I'm a bit lost at where it came from etc.

```gradle --version
 
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.21
Ant:          Apache Ant(TM) version 1.10.9 compiled on December 10 1969
JVM:          1.8.0_292 (Private Build 25.292-b10)
OS:           Linux 5.11.0-22-generic amd64
```

I removed the --illegal-access=permit from gradlew and that does indeed allow me to build... but I don't know how to stop it from showing up in gradlew in the first place :-)

**Comment by PieterVanPoyer** [comment]
It's hard to troubleshoot.

But, you should go to `/home/daedeloth/Workbench/client.quizwitz.com/cordova/platforms/android/` and run `gradlew version`.
That should be the version used for the Android project. 

In Cordova we work with the gradlew (wrapper) to ensure the correct gradle version for the projects.

I really don't know what changed the `gradlew` file. It could be the newest Android Studio or Ionic, but I don't think Ionic would change the content of the file.

**Comment by kepan12** [comment]
I'm remove // $DEFAULT_JVM_OPTS --illegal-access=permit // from the generated gradlew file that's works

**Comment by Steckelfisch** [comment]
I have a metoo. (on gradle 4.4.1 and 7.1.1)

from: https://tomgregory.com/gradle-vs-gradlew-difference/
The gradlew command, also known as the Gradle wrapper, is a slightly different beast. It’s a script that comes packaged up within a project. Yes, it gets committed into version control so when you clone the project you get the gradlew script automatically.

if i run: grep illegal `locate gradlew`
the only file with 'illegal-access' is in my platform/cordova dir. 

note that the the gradlew.bat in the same directory is lacking that option.

**Comment by Steckelfisch** [comment]
Removed all gradle stuff i coud find, installed 7.2 manually in /opt/gradle
updated cordova-lib (10.1.0) and cordova-android(10.1.1.0).
Now the --illegal-access  option is gone in the produced/generated gradlew

**Comment by breautek** [comment]
Closing because it has been found to be an environment issue rather than an issue with cordova-android.

**Comment by adipascu** [comment]
The Android SDK now supports JDK 11 and that solves the issue.
