### ISSUE TITLE
Support for JDK 11

### ISSUE THREAD

**Issue by adityatyagijtg** [apache/cordova-android#1277]
According to [this](https://github.com/apache/cordova-android/issues/908) and [this](https://github.com/apache/cordova-android/issues/908#issuecomment-598473380) the `cordova-android` supports JDK versions which is supported by the latest stable Android Studio release:

As per the investigation, the latest Android Studio v4.2.2 supports OpenJDK 11

```
C:\Program Files\Android\Android Studio\jre\bin>java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
OpenJDK 64-Bit Server VM (build 11.0.8+10-b944.6842174, mixed mode)
```

The upcoming release of Android Studio (4.3.x) ([Android Studio Arctic Fox](https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html)) will officially update gradle plugin as well as make JDK 11 as the minimum requirement. The version is currently in BETA.

>Java 11 requirement
With AGP 7.0.0-alpha01 we are changing the minimum required Java programming language version to Java 11. 
We are announcing this early in the Canary schedule and many months ahead of the stable release to allow developers time to get ready.

# PROBLEM
But the cordova (10.x.x) latest official guide still [explicitly mentions JDK 1.8](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#java-development-kit-jdk)

# QUESTION
1. Can we update the JDK version now?  
2. Will the cordova-android (9.x.x) and the upcoming (10.x.x) be compatible with JDK 11?

**Comment by erisu** [comment]
Master branch already removed the JDK 1.8 restriction.

**Comment by adityatyagijtg** [comment]
Thank you for the prompt reply @erisu 
Highly appreciate it.
