### ISSUE TITLE
AndroidInsecureFileModeEnabled breaks config.xml content src

### ISSUE THREAD

**Issue by ctayl** [apache/cordova-android#1289]
When using `<preference name="AndroidInsecureFileModeEnabled" value="true" />`
the `<content/>` tag's `src` is set to a hardcoded value: `file:///android_asset/www/index.html`. 

https://github.com/apache/cordova-android/blob/015db819aed3f35892d2b6035781ea4bd752149d/framework/src/org/apache/cordova/ConfigXmlParser.java#L54

**Comment by coolscene** [comment]
To add on a similar issue, when "AndroidInsecureFileModeEnabled" is set to false or not set at all, the "hostname" preference is ignored and always tries to run what's set in the content tag (eg: https://localhost/index.html).
