### ISSUE TITLE
gradle args cdvBuildToolsVersion is not correctly honoured

### ISSUE THREAD

**Issue by breautek** [apache/cordova-android#1290]
# Bug Report

### What is expected to happen?

It is expected for Cordova use the specified build tools version via `cdvBuildToolsVersion` gradle parameter if the parameter is defined.

### What does actually happen?

Cordova does use it, but now passes it through `findLatestInstalledBuildTools` call, effectively turning the parameter into a "minimum build tools version" parameter instead of a "build tools version" parameter.

## Information

This behaviour changed from cordova-android@9.1 where if `cdvBuildToolsVersion` was defined, it will simply use it. See [9.1](https://github.com/apache/cordova-android/blob/c9108d8479641b92b1694b48237830ebbe6a6444/bin/templates/project/app/build.gradle#L164-L167)

Further investigation notes are written: https://github.com/apache/cordova-android/issues/1288#issuecomment-885606552 where this issue was first identified.

### Command or Code

Have build tools version 30 & 31 installed. Building Build tools version 31 as described [here](https://github.com/apache/cordova-android/issues/1288)

Then run: `cordova build android --release -- --gradleArg=-PcdvBuildToolsVersion=30.0.3`

It is expected that cordova will use build tools version 30.0.3 instead of build tools 31.

### Environment, Platform, Device

Android

### Version information

cordova-android@10

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by gopi-hl** [comment]
This seems to have been addressed in 10.0.0.

#https://github.com/apache/cordova-android/issues/659#issuecomment-883864294

**Comment by breautek** [comment]
> This seems to have been addressed in 10.0.0.
> 
> [#659 (comment)](https://github.com/apache/cordova-android/issues/659#issuecomment-883864294)

That is unrelated.

The comment you referenced is in response to an issue where `cdvBuildToolsVersion` is **not** defined.

This issue is when `cdvBuildToolsVersion` is defined, but Cordova still decides to choose the latest installed anyway.

**Comment by EinfachHans** [comment]
Can someone publish `10.0.1` to npm?

**Comment by breautek** [comment]
It's currently in the apache voting process

https://www.apache.org/foundation/voting.html
