### ISSUE TITLE
--PackageType flag not creating APK. Always generating bundle

### ISSUE THREAD

**Issue by pawan-logiciel** [apache/cordova-android#1292]
# Bug Report

## Problem
--PackageType=apk flag not creating APK. Always generating bundle file
### What is expected to happen?
it should create release apk if I pass --PackageType=apk

### What does actually happen?
Command is creating only bundle release

## Information
After updating cordova to 10 I have tried to create release apk using this command
cordova build android --release --prod --packageType=apk

but it's generating only bundle release 

### Command or Code
cordova build android --release --prod --packageType=apk

### Environment, Platform, Device
Cordova - 10
Android 

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
The command your writing looks incorrect.

Please use:

```
cordova build android --release --prod -- --packageType=apk
```

Please refer to the note section under "Using Flags" about platform specific arguments.

**Comment by pawan-logiciel** [comment]
Thanks, @erisu Working now
