### ISSUE TITLE
Order of hostname preference and content in config.xml matters and breaks things

### ISSUE THREAD

**Issue by AdriVanHoudt** [apache/cordova-android#1299]
# Bug Report

### What is expected to happen?
Setting hostname 'just works' with the content option.
```xml
<content src="index.html" />
<preference name="hostname" value="mydomain.com" />
```

### What does actually happen?

The app doesn't load.

## Information

The config xml parser sees the content node first and sets the launch url to the default https://github.com/apache/cordova-android/blob/e69ab6a6879071262cd82e527fba8bf141ec7240/framework/src/org/apache/cordova/ConfigXmlParser.java#L133
it then sees the hostname pref and sets it in the prefs.
Afterwards getLaunchUrl is called which then returns the localhost one and not the prefs one. https://github.com/apache/cordova-android/blob/e69ab6a6879071262cd82e527fba8bf141ec7240/framework/src/org/apache/cordova/ConfigXmlParser.java#L48

I think just not doing https://github.com/apache/cordova-android/blob/e69ab6a6879071262cd82e527fba8bf141ec7240/framework/src/org/apache/cordova/ConfigXmlParser.java#L159-L163 would make getLaunchUrl reutrn the correct result in all cases.

### Command or Code

Config.xml
```xml
<content src="index.html" />
<preference name="hostname" value="mydomain.com" />
```

### Environment, Platform, Device
cordova-android 10.x

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
We have an open PR that is making changes to this stuff and I think will probably resolve this issue as well: https://github.com/apache/cordova-android/pull/1298

Can you give that a PR a test to see if it does address your issue?

**Comment by erisu** [comment]
This issues was already fixed in the PR that @breautek mentioned.

**Comment by AdriVanHoudt** [comment]
Jup that seems like it would fix this issue, thanks! 🎉

**Comment by AdriVanHoudt** [comment]
I thought I could get around this by putting the hostname pref before the content but it seems that the config.xml it generates in the android project has a fixed order where the content is always first. Which means that this issue now totally prevents me from having a working build :/
Do you have an ETA on 10.0.2 with the referenced patch in it?

**Comment by AdriVanHoudt** [comment]
Thanks @erisu for merging the fix 🙏 
Do you have an ETA on a release that will contain this fix?
