### ISSUE TITLE
Use D8 Compiler instead of DX

### ISSUE THREAD

**Issue by dattakadiyala** [apache/cordova-android#1309]
#Use D8 Compiler instead of DX

## Motivation Behind Feature
DX is deprecated as per google https://android-developers.googleblog.com/2020/02/the-path-to-dx-deprecation.html

**Comment by erisu** [comment]
I am closing out this ticket.

We are not specifically choosing which compiler (D8 or DX) to use. This is all controlled by the Android Gradle Plugin.

Google has been working towards deprecating the `DX` compiler for quite some time. They even said:

> During the third and final phase, DX will be removed from Android Studio. At this point, you'll need to use a legacy version of the Android Gradle Plugin in order to continue to build with DX.

We do not support at this time Build Tools 31.x or AGP 7.x. We also do not have a roadmap for the next major release as we just finished a major release last month.
