### ISSUE TITLE
AndroidInsecureFileModeEnabled prefrence not working 

### ISSUE THREAD

**Issue by pawan-logiciel** [apache/cordova-android#1312]
# Bug Report

## Problem

After Cordova 10 release Cordova added WebViewAssetLoader support which can cause data associated with the `file://` scheme, such as cookies, local storage, local cache, and web-based databases

But if we set AndroidInsecureFileModeEnabled to true according to docs(https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html) it will work like earlier which is not working for me 

Due to this I am facing cookies issue

### What is expected to happen?

After setting AndroidInsecureFileModeEnabled preference to true in config.xml it should work like old one 

### Command or Code

``` <preference name="AndroidInsecureFileModeEnabled" value="true" />```

### Version information

Cordova-android@10.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by secretmoo35** [comment]
Same issue, How to fixed this?

**Comment by erisu** [comment]
This ticket does not give enough Information.

At best, I can only recommend upgrading to the latest `cordova-android@10.1.0` and try again.

```
cordova platform rm android
cordova platform add android@latest
```

If you still have the issue after upgrading, try and provide more Information.

For example, provide the information that comes from the network & application tab of the **DevTools** and make sure its from both the working and non-working app. Both should show that the `index.html` is loading from `file:///android_asset/www/index.html`... Application tab should also show that it is reading from `file://` for the cookies, etc. If you see it checking `file://` but there are no cookies, it probably means Android wiped out the information for more space.

Make sure to also test with `10.1.0` as it might have fixed that area.

**Comment by secretmoo35** [comment]
> This ticket does not give enough Information.
> 
> At best, I can only recommend upgrading to the latest `cordova-android@10.1.0` and try again.
> 
> ```
> cordova platform rm android
> cordova platform add android@latest
> ```
> 
> If you still have the issue after upgrading, try and provide more Information.
> 
> For example, provide the information that comes from the network & application tab of the **DevTools** and make sure its from both the working and non-working app. Both should show that the `index.html` is loading from `file:///android_asset/www/index.html`... Application tab should also show that it is reading from `file://` for the cookies, etc. If you see it checking `file://` but there are no cookies, it probably means Android wiped out the information for more space.
> 
> Make sure to also test with `10.1.0` as it might have fixed that area.

Thanks.
cordova-android@10.1.0 It's works fine for me.

**Comment by breautek** [comment]
@pawan-logiciel At your earliest convenience, If you could confirm that updating to cordova-android@10.1.0 solves your issue for us so we can determine if this issue can be closed or not.

Cheers,
Norman

**Comment by pawan-logiciel** [comment]
@breautek @erisu It's still not working for me.

**Comment by HarelM** [comment]
I've just tried it out and it seems to be working as expected (for me).

**Comment by breautek** [comment]
Is it possible that the server is setting a restrictive `SameSite` policy?

**Comment by jcesarmobile** [comment]
Closing as can't reproduce since the setting is working fine for everybody except from the reporter and by the last message the setting seems to be working, but there are cookie problems, which seems related to some server configuration problem, but there was no response to the last question.

Note that the setting, as the name says, is insecure, because google marked it as insecure and might eventually break in future Android versions, so we don't recommend using it and if things stop working there we won't fix them (mostly because we probably can't)
