### ISSUE TITLE
Android 12 splash screen issue 

### ISSUE THREAD

**Issue by bhandaribhuminpfizer** [apache/cordova-android#1313]
https://developer.android.com/about/versions/12/features/splash-screen
# Feature Request

when launch the application splash screen is getting display twice.

## Feature Description

when launch the application splash screen is getting display once.

## Alternatives or Workarounds

Temporary solution using hook 

adding styles.xml in `res/values/`
```
<resources>
  <style name="" parent="">
    <item name="">true</item>
  </style>
</resources>
```

**Comment by bhandaribhumin** [comment]
Thank you @breautek
