### ISSUE TITLE
The AllowList plugin may throw a NullPointerException in some case

### ISSUE THREAD

**Issue by YCKang** [apache/cordova-android#1322]
# Bug Report

## Problem
The AllowList plugin may throw a NullPointerException in some case.

### What is expected to happen?
To check the url correctly.

### What does actually happen?
Throw NullPointerException error.

## Information

If you don't set any `<allow-navigation>` in the config.xml, `this.shouldAllowNavigation(url)` will return `null`.
And operator '||' cannot be applied to 'null', 'boolean', it will throw NullPointerException error.

L130 should be `return (Boolean.TRUE.equals(this.shouldAllowNavigation(url)) || this.allowedRequests.isUrlAllowListed(url)) `.

https://github.com/apache/cordova-android/blob/bedb4427f420157ac547588acdf1083e8e916e20/framework/src/org/apache/cordova/AllowListPlugin.java#L122-L133

### Version information

cordova-android@10.0.1

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
PR is welcome

**Comment by jskrepnek** [comment]
If I understand this right, it would mean that any allowed requests that are not also in allowed navigations will always fail.  I'm able to reproduce this, even if there are some `allow-navigation` tags, for any requests that are also not in allowed navigations, even if they are in allowed requests.
