### ISSUE TITLE
10.1.0 - deviceready not fired when hostname is set and plugin installed

### ISSUE THREAD

**Issue by codeconsole** [apache/cordova-android#1328]
**>>> ANY <<< Android 10.1.0** app will break and deviceready will not fire when `<preference name="hostname" value="apache.org" />` is set and **cordova-plugin-device** is installed.

I do not believe this is related to the plugin because simply adding 
`<preference name="AndroidInsecureFileModeEnabled" value="true" />` resolves the issue.

Here is a complete very minimal app replicating the issue:
https://github.com/codeconsole/cordova-bug

However, you can break any app by just adding this preference `<preference name="hostname" value="apache.org" />`  and installing **cordova-plugin-device**.

This is possibly related to this commit:
https://github.com/apache/cordova-android/pull/1275/files#diff-c2eeba9559f1ec42b3e90bd1531f3389a2aab9d199752d4cca70fbf489d92ca0R88

in which https is hard coded.

**Comment by lirancr** [comment]
@erisu 

any chance to share a like to the PR ? just to verify it solve the use case in the meanwhile ?

**Comment by erisu** [comment]
Sorry, I got distracted and forgot to submit the PR. I just linked to PR to this ticket, seen above.
