### ISSUE TITLE
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01

### ISSUE THREAD

**Issue by zoranmil** [apache/cordova-android#1331]
# Bug Report

## Information

BUILD SUCCESSFUL in 15s
2 actionable tasks: 2 executed
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01

### Version information

windows 10 64bit
cordova android@10.1.0
Android Studio Artic Fox 2020.3.1

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
This is a warning starting from AS Artic Fox, so I assume it requires API 31 tooling to address properly, thus I've put this in the 11.x milestone.

**Comment by Sumanmali019** [comment]
Facing same issue

**Comment by ram15686** [comment]
codova app perfectly work in api level 29 but update my system for api level 30 
java 11
gradle 7.1.1
build tool 30.0.3 
then facing this issue . app build but some pugine not properly work please help me 

`C:\Users\Education\Desktop\my app\myApp>cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Education\AppData\Local\Android\Sdk (DEPRECATED)
Using Android SDK: C:\Users\Education\AppData\Local\Android\Sdk
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 51s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :CordovaLib:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 14m 5s
48 actionable tasks: 48 executed
Built the following apk(s):
        C:\Users\Education\Desktop\my app\myApp\platforms\android\app\build\outputs\apk\debug\app-debug.apk
`

**Comment by breautek** [comment]
I can reproduce this on current release but does not produce in current master.

I'm guessing underlying android dependencies for API 31/32 have corrected this issue. Closing.

**Comment by SirFluffDev** [comment]
This still happens to me using android SDK 31 and 32.

**Comment by breautek** [comment]
> This still happens to me using android SDK 31 and 32.

I would suggest opening a new issue with the relevant information.
