### ISSUE TITLE
`window.open` opens the url in webview instead of system browser.

### ISSUE THREAD

**Issue by The-White-Fang** [apache/cordova-android#1341]
# Bug Report

## Problem
`window.open(url, '_system')` opens the `url` in webview.

### What is expected to happen?
The URL should open in the system's default browser.

### What does actually happen?
The URL opens in the same system webview.

## Information

I recently moved to android 10 as it is required by google play to upload the builds with minimum target api of 30 i.e. Android 10. Earlier I was using window.open to open some pages that I didn't want to open in main webview and that were not supported by the inappbrowser. After upgrading to 10, I noticed it no longer works.

### Command or Code
beforeload = (params, callback) => {
        if (params.url.startsWith('https://api.whatsapp.com/')) {
	        window.ref.executeScript({ code: 'window.location.href = "/"' });
	        window.open(params.url, '_system');
        } else {
	        callback(params.url);
        }
};

### Version information

cordova: 10.0.0
android: 10.1.0
target api: 30

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by WuglyakBolgoink** [comment]
@The-White-Fang you need IAB plugin to open links on a system browser!

**Comment by The-White-Fang** [comment]
It worked in android 9.x

**Comment by siju-s** [comment]
Even with IAB plugin, link opens in webview instead of browser. Used to work fine on `cordova-9.0`. Any workaround?

**Comment by jcesarmobile** [comment]
InAppBrowser plugin removed the overwrite of window.open long ago, you can reenable it by doing 
```
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    window.open = cordova.InAppBrowser.open;
}
```
