### ISSUE TITLE
Entry added to `allowedNavigations` for the `WebViewAssetLoader` disregards logic from preferences

### ISSUE THREAD

**Issue by usernuno** [apache/cordova-android#1343]
# Bug Report
The change that adds an entry to `allowedNavigations` for the added `WebViewAssetLoader` disregards logic from preferences.

## Problem
The problem is in the change introduced here: https://github.com/apache/cordova-android/pull/1275

The `CordovaPreferences` object is never filled, so it has no keys/values. Therefore lines 87 and 88 in the diff above always use the default values.

In the end, no matter the values of preferences `AndroidInsecureFileModeEnabled` and `hostname`, `https://localhost` is always added to the `allowedNavigations`.

### What is expected to happen?
Only when `AndroidInsecureFileModeEnabled` is false, should an entry be added to `allowedNavigations`. That entry must use the value from `hostname` when provided.

At least it was what I could gather from the code.

### What does actually happen?
`https://localhost` is always added to the `allowedNavigations`, and no entry based on `hostname` is added.

### Version information
Cordova-android 10.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
It was fixed here 
https://github.com/apache/cordova-android/pull/1332
