### ISSUE TITLE
PackageType flag ignored with cordova-android 10 with release builds

### ISSUE THREAD

**Issue by dtarnawsky** [apache/cordova-android#1344]
# Bug Report

## Problem
If you call `cordova build android --release --packageType=apk` the resulting file is of type .aab (when cordova-android is 10.x)

### What is expected to happen?
The --packageType flag should control whether an apk or aab file is generated. If the packageType flag is omitted it should default to apk (according to documentation) but it generates .aab files for release builds.

### What does actually happen?
An .aab file is generated (regardless of the --packageType flag)

### Command or Code

`cordova build android --release --packageType=apk`

### Environment, Platform, Device

Only happens when cordova-android is version 10 or higher

### Version information

Cordova CLI: 10.0.0
Cordova Platforms: android 10.1.0, ios 6.2.0
Android SDK Tools : 26.1.1 (/Users/damian/Library/Android/sdk)
ios-deploy        : 1.11.4
ios-sim           : 8.0.2
NodeJS            : v14.17.0 (/usr/local/bin/node)
npm               : 7.23.0
OS                : macOS Big Sur
Xcode             : Xcode 12.5.1 Build version 12E507

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This is a big gotcha... but You're missing a set of  of -- to signal passing to a sub process.

E.g. `cordova build android --release -- --packageType=apk`

**Comment by dtarnawsky** [comment]
Ah. That is too easy to fix! and too easy to assume is broken :(

I'll close the issue out.

**Comment by jpike88** [comment]
after many sacrifices to the android gods and hours of agony, my journey has come to an end.

goddamit.
