### ISSUE TITLE
Android@9.0.0-9.10 ,Native SO complile bugs

### ISSUE THREAD

**Issue by bonabaa** [apache/cordova-android#1346]
### Issue Type

- [x] Bug Report 
- [ ] Feature Request
- [ ] Support Question

## Description
for android platform of version 9.0.0 & 9.1.0
I make a native code and complie a so file int o the plugin (xxx)  to invoke by the cordova develop inovke.
1 .  for xxx cordova plugin, use the cordova doc , to edit the plugin.xml , to copy the SOs into the DIR,when exe 'cordova plugin add xxx' command,  but the files will locate on the /app/libs of  project root DIR. why can not move these files into the DIR  app/src/main/jniLibs/?
		<lib-file src="src/android/armeabi-v7a/libCdaCore.so" target-dir="app/src/main/jniLibs/armeabi-v7a" arch="device" />
		<lib-file src="src/android/arm64-v8a/libCdaCore.so" target-dir="app/src/main/jniLibs/arm64-v8a" arch="device" />

2. add the xxx plugin( which contains some SOs file of native code) into name testyy project,  add no problem,when complie the project testyy, the android studio tell me 'No version of NDK matched the requested version 21.0.6113669', then I edited the android studio setting  of  androd gradle plugin  '4.0.0' to 4.1.3, it is work well(not reqiure to install NDK ) . I think these some bugs to support native cordova plugin. my suggestion update androd gradle plugin from 4.0.0 to 4.1.3 of android@9.0.0 , android@9.1.0 . because the old version like android@8.0.0 was not problem. please check it .

3. ## Information

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

![20210528111026](https://user-images.githubusercontent.com/34535476/119924001-64685400-bfa5-11eb-93e1-b0d992cc9840.png)

**Comment by breautek** [comment]
We won't be updating AGP from 4.0 to 4.1 in 9.x as that is a breaking change.

AGP updates are always done in major releases and in general, we don't maintain older releases outside of serious security issues.

You should be able to install and use a specific NDK version by using android's SDK manager if the required NDK version is different from AGP's default.
