### ISSUE TITLE
HTML5 Audio and Video not working on app background and lock screen.

### ISSUE THREAD

**Issue by shreeshailsg** [apache/cordova-android#1358]
# Bug Report
HTML5 audio and video are not working on app background and lock screen.

## Problem
Android project built on cordova-android 9.0 version. When user plays audio and video on webview it's working fine but as soon as app goes to background/lock it stops playing. And even music controls are not showing up on lock screen.

### What is expected to happen?
Even though app goes to background or on lock screen user has to get music controls to play/pause the media.

### What does actually happen?
Music controls are not showing up and media stops playing on app background and lock screen

### Command or Code

<video #videoPlayer class="html5-player" width="100%" controls controlsList="nodownload" playsinline [src]="videoUrl">
Your browser does not support the video tag.
</video>

<video #audioPlayer class="html5-player" width="100%" controls controlsList="nodownload" playsinline [src]="videoUrl" type="audio/mp3">
Your browser does not support the video tag.
</video>

### Environment, Platform, Device

Android, On all android devices.

### Version information

cordova-android v9.0, 
Android Studio v4.0.1
Operating System: Mac OS 10.14

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
HTML5 features are part of the webview engine, not something that Cordova implements. If an HTML5 feature isn't working as expected, then you should post an issue against the webview (e.g. Chrome Bug Tracker).

I'm fairly sure that HTML5 audio/video doesn't support backgorund playback in the Android Webview (unlike in the chrome browser). If you want audio/video playback while in background, you may want to look into the [Media](https://github.com/apache/cordova-plugin-media) plugin, which I _believe_ has the capability of background playback.

Closing as not-a-bug.
