### ISSUE TITLE
Cannot append permission into the AndroidManifest file

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-android#1359]
# Bug Report

### What is expected to happen?

add custom permissions from project config.xml (not from plugin)

### What does actually happen?

add in config.xml file

```xml
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/uses-permission">
            <uses-permission android:name="android.permission.CAMERA" />
</edit-config>
```

or

```xml
<edit-config file="app/src/main/AndroidManifest.xml" mode="overwrite" target="/manifest/uses-permission">
            <uses-permission android:name="android.permission.CAMERA" />
</edit-config>
```

then remove android platform folder and build app again.

in result manifest file I can see `permission.CAMERA` but both modes (`merge` & `overwrite`) remove `permission.INTERNET` from the manifest file (or maybe any other first permission in the whole list)

Is it possible to `append` a new permissions into the manifest file?

### Version information

- `cordova-android@10.1.1`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by WuglyakBolgoink** [comment]
related to https://github.com/apache/cordova-plugin-camera/issues/763

**Comment by WuglyakBolgoink** [comment]
fyi @dpogue / @breautek

**Comment by breautek** [comment]
You're targeting `uses-permission` where `edit-config` edits the target in place.

I think what you're after is [config-file](https://cordova.apache.org/docs/en/11.x/plugin_ref/spec.html#config-file) instead, which does insertions.

> The config-file element only allows you to append new children to an XML document tree. The children are XML literals to be inserted in the target document.

The syntax is slightly different, see the example in the docs. Let me know of this helps.
