### ISSUE TITLE
`add android` command changes package.json

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-android#1360]
# Bug Report

## Problem

I'm trying to upgrade all my plugins to latest versions.
In doing so some plugins needs to be taken from github repo to facilitate the transition.
When I run `cordova platform add android` two things happen
1. package.json gets updated with github:...
2. Some plugin fetch do not happen, or fail thus causing the app to crash

### What is expected to happen?
No changes to package.json
All plugins should be fetched like in version 9.x

### What does actually happen?
package json gets some weird edits in it
Some plugins are missing

## Information
To reproduce you can use my repo here:
https://github.com/IsraelHikingMap/Site/tree/7f575d0fe8e9afa88cc0f4157a37842ffb6d9447
Go to `IsraelHiking.Web`
run npm install
run npx cordova add android
Look at the git diff for the package.json file and the output of the command, both are weird.

### Command or Code
`cordova platform add android`

### Environment, Platform, Device
macOS, node v14.17.0 npm 7.24.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by WuglyakBolgoink** [comment]
@HarelM how you install/update plugins and platform. I see no problems in your package.json

**Comment by HarelM** [comment]
The problem is not with the current state of the file but what happens after running the add command...

**Comment by breautek** [comment]
> No changes to package.json

the add command will ultimately make edits to `package.json` for 2 reasons:

1. It will call on NPM behind the scenes, which will manipulate your `package.json` accordingly
2. Cordova will also change `cordova` object and rewrite your `package.json`.

If you had your `package.json` ordered or formatted a specific way, due to the nature of JavaScript objects having their keys in an nondeterministic order, the file may change or be re-ordered.

> package.json gets updated with github:...

This is something that [NPM](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major) does when it finds a GitHub repo.

> Git dependencies on known git hosts (GitHub, BitBucket, etc.) will always attempt to fetch package contents from the relevant tarball CDNs if possible, falling back to git+ssh for private packages. resolved value in package-lock.json will always reflect the git+ssh url value. **Saved value in package.json dependencies will always reflect the canonical shorthand value.**

I've attempted to clone the app to determine what you're seeing exactly, but `IsraelHiking.Web/` doesn't appear to contain a cordova project (I see the `config.xml` file but no `www` folder and Cordova seems to believe that the folder is not a cordova project.

> Some plugin fetch do not happen, or fail thus causing the app to crash

All plugin fetching is handled by NPM, so if you're experiencing plugin fetch issues, I'd suggest ensuring that you're using the latest NPM version available including any patch versions. It may help to also delete `node_modules` as well as `package-lock.json` as sometimes having a package existing in either or can cause issues in my experience, particularly when trying to upgrade them.

Closing because there doesn't seem to be any issues related to the Cordova codebase.

**Comment by HarelM** [comment]
You need to call npm run build:cordova to create the www folder.
I'm aware of the npm formatting, but it's not it as I run npm install and it doesn't change the format.
I'm pretty sure there is a problem with cordova code base.
I would appreciate if this issue remains open.
I'm available and active in cordova slack if more info is needed.

**Comment by erisu** [comment]
I am still unsure how this is an issue of Cordova... We do not format the npm specs.

Under the covers we call the `npm` binary directly with the information supplied by the user.

The only packages we might use within Cordova is `npm-package-arg` and `pacote` to try and `determine the name from the spec using npa.` These npm packages are npm cli internal packages and managed by npm.

Again nothing we created or modified.

Even if you test "npm install" with the `git+https` url, it will format it,

E.g.

* **Create Cordova Project**

  ```
  cordova create cordovaTest com.foobar.cordovaTest cordovaTest && $_
  ```

* **Add Android Platform**

  ```
  cordova platform add android
  ```

* **Add `git+https` package with npm**

  In this case we are showing how npm performs the changes... We are completely bypassing Cordova CLI.

  ```
  npm install -D "git+https://github.com/apache/cordova-plugin-file-transfer.git#88e39df8a547ba321ed02ec5dde4df68544bf09d"
  ```

* **Check `package.json`**

  We will notice the package path has changed to `"github:apache/cordova-plugin-file-transfer#88e39df8a547ba321ed02ec5dde4df68544bf09d"`


If I manually change the `package.json` back to `git+https`, perform a cleanup of the directory,

```
rm -rf node_modules platforms plugins package-lock.json
```

and then perform a recheck out of the packages using `cordova prepare`, the `git+https` still remains.

**Comment by HarelM** [comment]
I'm not sure I understand the push back here.
Here are the screenshots of the diff created in my package.json (not lock file) after I run the `add` command on a clean clone of my project:
1. Added new line at the end of the file:
![image](https://user-images.githubusercontent.com/3269297/168991544-92303fe6-574a-4253-bb4b-a53de8ccde1f.png)
2. A plugin with a "regular" version was changed to a git link repo version (might be related to a plugin but I'm not sure a plugin should be able to change versions of other plugins):
![image](https://user-images.githubusercontent.com/3269297/168991704-b599008e-a09d-4cf6-ba2a-b1838a1480a8.png)

The first one is simply annoying, the second one is concerning from my point of view.

**Comment by HarelM** [comment]
I'm not worried about the git text link, honestly :-)
I would expect the version in my package.json to be the "respected" one I guess, and as I said, I wouldn't expect the `add` command to manipulate my package.json in this scenario.
You can say that this is a limitation of the platform, but still an issue from my point of view...

**Comment by HarelM** [comment]
While I understand the technical details that caused this and the method of operating, the facts remain the same from my perspective:
1. There's shouldn't be a newline added at the end of the file
2. Cordova should respect the version I define in the package.json and not a version from a plugin I use, even if the plugin is referencing git which npm considers newer.

For example (and this might be a very bad solution) cordova can store the package.json in memory before starting, installing all the plugins and their dependencies. After this is done overriding whatever the current package.json is with the one in memory and apply it again so that package version remain as defined.
This is probably not a good solution as I'm not taking into account all the various scenarios there are.
I prefer to define the problem statement and not the solution as I have very limited knowledge in how cordova internals work...
