### ISSUE TITLE
Sdk 31 needed but not available

### ISSUE THREAD

**Issue by MarijaPopovic** [apache/cordova-android#1364]
Hi,

When building cordova android part there is issue with this dependency
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
**The minCompileSdk (31)** specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) **is greater than this module's compileSdkVersion (android-30).**

With cordova-android@10 I've got sdk-30, but how can I have sdk-31?

**Comment by breautek** [comment]
Do you use the `cordova.plugins.diagnostic` ​plugin?

This a known issue with that plugin where it improperly pinned the version allowing it to accept breaking changes automatically. There was a raised issue at https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440 and a fix was already landed and released. See https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440#issuecomment-932098282 for more details.

If you don't use the diagnostics plugin, then I'd advise scanning through your plugin's plugin.xml or gradle files for any overrides of the `androidx.appcompat:appcompat` package

**Comment by MarijaPopovic** [comment]
Yes, I do. I did an update and I'll se the outcome. Thanks for a hint!
