### ISSUE TITLE
Android 10 Ajax https calls not working in release builds, works in debug builds

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-android#1365]
# Bug Report

## Problem
Android 10 Ajax https calls not working in **Release builds**, works in debug builds, including on physical device.
Only fails once the app is packaged as release bundle. This only affects ANDROID, there is no issue on iOS.

### What does actually happen?
readyState : 0 Ajax error

## Information
All calls are made in HTTPS. Everything works perfectly in DEBUG including on physical device.
HTTPS calls fail (readyState : 0) in RELEASE builds (bundle) for no apparent reason.
Obviously not a CORS/SSL issue since everything works perfectly in debug (.apk)
Tested with a debug bundle, extracted to .apks via bundletools, works perfectly...
Tested with standard debug APK, works perfectly.

Tested with
```
<access origin="*" />    
<allow-navigation href="*" />
<preference name="AndroidXEnabled" value="true" />
<preference name="AndroidInsecureFileModeEnabled" value="true" />
<preference name="android-minSdkVersion" value="23" />
<preference name="android-targetSdkVersion" value="30" />
<edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
</edit-config>
<resource-file src="res/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
```

this has no impact whatsoever (res/xml/network_security_config.xml)

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />  
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">api.domain.com</domain>
    </domain-config>
</network-security-config>
```

### Environment, Platform, Device
Windows 10 x64
Tested on Android 6.0.1

### Version information
Cordova Android 10.1.1
Cordova 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by globules-io** [comment]
I will answer my own question, it might save someone A LOT of time. The issue is that I'm using let's encrypt SSL certificates and I had been testing on Android 6.1.0. Following this post I just noticed that Let's Encrypt SSL certificates will not work anymore on Android < 7.1.1

**Comment by breautek** [comment]
I use lets encrypt certificates successfully with devices as far back as android 4.1.

But the server must be configured to support potentially weaker ciphers. You can use SSL Labs to test your servers for compatibility.

**Comment by globules-io** [comment]
Thanks @breautek I'm using Win-Acme here since we're on Windows Server. I'm not sure I can do much about that...

**Comment by kzimny** [comment]
Thank you @globules-io! Yes, your answer save a lot of time, although I've already stopped paying attention to time I spend to investigate this issue. Did you find a solution with the certificate? Let's Encrypt say: 

> We’re happy to announce that we have developed a way for older Android devices to retain their ability to visit sites that use Let’s Encrypt certificates after our cross-signed intermediates expire.

What should be done to get it work with Android Version < 7.1.1?

**Comment by globules-io** [comment]
@kzimny Since we didn't find any solution with WinAcme
