### ISSUE TITLE
net: ERR_UNKNOWN_URL_SCHEME with targetSdkVersion 30

### ISSUE THREAD

**Issue by benmesza** [apache/cordova-android#1366]
# Bug Report

## Problem

Use auth0 in Ionic cordova app, and when user sign in to app successfully cannot redirect to app because net: ERR_UNKNOWN_URL_SCHEME error. targetSdkVersion 29 was worked, but when upgrade to 30 get this error on Android 11 platform, but works on Android 10.

### What is expected to happen?

Successfully redirect to app on Android 11

### What does actually happen?

Get net: ERR_UNKNOWN_URL_SCHEME  error.

### Command or Code

Auth0 integration

### Environment, Platform, Device

Android 11

### Version information

Cordova CLI: 10.0.0
Cordova platform: Cordova-Android 10.1.1
Frameworks: Ionic 5 with Angular 12.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by benmesza** [comment]
> Can you provide an example of the url you're redirecting to. Do include the actual scheme, **https://** example.com/...

scheme format: io.ionic.starter://subdomain.domain.hu/cordova/io.ionic.starter
io.ionic.starter is the config.xml file widget id
My config.xml file include <allow-navigation href="*" />, <allow-intent href="*" />

**Comment by brassier** [comment]
We are noticing similar issues in our app.  Is there any suggestion/work-around?

**Comment by jpduckwo** [comment]
Have you tried moving
```
    <preference name="Hostname" value="example.example.com" />
    <preference name="Scheme" value="https" />
```
To the iOS section in config.xml. Ie 
```
    <platform name="ios">
      <preference name="Hostname" value="example.example.com" />
      <preference name="Scheme" value="https" />
```

I think those settings break stuff in cordova-android with version 10

**Comment by jcesarmobile** [comment]
You are using cordova-plugin-ionic-webview in the provided app, in that case the bug is not on cordova-android since the navigation is handled by the plugin
