### ISSUE TITLE
--packageType argument is ignored, compiles aab instead of apk

### ISSUE THREAD

**Issue by MelvilQ** [apache/cordova-android#1369]
# Bug Report

## Problem

We build our Android project with 

`cordova build android --release --verbose -- --packageType=apk --keystore=.\app-stores\android.keystore --storePassword=xxx --alias=xxx --password=xxx`

and the packageType argument is ignored.

### What is expected to happen?

Generation of an **apk**.

### What does actually happen?

Generation of an **aab**.

### Version information

cordova@9.0.0 (cordova-cli@9.0.1)
cordova-android@10.1.1
Android API level 30
Operating System: Windows

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
If you're on windows and using powershell, the workaround is to use Command Prompt instead.

Powershell doesn't appear to understand the `... -- -- ...` syntax.

**Comment by xdrkush** [comment]
> Thank you, your hint was absolutely correct. We can solve the problem by writing `"--"` instead of `--`.

No its that
`cordova -release build -- --packageType=apk`

https://github.com/apache/cordova-android/issues/1377#issuecomment-972409841
