### ISSUE TITLE
Android app won't open (java.lang.ClassNotFoundException)

### ISSUE THREAD

**Issue by antbelogurov** [apache/cordova-android#1370]
Hi.
I created app with vue quasar cordova.
debugg version works. But when you upload a file to google play, the application is installed on the phone but immediately exits. And in the console it shows such an error. What to do?
![image](https://user-images.githubusercontent.com/63599667/136019495-82ec4624-e8e5-4c14-bc51-c40d049d02e3.png)

**Comment by breautek** [comment]
Did you change your app ID?

**Comment by breautek** [comment]
Closing as stale.

> Changing App ID after the platform is added will cause issues with finding classes.

If it is indeed this issue, it will be fixed by https://github.com/apache/cordova-android/pull/1154 in our next cordova android release.
