### ISSUE TITLE
Build release apk via Cordova CLI 10.0.0

### ISSUE THREAD

**Issue by valsoray14** [apache/cordova-android#1377]
Dear Cordrova Support team,

I want to generate unsigned release apk via Cordova CLI 10.0.0. However, I receive app-release.aab bundle instead of apk by 'cordova build --release android' command. Could you please advise how to build release apk via CLI 10.0.0?

Thank you in advance!

**Comment by breautek** [comment]
use `cordova build android --release -- --packageType=apk` if you need an apk.

Alternatively you can also set your packageType via your build.json file.

See https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#signing-an-app for more information.
