### ISSUE TITLE
[Feature-Request] Ability to set GRADLE_VERSION via config.xml as a preference

### ISSUE THREAD

**Issue by mosabab** [apache/cordova-android#1378]
# Feature Request

## Feature Description

An option to set Gradle version from `config.xml` file, so the user can set GRADLE_VERSION via `config.xml` file as a preference like:
`<preference name="GRADLE_VERSION" value="7.3" />`

This can help users to integrate with latest version of Gradle before produce new version of `cordova-android`, so no need to wait until any new version of `cordova-android`.

So, if the user have the last version of Gradle at the PC, then no need to install old version (this lead for slow build).

**Comment by almothafar** [comment]
I think you can set environment variable of `CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL` with the URL of Gradle, I have that in the docker image https://github.com/capellasolutions/ionic-cordova-docker 

```docker
ARG GRADLE_VERSION
ENV CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL https\\://services.gradle.org/distributions/gradle-${GRADLE_VERSION:-7.2}-all.zip
```

**Comment by breautek** [comment]
It might not be documented but I think this is already exposed under the `GradleVersion` preference...

https://github.com/apache/cordova-android/blob/4744bfe6bfa8bfa6b6d453164b5f5b73cf254c42/lib/prepare.js#L105

**Comment by jcesarmobile** [comment]
yeah, it's already possible, but not documented, we have this issue on docs repository to track it
https://github.com/apache/cordova-docs/issues/1169

**Comment by alimhv** [comment]
You can set this property in config.xml
`<preference name="GradleVersion" value="8.4" />`

**Comment by jcesarmobile** [comment]
Yeah, it's now documented 
https://cordova.apache.org/docs/en/12.x/config_ref/index.html#preference

Note that is not recommended to change the value

> This preference is primarily for cordova development, for testing upcoming versions of the Android SDK. Changing this has a high risk of breaking builds as newer build tools frequently introduce breaking changes.
