### ISSUE TITLE
Why app shows in chrome remote debugging?

### ISSUE THREAD

**Issue by balaji-subramaniyam** [apache/cordova-android#1379]
Hi **team**, I have facing the issue,  I don't need my app to see in  **Chrome Remote debugging**. I don't know the exact solution, but i tried this, I just add this code in my config.xml 
```
 <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:debuggable="false" />
        </edit-config>
 </platform>
``` 
Even after build my app with this above code my app is shown in the ``` Chrome://inspect/#devices ```. 
How to solve this issue?
Thanks in advance :)

**Comment by takuyaW** [comment]
When you check the built apk with android studio analyzer, what are the settings in the manifest file?
The "android:debuggalbe" should be false by default.

https://developer.android.com/studio/debug/apk-analyzer

**Comment by erisu** [comment]
If you are building with one of the two following commands, then it will always set debuggable to true. 

```
cordova build android --debug
cordova build android
```

`true`, is the default value for debug builds. This is not something Cordova is overriding.

[Android Developer Docs - Configure build types](https://developer.android.com/studio/build/build-variants#build-types)

When you build for release, this value is not set and defaults to `false`. You can build for release using the following command:

```
cordova build android --release
```

Depending on which version of Cordova-Android you using, the above command will create an `aab` file format by default which is required by Google Play Store. If you need an APK for testing locally, use the following command:

```
cordova build android --release -- --packageType=apk
```

**Comment by balaji-subramaniyam** [comment]
Thank you **@takuyaW** and **@erisu** for your reply. Let me try it and if it works fine i close the issue
