### ISSUE TITLE
Error : Invalid character in entity name when &amp; is in the <name>

### ISSUE THREAD

**Issue by tpneumat** [apache/cordova-android#1380]
# Bug Report

## Problem

Can not include `&amp; ` in the cordova app name without causing a build failure to occur when strings.xml is created.

### What is expected to happen?

If I have properly escaped the & in the config.xml, it should also apply to the strings.xml.  

### What does actually happen?
It seems the `&amp;` is converted back to `&` when strings xml is created, perhaps in prepare.js.  This causes the cordova add command to fail.

## Information

Given the following config.xml
```
<?xml version='1.0' encoding='utf-8'?>
<widget id="xxx.xxx.xxxx" version="6.2.2" android-versionCode="622000062" versionCode="62" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:gap="http://phonegap.com/ns/1.0">

    <name>TIMING &amp; TRACKING</name>
    <description>
        Timing APP
    </description>
```

### Command or Code
Run the command to create the cordova project

```
cordova platform add android@10.1.1
Using cordova-fetch for cordova-android@10.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: me.rtrt.app.tsa
	Name: TIMING & TRACKING
	Activity: MainActivity
	Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.1
Invalid character in entity name
Line: 3
Column: 37
Char:
```

Then, checking the strings.xml that was created, you can find there is a non-escaped & 

/platforms/android/app/src/main/res/values/strings.xml

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- App label shown within list of installed apps, battery & network usage screens. -->
    <string name="app_name">TIMING & TRACKING</string>
    <!-- App label shown on the launcher. -->
    <string name="launcher_name">@string/app_name</string>
    <!-- App label shown on the task switcher. -->
    <string name="activity_name">@string/launcher_name</string>
</resources>
```

### Environment, Platform, Device
N/A

### Version information

Android  Cordova 10.1.1 
MacOs 10.15.7 (catalina)

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by tiagoappereira** [comment]
Adding a bit of context on what I believe caused the issue: on cordova-android 10, a [change](https://github.com/apache/cordova-android/commit/13bd3f4a9f8541147dcd2e458390cb34774e73bf#diff-2d637acb73216ac5e27baf300c9dd71a6b514f304941ebaaa13f30615fe4932dL207) was made that broke the use case. Bringing the removed `replace` (or adapt it to only transform the `&` character) would most likely fix the issue.

![image](https://user-images.githubusercontent.com/36884956/143606021-2655bcb9-0a25-4236-9cf7-6c5586c30984.png)
 
The error is not caused in that file but it was disclosed by that linked change. The error in hands is related to the way the name is written to Android’s `strings.xml` ([here](https://github.com/apache/cordova-android/blob/13bd3f4a9f8541147dcd2e458390cb34774e73bf/lib/create.js#L258)), which causes the error when parsing it, in [prepare.js](https://github.com/apache/cordova-android/blob/05e3e3cf8dcceb17aff945328ecd60ad69c43dc2/lib/prepare.js#L263) file.

**Comment by breautek** [comment]
PR, preferably with an added test case is welcome.

**Comment by saggio89** [comment]
Same, I need this fix in -- is there plans to merge this pull request?

**Comment by pkwiatkowski0** [comment]
Also looking forward for this one

**Comment by up2-date** [comment]
@saggio89 thx for tip

**Comment by pkwiatkowski0** [comment]
@saggio89 Thanks, but we can't use `*nightly*` versions in production.
Does someone know when can we expect final 10.1.2 version?
