### ISSUE TITLE
Application Error. connection to server was unsuccessful on release apk 

### ISSUE THREAD

**Issue by yashp98** [apache/cordova-android#1381]
# Bug Report

## Problem
When I upgraded cordova-android@9.1.0 to cordova-android@10.1.1 on release apk getting applicaton error but debug apk is working good .but when i again switch to cordova 9.1.0 every thing is working good.i already remove cordova-whitelist-plugin from app. cordova-plugin-proguard plugin crash app. 

 
### What is expected to happen?
-release apk should be work with android sdk-31 

### What does actually happen?
-when i upgrade my project to cordova android 10.1.1 with android sdk-31 . release apk is crash on open app and getting 
Application Error. connection to server was unsuccessful.

### Version information

Ionic:

   Ionic CLI                     : 6.18.1 
   Ionic Framework               : @ionic/angular 5.9.1
   @angular-devkit/build-angular : 12.1.4
   @angular-devkit/schematics    : 12.1.4
   @angular/cli                  : 12.1.4
   @ionic/angular-toolkit        : 4.0.0

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : android 10.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 25 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\Deacons\AppData\Local\Android\Sdk)
   NodeJS            : v14.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.1.4
   OS                : Windows 10

plugins 
   "cordova-open-native-settings": "^1.5.2",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-camera": "^6.0.0",
    "cordova-plugin-contacts-x": "^2.0.0",
    "cordova-plugin-facebook-connect": "^3.2.0",
    "cordova-plugin-firebasex": "^13.0.1",
    "cordova-plugin-inappbrowser": "^5.0.0",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-proguard": "^2.2.0",
    "cordova-plugin-safariviewcontroller": "^2.0.0",
    "cordova-plugin-sign-in-with-apple": "^0.1.2",
    "cordova-plugin-splashscreen": "^6.0.0",
    "cordova-plugin-whitelist": "^1.3.5",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Ayan-Kumar-Saha** [comment]
@yashp98 I am facing the same problem. What is the fix?
