### ISSUE TITLE
Kotlin version not used for plugin

### ISSUE THREAD

**Issue by craig-at-rsg** [apache/cordova-android#1383]
# Bug Report

### What is expected to happen?
The GradlePluginKotlinVersion preference should be used for the entire build.

### What does actually happen?
The build.gradle file has a kotlin version hardcoded, so the value set with GradlePluginKotlinVersion isn't used for the entire build.

## Information
When using `<preference name="GradlePluginKotlinVersion" value="1.6.0" />` in my config.xml, my custom plugin fails with:

`Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.`

Manually setting the ext.kotlin_version in the build.gradle files gets my project building successfully. 

### Command or Code
cordova build android

### Environment, Platform, Device
Mac, Android, any.

### Version information
Not sure if it's limited to this version, but we're currently on cordova-android 9.1.0.

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
cordova-android@10 has a complete rewrite of how build variables are managed, so this issue shouldn't be a problem on cordova-android@10. I'd suggest upgrading to cordova-android@10 if possible. A backport release won't be made (although feel free to fork cordova-android yourself to backport a patch to cordova-android@9 if this is a blocking issue and cordova-android@10 upgrade isn't feasible).

For this reason I'll be closing this ticket. However, if you find that this issue still exists on cordova-android@10, we can reopen this issue and update the description accordingly.
