### ISSUE TITLE
Error 'App not Installed' use --packageType=apk flag

### ISSUE THREAD

**Issue by eviv3k** [apache/cordova-android#1387]
# Bug Report

## Problem
If use `cordova build android --release -- --packageType=apk` then an apk file is generated.  (when cordova-android is 10.x)

I get the error message "App not installed" when I try to install the .apk. It runs fine (download the APK from the play store).

### What is expected to happen?
The --packageType=apk flag should control an apk file is generated. I get the error message "App not installed".

### What does actually happen?
The --packageType=apk flag should control an apk file is generated. I need to test a release build.

### Command or Code
`cordova build android --release -- --packageType=apk`

### Environment, Platform, Device
Only happens when cordova-android is version 10 or higher

### Version information
Cordova CLI: 10.0.0
Cordova Platforms: android 10.1.0
Android SDK Tools : 30.0.3
NodeJS : v14.16.1
npm : 6.14.12
OS : Window

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by JLWINC** [comment]
+1 same error , do you find any solution ?

**Comment by JLWINC** [comment]
@eviv3k  do you find any solution ?

**Comment by breautek** [comment]
There seems to be some kind of disconnect. `cordova build...` responsibility is build a distributable binary in either a form of a bundle or apk. Which it sounds like it's doing successfully.

> "App not installed"

What is showing this error message and what is being done leading up to this error message? (e.g. are you using `adb` or `cordova run` or some other method of installing the apk?)

**Comment by dpchami** [comment]
same happen to me
Any solution available?

**Comment by eviv3k** [comment]
@JLWINC @dpchami 
The complete way we had to do:

1. Download `bundletool-all-1.8.2.jar` from [this link](https://github.com/google/bundletool/releases), download the latest version available.

2. Create an app bundle using cordova `cordova build android --prod --release` 

3. Copy the bundletool jar to some location and get its path. In my case its `C:\Users\eviv3k\Desktop\bundletool-all-1.8.2.jar`

4. Use this command: `java -jar "BUNDLE_TOOL_JAR_PATH" build-apks --mode=universal --bundle="BUNDLE_PATH" --output=YOUR_OUTPUT_NAME.apks` In my case it will be `java -jar "C:\Users\vivek.singh\Desktop\bundletool-all-1.8.2.jar" build-apks --mode=universal --bundle="C:\Users\vivek.singh\Desktop\app-release.aab" --output="C:\Users\eviv3k\Desktop\my_app.apks" --ks="D:\Works\Ionic\B23\certificates\my-release-key.keystore" --ks-key-alias=alias_name"`

5. This will create a file `my_app.apks`, rename it to .zip `my_app.zip`, extract this file, and done You will have `universal.apk`.

**Comment by gmalignon** [comment]
Thank you so much!!! I was trying to figure out for hours why APKs generated were not working any more. 
This really saved me, it works!!!

**Comment by breautek** [comment]
> OS : Window

On windows, particularly with powershell, instead of

`cordova build android --release -- --packageType=apk`

You need to wrap the intermediate `--` in quotations, like so:

`cordova build android --release "--" --packageType=apk`

Closing this issue cause I don't believe this is an actual bug.

**Comment by mkurzweil** [comment]
works also for mac user: `cordova build android --release "--" --packageType=apk
`

**Comment by rajiv-eulogik** [comment]
> @JLWINC @dpchami The complete way we had to do:
> 
> 1. Download `bundletool-all-1.8.2.jar` from [this link](https://github.com/google/bundletool/releases), download the latest version available.
> 2. Create an app bundle using cordova `cordova build android --prod --release`
> 3. Copy the bundletool jar to some location and get its path. In my case its `C:\Users\eviv3k\Desktop\bundletool-all-1.8.2.jar`
> 4. Use this command: `java -jar "BUNDLE_TOOL_JAR_PATH" build-apks --mode=universal --bundle="BUNDLE_PATH" --output=YOUR_OUTPUT_NAME.apks` In my case it will be `java -jar "C:\Users\eviv3k\Desktop\bundletool-all-1.8.2.jar" build-apks --mode=universal --bundle="C:\Users\eviv3k\Desktop\app-release.aab" --output="C:\Users\eviv3k\Desktop\my_app.apks" --ks="D:\Works\certificates\my-release-key.keystore" --ks-key-alias=alias_name"`
> 5. This will create a file `my_app.apks`, rename it to .zip `my_app.zip`, extract this file, and done You will have `universal.apk`.

This one works, above all didn't work for me. May be some cli issue.

**Comment by TotomisPanos** [comment]
Bump! This fixed my problem!!!

**Comment by ParisMichael** [comment]
You saved my life too!!!
A million thanks a million :)

**Comment by TotomisPanos** [comment]
> @JLWINC @dpchami The complete way we had to do:
> 
> 1. Download `bundletool-all-1.8.2.jar` from [this link](https://github.com/google/bundletool/releases), download the latest version available.
> 2. Create an app bundle using cordova `cordova build android --prod --release`
> 3. Copy the bundletool jar to some location and get its path. In my case its `C:\Users\eviv3k\Desktop\bundletool-all-1.8.2.jar`
> 4. Use this command: `java -jar "BUNDLE_TOOL_JAR_PATH" build-apks --mode=universal --bundle="BUNDLE_PATH" --output=YOUR_OUTPUT_NAME.apks` In my case it will be `java -jar "C:\Users\eviv3k\Desktop\bundletool-all-1.8.2.jar" build-apks --mode=universal --bundle="C:\Users\eviv3k\Desktop\app-release.aab" --output="C:\Users\eviv3k\Desktop\my_app.apks" --ks="D:\Works\certificates\my-release-key.keystore" --ks-key-alias=alias_name"`
> 5. This will create a file `my_app.apks`, rename it to .zip `my_app.zip`, extract this file, and done You will have `universal.apk`.

Bump! This fixed it! Works great
