### ISSUE TITLE
make cordova jar

### ISSUE THREAD

**Issue by mzelecom** [apache/cordova-android#1389]
Hi .
refer to https://cordova.apache.org/docs/en/2.8.0/guide/cordova-webview/android.html 
cd into /framework and run ant jar to build the cordova jar (it will create the .jar file in the form cordova-x.x.x.jar in the /framework folder)
but when use  ant jar.
it say Buildfile: build.xml does not exist!

**Comment by dpogue** [comment]
You're looking at the docs for Cordova 2.8.0, which is almost 10 years out of date.

To embed Cordova as a framework in an existing Android project, you should install it as a Gradle dependency from Maven: https://mvnrepository.com/artifact/org.apache.cordova/framework

**Comment by mzelecom** [comment]
thanks.i download it.size is 140 k.is it ok?i think the same as crosswalk it need embed engine.
crosswalk size is 25 M.but it is not working on target sdk 29.

**Comment by dpogue** [comment]
Cordova uses the Android System WebView, which is part of the Android operating system and powered by Chrome.
Crosswalk is a custom build of the entire Chrome webview, which is why it's so large.

**Comment by mzelecom** [comment]
is cordova better than webview.
i used webview for load html5 game .but in some devise it is slow.
if i used cordovaview solve my problem?
do you have any app to test?

**Comment by dpogue** [comment]
Cordova is a wrapper around the system webview, so it probably won't make any difference
