### ISSUE TITLE
Fix error message when installed build tools version greater than MIN_BUILD_TOOLS_VERSION + 1

### ISSUE THREAD

**Issue by cdmahoney** [apache/cordova-android#1391]
# Bug Report

## Problem
I have build tools 32 installed. Compiling an android application using cordova-android 10.1.1 fails with the message:

This is clearly misleading and led me to waste a fair amount of time trying to track down the real problem

### What is expected to happen?
Compilation should fail and display an error message indicating the required versions of build tools, something like
`No usable build tools found. Android build tools version should be between 30.0.3 and 31.0.0.`

### What does actually happen?
Compilations fails with the message:
`No installed build tools found. Install the Android build tools version 30.0.3 or higher.`

## Information

There are related issues about the compilation failing, but they don't address the problem of the misleading error message:
https://github.com/apache/cordova-android/issues/1288
https://github.com/apache/cordova-android/issues/1335

### Command or Code
cordova compile android

### Environment, Platform, Device

Windows 10.

### Version information

Cordova cli 11.0.0
Cordova android 10.1.1

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by jmarshall-com** [comment]
I had this same problem and finally found the problem in `cordova.gradle`, line 57:

`def maxVersion = new Version((minBuildToolsVersion.getMajor() + 1) + ".0.0")`

... and then line 62:

`.findAll { it.isHigherThan('0.0.0') && it.isLowerThan(maxVersion) }`

Is there a good reason for setting a `maxVersion` to be no more than 1 major version higher than `minversion`?  At a minimum, the error message should change to reflect what the highest allowed version is, not just say "version 30.0.3 or higher."  I spent a lot of time tracking this down.

I'm using Cordova 11 with build tools 32, on a brand new Mac mini.

Thanks!

**Comment by breautek** [comment]
In regards to the error message, it's definitely an oversight. It should be more descriptive.

The code in question attempts to automatically find the latest version of build tools that is installed, but it should not automatically choose the next major version. Doing so is error prone as major version jumps generally indicate some sort of breaking change.

`android-buildToolsVersion` preference should forcefully allow a particular build tools version but changing the build tools version will likely cause build issues.

**Comment by jmarshall-com** [comment]
> The code in question attempts to automatically find the latest version of build tools that is installed, but it should not automatically choose the next major version. Doing so is error prone as major version jumps generally indicate some sort of breaking change.
> 
> `android-buildToolsVersion` preference should forcefully allow a particular build tools version but changing the build tools version will likely cause build issues.

Gotcha, thanks.  It's indeed working now with version 30.0.3 .

**Comment by bhandaribhumin** [comment]
@breautek  found same issue after changed SDK tools to 30.+
https://github.com/apache/cordova-android/issues/1399#issuecomment-1046047288

**Comment by breautek** [comment]
I've resolved this by rewording the the error message to something like:

> * What went wrong:
A problem occurred evaluating script.
> No installed build tools found. Please install the Android build tools version 30.0.3.

I left it open ended so that the error message will ask for the minimum/recommended version that Cordova uses. Users can still install an alternate version for testing/if they know what they are doing using the preferences.
