### ISSUE TITLE
cordova prepare android @10.x.x fails, on Windows, with \cordova\version is not recognized as an internal or external command

### ISSUE THREAD

**Issue by simonjmartin** [apache/cordova-android#1392]
# Bug Report

## Problem

After upgrading to v10 when I run cordova prepare android the process fails with 
"...\platforms\android\cordova\version"' is not recognized as an internal or external command"

### What is expected to happen?

The app should be prepared for android without error

### What does actually happen?

the process fails with 
"...\platforms\android\cordova\version"' is not recognized as an internal or external command"

## Information

Issuing the command in my terminal produces the same error, but as it looks like it's trying to invoke the file if I prepend the line with 'node' then the version is correctly returned and there are no errors.
If I downgrade from v10.x to v9 and compare the folder contents, version.bat has been removed, which was part of https://github.com/apache/cordova-ios/pull/1180 also https://github.com/apache/cordova-ios/pull/1180#issuecomment-962008827
As a workaround I have copied version.bat from the v9 folder and paste it into the folder after reverting to v10.1.1 - but this shouldn't be necessary. 
This is only an issue on Windows, macs seem to respect the shebang #!/usr/bin/env node statement at the top of the plain version file

### Command or Code

cordova prepare android

### Environment, Platform, Device

Windows 10

### Version information

Android Cordova 10.1.1
Windows 10
npm 6.14.13
node 14.17.1
Powershell 7.2.0 or regular Windows cmd

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Is there any other information about your environment you can share?

I just tested this in a windows 10 environment on a simple hello world app, which doesn't reproduce the issue.

**Comment by breautek** [comment]
duplicate: https://github.com/apache/cordova-android/issues/1395
