### ISSUE TITLE
Application Error. connection to server was unsuccessful on release apk

### ISSUE THREAD

**Issue by Ayan-Kumar-Saha** [apache/cordova-android#1404]
# Bug Report

## Problem
I am working on an Angular + Cordova application. Everything seems to work fine in the debug build. No issues with the application. However, whenever I am trying to build a release APK, the build gets successful. But the application doesn't open and crashes with the following screen.

![1646995942083](https://user-images.githubusercontent.com/51525248/157867041-6498494e-129f-426e-9ab7-cf6362b4a264.JPEG)

### What is expected to happen?
The application should seamlessly work as a debug build and release build.

### What does actually happen?
Earlier it worked fine with `cordova-android@7.1.4` but after I upgrade to `cordova-android@^8.1.0`, I am facing this problem.

### Environment, Platform, Device

Angular

@angular-devkit/build-angular: ~13.2.2
@angular/core: ~13.2.0
@angular/cli: ~13.2.2

Cordova:

- cordiva CLI - 11
- cordova-android - 8.1.0

System:

NodeJS : v14.17.3
npm: 6.14.16
OS: macOS Monterey 12.2.1

### Version information

- Cordova plugins -
    "com.cordova.plugins.cookiemaster": "^1.0.1",
    "cordova-android": "^8.1.0",
    "cordova-ios": "^6.1.0",
    "cordova-plugin-app-version": "^0.1.13",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-inappbrowser": "^4.1.0",
    "cordova-plugin-ios-camera-permissions": "^1.2.0",
    "cordova-plugin-proguard": "^2.2.0",
    "cordova-plugin-splashscreen": "^5.0.4",
    "cordova-plugin-uniquedeviceid": "^1.3.2",
    "cordova-plugin-whitelist": "^1.3.5",
    "cordova-sqlite-storage": "^6.0.0",

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to the most recent version
- [x] I included all the necessary information above

**Comment by Ayan-Kumar-Saha** [comment]
I have found out the issue. The problem is with the 'cordova-plugin-proguard'. Once I remove it, everything is working fine. Any suggestion for this?

**Comment by breautek** [comment]
Proguard works by obfuscating the native code, changing the method symbols, which will likely break some cordova code which calls methods dynamically based on strings when communicating over the webview bridge.

**Comment by Ayan-Kumar-Saha** [comment]
I believe the issue is with proguard's support for Angular. Earlier, I used the proguard plugin with Angular 11, everything worked fine even after building the release apk. However, now with Angular 13, I am facing this issue. The last release for proguard was 2 years back. 

I think the proguard is not updated yet to support Angular 13.
