### ISSUE TITLE
Build Error - (no such file or directory) ./cdv-gradle-config-defaults.json on cordova android v10.1.1

### ISSUE THREAD

**Issue by ciwhiz** [apache/cordova-android#1408]
# Bug Report

## Problem
**build error cordova android 10.1.1 with android gradle plugin 7.1.2** 
### What is expected to happen?
build success 

### What does actually happen?

Build Fail with followings...
**but actually, ./cdv-gradle-config.defaults.json already exists on root of project normally.** 
so, I can't understand this error messages...
* Where:
Script '/workspace/myproject/web/platforms/android/CordovaLib/cordova.gradle' line: 211

* What went wrong:
A problem occurred evaluating script.
> ./cdv-gradle-config-defaults.json (No such file or directory)

cordova.gradle line: 211 is followings.
![image](https://user-images.githubusercontent.com/3581824/158522117-ad776301-0833-46c7-be3a-9e297c3a63f9.png)

## Information

Originally, it was a project that was built. In cordova android v.8.0.0.
But this time I posted Android Gradle Plugin Version of Android Project. Gradle Wrapper(6.5.1->7.2) is also too.
(AGP 4.1.3 -> 7.1.2)
Then, Cordova android version also needed to upload.
Because updating of targetSDK and Java Version (AGP 7.x are required to Java 11) is required.

And then, the above error occurs when the build attempts occur.
Does the Cordova-Android version still do not support AGP 7?
Is there any other work-around resolution?

### Version information

Linux 
openJDK version : 11.0.14
cordova version : 11.0.0
cordova android version : 10.1.1
gulp version : CLI version: 2.3.0
npm version : 6.14.13
node version : 14.17.1
android project targetSDK 30, compileSDK 30.
gradle version: 7.4.1-all

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
cordova-android@10 doesn't support AGP 7.x.

By default, cordova-android@10 uses AGP `4.2.2`

AGP 7.x support is planned for our next major release For API 31 and/or API 32 support.

**Comment by ciwhiz** [comment]
I see,
Thank you very much for reply , 
I'm expecting :)
