### ISSUE TITLE
adb server doesn't start automatically

### ISSUE THREAD

**Issue by merbin2012** [apache/cordova-android#1414]
I need to start the ADB server manually or need to at least once run `cordova run android` command or needs to open Android Studio. Then only the server starts otherwise I need to start the server by using `adb server start`  command.

**Comment by breautek** [comment]
ADB commands generally will start the server itself if it's not already running. If it's not for you, then I'd suggest ensuring you're running a modern version of `Android SDK Platform Tools` (I'm currently running v33 atm with no issues, including running adb commands when the server hasn't been started).

If that doesn't address your issue, you may want to create a bug report against Android / ADB itself. Apache Cordova doesn't maintain the ADB codebase.

Closing as this does not appear to be a bug with Cordova.
