### ISSUE TITLE
Unable to target Android 12L Devices

### ISSUE THREAD

**Issue by Spritewrench** [apache/cordova-android#1415]
# Bug Report

## Problem
Unable to target Android 12L 

### What is expected to happen?
by setting the target/max SDK to 32 I'm expecting to have my app compatible with Android 12L (API 32) devices 

### What does actually happen?
Checking the merger reports shows that Cordova Andoird 10.1.1 sets max SDK to 31 regardless of config.xml contents

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version

**Comment by breautek** [comment]
Cordova doesn't set a max target sdk by default.

It does so only via the `android-maxSdkVersion` preference. If you don't have that preference in your `config.xml` file, then you may have a plugin that is setting the max SDk version.

**Comment by Spritewrench** [comment]
Confirming that there are no plugins are installed on this project. 
Regardless of what I set the max & min SDK version in the config.xml. 
They are always set to 31 and 26 respectively according to `manifest-merger-blame-release-report`

**Comment by breautek** [comment]
I am unable to reproduce this with a Hello Cordova test app.

Nothing in `manifest-merger-blame-release-report` indicates that a max SDK version is being set, nor does the `Merged Manifest View` in Android Studio shows a Max SDK version being set.

![Screenshot from 2022-04-08 11-54-02](https://user-images.githubusercontent.com/11200662/162465243-30a3aae8-00e6-4801-b99c-66be35ffcf38.png)

Another way the Max SDK version may be set is via a gradle property `cdvMaxSdkVersion`, so you may want to check your user gradle config files especially if you have `$GRADLE_USER_HOME` set, or if you use a `build-extras.gradle` file.

We'll likely need a sample reproduction app to move this forward.

> by setting the target/max SDK to 32 I'm expecting to have my app compatible with Android 12L (API 32) devices

Also note that it's not yet legal to upload an app with Target SDK 32 to the play store yet as SDK 32 is still in beta. The SDK is simply released to test your apps (and cordova-android@10 is not compatible with SDK >= 31). Apps targeting 31 can still be ran on SDK 32 devices.

**Comment by Spritewrench** [comment]
Confirming that the issue seems to have been with my `$GRADLE_USER_HOME` settings.
Once I edited the properties there my API levels were no longer locked between 25 and 31. 
Many thanks!
