### ISSUE TITLE
Android SDK 31 iframe not save cookies

### ISSUE THREAD

**Issue by VVilquack** [apache/cordova-android#1417]
When I set targetSdkVersion to 31 my iframe not saving session cookies
`<preference name="android-targetSdkVersion" value="31" />`
When I change targetSdk to 30 everythings worked

**Comment by breautek** [comment]
Starting in API 31 on Android 12 devices, [Google](https://developer.android.com/about/versions/12/behavior-changes-12#samesite) has started enforcing SameSite policies for WebView cookies.

Cordova cannot override this policy.

Personally I don't use cookies so I'm not totally familiar with the SameSite policies but they have a [guide](https://web.dev/samesite-cookies-explained/) that should be able to help. It may involve making changes to your server.

Closing as won't fix.

**Comment by monbutiong** [comment]
since the cookies and sessions are not working in to the iframe from targetSdk 31 and up, also it will not work on IOS app, I used window.open() to make a workaround solution.

**Comment by nzionisf** [comment]
@W84Soft Did you find a solution for that?
I'm trying to add SameSite=None; Secure but I see that it is still not working and the cookie is still missing in my request

**Comment by nzionisf** [comment]
@enricodente you should add to your cookie the attribute SameSite=None (and "Secure" attribute if you don't have it yet)
you can read more here:
https://developer.android.com/about/versions/12/behavior-changes-12#samesite

**Comment by manuweb** [comment]
According to the article: _[https://developer.android.com/about/versions/12/behavior-changes-12?hl=es-419#samesite](https://developer.android.com/about/versions/12/behavior-changes-12?hl=es-419#samesite)_, cookies that do not have a SameSite attribute are considered SameSite=Lax.

I had this problem with an online store in my app that was in an iframe, it did not take any cookies (cart, login, etc.). I solved it by editing the **.htaccess** file of my online store and adding at the beginning of the file:
**Header always edit Set-Cookie (.*) "$1; SameSite=None; Secure"**

I hope this solution helps you.
