### ISSUE TITLE
WebAuthn / FIDO2 support

### ISSUE THREAD

**Issue by Jammmmm** [apache/cordova-android#1429]
## Feature Request
Support for WebAuthn in Cordova Android.

## Motivation Behind Feature
Enables passwordless authentication in websites using WebAuthn, giving security and convenience.

Google, Apple and Microsoft are expanding support for this so it would make sense for it to be available in Cordova: [FIDO Alliance press release](https://fidoalliance.org/apple-google-and-microsoft-commit-to-expanded-support-for-fido-standard-to-accelerate-availability-of-passwordless-sign-ins/).

## Feature Description
A user goes to a website and sees an ordinary login form. Instead of typing a username and password, they can simply type their username and then use their fingerprint scanner/external security key/etc. to login. A password is no longer required.

A demo, which works in any web browser that supports it, can be found at https://webauthn.io/. I have confirmed it works on desktop browsers, Android (Chrome and Firefox), and iOS (Safari). It does not work in any Cordova app I have built on either platform (latest Cordova + latest Android WebView, for example)

Some Javascript to check if the browser supports WebAuthn:

	if (window.PublicKeyCredential === undefined || typeof window.PublicKeyCredential !== "function")
	{
		var errorMessage = "WebAuthn not supported."
		if (window.location.protocol === "http:" && (window.location.hostname !== "localhost" && window.location.hostname !== "127.0.0.1"))
		{
			errorMessage = "WebAuthn only supports secure connections. For testing over HTTP, you can use the origin \"localhost\"."
		}
		alert (errorMessage);
	}
	else { alert ("Supported"); }

## Alternatives or Workarounds
Currently there is a [Cordova plugin](https://github.com/niklasmerz/cordova-plugin-fingerprint-aio) that seems like it would work but as far as I can tell, it does not use WebAuthn. It would be better to support a web standard over a custom implementation.

Ideally any implementation would work be multiplatform (ie. cordova-android + cordova-ios, etc).

**Comment by dpogue** [comment]
This is something that would have to be implemented in the underlying WebView library (in this case by Google), not something that Cordova would add itself or be responsible for maintaining. Cordova does not provide the implementation of the webview, it just wraps what's available on the system.

**Comment by breautek** [comment]
FYI: This feature while available in desktop and mobile chrome, it's intentionally not available for the android webview.

Source: https://groups.google.com/a/chromium.org/g/blink-dev/c/qCJhuuZH5p0

> This feature will be supported on all platforms except for Android WebView.

I do not know the rationale behind omitting support for the android webview.

**Comment by liulyxandy-codemao** [comment]
Hi, I'm encountering what appears to be the same issue on a much newer environment and would like to confirm whether WebAuthn is currently unsupported in `cordova-android` WebView, or if additional configuration is required.

### Environment

* Android: `16`
* Android System WebView / Chromium: `149.0.7827.91`
* Running inside Cordova WebView (`wv`)
* Secure Context: `true`

### Detection results

Attempting to call:

```js
navigator.credentials.create({
  publicKey: ...
})
```

results in:

```text
NotSupportedError:
The user agent does not support public key credentials.
```

Since the app is already running in a secure context and the Credential Management API is available, I expected `PublicKeyCredential` to also be exposed on this recent WebView version.

Is WebAuthn intentionally unsupported in `cordova-android` WebView, or is there some additional setup required to enable `PublicKeyCredential` support on modern Android WebView versions?

**Comment by erisu** [comment]
@liulyxandy-codemao This is something that Google would have to implement in the Android WebView library and has nothing to do with Cordova.

The Web Authentication compatibility table on MDN also shows that the Web Authentication API is not supported in Android WebView.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API#browser_compatibility

**Comment by liulyxandy-codemao** [comment]
> This is something that Google would have to implement in the Android WebView library and has nothing to do with Cordova.
> 
> The Web Authentication compatibility table on MDN also shows that the Web Authentication API is not supported in Android WebView.

@erisu Thanks for the clarification.
