### ISSUE TITLE
11.0.0 not yet published on maven central

### ISSUE THREAD

**Issue by wmathurin** [apache/cordova-android#1460]
# Bug Report
I see the release notes and tag for 11.0.0, but I can't find the aar on maven central.
See https://search.maven.org/artifact/org.apache.cordova/framework/10.1.2/aar

## Problem
Not published on maven central yet.

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dpogue** [comment]
11.0.0 has not been released yet. It is still going through the release process and voting period.
