### ISSUE TITLE
cordova app for android 11  , unable to get splash screen

### ISSUE THREAD

**Issue by limrahsoft** [apache/cordova-android#1462]
sir,

we use cordova platform for our hybrid app development , 

as we have updated our cordova android version to 11 , api 30 , 31 ,32

*****  splash screen plugin is not working ,  *****

please guide us ,

thansk

**Comment by cytostatic** [comment]
Since v6 there is no need for an extra splash screen plugin.

But since v11 the "splash" config tags are removed and can not used anymore. 
The newer Android 11 splash screen must be used.

https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions

But i have not understand how to handle different densities yet.

**Comment by jcesarmobile** [comment]
That information is not accurate:
> Since v6 there is no need for an extra splash screen plugin.
cordova-ios 6 included the splash screen logic for iOS, but the plugin was still needed for cordova-android < 11

cordova-android 11 included the splash screen logic for Android, so the plugin should be uninstalled now, supposedly it's skipped if using the latest version
 
cordova-android 11 uses the newer Splash Screen API provided by google that doesn't use the old splash images, it will use the round app icon by default or you can configure an animated icon with `AndroidWindowSplashScreenAnimatedIcon` preference, so all splash tags for android should be removed from config.xml 

https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html

**Comment by limrahsoft** [comment]
sir ,

can u please tell how to configure splash screen preferences for adroid 11 cordova ,

as i have no idea about androd settings , thanks in advance for cordova splash screen complete settings for android 11

ok
________________________________

**Comment by Wolf00Bomber** [comment]
Any implementation sample available for the Android 11 or 12 Use case? Cordova documentation in https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/ is very vague !

**Comment by clopez1winsupply** [comment]
By implementing the suggestion to replace the splash tag by:
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/splash.png" />
now this works fine for devices with Android 12 and above, but the app is crashing for android 11 devices and below.

**Comment by breautek** [comment]
> Any implementation sample available for the Android 11 or 12 Use case? Cordova documentation in https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/ is very vague !

At the very minimum, all that is needed is:

```xml
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/android/splash/xxxhdpi.png" />
<preference name="AndroidWindowSplashScreenBackground" value="#6dADDF" />
```

where `res/android/splash/xxxhdpi.png` is a path to an image file and `AndroidWindowSplashScreenBackground` sets the background color of the overall splashscreen, which should be used to complement your splashscreen icon.

**Comment by bhargavas12** [comment]
> By implementing the suggestion to replace the splash tag by: < preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/splash.png" /> now this works fine for devices with Android 12 and above, but the app is crashing for android 11 devices and below.

@clopez1winsupply any update on this? I am facing the same issue
