### ISSUE TITLE
Fullscreen:  Device elements overlap ionic header

### ISSUE THREAD

**Issue by boengli** [apache/cordova-android#1467]
I'm not sure, maybe [this](https://github.com/apache/cordova-plugin-statusbar/issues/234) issue could be related to the implementation of "AndroidX SplashScreen Core Library: 1.0.0-rc01":

https://github.com/apache/cordova-plugin-statusbar/issues/234

----
Since updating to cordova-android 11.0.0 I have the problem, that device elements overlap ion-header.

Before the update, it extended the header and made space.

[![enter image description here][1]][1]

Config.xml:

    <preference name="StatusBarOverlaysWebView" value="false" />
    <preference name="Fullscreen" value="true" />

So far, I found out, that it works, after `window.location.replace('/home');` but that's not really a solution.
Looks like '--ion-safe-area-top' is only set after a reload.
StatusBarOverlaysWebView: true/false makes no difference.

  [1]: https://i.stack.imgur.com/QxMm2.png

**Comment by breautek** [comment]
Are you using CSS safe area insights? Could be the same issue as reported https://github.com/apache/cordova-android/issues/1465

**Comment by boengli** [comment]
No, I don't use CSS safe area.

**Comment by boengli** [comment]
I experimented a bit and added the following to my code:
`var style = getComputedStyle(document.body);
alert(style.getPropertyValue('--ion-safe-area-top'));`

On the first start of the app it is : **0px**

after `window.location.replace('/pageXY');`
the output is **43px** 

So the calculation is there somewhere... just not at the right place

**Comment by breautek** [comment]
Duplicate: #1465
