### ISSUE TITLE
App crashing Cordova-android 11

### ISSUE THREAD

**Issue by bhandaribhumin** [apache/cordova-android#1469]
# Bug Report

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

## Problem

Application crash on startup 

### What is expected to happen?

Application should work after change Cordova-android-11 with target sdk 32

### What does actually happen?

Application crash on startup 

### App not compile 

 
![Screenshot 2022-07-28 at 6 39 14 PM](https://user-images.githubusercontent.com/3336047/181513160-bc63a9ba-e812-4f2d-ba2a-2b3499e7dd16.png)

![Screenshot 2022-07-28 at 6 48 03 PM](https://user-images.githubusercontent.com/3336047/181514852-468bd414-b46b-4797-a2d4-93827507f152.png)

## Fixed using 

After add `implementation 'androidx.work:work-runtime:2.7.0-alpha05'` to cordovaLib-> build.gradle file application works 

### Version information
```
Ionic:

   Ionic CLI          : 6.20.1 (/Users/bhuminbhandari/.nvm/versions/node/v14.15.4/lib/node_modules/@ionic/cli)
   Ionic Framework    : ionic-angular 3.9.10
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 22 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.0
   native-run                             : 1.6.0

System:

   Android SDK Tools : 26.1.1 (/Users/bhuminbhandari/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v14.15.4 (/Users/bhuminbhandari/.nvm/versions/node/v14.15.4/bin/node)
   npm               : 6.14.10
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100
```

CDV-gradle

  ```
"MIN_SDK_VERSION": 25,
  "SDK_VERSION": 32,
  "COMPILE_SDK_VERSION": 32,
  "GRADLE_VERSION": "7.4.2",
  "MIN_BUILD_TOOLS_VERSION": "32.0.0",
  "AGP_VERSION": "7.2.1",
  "KOTLIN_VERSION": "1.5.21",
  "ANDROIDX_APP_COMPAT_VERSION": "1.4.2",
  "ANDROIDX_WEBKIT_VERSION": "1.4.0",
  "ANDROIDX_CORE_SPLASHSCREEN_VERSION": "1.0.0-rc01",
  "GRADLE_PLUGIN_GOOGLE_SERVICES_VERSION": "4.3.8",
  "IS_GRADLE_PLUGIN_GOOGLE_SERVICES_ENABLED": true,
  "IS_GRADLE_PLUGIN_KOTLIN_ENABLED": false
```

**Comment by breautek** [comment]
Error is coming from dependencies of plugins it seems, but it also states that the `:app` is currently compiled against android-29, which does not match either the default configuration or your pasted configuration.

If you upgraded cordova-android simply via `npm install`, then you may need to `cordova platform remove android` / `cordova platform add android@11` so the native project starts from a clean slate. In-place platform upgrades aren't well supported and tends to cause issues.

Otherwise you can try running `cordova clean android` to clean any built files to ensure they are rebuilt with the current compile settings.

**Comment by bhandaribhumin** [comment]
Thank you @breautek you are right this is due to some plugin dependancy.
But this is a bit weird issue, all the plugins I used in the project I installed in the blank project of cordova and everything works, don't know what is the problem and where is the problem?

**Comment by breautek** [comment]
> Thank you @breautek you are right this is due to some plugin dependancy. But this is a bit weird issue, all the plugins I used in the project I installed in the blank project of cordova and everything works, don't know what is the problem and where is the problem?

If building on a blank cordova project works, then I'll try to let Cordova build the native project from scratch. Easiest way to do this is by removing the platform and re-adding it again, as noted in my above comment. Also if you were upgrading plugins, it might be best to remove them then re-add them as well, that way the native project gets configured from a clean slate.

**Comment by AndrWeisR** [comment]
@bhandaribhumin Are you using @havesource/cordova-plugin-push by any chance? I have seen this "FLAG_IMMUTABLE or FLAG_MUTABLE" error come from that plugin.

**Comment by jcesarmobile** [comment]
This is something plugins need to fix because is an SDK 32 requirement.
I see @havesource/cordova-plugin-push have already fixed it, but hasn't released the fix to npm yet.
