### ISSUE TITLE
Can't add custom scheme to android project

### ISSUE THREAD

**Issue by VVilquack** [apache/cordova-android#1473]
I can't add custom scheme to android project but in iOS custom scheme working very well

**Comment by breautek** [comment]
Android only supports `http` or `https` for schemes. This is a limitation of the underlying WebViewAssetLoader.

iOS on the other hand only supports custom schemes that are not well known schemes, so iOS doesn't support schemes that are `http`, `https`, or any other scheme that is standardised.
