### ISSUE TITLE
PermissionHelper. requestPermissions fail to prompt the user in the inappbrowser plugin

### ISSUE THREAD

**Issue by 75341704** [apache/cordova-android#1474]
https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#runtime-permissions-cordova-android-500
The onPermissionRequest is overrided as follows
https://github.com/75341704/cordova-plugin-themeablebrowser/commit/1431a4e0f804944473408525d0d57b9840c76b7e
But the 'PermissionHelper.requestPermissions' fail to prompt the user.

Any idea wil be highly appreciated.

PS:
```
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-feature android:name="android.hardware.microphone" android:required="false" />
```
have been added in the AndroidManifest.xml

**Comment by jcesarmobile** [comment]
You are referencing themeablebrowser, which is not an apache project, report the issue on that repository.
