### ISSUE TITLE
Error when adding AndroidWindowSplashScreenBrandingImage

### ISSUE THREAD

**Issue by fortunella** [apache/cordova-android#1475]
# Bug Report

### What is expected to happen?
Branding image is shown in the splash screen

### What does actually happen?
Error during build of the project.

## Information

I migrated my app project to cordova-android 11 and got the splash screen working with the new API. Therefor I added these lines to config.xml:
```
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/android/splash-android.png" />
<preference name="AndroidWindowSplashScreenBackground" value="#FF0000" />
```
This works fine. I then wanted to add a branding image to the bottom of the splash screen with this setting:
```
<preference name="AndroidWindowSplashScreenBrandingImage" value="resources/android/brand-image.png" />
```
When I then build the project I get this error:
```
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/home/ralf/myAppBuild/platforms/android/app/build/intermediates/incremental/debug/mergeDebugResources/merged.dir/values/values.xml:2210: AAPT: error: style attribute 'attr/windowSplashScreenBrandingImage (aka de.foonax.myapp:attr/windowSplashScreenBrandingImage)' not found.
```
The specified image file exists at the specified location.

### Version information

cordova-android:  11.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by expcapitaldev** [comment]
looks like error here:
`<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen.IconBackground">
        <item name="windowSplashScreenBackground">@color/cdv_splashscreen_background</item>
        <item name="windowSplashScreenAnimatedIcon">@drawable/ic_cdv_splashscreen</item>
        <item name="windowSplashScreenAnimationDuration">1000</item>
        <item name="postSplashScreenTheme">@style/Theme.AppCompat.NoActionBar</item>
        <item name="windowSplashScreenIconBackgroundColor">@color/cdv_splashscreen_icon_background</item>
        <item name="**android:windowSplashScreenBrandingImage**">@drawable/ic_cdv_splashscreen_branding</item>
    </style>
</resources>`
 because after cordova prepare I see 
` <item name="**windowSplashScreenBrandingImage**">@drawable/ic_cdv_splashscreen_branding</item>`

**Comment by valid13** [comment]
Same issue here.
I removed AndroidWindowSplashScreenBrandingImage for now, but it's quite problematic.
