### ISSUE TITLE
Canvas run very slow on Cordova

### ISSUE THREAD

**Issue by amihanya** [apache/cordova-android#1484]
We Build an App with Cordova that use HTML CANVAS to Andorid on the Phone that run great.
But when we run it on android TV or Minix (littel streamer that run android) that run very slow.

**Comment by breautek** [comment]
The System WebView can be a different version of the browser app, or it could be a completely different rendering engine altogether.

I've never worked with an Android TV system myself but if you can gain access to the chrome developer tools to remote debug it, then you can use it's performance audit tools to gain more insights on where the browser is taking the most time to perform tasks.

**Comment by amihanya** [comment]
That possible to forces the app to use chrome?
like that:
appView.setWebChromeClient(new WebChromeClient());
?

**Comment by breautek** [comment]
No, it always uses Android System Webview, whatever implementation that might be on the local device.

[WebChromeClient](https://developer.android.com/reference/android/webkit/WebChromeClient) is simply a delegate class, it's not a browser engine.

In practice, the Android System Webview is usually a variant of Chrome or Chromium. Outside of really old android devices (pre android 4.4) I'm not sure of any devices that doesn't use a version of chrome as the system webview. It is a however, still a completely separate package with different build settings than the browser application. So there isn't a guarantee that the Android System Webview will behave identical to the Chrome Browser application, even if they are both based on the same version of the browser engine.

As far as applications are concerned, there is just a [Webview](https://developer.android.com/reference/android/webkit/WebView) class, which API is powered by the Android System Webview package. [WebChromeClient](https://developer.android.com/reference/android/webkit/WebChromeClient) is simply a delegate class to listen onto events.

**Comment by amihanya** [comment]
Thanks
