### ISSUE TITLE
Scaling issue only displays viewport within 75% of screen

### ISSUE THREAD

**Issue by joefaron** [apache/cordova-android#1500]
# Bug Report

### What is expected to happen?
Display full screen width

### What does actually happen?
Randomly decides to not use full width of viewport.

## Information
I've tried disabling all plugins, custom icons, still happens.  Happens randomly on our live app as well: https://play.google.com/store/apps/details?id=com.fishwranglr.app

### Command or Code
Random loads decide not to load within full width of screen.

### Environment, Platform, Device
Samsung S20 FE.

### Version information
`"cordova-plugin-device": "2.1.0",
"cordova-plugin-facebook-connect": "3.2.0",
"cordova-plugin-network-information": "3.0.0",
"cordova-plugin-purchase": "11.0.0",
"admob-plus-cordova": "1.28.0"`

    `<uses-sdk
        android:minSdkVersion="22"
        android:targetSdkVersion="31" />`

Cordova 11, cordova android 10.1.2, gradle 7.3.

The grey area in screen shot is draggable, it's not <html> or <body>.. it's outside of the viewport I imagine.

My viewport meta is:
`<meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, user-scalable=no, viewport-fit=cover">`

js vars are always the same, even when it displays like this.
`window.screen.width=360
window.innerWidth=420
window.devicePixelRatio=3`

![Screenshot_20220927-110554_Fish Wrangler](https://user-images.githubusercontent.com/702672/192607656-b5471fc9-f5e4-4288-923d-246a59bcb13e.jpg)

**Comment by joefaron** [comment]
It looks like manually adding:
`android:screenOrientation="portrait"` to the androidmanifest.xml in 
`<application><acitivity android:screenOrientation="portrait">` is possibly what causes this behavior..

What's the best way to force portrait orientation?

**Comment by joefaron** [comment]
Turns out that https://github.com/apache/cordova-plugin-screen-orientation has the same exact problem.. start phone in landscape, have it lock to portrait ondeviceready, leads to same exact screenshot as above.

**Comment by dpogue** [comment]
This sounds like the same sort of problem as https://github.com/apache/cordova-android/issues/1478 which appeared to be a bug in a Samsung system WebView update.

Does this only happen on Samsung phones? Is the system WebView up to date?

**Comment by joefaron** [comment]
I'm only able to test on samsung.

Android System WebView says it's up to date, version: 105.0.5195.136

**Comment by breautek** [comment]
Does not reproduce on Samsung Note 9.

![Screenshot_20220927-191030_FishWrangler](https://user-images.githubusercontent.com/11200662/192646746-682faa30-a16a-466f-8d37-0fef1b547ea3.jpg)

Used the latest available version of the app from the play store.

My system webview version is 105.0.5195.136

**Comment by joefaron** [comment]
Sadly you have to close it and open it about 20 times to really verify it. There's clearly an edge case in play here. Happens with hello Cordova on v11.

Same issue as #1478.

**Comment by joefaron** [comment]
Duplicate is #1478.
