### ISSUE TITLE
how to set  background color  Gradation for android 12 splash screen

### ISSUE THREAD

**Issue by 192kobayashi** [apache/cordova-android#1512]
Thank you for migrating #1441.

My Android app uses a gradient for the background color of the splash screen.

In this migration, I think that the background color of the splash screen is specified with `AndroidWindowSplashScreenBackground`.

Does this value only allow color codes?

Is there a way to specify the gradient in xml?

I would appreciate it if you could comment.

Thank you.

**Comment by erisu** [comment]
Per Android documentation, only color codes is allowed.

> The background color for the splash screen, if not specify then system will calculate from windowBackground.
> 
> May be a color value, in the form of "#rgb", "#argb", "#rrggbb", or "#aarrggbb".

https://developer.android.com/reference/android/R.attr#windowSplashScreenBackground

I am not aware if gradient background can be done.

**Comment by 192kobayashi** [comment]
@erisu 

thank you for your answer.

got it.

Thanks again for your migration.
