### ISSUE TITLE
White screen showing after splash screen before app load ionic 5.

### ISSUE THREAD

**Issue by adnanganie** [apache/cordova-android#1521]
# Bug Report
After Migration to cordova-android-11.
## Problem
When we lunch app splash screen is appears then after some seconds another white screen is also appears,  after couple of seconds then  home page appears in both android 10/android 12 devices.
I am not using any splash-screen plugin.
### Environment, Platform, Device

This is my configs in config.xml
` <preference name="DisallowOverscroll" value="true" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="AutoHideSplashScreen" value="true" />
    <preference name="SplashScreenDelay" value="400" />
    <preference name="FadeSplashScreen" value="true" />
    <preference name="FadeSplashScreenDuration" value="100" />
    <preference name="SplashScreen" value="screen" />
    <preference name="ShowSplashScreen" value="true" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="SplashShowOnlyFirstTime" value="false" />`

### Version information

 In ionic V.5
cordova-android: "^11.0.0"

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
This doesn't sound like a bug.

It sounds like the splashscreen is hiding after the configured 400ms while you're app UI hasn't finished loading yet.
You could try increasing `SplashScreenDelay`, or better, disable `AutoHideSplashScreen` and call [navigator.splashscreen.hide](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/index.html#navigatorsplashscreenhide) when you are ready to show your UI (e.g. after the document is loaded).

Let me know if this helps.

**Comment by jcesarmobile** [comment]
Closing due to the lack of response
