### ISSUE TITLE
lib-file in plugin generates gradle file with compile() dependency

### ISSUE THREAD

**Issue by dariosalvi78** [apache/cordova-android#1524]
# Bug Report

## Problem
I have a simple plugin with an external .aar library. The pluign has `<lib-file src="path_to_.aar" />` declared in plugin.xml.

When trying to build the project, a file named app-pluginame.gradle is generated automatically, my understanding is that this is done by the android platform.

When gradle 7.6 tries to put the code all together it complains about a `compile()` directive. I changed `compile()` to `implementation`manually and now it works.

### What is expected to happen?
  
`compile()` is deprecated, `implementation`should be used in the automatically generated file.

### What does actually happen?

In the automatically generated file, I find:

```
dependencies {
    compile(name:'nameOfTheLib', ext:'aar')
}
```
 I changed `compile()` to `implementation`manually and now it works.

## Information
I could not find the exact file or files responsible for this error, otherwise I would have sent a PR, sorry!

### Command or Code

To reproduce, create a simple plugin with an external compiled library for Android, add the lib-file tag in the plugin.xml and import the plugin into a basic cordova app. Compile the app with `cordova build android` and check the output from Gradle. I used gradle 7.6, as far as I can tell gradle >7 has banned "compile()" completely.

### Environment, Platform, Device
mac os ventura 13.0.1
android 
ONEPLUS A5010

### Version information
openjdk 11.0.16
gradle 7.6
cordova 11.0.0
cordova android 11.0.0
android studi dolphin (irrelevant)
SDK Build Tool: 32.0.0

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
I think `compile` is coming from elsewhere. I'm fairly certain that `lib-file` **only** copies the target file into the `libs` folder, and the [codebase](https://github.com/apache/cordova-android/blob/56d4b8312bc85253e975da524d9a3c72d7df5418/lib/pluginHandlers.js#L49) appears to reflect this.

In my plugin I use:

```xml
<platform name="android">
    <framework src="src/android/sqlite.gradle" custom="true" type="gradleReference" />
    <lib-file src="bin/sqlite3.aar" />
  </platform>
```

`lib-file` copies the aar file into the proper directory inside the android studio project. The gradle reference adds `apply from: "../@totalpave/cordova-plugin-libsqlite/iriapp-sqlite.gradle"`  to my `build.gradle` file which contains the following contents:

```gradle
dependencies {
    implementation files('libs/sqlite3.aar')
}
```

`lib-file` by itself doesn't appear to change any of the gradle files.

**Comment by dariosalvi78** [comment]
OK I have found it, the .gradle file was specified inside the plugin.
My bad!

**Comment by breautek** [comment]
No worries, glad I was able to help you look in the right direction  :)
