### ISSUE TITLE
$.ajax POST returning “status”:403,“ with cordova android@9.1.0 and Android Target API level to 31

### ISSUE THREAD

**Issue by sathishavunoori** [apache/cordova-android#1548]
Hi every one,
I am working on a product and developing Cordova android application.
$.ajax/fetch POST returning “status”:403,“statusText”:“Forbidden” cordova android@9.1.0 when i target it to Android Target API level to 31, But the previous build is working on same devices and same servers with Target Level 30 and cordova android@9.1.0.
I have already added usesClearTextTraffic flag to true and installed whitelist plugin.
Can some one provide any help or inputs to resolve this problem, as i need to upload latest APK with target API level 31 into google store.
thanks

**Comment by jfoclpf** [comment]
Try adding this to your `config.xml`

```
<preference name="AndroidInsecureFileModeEnabled" value="true" />
```

does it work?

**Comment by breautek** [comment]
cordova-android@9 is not a supported platform nor does it support API 31.

cordova-android@11 is the minimum version required with support of API 31+. Please upgrade to cordova-android@11 and if you continue to have issues, fill a new issue with the issue template filled out.

**Comment by sathishavunoori** [comment]
> 

I already added this in my config.xml and still there is the issue.

**Comment by sathishavunoori** [comment]
> cordova-android@9 is not a supported platform nor does it support API 31.
> 
> cordova-android@11 is the minimum version required with support of API 31+. Please upgrade to cordova-android@11 and if you continue to have issues, fill a new issue with the issue template filled out.

@breautek , I have almost 15+ plugins in my app, so if i update to cordova-android@11 , then most of the plugins won't work and it will take much time to fix the plugin issues. and if i set android-targetSDKversion to 31 it is accepting with cordova-android@9 and building the APK with target 31, which will allow me to upload to google play store. So with cordova-android@9 if we can fix this issue is the happiest answer.

**Comment by sathishavunoori** [comment]
> Try adding this to your `config.xml`
> 
> ```
> <preference name="AndroidInsecureFileModeEnabled" value="true" />
> ```
> 
> does it work?
@jfoclpf

I already added this in my config.xml and still there is the issue.

**Comment by jfoclpf** [comment]
I have dozens of plugins also and strangely they all worked well in Cordova
11. Try it out. If a plugin doesn't support Cordova 11 it should pop up an
error or warning when you add the platform.

**Comment by ksch10bob** [comment]
@sathishavunoori 
I assume the following

* the endpoint you try to consume is protected 
* the authentication against the endpoint is based on cookies

I ran into the same problem meaning:
* cordova-android 9.0.0
* config.xml ```<preference name="android-targetSdkVersion" value="30" />```  everything works
* config.xml ```<preference name="android-targetSdkVersion" value="31" />```  getting 403 

If you target Api Level 31 a lot of Android Devices apply the stricter rule of handling SameSite Cookies
It is nothing the cordova core can do about it. It is just a stricter cookie policy that is applied from the android system webview.

Please check the cookie section in chrome Debugger:
* for API 30 Build
* for API 31 Build
and compare the cookies that are send with the request.
Iam sure some essential session cookies are not sent, because they violate samesite policy.

Make sure to check the show filtere cookies checkbox 
![image](https://user-images.githubusercontent.com/17985877/215260957-407a675f-462c-45e6-9cbf-3be4cf8813ad.png)

**Comment by sathishavunoori** [comment]
Hi @ksch10bob  after digging into comparing both requests for Target 30 and 31, it is clear that cookies are missing in 31 request headers. But how to fix it from cordova or android side , still searching.

**Comment by ksch10bob** [comment]
@sathishavunoori  We did not change anything on cordova or android site.
The root cause is how the server that sets the cookies sets theese cookies.
The server has to  set the Attribute SameSite=NONE for the essential session cookies !

**Comment by anuskaoo** [comment]
With android 11 platform calls to external domains like:
(async () => {             
    await fetch("https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaxxxxxxxxxxxxxxx", requestOptions)
..............

or somethink like that not working. 

I have already tried all the solutions that I have found on the internet such as:
<preference name="AndroidInsecureFileModeEnabled" value="true" />
but nothing works. Will there be a problem in Cordova?
In the simulator it works perfectly so it can't be a problem with my server. When I upload the app to the Play Store and try it on the device, it doesn't work. Can you help me?
I need to access some REST API and I can't. That's a big problem for me
Thanks
