### ISSUE TITLE
Cordova 11 Broken when using  vue cli removes res files like colors.xml and google-services.json

### ISSUE THREAD

**Issue by jonathanalberghini** [apache/cordova-android#1551]
# Bug Report

## Information
For some reason I run

1. yarn install
2 cordova prepare

All of the Res files from the config.XML are present in platforms/android/app/src/main/res and the google-services.json in platforms/android/app
then I do a

3 yarn build:browser && yarn build:ios && yarn build:android

which is
"build:android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android",
"build:browser": "cross-env CORDOVA_PLATFORM=browser vue-cli-service cordova-build-browser",
"build:ios": "cross-env CORDOVA_PLATFORM=ios vue-cli-service cordova-build-ios",

"build:android": "cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android",
**In this command somewhere it does a clean and it ends up removing those files.**

and I get the error missing colors.xml and it gives a path but it was there for some reason I don't know why it is cleaning them out.

All I have to do is change one line and it will build perfect.
"dependencies": {
"cordova-android": "11.0.0",
to "dependencies": {
"cordova-android": "10.1.2",
here is the package.json
[package.json.txt](https://github.com/m0dch3n/vue-cli-plugin-cordova/files/10503303/package.json.txt)

Does anyone have any input on why this is broken?

### Command or Code
vue-cli-service cordova-build-android

### Environment, Platform, Device
mac new chip

### Version information
attached package.json

## Checklist

- [x ] I searched for existing
[package.json.txt](https://github.com/apache/cordova-android/files/10503466/package.json.txt)
 GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Cordova doesn't "clean" anything unless if the `cordova clean` command. It may overwrite files however when it prepares the native project.

Can you reproduce your issue when using the cordova command line in your cordova project, wherever that might be? Tracking issues when there is third party tooling or frameworks involved is problematic. It's best if we can isolate the issue away from these third party tools.

**Comment by jonathanalberghini** [comment]
I will try it. I find it really strange that just changing the version of your plug-in that's the only thing I change and it works I'll try to capture the output of where it's actually cleaning the files out also.

**Comment by breautek** [comment]
Also going to add that `cordova clean` also doesn't touch the resource files...

It will remove the app build directory (e.g. `<cordova-project/platforms/android/app/build`) so that you're next build will build the source from scratch.

**Comment by jonathanalberghini** [comment]
The files that go missing are the one listed in config.xml.  The ones listed as resource stash file and the google–services,json file not the icons though.

-  <platform name="android">
-         <allow-intent href="market:*" />
-         <icon density="mdpi" src="res/icon/android/mdpi.png" />
-         <icon density="hdpi" src="res/icon/android/hdpi.png" />
-         <icon density="xhdpi" src="res/icon/android/xhdpi.png" />
-         <icon density="xxhdpi" src="res/icon/android/xxhdpi.png" />
-         <icon density="xxxhdpi" src="res/icon/android/xxxhdpi.png" />
-         <resource-file src="google-services.json" target="app/google-services.json" />
-         <resource-file src="custom-resources/android/res/values/colors.xml" target="app/src/main/res/values/colors.xml" />
-         <resource-file src="custom-resources/android/res/drawable/background_no_splash.xml" target="app/src/main/res/drawable/background_no_splash.xml" />
-         <resource-file src="custom-resources/android/res/drawable/logo.xml" target="app/src/main/res/drawable/logo.xml" />
-         <resource-file src="custom-resources/android/res/values/styles.xml" target="app/src/main/res/values/styles.xml" />
-         <preference name="android-targetSdkVersion" value="32" />
-     </platform>

**Comment by jonathanalberghini** [comment]
I clean everything
rm -rf ./plugins ./platforms ./node_modules ./www/* ./yarn.lock ./package-lock.json
then run 
yarn install && cordova prepare
I look in 
platforms/android/app/  and google-services.json is there 
and 
platforms/android/app/source/main/res/values  and colors.xml and styles.xml are there 
I then run 
 cordova build android
 and it works 

It seems it only breaks when I run
cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android
but only in 11 not in 10.1.2
Just as the files disappear this is what is output in the build process
cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android

JX47NL6DHQ~/src/opportunistic-trader-mobile(jerk|✚1) % cordova build:android
Cordova does not know build:android; try `cordova help` for a list of all the available commands.
JX47NL6DHQ~/src/opportunistic-trader-mobile(jerk|✚1) % yarn build:android
yarn run v1.22.19
$ cross-env CORDOVA_PLATFORM=android vue-cli-service cordova-build-android

⠼  Building for production...

 WARNING  Compiled with 2 warnings                                                                                                                                                                                           10:06:08 AM

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/app.cfb8c76d.js (382 KiB)
  css/chunk-vendors.f5b80ee0.css (450 KiB)
  js/chunk-vendors.49a6bc86.js (652 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (1.62 MiB)
      css/chunk-vendors.f5b80ee0.css
      js/chunk-vendors.49a6bc86.js
      css/app.0a99e3f5.css
      js/app.cfb8c76d.js


  File                                   Size              Gzipped

  www/js/chunk-vendors.49a6bc86.js       651.74 KiB        210.66 KiB
  www/js/app.cfb8c76d.js                 382.40 KiB        54.11 KiB
  www/js/chunk-499abac6.03e5e054.js      3.90 KiB          1.75 KiB
  www/js/chunk-2d21a5c5.a81b9a0b.js      3.00 KiB          1.38 KiB
  www/js/chunk-2d0e9993.7b3657ef.js      2.75 KiB          1.33 KiB
  www/js/chunk-2d0aaf94.df2a6a9b.js      2.40 KiB          1.15 KiB
  www/js/chunk-2d2262ea.1c7f0404.js      2.06 KiB          1.02 KiB
  www/js/chunk-95df9744.44ba7d71.js      0.98 KiB          0.59 KiB
  www/js/chunk-61471f4c.d15b27b2.js      0.97 KiB          0.57 KiB
  www/js/chunk-11604a98.7e1cb444.js      0.85 KiB          0.53 KiB
  www/js/chunk-3ad08596.b389aa83.js      0.83 KiB          0.53 KiB
  www/js/chunk-0c321ec6.dfc75661.js      0.74 KiB          0.49 KiB
  www/js/chunk-2d0e8c8e.e253266c.js      0.55 KiB          0.41 KiB
  www/js/chunk-2d21ad78.9c1d55ae.js      0.55 KiB          0.40 KiB
  www/js/chunk-2d225232.99112fc2.js      0.54 KiB          0.40 KiB
  www/js/chunk-2d208107.c114d54e.js      0.37 KiB          0.28 KiB
  www/js/chunk-2d22dba2.4d1487a5.js      0.37 KiB          0.29 KiB
  www/css/chunk-vendors.f5b80ee0.css     450.47 KiB        54.39 KiB
  www/css/app.0a99e3f5.css               169.24 KiB        39.97 KiB
  www/css/chunk-499abac6.43091943.css    0.35 KiB          0.15 KiB
  www/css/chunk-0c321ec6.0e433876.css    0.00 KiB          0.02 KiB
  www/css/chunk-11604a98.0e433876.css    0.00 KiB          0.02 KiB
  www/css/chunk-3ad08596.0e433876.css    0.00 KiB          0.02 KiB
  www/css/chunk-61471f4c.0e433876.css    0.00 KiB          0.02 KiB
  www/css/chunk-95df9744.0e433876.css    0.00 KiB          0.02 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The www directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
                                  
 INFO  executing "cordova clean" in folder /Users/jalberghini/src/opportunistic-trader-mobile
Checking Java JDK and Android SDK versions
ANDROID_HOME=/Users/jalberghini/Library/Android/sdk (recommended setting)
ANDROID_SDK_ROOT=/Users/jalberghini/Library/Android/sdk (DEPRECATED)
Using Android SDK: /Users/jalberghini/Library/Android/sdk

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 747ms
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.10

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 941ms
3 actionable tasks: 3 up-to-date
Running command: xcodebuild -project Opportunistic Trader.xcodeproj -configuration Debug -alltargets clean
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project "Opportunistic Trader.xcodeproj" -configuration Debug -alltargets clean

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES


** CLEAN SUCCEEDED **

Running command: xcodebuild -project Opportunistic Trader.xcodeproj -configuration Release -alltargets clean
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project "Opportunistic Trader.xcodeproj" -configuration Release -alltargets clean

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES


** CLEAN SUCCEEDED **

 INFO  executing "cordova build android --release" in folder /Users/jalberghini/src/opportunistic-trader-mobile
ENOENT: no such file or directory, open '/Users/jalberghini/src/opportunistic-trader-mobile/platforms/android/app/src/main/res/values/colors.xml'
✨  Done in 40.79s.

**Comment by jonathanalberghini** [comment]
I do not understand why the clean with xcode happens that is when the file disappear.

**Comment by jonathanalberghini** [comment]
Changing to 10.1.2 works. And not using vue cli works.

**Comment by breautek** [comment]
I'm unable to reproduce this with the Cordova CLI.

Given your config, `<resource-file src="custom-resources/android/res/values/colors.xml" target="app/src/main/res/values/colors.xml" />` will cause a build to fail because `resource-file` provides and overwrites files, and cordova` will want to have the following XML:

```
<?xml version='1.0' encoding='utf-8'?>
<resources xmlns:tools="http://schemas.android.com/tools">
    <color name="cdv_splashscreen_background">#FFFFFF</color>
</resources>
```

I used dummy files for my testing but purely what I was looking for is whether files "disappears" or gets removed, which doesn't appear to be the case when using the Cordova CLI.

`cordova prepare` and `cordova build` will copy the resources files. `cordova clean` will clean some custom resource files (so I was mistaken in my past posts).

Even if you ran the `cordova clean` command, running `cordova build` implicitly does a `cordova prepare` which reconfigures those source files.

I've conducted my test using cordova-android@11.

I do not know what vue cli is doing behind the scenes, but the Cordova CLI appears to be working as intended.

**Comment by 4lyn** [comment]
Hi,

I have the same problem here upgrading to Cordova Android 11
I also use vue cli with this plugin [vue-cli-plugin-cordova](https://www.npmjs.com/package/vue-cli-plugin-cordova)
After `cordova prepare android` the `colors.xml` is present
And when the `vue-cli-service cordova-build-android` is run it seems to be removed somewhere

```
ENOENT: no such file or directory, open '/home/pakal/git/perfarmer_app/src-cordova/platforms/android/app/src/main/res/values/colors.xml'
```

Going back to Cordova Android 10.1.2 is not really an option since it's [not compatible with Android API level 32](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html) which is the [targetSdkVersion required](https://developer.android.com/google/play/requirements/target-sdk) by the playStore now

I'm not sure it is Cordova Android's fault but clearly this new version does something different that causes these files to be removed

**Comment by 4lyn** [comment]
Actually it has nothing to do with vue cli
See #1553

**Comment by jonathanalberghini** [comment]
So it’s not the view CLI did something inside Cordova-android plug-in 11? Because when I make a native Cordova android 11 project I don’t have the issue without VUE CLI.

From: Pascal Combescot ***@***.***>
Date: Monday, January 30, 2023 at 5:13 AM
To: apache/cordova-android ***@***.***>
Cc: Jon Alberghini ***@***.***>, Author ***@***.***>
Subject: Re: [apache/cordova-android] Cordova 11 Broken when using vue cli removes res files like colors.xml and google-services.json (Issue #1551)

Actually it has nothing to do with vue cli
See #1553<https://github.com/apache/cordova-android/issues/1553>

**Comment by mariusurbelis** [comment]
Having the same issue.
