### ISSUE TITLE
Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin

### ISSUE THREAD

**Issue by kbrownlees** [apache/cordova-android#1564]
# Bug Report

### What is expected to happen?

The build to complete successful.

### What does actually happen?

The build fails with an error of `Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1`

## Information

Some more context in https://github.com/apache/cordova-android/pull/1543.

This started happening for two of our developers in the last week or so. I was not able to lock down the exactly change which triggered this, but it is a tooling change rather than code changes since we have not done any cordova package upgrades in the last few months.

The workaround is to add `<preference name="GradlePluginKotlinVersion" value="1.7.22"/>` to your config.xml.

### Command or Code

Attempt to build android, either via the command line or android studio.

### Version information

cordova@11
cordvoa-android@11
MacOS Ventura
Android Studio 2022.1.1 Patch 2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AlexPashley** [comment]
I can confirm adding `<preference name="GradlePluginKotlinVersion" value="1.7.22"/>` to your config.xml as @kbrownlees suggested worked, thanks!
