### ISSUE TITLE
Gradle version no longer supported

### ISSUE THREAD

**Issue by jacobg** [apache/cordova-android#1572]
Both `cordova build android` and Android Studio fail to build on Gradle version 7.4.2:
```
Minimum supported Gradle version is 7.5. Current version is 7.4.2.
```
https://github.com/apache/cordova-android/blob/dbddbf253bb1b47ca5220f8360536433c7c682b2/spec/fixtures/android_studio_project/gradle/wrapper/gradle-wrapper.properties#L6

Please bump to 7.5 or higher.

Thanks.

**Comment by breautek** [comment]
Support for updated AGP + Gradle will be coming in cordova-android@12 via https://github.com/apache/cordova-android/pull/1539

If you opened the native project in Android Studio and accepted the AS prompt to upgrade AGP (Android Gradle Plugin), then you'll need to downgrade AGP back to version 7.2.1, which is what cordova-android@11 expects.

If the downgrade doesn't work, you may need to rebuild the native project by doing:

```
cordova platform remove android
cordova platform add android@11
```
