### ISSUE TITLE
Cannot read property 'find' of null

### ISSUE THREAD

**Issue by Lyfei** [apache/cordova-android#1576]
# Bug Report

### What is expected to happen?

add android platform

### What does actually happen?

get error: Cannot read property 'find' of null

## Information

Cordova Packages:

    cli: 11.0.0
        common: 4.1.0
        create: 4.1.0
        lib: 11.1.0
            common: 4.1.0
            fetch: 3.1.0
            serve: 4.0.1

Project Installed Platforms:

    android: 11.0.0
    ios: 6.2.0

Environment:

    OS: macOS Monterey 12.6.3 (21G419) (darwin 21.6.0) x64
    Node: v12.14.0
    npm: 6.14.10

### Command or Code

```shell
$ ionic cordova platform add android@latest --verbose
# ...
Cannot read property 'find' of null
TypeError: Cannot read property 'find' of null
    at /.../node_modules/cordova-android/lib/prepare.js:387:49
    at Array.forEach (<anonymous>)
    at updateProjectSplashScreen (/.../node_modules/cordova-android/lib/prepare.js:384:7)
    at updateProjectAccordingTo (/.../node_modules/cordova-android/lib/prepare.js:269:5)
    at /.../node_modules/cordova-android/lib/prepare.js:67:21
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

I found the reason on prepare.js:
```diff
function updateProjectSplashScreen (platformConfig, locations) {
    // res/values/themes.xml
    const themes = xmlHelpers.parseElementtreeSync(locations.themes);
    const splashScreenTheme = themes.find('style[@name="Theme.App.SplashScreen"]');

    [
        'windowSplashScreenAnimatedIcon',
        'windowSplashScreenAnimationDuration',
        'windowSplashScreenBackground',
        'windowSplashScreenBrandingImage',
        'windowSplashScreenIconBackgroundColor',
        'postSplashScreenTheme'
    ].forEach(themeKey => {
        const cdvConfigPrefKey = 'Android' + themeKey.charAt(0).toUpperCase() + themeKey.slice(1);
        const cdvConfigPrefValue = platformConfig.getPreference(cdvConfigPrefKey, this.platform);
-        let themeTargetNode = splashScreenTheme.find(`item[@name="${themeKey}"]`);
+       let themeTargetNode = splashScreenTheme ? splashScreenTheme.find(`item[@name="${themeKey}"]`) : null;
``` 
If you change this line, you can add android successfully

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
It's my understand that the use of `"Theme.App.SplashScreen"` theme is **required** by the Splashscreen compatibility library. So if you're missing this theme configuration, I believe you you will run into a runtime crash on all android devices that makes use of the Compatibility library (API 30 and earlier if I recall correctly).

Note that Cordova configures a project with these theme node present, so you may have a hook, or something in the ionic framework might be overriding the themes file.

**Comment by Lyfei** [comment]
> It's my understand that the use of `"Theme.App.SplashScreen"` theme is **required** by the Splashscreen compatibility library. So if you're missing this theme configuration, I believe you you will run into a runtime crash on all android devices that makes use of the Compatibility library (API 30 and earlier if I recall correctly).
> 
> Note that Cordova configures a project with these theme node present, so you may have a hook, or something in the ionic framework might be overriding the themes file.

When I removed the cordova-plugin-telerik-imagepicker， I re-added the Android platform successfully。It replaces the themes.xml
