### ISSUE TITLE
Splashscreen keeps showing default cordova logo SDK-32 Android

### ISSUE THREAD

**Issue by noriellecruz** [apache/cordova-android#1578]
# Bug Report
Splashscreen keeps showing default cordova logo SDK-32 Android

## Problem
Splashscreen keeps showing default cordova logo SDK-32 Android. Also, after doing some search here, it seems not possible to disable the splashscreen in android 12 or above. We really don't need splashscreen but since it cannot be disabled, we expected that the default cordova logo will be replaced with the app icon if not configured.

### What is expected to happen?
Use the provided app icon if splash is not configured

```
<icon src="resources/icon/ldpi/ic_launcher.png" background="resources/icon/ldpi/ic_launcher_background.png" density="ldpi" foreground="resources/icon/ldpi/ic_launcher_foreground.png" />
<icon src="resources/icon/mdpi/ic_launcher.png" background="resources/icon/mdpi/ic_launcher_background.png" density="mdpi" foreground="resources/icon/mdpi/ic_launcher_foreground.png" />
<icon src="resources/icon/hdpi/ic_launcher.png" background="resources/icon/hdpi/ic_launcher_background.png" density="hdpi" foreground="resources/icon/hdpi/ic_launcher_foreground.png" />
<icon src="resources/icon/xhdpi/ic_launcher.png" background="resources/icon/xhdpi/ic_launcher_background.png" density="xhdpi" foreground="resources/icon/xhdpi/ic_launcher_foreground.png" />
<icon src="resources/icon/xxhdpi/ic_launcher.png" background="resources/icon/xxhdpi/ic_launcher_background.png" density="xxhdpi" foreground="resources/icon/xxhdpi/ic_launcher_foreground.png" />
<icon src="resources/icon/xxxhdpi/ic_launcher.png" background="resources/icon/xxxhdpi/ic_launcher_background.png" density="xxxhdpi" foreground="resources/icon/xxxhdpi/ic_launcher_foreground.png" />
```

### What does actually happen?
Keeps showing the default cordova logo in the new splashcreen api

### Environment, Platform, Device

Linux, Android, SDK-32

### Version information

Cordova CLI, Cordova Platforms

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
I'm not aware of any third-party tools.

All it needs is an image, it can be a PNG file. If you do use a PNG file, then you'll need to multiply all dimensions by 4 (xxxhpdi is x4 of the base display pixel unit). But if you're using a vector then as long as the canvas size is the display pixel, android can scale them correctly to the proper resolution by device.

Android Studio itself has a Vector Asset Studio tool which can be used to import PSD or SVG files and convert them into an AVD (Android Vector Drawable). So if you have an existing SVG, this might be able to be used.

Otherwise any graphic editing software that can produce PNGs or SVGs would do, but I'm not aware of anything that would generate things automatically.

**Comment by noriellecruz** [comment]
ok thanks.

**Comment by noriellecruz** [comment]
just to add some solution. supplying a 2732x2732 png image can still work for the splashscreen. just include this to your config.xml file:

`<preference name="AndroidWindowSplashScreenAnimatedIcon" value="path/to/your/splash.png" />`

just make sure that your logo will be centered and will not cover the whole image. additionally, [navigator.splashscreen.hide](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#navigatorsplashscreenhide) and [navigator.splashscreen.show](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#navigatorsplashscreenshow) doesn't work on the latest cordova-android anymore even though it says it's still supported from the [docs](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#javascript-public-apis).

**Comment by noriellecruz** [comment]
oh sorry, i didn't see that. will edit my reply.

**Comment by dylanfpaul** [comment]
> just to add some solution. supplying a 2732x2732 png image can still work for the splashscreen. just include this to your config.xml file:
> 
> `<preference name="AndroidWindowSplashScreenAnimatedIcon" value="path/to/your/splash.png" />`
> 
> just make sure that your logo will be centered and will not cover the whole image. additionally, [navigator.splashscreen.show](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#navigatorsplashscreenshow) doesn't work on the latest cordova-android anymore.

Can you confirm if a .png still works when targeting Android 13? I cannot simply use a png for the value of this preference and get my icon to show up. It always defaults to the cordova default splashscreen even on a real device.

**Comment by breautek** [comment]
> Can you confirm if a .png still works when targeting Android 13? I cannot simply use a png for the value of this preference and get my icon to show up. It always defaults to the cordova default splashscreen even on a real device.

PNGs can be used and is what I'm using for my apps.

But a 2732x2732 png probably won't look right, that's not the expected resolution. Like I mentioned in https://github.com/apache/cordova-android/issues/1578#issuecomment-1489255644, the icon should be 240x240dp.

If you're using rasterized PNGs instead of vectors, you'll need to scale up dp unit to px unit, otherwise it won't look right on high density devices. `xxxhdpi` devices is 4x the base dp unit. So you'll need a 960x960 PNG image.

Android masks the image, so only the center 160dp (or 640px) radius will be shown.

**Comment by dylanfpaul** [comment]
> > Can you confirm if a .png still works when targeting Android 13? I cannot simply use a png for the value of this preference and get my icon to show up. It always defaults to the cordova default splashscreen even on a real device.
> 
> PNGs can be used and is what I'm using for my apps.
> 
> But a 2732x2732 png probably won't look right, that's not the expected resolution. Like I mentioned in [#1578 (comment)](https://github.com/apache/cordova-android/issues/1578#issuecomment-1489255644), the icon should be 240x240dp.
> 
> If you're using rasterized PNGs instead of vectors, you'll need to scale up dp unit to px unit, otherwise it won't look right on high density devices. `xxxhdpi` devices is 4x the base dp unit. So you'll need a 960x960 PNG image.
> 
> Android masks the image, so only the center 160dp (or 640px) radius will be shown.

Thanks for confirming pngs are still usable. I am referencing a png file in this tag `<preference name="AndroidWindowSplashScreenAnimatedIcon"` to no avail. Instead of showing my png file, it always shows the default cordova splashscreen with the cordova logo. I have tried this in multiple emulated devices as well as a physical device and it is always showing the default cordova splashscreen. I am on Cordova 11 by the way. Perhaps I should open a new issue if it isn't easily answerable here.

**Comment by breautek** [comment]
> Perhaps I should open a new issue if it isn't easily answerable here.

If you believe there is a bug, then I'd open a new issue. Try to describe all the details and possibly include a sample project that would be expected to work.

But if you're not sure if it's a bug, a more proper place for community support would be at our [discussions](https://github.com/apache/cordova/discussions). Having a sample project in this case will probably still be helpful though.

> Cordova 11

if by that you mean cordova-android@11, then you should be good for the splashscreen support. Though cordova-android@12 would be recommended for API 33 support.

**Comment by dylanfpaul** [comment]
> > Perhaps I should open a new issue if it isn't easily answerable here.
> 
> If you believe there is a bug, then I'd open a new issue. Try to describe all the details and possibly include a sample project that would be expected to work.
> 
> But if you're not sure if it's a bug, a more proper place for community support would be at our [discussions](https://github.com/apache/cordova/discussions). Having a sample project in this case will probably still be helpful though.
> 
> > Cordova 11
> 
> if by that you mean cordova-android@11, then you should be good for the splashscreen support. Though cordova-android@12 would be recommended for API 33 support.
> 
> I tend to watch my email pretty closely so I'll probably take a closer look at your issue/discussion sometime Sunday, but if I don't feel free to ping me.

Oh I am on cordova-android@12 and Cordova CLI 11, but yeah I'll start with creating a discussion and maybe that can help me figure out if it is a bug or not. Regardless, I really appreciate the reply as I have been wrestling with trying to use pngs for a couple days now. Stay tuned for the discussion. I appreciate it!

**Comment by dylanfpaul** [comment]
@breautek I appreciate the help. I have started a discussion that is outlining my problem:

https://github.com/apache/cordova/discussions/430

**Comment by MEGAMINDMK** [comment]
[Resolved my Issue](https://github.com/apache/cordova-android/issues/1578#issuecomment-1489255644)
Cordova enables splashscreen with background, so Android expects a 240x240dp image, with the icon content to fix within a 160dp center diameter.
