### ISSUE TITLE
Splashscreen logo not showing on Android 11 and below

### ISSUE THREAD

**Issue by noriellecruz** [apache/cordova-android#1579]
# Bug Report
Splashscreen logo not showing on Android 11 and below
## Problem
Splashscreen logo not showing on Android 11 and below
### What is expected to happen?
Also show splashscreen logo on Android 11 and below

### What does actually happen?
Only splashscreen background is showing

## Information

It is working properly on android 12 and above: 
https://i.ibb.co/1Q91zhK/Screenshot-1680190572.png

Only splashscreen background is showing on android 11 and below: 
https://i.ibb.co/DwCnqhJ/Screenshot-2023-03-30-23-36-07-16-f1daee9170fda1df4088c67226246dc4.jpg

Is this a bug? or I'm just missing something?

### Command or Code

```
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/splash.png" />
<preference name="AndroidWindowSplashScreenIconBackgroundColor" value="#ffffff" />
<preference name="AutoHideSplashScreen" value="false" />
```

### Environment, Platform, Device

Linux, Android

### Version information

Cordova cli latest, Cordova android latest

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> Is this a bug? or I'm just missing something?

There are bugs on the Android Emulator where the underlying compat library doesn't always draw the image. Afaik, this doesn't happen on real devices. This quirk is noted [here](https://cordova.apache.org/docs/en/11.x/core/features/splashscreen/#android).

Can you confirm if you're testing on an emulator?

**Comment by noriellecruz** [comment]
this is weird. it only happens on Realme device, i also have another realme with android 12. i tested it on a samsung android 12 and it's working fine.

**Comment by noriellecruz** [comment]
i tested again, this time on android 7 and it's working fine. i think this only happens on realme devices. anyway, thank for your response.

**Comment by noriellecruz** [comment]
we followed the instructions here: https://ionic.zendesk.com/hc/en-us/articles/7891143965975-Migrating-to-Cordova-Android-11

it says to use 2732x2732. here's the png image we used: https://i.ibb.co/169sNv5/splash.png

**Comment by breautek** [comment]
> we followed the instructions from here: https://ionic.zendesk.com/hc/en-us/articles/7891143965975-Migrating-to-Cordova-Android-11

it says to use 2732x2732. 

That's bad advice. The iOS splash screen universal image is 2732x2732, which is what Ionic is incorrectly referencing.

Android uses Bitmaps internally so once the PNG is decoded the memory size blows up.

> it says to use 2732x2732. here's the png image we used: https://i.ibb.co/169sNv5/splash.png

Either you've uploaded a 640x640 image or the the service scaled down the image to 640x640. You should be able to drag and drop onto GitHub when making a comment to attach image directly to github.

**Comment by noriellecruz** [comment]
we resized the image to 960x960 but still the same issue with Realme devices. it does work fine on other phone brands. we can settle to this for now.

thanks for your help.
