### ISSUE TITLE
 The top and bottom of the app are hidden by Android’s top and bottom bars in android 13

### ISSUE THREAD

**Issue by kptlclyx** [apache/cordova-android#1580]
# Bug Report

## Problem
In Android 13, our app does not display correctly. The top and bottom of the screen are obscured by the phone’s status strip at the top, and control strip at the bottom.

### What is expected to happen?
UI should have been rendered inside webview, that is, screen area which excludes system top bar and bottom bar

### What does actually happen?
UI gets rendered in full screen which includes systems top bar and bottom bars as well. Hence, systems ui getting displayed but mobile apps top/bottom bars and not getting displayed.

## Information
Device Details:
1)Samsung Galaxy A32 5G
Android 13
Samsung One UI 5.0
2)Samsung SM-A326W
Android 13

Images
https://onedrive.live.com/redir?resid=14F48D183050714E%21397921&authkey=%21AMvEMqR7WyJviYM&ithint=photo%2cjpg&e=rfsg1m

https://onedrive.live.com/redir?resid=14F48D183050714E%21397922&authkey=%21APVUnXAtxuBxINc&ithint=photo%2cjpg&e=C8UJWx

Note:
We are using voltbuilder to create andorid app, config file used to pass cordova details to voltbuilder as follows:
https://onedrive.live.com/redir?resid=14F48D183050714E%21397920&authkey=%21AGU9mKQgna2yhek&e=kwW8IB

**Checklist**
 
- [x] I searched for existing GitHub issues
- [x]  I updated all Cordova tooling to most recent version
- [x]  I included all the necessary information above

**Comment by Afnan0711** [comment]
Did you find any solution?

**Comment by kptlclyx** [comment]
@Afnan0711 No, I have not able to find any solution.

**Comment by timyyo** [comment]
Also having this issue, any possible solutions found?
