### ISSUE TITLE
Google play Android 13 support

### ISSUE THREAD

**Issue by gunpuz** [apache/cordova-android#1581]
# Bug Report

## Problem
Google play does not accept cordova application for newer devices like Android 13

### What does actually happen?

Application is not allowed to be installed in google play
![image](https://user-images.githubusercontent.com/39419120/229039269-fd60228e-0722-4758-9c34-f00228d39f14.png)

## Information

cordova config.xml
```xml
    <preference name="android-minSdkVersion" value="23" />
    <preference name="android-targetSdkVersion" value="33" />
    <preference name="android-compileSdkVersion" value="33" />
</widget>
```

Google play console:
![image](https://user-images.githubusercontent.com/39419120/229040198-da9ae851-3ba0-4e05-bf1e-3e2c2e35d234.png)

Does Cordova support android 13 devices (API level 33)? 
https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html

### Environment, Platform, Device

Android 13, Oppo find x5 pro, but it seems that this issue is not limited to only this specific device

### Version information

```json
"devDependencies": {
    "cordova": "^11.1.0",
    "cordova-android": "^10.1.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-network-information": "^2.0.1",
    "cordova-plugin-splashscreen": "^5.0.2"
  },
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Not much of this makes sense, so I have to ask...

As an internal tester on Google Play, you don't have access to The Production track, but rather the test track. So if you have an App Update published in the Production track but not your test track, then you may be seeing an old version of your application.

Are you sure your apps published to the right release tracks?

In the Play Store, go to your app page. Scroll to `About this app` and tap no the arrow. Scroll down to `App info` and ensure that the displayed version matches as expected.

**Comment by gunpuz** [comment]
No the production track is "untouched", usually internal testing, closed testing... is used first for testing purposes like this one. The application is published in "internal testing" track.
![image](https://user-images.githubusercontent.com/39419120/229461919-3cb51386-3a8b-4c5c-93b0-177e41b7a4be.png)

Further more, device catalog in google console shows this device as "supported"

**Comment by gunpuz** [comment]
What could be checked to debug this issue even more?

**Comment by breautek** [comment]
Can you confirm that Google Play Store (on the device) is showing the expected version?

> In the Play Store, go to your app page. Scroll to About this app and tap no the arrow. Scroll down to App info and ensure that the displayed version matches as expected. So based on your internal track, the app storage page should be showing version 1.1.0.

If it's not showing the correct version, then you're test account might belong to a different track...

If it is showing the expected version, then you might have to get into contact with Google Play support

**Comment by breautek** [comment]
One thing you can check is to make sure nothing isn't adding a max SDK version. If you don't explicit set it, it may come from a plugin.

**Comment by gunpuz** [comment]
Sorry, yes, the versionCode was not incremented as resulting in old application version.
