### ISSUE TITLE
App crashes on splashscreen on Android 11 (for apk release)

### ISSUE THREAD

**Issue by hejercherbib** [apache/cordova-android#1582]
I have barely the same issue my app crashes when launching the app on a device running on Android 11 (only for release apk, debug works fine)
knowing that I don't have any reference in my app to any resource called icon_background (and even when I had added one it also doesn't find it)
this is the error:
` java.lang.RuntimeException: Unable to start activity ComponentInfo{pssa.ww.parcelscan/pssa.ww.parcelscan.MainActivity}: android.content.res.Resources$NotFoundException: Drawable pssa.ww.parcelscan:drawable/icon_background with resource ID #0x7f070060 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3450) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3602) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7697) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) Caused by: android.content.res.Resources$NotFoundException: Drawable pssa.ww.parcelscan:drawable/icon_background with resource ID #0x7f070060 Caused by: android.content.res.Resources$NotFoundException: File res/Ln.xml from drawable resource ID #0x7f070060 at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:891) at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:673) at android.content.res.Resources.loadDrawable(Resources.java:996) at android.content.res.Resources.getDrawableForDensity(Resources.java:986) at android.content.res.Resources.getDrawable(Resources.java:925) at android.content.Context.getDrawable(Context.java:693) at androidx.core.splashscreen.SplashScreen$Impl.displaySplashScreenIcon(SplashScreen.kt:354) at androidx.core.splashscreen.SplashScreen$Impl.setOnExitAnimationListener(SplashScreen.kt:318) at androidx.core.splashscreen.SplashScreen.setOnExitAnimationListener(SplashScreen.kt:185) at org.apache.cordova.SplashScreenPlugin.setupSplashScreen(SplashScreenPlugin.java:141) at org.apache.cordova.SplashScreenPlugin.onMessage(SplashScreenPlugin.java:113) at org.apache.cordova.PluginManager.lambda$postMessage$0(PluginManager.java:345) at org.apache.cordova.PluginManager$$ExternalSyntheticLambda0.accept(Unknown Source:8) at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) at java.util.Collections$SynchronizedMap.forEach(Collections.java:2698) at org.apache.cordova.PluginManager.postMessage(PluginManager.java:343) at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:161) at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:234) at pssa.ww.parcelscan.MainActivity.onCreate(MainActivity.java:40) at android.app.Activity.performCreate(Activity.java:8000) at android.app.Activity.performCreate(Activity.java:7984) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3602) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7697) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)`

**Comment by hejercherbib** [comment]
Thank you for your reply, here is my generated theme (in platform):
What's a litle bit confusing is that the same version with debug apk works normally,
Here is the  theme.xml file (generated in platform):
`<?xml version="1.0" encoding="utf-8"?>

<resources>
    <style name="Theme.App.SplashScreen" parent="Theme.SplashScreen.IconBackground">
      
      <item name="windowSplashScreenBackground">@color/cdv_splashscreen_background</item>

      
      <item name="windowSplashScreenAnimatedIcon">@drawable/ic_cdv_splashscreen</item>

      
      <item name="windowSplashScreenAnimationDuration">200</item>

      
      <item name="postSplashScreenTheme">@style/Theme.AppCompat.NoActionBar</item>
    </style>
</resources>`

And here is my config.xml :
`<preference name="SplashScreen" value="screen"/>
    <preference name="AutoHideSplashScreen" value="false"/>
    <preference name="SplashScreenDelay" value="3600000"/>
    <preference name="FadeSplashScreen" value="false"/>
    <preference name="Orientation" value="portrait"/>
    <preference name="android-minSdkVersion" value="21"/>
    <preference name="android-targetSdkVersion" value="32"/>
    <preference name="ShowTitle" value="False"/>
    <preference name="target-device" value="handset"/>
    <preference name="deployment-target" value="9"/>
    <preference name="BackupWebStorage" value="none"/>
    <preference name="SuppressesIncrementalRendering" value="True"/>
    <preference name="HideKeyboardFormAccessoryBar" value="True"/>
    <preference name="KeepRunning" value="True"/>
    <preference name="InAppBrowserStorageEnabled" value="True"/>
    <preference name="AndroidPersistentFileLocation" value="Internal"/>
    <preference name="iosPersistentFileLocation" value="Library"/>
    <preference name="AndroidLaunchMode" value="singleTop"/>
    <preference name="android-build-tool" value="ant"/>
    <preference name="xwalkZOrderOnTop" value="false"/>
    <preference name="CrosswalkAnimatable" value="true"/>
    <preference name="StatusBarOverlaysWebView" value="true"/>
    <preference name="StatusBarStyle" value="lightcontent"/>
    <preference name="StatusBarBackgroundColor" value="#000000"/>
    <preference name="AndroidInsecureFileModeEnabled" value="true"/>
    <preference name="AndroidPersistentFileLocation" value="Compatibility"/>
    <allow-intent href="http://*/*"/>
    <allow-intent href="https://*/*"/>
    <allow-intent href="tel:*"/>
    <access origin="*"/>
    <allow-navigation href="http://*/*"/>
    <allow-navigation href="https://*/*"/>
    <hook src="local-hooks/android/6.4.0/copy-res.js" type="before_prepare"/>
    <hook src="local-hooks/android/6.4.0/androidWindowSoftInputMode.js" type="before_prepare"/>
    <hook src="local-hooks/android/10/copy_apks_after_build.js" type="after_build"/>
    <hook src="local-hooks/android/6.4.0/set_allowBackup.js" type="after_prepare" />

    <platform name="android">
        <icon density="ldpi" src="res/icons/android/icon-36-ldpi.png"/>
        <icon density="mdpi" src="res/icons/android/icon-48-mdpi.png"/>
        <icon density="hdpi" src="res/icons/android/icon-72-hdpi.png"/>
        <icon density="xhdpi" src="res/icons/android/icon-96-xhdpi.png"/>
        <icon src="res/icons/android/icon-96-xhdpi.png" />
    </platform>
    <custom-preference name="android-manifest/application/@android:usesCleartextTraffic" value="true"/>
    <platform name="ios">
        <icon height="180" src="res/icons/ios/icon-60-3x.png" width="180"/>
        <icon height="60" src="res/icons/ios/icon-60.png" width="60"/>
        <icon height="120" src="res/icons/ios/icon-60-2x.png" width="120"/>
        <icon height="76" src="res/icons/ios/icon-76.png" width="76"/>
        <icon height="152" src="res/icons/ios/icon-76-2x.png" width="152"/>
        <icon height="40" src="res/icons/ios/icon-40.png" width="40"/>
        <icon height="80" src="res/icons/ios/icon-40-2x.png" width="80"/>
        <icon height="57" src="res/icons/ios/icon-57.png" width="57"/>
        <icon height="114" src="res/icons/ios/icon-57-2x.png" width="114"/>
        <icon height="72" src="res/icons/ios/icon-72.png" width="72"/>
        <icon height="144" src="res/icons/ios/icon-72-2x.png" width="144"/>
        <icon height="29" src="res/icons/ios/icon-small.png" width="29"/>
        <icon height="58" src="res/icons/ios/icon-small-2x.png" width="58"/>
        <icon height="50" src="res/icons/ios/icon-50.png" width="50"/>
        <icon height="100" src="res/icons/ios/icon-50-2x.png" width="100"/>
    </platform>
    <platform name="android">
        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/drawable/ic_logo_pickup.xml" />
        <preference name="AndroidWindowSplashScreenBackground" value="#DC0032" />
    </platform>
    <plugin name="cordova-plugin-device" src="local-plugins\cordova-plugin-device-2.0.3" version="2.0.3"/>
    <plugin name="cordova-plugin-file" spec="6.0.2"/>
    <plugin name="cordova-plugin-network-information" version="1.2.0"/>
    <plugin name="cordova-plugin-zip" src="https://github.com/MobileChromeApps/zip.git" version="3.1.0"/>
    <plugin name="cordova-plugin-inappbrowser" version="1.3.0"/>
    <plugin name="cordova-plugin-statusbar" version="2.1.2"/>
    <plugin name="cordova-plugin-app-event" version="1.2.0"/>
    <plugin name="cordova-plugin-dialogs" version="1.2.0"/>
    <plugin name="cordova-plugin-vs-taco-support" version="0.2.3"/>
    <plugin name="org.apache.cordova.home" src="https://github.com/ZhichengChen/cordova-plugin-android-home" version="0.2.6"/>
    <plugin name="cordova-plugin-compat" version="1.2.0"/>
    <plugin name="cordova-plugin-fullscreen" src="https://github.com/mesmotronic/cordova-plugin-fullscreen.git" version="1.1.0"/>
    <plugin name="cordova-pssa-plugin-device-extra-infos" src=".\local-plugins\cordova-pssa-plugin-device-extra-infos" version="1.0.0"/>
    <plugin name="cordova-pssa-plugin-application" src=".\local-plugins\cordova-pssa-plugin-application" version="1.0.0"/>
    <plugin name="cordova-pssa-plugin-keyboard-height" src=".\local-plugins\cordova-pssa-plugin-keyboard-height" version="1.0.0"/>
    <plugin name="com.mirasense.scanditsdk.plugin" src=".\local-plugins\scandit-barcodescanner-phonegap_5.4.0" version="5.4.0"/>
    <plugin name="cordova-plugin-battery-status" version="1.2.0"/>
    <plugin name="cordova-pssa-plugin-athesi-barcodescanner" src=".\local-plugins\cordova-pssa-plugin-athesi-barcodescanner" version="2.5.0"/>
    <plugin name="cordova-pssa-plugin-mdmservice" src=".\local-plugins\cordova-pssa-plugin-mdmservice" version="1.1.1"/>
    <plugin name="com-darryncampbell-cordova-plugin-intent" src=".\local-plugins\com-darryncampbell-cordova-plugin-intent" version="1.1.1"/>
    <plugin name="cordova-plugin-awesome-shared-preferences" version="0.1.0"/>
    <plugin name="cordova-plugin-bluetoothle" version="6.7.0"/>
    <plugin name="it.zenitlab.cordova.plugins.zbtprinter" src=".\local-plugins\it.zenitlab.cordova.plugins.zbtprinter" version="1.0"/>
    <plugin name="cordova-plugin-app-version" version="0.1.9"/>
    <plugin name="cordova-plugin-appavailability" version="0.4.2"/>
    <plugin name="cordova-plugin-file-transfer" src=".\local-plugins\cordova-plugin-file-transfer"/>

    <plugin name="cordova-plugin-keyboard" src=".\local-plugins\cordova-plugin-keyboard" version="1.2.0"/>
    <plugin name="cordova-pssa-plugin-applauncher" src=".\local-plugins\cordova-pssa-plugin-applauncher" version="0.1.0"/>
    <plugin name="cordova-pssa-plugin-files-manager" src=".\local-plugins\cordova-pssa-plugin-files-manager" version="1.0.0"/>
    <plugin name="cordova-pssa-plugin-cze-payment" src=".\local-plugins\cordova-pssa-plugin-cze-payment" version="1.0.0"/>
    <plugin name="cordova-pssa-plugin-zebra-scan" src=".\local-plugins\cordova-pssa-plugin-zebra-scan" version="1.0.0"/>

</widget>`

**Comment by breautek** [comment]
Alright thanks.

The `themes.xml` actually looks fine and expected here. So I don't think the crash is from what I was originally expecting.

However, I see you're using an XML vector for your icon. `res/drawable/ic_logo_pickup.xml`.

**If this is an SVG**, then read on. If not, skip down below.

Android has limited support for SVG directives and can result in a crash if you're using an unsupported directive.

Android Studio does have a tool called [Asset Vector Studio](https://developer.android.com/studio/write/vector-asset-studio) which can be used to import an SVG and convert it to an AVD (Android Vector Drawable), and if the SVG does have something that cannot be converted, it should provide the appropriate feedback.

To access the Vector Asset Studio, you'll need to open up the project in Android Studio (available in `<cordova-project/platforms/android`). Android Studio may prompt you to update plugins like Android Gradle Plugin. **DO NOT UPDATE**, as it will likely break the cordova project. SImply dismiss the prompt.

On the left tab, you should see `Resource Manager`:

<img width="620" alt="Screenshot 2023-03-31 at 12 03 28 PM" src="https://user-images.githubusercontent.com/11200662/229157694-07481efd-c05f-420b-8551-5aa0a4acc613.png">

From there, click on the `+` Icon to add a `Vector Asset`, which will open a dialog where you can import an SVG.

<img width="701" alt="Screenshot 2023-03-31 at 12 04 54 PM" src="https://user-images.githubusercontent.com/11200662/229158046-b6983ceb-a7ef-4185-92cb-52088796df5a.png">

Click next and it will show you will it still store the asset. You'll need to copy the asset back to your root cordova project (rather than leaving it in the generated native project). Android Studio should have placed it in `<cordova-project>/platforms/android/app/src/main/res/drawable/<name_you_have_chosen>.xml`, which should be copied to your `res/drawable/` folder (same location as your `ic_logo_pickup.xml` as referenced in `config.xml`. Now when you generate the android project, you will have an AVD vector that will get copied.

**If the xml is already an AVD**, then if you could share the icon as well as a [minimal reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) that uses the vector, but without any additional plugins, I would suspect that it will be enough to trigger the crash. If so, sharing that reproduction app might help us drill down deeper.

**Comment by Carlosps** [comment]
@breautek What would be a good advice to find out which plugin may be causing the issue?

Do we have to remove one by one or there is a better approach?

**Comment by breautek** [comment]
> @breautek What would be a good advice to find out which plugin may be causing the issue?
> 
> Do we have to remove one by one or there is a better approach?

Currently cordova plugins are extracted and stored to `<cordova-project>/plugins` as a cache location. It doesn't really serve any great purpose but in this case it will make easy for you to use a `Find in Folder` kind of option if your code editor supports such feature.

Searching for `themes.xml` keyword would be a good start. However if the issue is related more to the given icon like the OP (as suspected...), then this might not help.

**Comment by breautek** [comment]
Closing as stale.
