### ISSUE TITLE
Backbutton causes screen overlapping

### ISSUE THREAD

**Issue by rennan0** [apache/cordova-android#1591]
# Bug Report

### What is expected to happen?
When pressed the back button should return to the previous screen.

### What does actually happen?
When pressing the back button the current screen is superimposed with elements from the previous screen.
*I ran the browser version just to show the problem. Note that 3 different pages are "stacked" in the view after hitting the backbutton:
[https://ibb.co/9HFqQLn](https://ibb.co/9HFqQLn)

## Information

My application was made with angular and exported to android using cordova. I use lazy loading for screen navigation.

### Command or Code

This is my navigation:
`const routes: Routes = [
  {
    path: '', component: HomeComponent, children: [
      {
        path: 'contato',
        loadChildren: () => import('../contato/contato.module').then(m => m.ContatoModule)
      },
      {
        path: 'perfil',
        loadChildren: () => import('../perfil/perfil.module').then(m => m.PerfilModule)
      },
      {
        path: 'minhaAgenda',
        loadChildren: () => import('../minha-agenda/minha-agenda.module').then(m => m.MinhaAgendaModule)
      },
      {
        path: 'sobre',
        loadChildren: () => import('../sobre/sobre.module').then(m => m.SobreModule)
      },
      {
        path: 'agendar',
        loadChildren: () => import('../agendar/agendar.module').then(m => m.AgendarModule)
      },
      {
        path: 'alterarSenha',
        loadChildren: () => import('../alterar-senha/alterar-senha.module').then(m => m.AlterarSenhaModule)
      }
      ,
      {
        path: 'buscarBarbearia',
        loadChildren: () => import('../buscar-barbearia/buscar-barbearia.module').then(m => m.BuscarBarbeariaModule)
      },
      {
        path: 'detalheInformativo',
        loadChildren: () => import('../detalhe-informativo/detalhe-informativo.module').then(m => m.DetalheInformativoModule)
      },
      {
        path: 'menuAdministrativo',
        loadChildren: () => import('../menu-administrativo/menu-administrativo.module').then(m => m.MenuAdministrativoModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'cadastrarBarbearia',
        loadChildren: () => import('../cadastrar-barbearia/cadastrar-barbearia.module').then(m => m.CadastrarBarbeariaModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'barbearia',
        loadChildren: () => import('../barbearia/barbearia.module').then(m => m.BarbeariaModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'cadastrarBarbeiros',
        loadChildren: () => import('../cadastrar-barbeiros/cadastrar-barbeiros.module').then(m => m.CadastrarBarbeirosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'barbeiro',
        loadChildren: () => import('../barbeiro/barbeiro.module').then(m => m.BarbeiroModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'agenda',
        loadChildren: () => import('../agenda/agenda.module').then(m => m.AgendaModule),
        canActivate: [FuncionarioGuard]
      },
      {
        path: 'cadastrarServicos',
        loadChildren: () => import('../cadastrar-servicos/cadastrar-servicos.module').then(m => m.CadastrarServicosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'servico',
        loadChildren: () => import('../servico/servico.module').then(m => m.ServicoModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'relatorios',
        loadChildren: () => import('../relatorios/relatorios.module').then(m => m.RelatoriosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'cadastrarHorarios',
        loadChildren: () => import('../cadastrar-horarios/cadastrar-horarios.module').then(m => m.CadastrarHorariosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'horarios',
        loadChildren: () => import('../horarios/horarios.module').then(m => m.HorariosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'filiarBarbearia',
        loadChildren: () => import('../filiar-barbearia/filiar-barbearia.module').then(m => m.FiliarBarbeariaModule)
      },
      {
        path: 'clientesFiliados',
        loadChildren: () => import('../clientes-filiados/clientes-filiados.module').then(m => m.ClientesFiliadosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'noticias',
        loadChildren: () => import('../noticias/noticias.module').then(m => m.NoticiasModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'cadastrarInformativos',
        loadChildren: () => import('../cadastrar-informativos/cadastrar-informativos.module').then(m => m.CadastrarInformativosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'informativos',
        loadChildren: () => import('../informativos/informativos.module').then(m => m.InformativosModule),
        canActivate: [AdministradorGuard]
      },
      {
        path: 'cadastrarPesquisa',
        loadChildren: () => import('../cadastrar-pesquisa/cadastrar-pesquisa.module').then(m => m.CadastrarPesquisaModule)
      },
      {
        path: 'pesquisa',
        loadChildren: () => import('../pesquisa/pesquisa.module').then(m => m.PesquisaModule)
      },
      // {
      //   path: 'cadastrarNotificacoes',
      //   loadChildren: () => import('../cadastrar-notificacoes/cadastrar-notificacoes.module').then(m => m.CadastrarNotificacoesModule)
      // },
      {
        path: 'notificacoes',
        loadChildren: () => import('../notificacoes/notificacoes.module').then(m => m.NotificacoesModule)
      },
      {
        path: 'faturas',
        loadChildren: () => import('../faturas/faturas.module').then(m => m.FaturasModule)
      },
      {
        path: 'detalheNotificacao',
        loadChildren: () => import('../detalhe-notificacao/detalhe-notificacao.module').then(m => m.DetalheNotificacaoModule)
      },
      {
        path: 'cadastrarComissao',
        loadChildren: () => import('../cadastrar-comissao/cadastrar-comissao.module').then(m => m.CadastrarComissaoModule)
      },
      {
        path: 'comissao',
        loadChildren: () => import('../comissao/comissao.module').then(m => m.ComissaoModule)
      },
    ],
    canActivate: [LoginGuard]
  },

  {
    path: 'login', component: LoginComponent
  },
  {
    path: 'cadastro', component: CadastroComponent
  },
  {
    path: 'esqueceuSenha', component: EsqueceuSenhaComponent
  },
  {
    path: 'alterarSenhaDeslog', component: AlterarSenhaDeslogComponent
  },
  {
    path: 'codigoRecuperacao', component: CodigoRecuperacaoComponent
  },
  { path: '**', component: LoginComponent }

];`

### Environment, Platform, Device

Android.

### Version information

What are relevant versions you are using?
Cordova: 11.1.0.
Angular CLI: 14.2.1
Node: 16.14.0
Java: 11.0.17

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
By default when the hardware back button is pressed, Cordova simply calls on the webview's history back API (natively), which ultimately makes the webview change the URL to the previously loaded URL (whether that be an actual page change, or a injected history value via the JS History API).

Cordova doesn't control the actual app web content here. So this sounds like an Application or potentially an Angular bug. If the history API isn't being used, then the back would trigger a page reload of the previous page, or change the `#` part of the URL without reloading, as per standard browser behaviour.

If the web application uses the History API, or pushes `#` urls, then it would be up to the application to listen for URL changes via the History API's [PopStateEvent](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent) or the [hashchange](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) event so it knows when to rerender and what to render. Which event to use would be depend on your routing strategy.

Can you provide more information on why it's believed that this is a bug within Cordova?

**Comment by rennan0** [comment]
> By default when the hardware back button is pressed, Cordova simply calls on the webview's history back API (natively), which ultimately makes the webview change the URL to the previously loaded URL (whether that be an actual page change, or a injected history value via the JS History API).
> 
> Cordova doesn't control the actual app web content here. So this sounds like an Application or potentially an Angular bug. If the history API isn't being used, then the back would trigger a page reload of the previous page, or change the `#` part of the URL without reloading, as per standard browser behaviour.
> 
> If the web application uses the History API, or pushes `#` urls, then it would be up to the application to listen for URL changes via the History API's [PopStateEvent](https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent) or the [hashchange](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) event so it knows when to rerender and what to render. Which event to use would be depend on your routing strategy.
> 
> Can you provide more information on why it's believed that this is a bug within Cordova?

Thanks for reply,
I managed to solve my problem placing the following code just before cordova.js on my index.html:

`  <script>
      window.addEventListener = function () {
        (window.EventTarget || Window).prototype.addEventListener.apply(this, arguments);
      };
      window.removeEventListener = function () {
        (window.EventTarget || Window).prototype.removeEventListener.apply(this, arguments);
      };
      document.addEventListener = function () {
        (window.EventTarget || Document).prototype.addEventListener.apply(this, arguments);
      };
      document.removeEventListener = function () {
        (window.EventTarget || Document).prototype.removeEventListener.apply(this, arguments);
      };
  </script>  
  <script type="text/javascript" src="cordova.js"></script>`
