### ISSUE TITLE
Color palette for native android date picker incorrect

### ISSUE THREAD

**Issue by tschuppi** [apache/cordova-android#1614]
# Bug Report

### What is expected to happen?

Colors for selected and current date have a blue color.

### What does actually happen?

Colors for selected and current date are transparent.

### Command or Code

Create new cordova project: "cordova create example-project"
Add platform: "cordova platform add android@9.1.0"
At the example www folder: index.html: Insert HTML input with type date
cordova run android
Click on datepicker
The datepicker looks like the image attached. 
All colours are messed up and the current day color + selected date color are transparent.

![Screenshot 2023-05-16 172556](https://github.com/apache/cordova-android/assets/10996180/a460abd6-15c2-45b8-9e50-1d134d8afdf4)

### Environment, Platform, Device

Galaxy XCover Pro
Android 13

### Version information

Cordova Android 9.1.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Cordova doesn't control browser features, that's implemented by the underlying webview. To some extent, the colours may be controlled by some CSS (although styling on `input` fields is usually limited)

Ensuring that your system webview is up to date may solve this issue. For what it's worth, I'm not reproducing it on Chrome webview v112.

Closing as not-a-bug.
