### ISSUE TITLE
Cordova 11 is not working on android 11 and angular 16

### ISSUE THREAD

**Issue by winwinkhaing-klw** [apache/cordova-android#1615]
# Cordova 11 is not working on android 11 and angular 16

After updating angular 16, the cordova build application doesn't work on android 11

**Comment by dpogue** [comment]
Did this happen after updating Angular, or updating Cordova? If updating Angular caused the problem, then it should be reported to Angular.

What does "not working" mean? Please provide a detailed description of the problem, any error messages, and (if possible) a simple test case that reproduces the problem.

**Comment by winwinkhaing-klw** [comment]
Thanks for quick reply. I can run after upgrading android 12 with angular 16. When I launched the application to emulator, the application is not working with android 11.

**Comment by jcesarmobile** [comment]
Angular browser support is just last 2 chrome/chromium versions, the emulator is probably running an unsupported chrome/chromium version.
You can usually configure angular to support older versions, check their docs about how to compile for older browsers or using polyfills.

you can e bug the app and see what error comes out to figure out if you need some polyfill 
https://developer.chrome.com/docs/devtools/remote-debugging/webviews/#open_a_webview_in_devtools
