### ISSUE TITLE
cordova-android 9 or below not working  but latest version working

### ISSUE THREAD

**Issue by hansarajgyaneswar** [apache/cordova-android#1618]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\HANSARAJ\Desktop\hello\platforms\android\CordovaLib\build.gradle' line: 50

* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin 'com.github.dcendents.android-maven'.
   > Could not create plugin of type 'AndroidMavenPlugin'.
      > Could not generate a decorated class for type AndroidMavenPlugin.
         > org/gradle/api/publication/maven/internal/MavenPomMetaInfoProvider

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

 "name": "com.khusilu.recharge",
  "displayName": "KhuSiluRecharge",
  "version": "1.0.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "devDependencies": {
    "cordova-android": "^9.1.0"
  },
  "cordova": {
    "platforms": [
      "android"
    ]
  }

**Comment by breautek** [comment]
cordova-android 9 is out of support.

cordova-android@12 is required to target API 33 which will be required **soon** by Google Play store. It's recommended to use cordova-android@12.

**Comment by hansarajgyaneswar** [comment]
cordova-android@12 app crashing and not  install issu

**Comment by breautek** [comment]
> cordova-android@12 app crashing and not install issu

Then I'd advise creating a new issue with that context and we may be able to help you to get back on track. For support style questions however, it would be better to post on our [discussions](https://github.com/apache/cordova/discussions)
