### ISSUE TITLE
How can I get my code after the app has neen builded for android?

### ISSUE THREAD

**Issue by FVellu** [apache/cordova-android#1629]
I tried unzipping the .apk, i can see a www folder, but there's no js folder inside

Typo in the title, I meant "been"

**Comment by breautek** [comment]
the src `www` folder will be inside the `assets` directory.

Whether a `js` folder exists depends on the structure of your `www` folder. At the very minimum you should see `assets/www/cordova.js` and `assets/www/cordova_plugins.js`

Also note that after an APK is signed/zip aligned, simply unzipping the contents may yield corrupt files. After an APK is zip aligned, the memory bits is formatted specifically to be read by Android OS.

Closing as not an issue.
