### ISSUE TITLE
Not able to add platform using cordova-android 12

### ISSUE THREAD

**Issue by kunalSBasic** [apache/cordova-android#1656]
Hello everyone,

I hope you're doing well. I'm currently facing an issue while trying to install Cordova-Android 12 for my project. I thought I'd reach out here to see if anyone else has encountered a similar problem or has insights on how to resolve it.

Error Message:
Upon executing the command `ionic cordova platform add android@latest`, I'm presented with the following error message:
<img width="1440" alt="Screenshot 2023-08-29 at 10 40 57 PM" src="https://github.com/apache/cordova-android/assets/109348919/bf5b5023-b341-4453-9740-54cbee061406">

Running command `cordova -v`:  **12.0.0 (cordova-lib@12.0.1)**

Running command `ionic info`: 
<img width="1440" alt="Screenshot 2023-08-29 at 10 46 24 PM" src="https://github.com/apache/cordova-android/assets/109348919/820dfa72-fe74-43b4-928b-ca564c083fb2">

**Comment by jcesarmobile** [comment]
cordova-support-google-services and cordova-plugin-androidx are not supported and also not needed in cordova-android 12, so uninstall them and that should allow the platform to install.
