### ISSUE TITLE
Splashscreen logo not showing on Android 12

### ISSUE THREAD

**Issue by igorsantos07** [apache/cordova-android#1669]
# Bug Report
This is the same as #1579, except I'm using Android 12 on an OnePlus 7t instead of a Realme.

## Problem
Splash screen shows just the background color, no icon whatsoever.

### What is expected to happen?
Migration to cordova-android 12 should go smooth, without having to do guesswork on migrating the splashscreen or why the heck the icon is never showing up.

### What does actually happen?
OnePlus splashes just with the background color. A Samsung tablet with Android 11, though, works just fine*.

Honestly, while the previous user decided to just abandon the bug report, I think this is an important problem since it actually makes our Cordova app *unreliable*. A splashscreen without any text or icon, even though it's colored, looks like a broken app for the user. The moment they click the icon, they _want_ to see something, and seeing just a blank/colored screen is confusing - specially if we're downloading a new payload, which could make the splashscreen hang for more time than the user would bear an empty screen.

> \* I realized I should try other devices only after I gave up and started googling for splash screen problems on cordova 12, and then found #1579; sadly, **I had spent almost a day trying to figure out what I was doing wrong**, since documentation is really lacking on that part. Specifically, it's missing an explanation on what formats are acceptable for the icon, since it looks like it only works with an XML file (from unknown origin, had to google to find how to create one) but it actually accepts the old PNG, as long as it has the proper padding. There's also no clear path of migration from the previous `<splash>` tags, not even in the announcement blog post - you have to read through the original Android documentation to piece stuff out, that's totally frustrating.

### Command or Code
Showing here the relevant(?) parts of `config.xml`:
```xml
<engine name="android" spec="^12.0.1" />
<platform name="android">
    <preference name="android-targetSdkVersion" value="33" />

    <!-- TODO overrides cordova-plugin-push's requirement of 1.5.20, which causes some deprecation errors -->
    <preference name="GradlePluginKotlinEnabled" value="true" />
    <preference name="GradlePluginKotlinVersion" value="1.7.21" />

    <preference name="AndroidWindowSplashScreenBackground" value="#F8B61D" />
    <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/drawable/bot.xml" />
    <!-- preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/drawable/bot.png" /-->
</platform>
<preference name="AutoHideSplashScreen" value="false" />
```

### Environment, Platform, Device
Affected device: Android 12, [OnePlus 7t](https://www.gsmarena.com/oneplus_7t-9816.php)
Working device: Android 11, [Samsung SM-P205](https://www.gsmarena.com/samsung_galaxy_tab_a_8_0_&_s_pen_(2019)-9651.php)
I also tested on an [ancient Moto G4 Play](https://www.gsmarena.com/motorola_moto_g4_play-8104.php#xt1603) running Android 7, it also works fine, if this is of any help :joy:

### Version information
Cordova CLI 12.0.0 (cordova-lib 12.0.1)
Cordova-android 12.0.1
Target Android SDK: API 33
Linux Mint Uma 20.2
Android Studio Giraffe (only used to generate the vector XML, but could be used for debugging if necessary, I guess?)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Providing the icon resources you have tried might help us determine if the icon itself is being authored incorrectly.

I've recently used Android Studio to convert a SVG into a Android vector and I did notice that creating a "Vector" asset doesn't work as expected. In fact using the DP values as suggested by Google itself doesn't actually work as expected because the scale seems to be wrong. Importing an Image asset however allows you get the vector XML file with a preview, and that seems to do what you'd expect.

The [docs](https://cordova.apache.org/docs/en/12.x/core/features/splashscreen/index.html#androidwindowsplashscreenanimatedicon) does state that you can use a PNG however, in which case you'll probably want to scale your PNG up to xxxhpdi density, which is 4x the base "dp" unit.

Cordova enables icon with background so the following applies:

> App icon with an icon background: this must be 240×240 dp and fit within a circle 160 dp in diameter.

That means if you author a PNG, you should multiply the dp units by 4, so your canvas size should be 960x960px and your icon content should not leave 640x640px diameter circle that is centered.

I've attached an inkscape template that shows what I mean, the circular area is the "visible" area of the icon. Outside of the circle is masked away. [androidSplashIconTemplate.svg](https://github.com/apache/cordova-android/assets/11200662/25d961b9-8e7f-4a62-80cc-4f0237ac343d)

And yes, I do agree that the docs could probably be a bit more clear on some of these details, but hopefully this will help you get going at the very least.

**Comment by igorsantos07** [comment]
Thanks for the thorough explanation! Sorry for taking a while to respond, I moved on with other tasks guessing this was an edge case, and soon after left for vacations.

I'm back now with good news / bad news.
The good news is: I found a reproducible scenario.
The bad news is: this seems a bit more widespread?

Since I have no Android 13 and needed to test some possible push problems from the dead `havesource` plugin fork, I created a couple of emulators... And guess what? The splash icons don't show in the standard Play Services API 32 image! Not even the standard Cordova icon shows up, it's just a blank splash screen, with the correct background color though. It also seems to work fine on Android 11.

I tested that out in four different scenarios:
- the generated XML from before
- the old xxxhdpi PNG we were using before the Cordova upgrade
- an invalid file path
- [a random PNG I got from Google's CC image search](https://freesvg.org/img/sample2.png) (wasn't properly edited to fit the space, so cropping is expected, I just wanted to know if it was a problem with my image files or not)

```xml
<preference name="AndroidWindowSplashScreenBackground" value="#F0F000" />
<preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/drawable/invalid.png" />
```

Random PNG, Android 13:
![image](https://github.com/apache/cordova-android/assets/532299/a74274ce-4de4-437d-9ed2-67a3c253b2ed)
invalid path, Android 13:
![image](https://github.com/apache/cordova-android/assets/532299/5e46ea9e-7e4d-4997-bc06-061304b89c15)
invalid path or random PNG, Android 12:
![image](https://github.com/apache/cordova-android/assets/532299/4105e7e2-1632-4d10-b781-41d945b8dfae)
Random PNG, Android 11 (also worked fine with our Vector XML):
![image](https://github.com/apache/cordova-android/assets/532299/dbc04dc5-72bc-4a3d-ab5f-f86c30404a2a)



> The screenshots show "Galaxy Tab A8" but that's just the screen ratio for my usual test tablet, there's nothing non-standard on these emulators' hardware profile. I created both in succession, just changing the API Level, and ran the exact same code to take the screenshots above.

**Comment by breautek** [comment]
> And guess what? The splash icons don't show in the standard Play Services API 32 image!

You could be experiencing an android quirk: https://cordova.apache.org/docs/en/12.x/core/features/splashscreen/index.html#android

> Android 12 does not show the splash screen when launching the application from Android Studio or Cordova CLI. This is a known Android 12 issue. After uploading the app to the device or simulator, exiting and opening the app will show the Splash Screen. If changes are not shown, try also performing a clean build. It has been fixed on Android 13.

To be sure, try closing the app and relaunching it directly on the device. The bug seems to only trigger (sometimes) when launching through Android Studio/CLI.

**Comment by igorsantos07** [comment]
Dang, you're right. Sorry for the trouble, thanks for the heads up!

**Comment by Boeblahoebla** [comment]
I was able to get my splash screen working, but It's centered in the screen & it's not using my full sized splash screen images. Would anybody be able to point me into the right direction?

I have created a splash image for a range of device sizes.

mdpi, hdpi, xhdpi, xxhdpi & xxxhdpi. All images have the correct size & extention.

This is what I get.

![image](https://github.com/apache/cordova-android/assets/55714738/40aa02d9-290a-4299-b1b6-74fa507b1db2)

My Splash image is actually this:

<img width="418" alt="image" src="https://github.com/apache/cordova-android/assets/55714738/b72b57af-3f1a-420d-8390-eb3e994adced">

Any idea why my spash image is being massacred?

This is the config.xml

`<?xml version='1.0' encoding='utf-8'?>
<widget id="be.chase2.chasebuddy" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
    <name>Chase Buddy</name>
    <description>Your buddy in all your chasing activities</description>
    <author email="info@chase2.be" href="https://www.chase2.be">
        Chase2be development team
    </author>

    
    <platform name="android">
        
        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
        </config-file>

        
        <allow-intent href="http://*/*" />
        <allow-intent href="https://*/*" />

        
        <allow-navigation href="*" />

        
        <preference name="Scheme" value="http" />
        <preference name="usesCleartextTraffic" value="true" />

        
        <icon src="res/android/icon/drawable-ldpi-icon.png" density="ldpi" />
        <icon src="res/android/icon/drawable-mdpi-icon.png" density="mdpi" />
        <icon src="res/android/icon/drawable-hdpi-icon.png" density="hdpi" />
        <icon src="res/android/icon/drawable-xhdpi-icon.png" density="xhdpi" />
        <icon src="res/android/icon/drawable-xxhdpi-icon.png" density="xxhdpi" />
        <icon src="res/android/icon/drawable-xxxhdpi-icon.png" density="xxxhdpi" />

        
        <preference name="AndroidWindowSplashScreenBackground" value="#F0F000" />
        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/android/splash/drawable-xxxhdpi/splash.png" />
        <preference name="SplashScreen" value="screen" />
        <preference name="ShowSplashScreenSpinner" value="false" />
        <preference name="SplashScreenDelay" value="4000" />
        <preference name="FadeSplashScreenDuration" value="300" />
        <preference name="SplashMaintainAspectRatio" value="true" />

        
        <preference name="android-minSdkVersion" value="21" />
        <preference name="android-targetSdkVersion" value="33" />
    </platform>

    
    <platform name="ios">
        
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />

        
        <allow-navigation href="*" />
    </platform>

    
    <content src="index.html" />
    <access origin="*" />
</widget>
`

This is the splash_screen.xml

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@android:color/white"/>
    <item>
        <bitmap
                android:gravity="fill"
                android:src="@drawable/splash"/>
    </item>
</layer-list>
`
