### ISSUE TITLE
Uncaught TypeError: cordova.exec is not a function

### ISSUE THREAD

**Issue by EmptyPages** [apache/cordova-android#1674]
![image](https://github.com/apache/cordova-android/assets/22334853/95bf25c5-2986-413c-9b51-fc8255360a6a)
![image](https://github.com/apache/cordova-android/assets/22334853/a9963acd-1c38-461f-a5d8-f17aae5a71ae)

**Comment by breautek** [comment]
I'm unable to reproduce this issue, `cordova.exec is not a function` suggests that the `cordova.js` file didn't load in.

However manual tests hasn't really been maintained, and while I don't reproduce this issue, it's still attempting to call on a plugin that doesn't appear to exists anymore.

We mostly rely on the automated tests, I'm not sure how valid the manual tests are.
