### ISSUE TITLE
Android 14 support ?

### ISSUE THREAD

**Issue by matrixreal** [apache/cordova-android#1688]
Hello,
Does cordova android 12 support android 14?
Thanks

**Comment by breautek** [comment]
Depends what you mean by "support".

Will it run on Android 14? Yes, it should.

cordova-android@12 however doesn't target Android 14 (aka API 34) nor does it compile with API 34 SDK. That will come with https://github.com/apache/cordova-android/pull/1678 which will be available in a 13.x release.

The fork can be installed if you want to it a preliminary test.
