### ISSUE TITLE
Will Cordova Android 13 support Kotlin 1.9.x ?

### ISSUE THREAD

**Issue by fan-min-aeon** [apache/cordova-android#1692]
In my company, we integrate vendor's SDK to our cordova application. The vendor request us to raise the version of Kotlin to 1.9.x but Cordova Android has not support is now. 
If possible, could you tell me whether Cordova Android 13 will support Kotlin 1.9.x  or not.

**Comment by webberig** [comment]
The latest versions of the Firebase Analytics SDK requires at least Kotlin version 1.9 which is how I ended up here.

The only problem I encountered was related to the deprecation of `kotlin-android-extensions`. This has already been reported (with temporary workaround) in another issue: #1642
