### ISSUE TITLE
Panoramic images

### ISSUE THREAD

**Issue by AsandahDevs** [apache/cordova-android#1704]
# Feature Request

## Motivation Behind Feature

I want app users to have the ability to take wider pictures without having to capture the same image in different positions. This could result in an improvement in the device storage.

## Feature Description

The current camera plugin only allows users to take pictures or upload images from the gallery . I need an option to allow users to take panoramic images especially since most modern device cameras support this feature natively. I may not have a clue how the code may look but the screenshot should provide a clue of how this feature should work.
![Screenshot_20240414_165512_Camera](https://github.com/apache/cordova-android/assets/89397749/a6295a6c-514e-4bf2-9038-f4e16ff2cb57)

## Alternatives or Workaroun
Currently there are no alternatives i know of.

**Comment by jcesarmobile** [comment]
You should report this in the repository of the camera plugin you use, not in cordova-android, most likely here https://github.com/apache/cordova-plugin-camera/issues

But pretty sure it's not possible to implement with the Camera Intent the plugin uses at the moment.
