### ISSUE TITLE
backgroundMode plugin quirks

### ISSUE THREAD

**Issue by massimilianocom** [apache/cordova-android#1705]
It really gets crazy here

I create an app with the backgroundMode plugin, everything works perfectly, so much so that I conclude the app and create it with build.

I test the app on various devices and it works on all of them including backgroundMode.

Today I go to the app code and run Android on the emulator and as if by magic the backgroundMode no longer works.

I want to point out that I didn't make any changes to the code, I just added some other graphic icons and emulated the app.

What happened?

**Comment by massimilianocom** [comment]
in the plugin specifications the icon carries this path: platforms/android/res/drawable|mipmap

but in android platforms the path where the icon is located is the following: platforms/android/app/src/main/res/drawable|mipmap

could this be the problem?

But if this is the problem, why did it work for me with the same path before?

**Comment by jcesarmobile** [comment]
You should ask or report the issue on the backgroundMode plugin repository, this is unrelated to cordova-android
