### ISSUE TITLE
Cordova undefined when AndroidInsecureFileModeEnabled set to false

### ISSUE THREAD

**Issue by formidable255** [apache/cordova-android#1706]
Using cordova android version 12 via voltbuilder.

Currently trying to fix a google recaptcha issue on android where google returns invalid domain. This happens when `AndroidInsecureFileModeEnabled` is set to true and the origin is `file:///`. When set to false, the domain becomes 'https' and recaptcha works fine but cordova is undefined inside the project causing non of my plug-ins to work.

Why does cordova become undefined and any way this can be fixed?

**Comment by jcesarmobile** [comment]
can you provide a sample app that reproduces the issue?

**Comment by jcesarmobile** [comment]
Closing since there was no response
