### ISSUE TITLE
`cordova emulate android` report ERR_INVALID_ARG_TYPE error

### ISSUE THREAD

**Issue by ymrdf** [apache/cordova-android#1717]
# Bug Report

## Problem
After i created a new project, and ran `cordova platform add android`.
when i ran `cordova emulate android`, i got this errors:

```
BUILD SUCCESSFUL in 1s
50 actionable tasks: 50 up-to-date
Built the following apk(s): 
	/Users/gaozhenqian/my/photo-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
No scripts found for hook "before_deploy".
Checking Java JDK and Android SDK versions
ANDROID_HOME=/Users/gaozhenqian/Library/Android/sdk (recommended setting)
ANDROID_SDK_ROOT=undefined (DEPRECATED)
Using Android SDK: /Users/gaozhenqian/Library/Android/sdk
Trying to find target matching { type: 'emulator' }
Looking for emulator image that best matches the target API
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ENOENT')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at /usr/local/lib/node_modules/cordova/bin/cordova:32:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Information

Installed platforms:
  android 13.0.0
Available platforms:
  browser
  electron
  ios

cordova --version
12.0.0 (cordova-lib@12.0.1)

### Environment, Platform, Device

platform:
MacOS: 13.4

nodejs:
v20.11.0

## Checklist

- [y ] I searched for existing GitHub issues
- [ y] I updated all Cordova tooling to most recent version
- [y ] I included all the necessary information above

**Comment by ymrdf** [comment]
After i launch the AVD, this error didn't show anymore. Please update your document, so that user know that they should launch AVD before run ` cordova emulate android`

**Comment by moba-dev** [comment]
Thanks to @ymrdf , i was facing the same issue.
