### ISSUE TITLE
Cordova SDK error when publishing com.google.android.play:core:1.10.0

### ISSUE THREAD

**Issue by BenLaKnet** [apache/cordova-android#1720]
I obtained this error message when I published an new version of my app.

```
com.google.android.play:core:1.10.0

Google Play Core (com.google.android.play:core) has added this note for SDK version 1.10.0:

Update your Play Core Maven dependency to an Android 14 compatible version! Your current Play Core library is incompatible with targetSdkVersion 34 (Android 14), which introduces a backwards-incompatible change to broadcast receivers to improve user security. As a reminder, from August 31, Google Play requires all new app releases to target Android 14. Update to the latest Play Core library version dependency to avoid app crashes: https://developer.android.com/guide/playcore#playcore-migration

From September 21, 2024 00:00 (UTC) you won't be able to release new versions of your app containing this SDK version to production or open testing.
```

I update cordova-android to v13 and it is the same problem.
I tried this:
`platforms\android>tools\gradlew.bat app:dependencies > dependencies.txt`

But I do not know what could I do to update this version of com.google.android.play:core.

Please help.

**Comment by breautek** [comment]
I'm just about to go to sleep so I won't be responsive... but I don't believe `com.google.android.play:core` is something that the Cordova framework depends on. So it's likely being added to your project by a plugin that you have installed.

Chances are a plugin will contain a `<framework>` tag for `com.google.android.play:core` so if you search for that text inside the `plugins/` folder you'll probably find the plugin importing the dependency.

It sounds like version `1.10.0` is not compatible with API 34, the plugin that imports it might need to update it.

**Comment by BenLaKnet** [comment]
Hi @breautek , many thanks for your answer.

I found a plugin that needed to be updated:

`cordova-plugin-native-app-update`

**Comment by aranda-dev** [comment]
I had the same problem, and my solution was to remove the plugin that was using **com.google.android.play:core**, for my app the plugin I had to remove **cordova-plugin-apprate** with this command: `cordova plugin remove cordova-plugin-apprate`
