### ISSUE TITLE
Application should support Android 14 and API LEVEL 34, Please provide suggestions

### ISSUE THREAD

**Issue by balaji-aasapu** [apache/cordova-android#1737]
The current Cordova CLI Version is 
![image](https://github.com/user-attachments/assets/1c8b2dc1-f2d2-49bf-96d6-c6a30a395d27)

Now, I am planning to support Android 14 AND API Level 34. 
Seems the Cordova CLI 12 version does not support the same as per this document. https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html

As per this document - I can use cordova-android 13 https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html#:~:text=This%20release%20has%20increased%20the,to%2034%20(Android%2014).&text=Android%20Studio%20Jellyfish%20is%20required%20if%20building%20and%20running%20from%20Android%20Studio.&text=To%20use%20cordova%2Dandroid%4013,0%20must%20be%20installed. 

but no where mentioned about CLI version of cordova. 

can I upgrade Cordova-android version 13 to support Android 14 and API LEVEL 34 and continue to use the Cordova CLI Version 12?

**Comment by kiwi-x** [comment]
Did you try

cordova platform remove android
cordova platform add android@13.0.0

This should work. cordova-lib is the latest - I doesn't see any problem

**Comment by breautek** [comment]
> can I upgrade Cordova-android version 13 to support Android 14 and API LEVEL 34 and continue to use the Cordova CLI Version 12?

Yes. CLI 12 supports cordova-android@13 which supports and targets SDK 34 by default. Your environment may require further changes outside of Cordova tooling to support API 34.

The cordova docs is lacking API 34/cordova-android@13 details but the [blog](https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html) should provide the details about what is required outside of installing cordova-android@13 (e.g. it will require JDK 17).

If you have any other questions, community support is best asked at our [Discussions](https://github.com/apache/cordova/discussions) page. If you believe you have found a bug with cordova-android@13 then please create a new issue with the details filled.
