### ISSUE TITLE
Unable to Build Cordova Android Project - BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

### ISSUE THREAD

**Issue by Senglean** [apache/cordova-android#1738]
Hello

I'm having trouble building my Cordova Android project, and I've tried different combinations of Java and Gradle versions with no success. I need to push an urgent update to the play store and would appreciate any help resolving the issue.

Current gradle version > 8.6
Current java version > 21

Error > Unsupported class file major version 66

**Comment by breautek** [comment]
> Hello
> 
> I'm having trouble building my Cordova Android project, and I've tried different combinations of Java and Gradle versions with no success. I need to push an urgent update to the play store and would appreciate any help resolving the issue.
> 
> Current gradle version > 8.6 Current java version > 21
> 
> Error > Unsupported class file major version 66

file major version 66 refers to Java 22, which suggest you're using 22 not 21. This could be `PATH` or `JAVA_HOME` misconfiguration.

The recommended JDK version is JDK 17 because that's what Android Studio will use and is tested with.
