### ISSUE TITLE
Version 13.0.0 requires java version 22 which is not maintained -> update gradle

### ISSUE THREAD

**Issue by dariosalvi78** [apache/cordova-android#1744]
# Bug Report

## Problem
When compiling with version 13.0.0 gradle 8.7 is used, which requires Java version 22 (see [table](https://docs.gradle.org/current/userguide/compatibility.html#java)), but java 22 is not maintained and not retrivable, for example, with brew.

Suggestion: update to gradle 8.10.

### What is expected to happen?
Compilation of an Android app should work.

### What does actually happen?

Compilation fails with a: Unsupported class file major version 67
I suppose that gradle doesn't even run

## Information
Try to compile a cordova Android app with JDK other than 22, gradle doesn't support it.
Updating the version of gradle to 8.10 would allow Java v 23.

### Command or Code
cordova build android

### Environment, Platform, Device
Compiled on Mac, platform: Android

### Version information
Android cordova: 13.0.0
Cordova CLI: 12.0.0
Java: open JDK 23.0.1

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by dpogue** [comment]
ooof, after spending most of a decade on Java 8, I didn't realize Java was doing a mix of LTS releases and non-LTS releases with only 6 months of support 😞 

It looks like Java 21 is the LTS version, and Java 23 would have the same problem of support ending very quickly.

Do we know, are the current versions of Gradle and Android Gradle Plugin used by cordova-android compatible with Java 21?

**Comment by dariosalvi78** [comment]
tried with JDK 21, it works! I'm gonna close this. Thanks..

**Comment by breautek** [comment]
FYI the tooling that is pinned is tested against JDK 17, so the recommended JDK version is 17. It's also the minimum requirement for Android Gradle Plugin. 

But 21 should work fine as well. I've been using 21, as that is what is shipped with the current android studio without issue and will likely become the new minimum requirement _soon_.
