### ISSUE TITLE
Issue on backbutton event listener

### ISSUE THREAD

**Issue by ambatidilip** [apache/cordova-android#471]
I am working on Cordova, Angular5 and OnsenUI(CSS Only). 

1.  I added backbutton event listener in deviceready.
2.  When i navigate to 3 pages and press backbutton, the backbutton callback triggered but default backbutton executes after that and webview got terminated.

**Now when i add backbutton event listener it should override with my call back, but it executes both, Can some one help me out**

Note: Before integrated OnsenUI CSS, callback of backbutton working properly which means only Cordova with Angular5

**Comment by janpio** [comment]
So did I understand correctly that adding OnsenUI to your app broke some functionality? Seems like an issue for their bug tracker then, right?

**Comment by ambatidilip** [comment]
Seems like its better to post in OnseUI group. Because base functionality is working properly, when i add it then it breaks the default behaviour. Thank you for the reply.

**Comment by janpio** [comment]
You're welcome. 
Feel free to come back and ask here or over at slack.cordova.io again if OnsenUI can't help you.
