### ISSUE TITLE
Android 8 - SVG feColorMatrix - Crash

### ISSUE THREAD

**Issue by Adrion** [apache/cordova-android#472]
I made an app about color blindness : https://github.com/healthonnet/ColorVisionQuiz-App
I use camera and apply SVG filters with feColorMatrix rules in order to simulated color blindness. 

filter example : 
```
<filter id="protanomaly">
      <feColorMatrix
        type="matrix"
        values="0.817 0.183 0 0 0
                0.333 0.667 0 0 0
                0 0.125 0.875 0 0
                0 0 0 1 0"/>
</filter>
```

Built with :  (EDITED)
```
 - cordova@8.0.0
 - cordova-android@7.1.1
```

Everything works but not an Android 8, it just crashes the app. No error, nothing with adb logcat too. 

 - Other filter rule like `feGaussianBlur` works. 
 - `feColorMatrix` works on chrome Desktop
 - `feColorMatrix` works on static DOM element 
 - `feColorMatrix` Crashes when a video is running under the filter.

As Oreo use the chrome `Chrome/68.0.3440.85` it may comes from cordova ?

**Comment by Adrion** [comment]
Sorry transferred to JIRA issue tracker

**Comment by janpio** [comment]
We are in the process of moving issues to Github, so you are fine here.

**Comment by janpio** [comment]
>  - cordova@7.1.0
> - cordova-android@6.3.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by Adrion** [comment]
After painfull updates, same problem. `feColorMatrix` makes the app crash.

**Comment by Adrion** [comment]
Ok I have new informations : 
`feColorMatrix` works on DOM. 
It fails on video content... I also tried to apply it on parent element and failed too. 

Do we have a conflict between video and svg processing ?

**Comment by janpio** [comment]
Can you reproduce the behaviour in the system browser or other browsers?
Can you reproduce it in a plain webview added to a new Android project where you load that page? (Requires some native coding)

**Comment by Adrion** [comment]
https://issuetracker.google.com/issues/112323202
We'll see.

**Comment by janpio** [comment]
Awesome, left a star. Hope this gets some eyeballs from Google, although it is a pretty niche problem.

**Comment by janpio** [comment]
(Making sure Google is aware this is an accessibility problem and maybe reaching out to a team that handles that for Android might be beneficial here)

**Comment by Adrion** [comment]
Also happened when you use the filter on an element with `overflow: scroll`.
That's a very strange behaviour.
