### ISSUE TITLE
404 error when debugging Cordova in Chrome inspect page

### ISSUE THREAD

**Issue by weixingsun** [apache/cordova-android#474]
I am going to use chrome to debug my app, 
When I click on the link under my app name, a blank page popped up, and shown a 404 error on it, 
Any suggestions?

**Comment by janpio** [comment]
What do you mean exactly? Where does this 404 come from? Best post a screenshot of it here. You can just paste an image from the clipboard and it will upload and embed it in the comment.

**Comment by weixingsun** [comment]
Thanks for your reply, screenshot attached. and this is the brief information
OS: MacOS High Sierra 10.13.6
Chrome Version 67.0.3396.99 (64-bit)
Android 7.0 (ZUI 3.1.117)
![cordova_inspect](https://user-images.githubusercontent.com/5229930/44008931-cfc8b8d2-9eda-11e8-943e-3c62aa4138a6.png)

**Comment by janpio** [comment]
That's a new one for me.

How exactly did you build your app?
Does the app work on the device itself?
Can you try another Android device?

**Comment by weixingsun** [comment]
app building cmd: cordova build android --debug
app install cmd:  adb install -r platforms/android/build/outputs/apk/armv7/debug/android-armv7-debug.apk
I use this app to debug a simple usb device, and it works pretty well, and I want to change a page on it
I tried another android device, the same error

Thanks for your help, I really appreciate it

**Comment by janpio** [comment]
Another computer then maybe?

I google the error a bit, maybe have a look at this:
https://stackoverflow.com/a/46220364/252627

Other people seem to have the same problem:
https://bugs.chromium.org/p/chromium/issues/detail?id=853525
https://stackoverflow.com/questions/51562724/inspect-edge-on-remote-devices-result-in-404-not-found
https://stackoverflow.com/a/51535351/252627

**Comment by weixingsun** [comment]
I tried on my Mac Air, Mac Pro, Windows 10, Windows 7
And I installed this app on Android 4.4, Android 7.0
All the same 404, how do I do, then ?

**Comment by janpio** [comment]
Difficult to say as it seems to be a Chrome bug. Find a computer with an older Chrome version maybe?

**Comment by girotomas** [comment]
In my case, my device was connected to the internet but my computer wasn't. Connecting my computer to the internet fixed this problem.

**Comment by Menardi** [comment]
@weixingsun Try renaming your file from `main.html` to `index.html`. Cordova is trying to load `index.html`, but can't find it, which it what would cause this 404.

**Comment by pallaviMN** [comment]
@weixingsun , have you got any solution. Even i am facing this issue

**Comment by chiefbrob** [comment]
Check your internet connection.

**Comment by e88y** [comment]
> 
> 
> In my case, my device was connected to the internet but my computer wasn't. Connecting my computer to the internet fixed this problem.

In my case it was because i was running a VPN-Client

**Comment by jcesarmobile** [comment]
Closing since doesn’t look like a cordova bug but a connection problem.

**Comment by uzxmx** [comment]
I also encountered this problem. Find out it was because of network blocking issue in China. Once I switched the browser proxy on, 404 error disappeared.

**Comment by Carsak** [comment]
> I also encountered this problem. Find out it was because of network blocking issue in China. Once I switched the browser proxy on, 404 error disappeared.

I didnt believe at first, because google services not blocking in my Country. But I launch VPN and all works. Why? 
How to check which network services is needed for chrome devtools? 
I can connect to google cloud, google photos and other services via browser

**Comment by vigneshChakkaravarthi** [comment]
Hello everyone, In my case following commands helped me to resolve the issue. I hope this helps someone.
cordova platform rm android 
cordova platform add android
