### ISSUE TITLE
WEB-RTC for  CORDOVa 

### ISSUE THREAD

**Issue by ajay01994** [apache/cordova-android#475]
Hi all while i run WEB-RTC into cordova app the native browser android 4.0 does not support WEB-RTC , so can you please tell how to solve it apart from  cross walk or is there any road map that cordova is planning for WEB-RTC

**Comment by janpio** [comment]
Cordova Android uses the native web view by default. If your device's web view doesn't support a technology, then Cordova Android doesn't support it. The only workaround are custom webviews like e.g. Crosswalk or others.

By the way: Android 4.0 is not supported by current Cordova Android versions:
https://cordova.apache.org/docs/en/8.x/guide/platforms/android/index.html#requirements-and-support
