### ISSUE TITLE
Cordova doesn't wait for emulator to start: ask for fix release

### ISSUE THREAD

**Issue by blackholegalaxy** [apache/cordova-android#476]
A fix for this issue: https://issues.apache.org/jira/browse/CB-14165 has been merged recently through this PR:

https://github.com/apache/cordova-android/pull/457

But it's not release yet. It causes a lot of devs to have to pre-launch emulators.

Could you consider releasing a 7.1.2 version to include latest fixes, including this one?

**Comment by janpio** [comment]
We are always considering new releases - but it is a lot of work and will be done when it is done.

Have you tried installing the platform from `master` to get the current state?

**Comment by blackholegalaxy** [comment]
Nope I didn't indeed. Could try that.

**Comment by MatanYed** [comment]
+1 guys just release the fix

**Comment by brodybits** [comment]
You would have to do `cordova platform add https://github.com/apache/cordova-android` or `cordova platform add https://github.com/apache/cordova-android` to use `master` branch. If you need this published right away I suggest you send request to <dev@cordova.apache.org>.

**Comment by blackholegalaxy** [comment]
Adding master works as expected. Thanks for your time. We will wait until full release to change that :)
