### ISSUE TITLE
cordova android is very slow

### ISSUE THREAD

**Issue by Nemra1** [apache/cordova-android#477]
im used very standard webview without any plugin
and typing or write its very sloooow 
this video explain my problem
https://streamable.com/me494

this is my plugins
    "dependencies": {
        "cordova-android": "^7.0.0",
        "cordova-plugin-whitelist": "^1.3.3"
    },

**Comment by janpio** [comment]
Please create a new Cordova Android app just with a plain text field. Type the same stuff - also slow?

**Comment by Nemra1** [comment]
all version of cordova since 6 x  to 8x same slow when im trying to write anything inside <textarea>
am found this tips about transition 
but also is not working...but the strange thing here ..when browser my app linke
https://app.nemra-1.com by browser its normally and fast...im trying crosswalk but still more slow 
`@media (max-width: 800px) {
.form-control, .postText, .ui-autocomplete-input, .fa-spin, .panel, .panel-white, .post panel-shadow{
/*CSS transitions*/
-o-transition-property: none !important;
-moz-transition-property: none !important;
-ms-transition-property: none !important;
-webkit-transition-property: none !important;
transition-property: none !important;
/*CSS transforms*/
-o-transform: none !important;
-moz-transform: none !important;
-ms-transform: none !important;
-webkit-transform: none !important;
transform: none !important;
/*CSS animations*/
-webkit-animation: none !important;
-moz-animation: none !important;
-o-animation: none !important;
-ms-animation: none !important;
animation: none !important;
 transition: none !important;
		}
}
`

**Comment by janpio** [comment]
Did you try what I told you to? 
This was to find out if the culprit is your app or if this is a general Cordova problem.

**Comment by Nemra1** [comment]
i will try standard input now..holdon

**Comment by Nemra1** [comment]
@janpio its working normally in standard <textarea>
but why is hanging and slowly and also my keyboard lag when loaded inside cordova?

**Comment by janpio** [comment]
Then the combination of Cordova and your app does not work as good as it should. Your app seems to do something that takes time. What this is, only you can find out by removing everything bit by bit or debugging your code. You can also start rebuilding your app's state by adding the features one by one to the plaing `<textarea>`.

**Comment by Nemra1** [comment]
am trying this code
    if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) 
    {
        $('body').addClass('noanimated'); // to remove transition
    }
the slow issue is gone but some important functions is damge

**Comment by janpio** [comment]
Whatever you are doing there, this seems to just need to many cycles to be computer. Find another way somehow.

(I am closing this issue as it is not a direct problem with `cordova-android` but something with your app. Feel free to keep answering, I will try to help you as I can.)
