### ISSUE TITLE
Open PDF with Adobe Acrobat from Cordova

### ISSUE THREAD

**Issue by subashdbc** [apache/cordova-android#478]
I have a pdf file which can be edited through Adobe Acrobat. When I open the file straight away from Adobe Acrobat app and edit the file, and when I press the back button it gets saved automatically by Adobe Acrobat app, but when I open from Cordova application, it is opening with Adobe Acrobat app and I can also able to edit that, but when press the back button and come back to app, and once again hit the pdf file from the Cordova app, it is not showing the edited content (it happens only with above android 7 versions, but below android version 7 it is working fine from the app).

I open the file with this code from Cordova,
```
Uri path = Uri.fromFile(file);

PackageManager packageManager = this.cordova.getActivity().getPackageManager();

String application_id = "com.package.name";

try {

      PackageInfo packageInfo = packageManager.getPackageInfo(

      this.cordova.getActivity().getPackageName(), 0);

      application_id  = packageInfo.packageName

} catch (NameNotFoundException e1) {

       e1.printStackTrace();

}

if (Build.VERSION.SDK_INT >= 24) {            

       path = FileProvider.getUriForFile(this.cordova.getActivity(), application_id + ".provider", file);

}

Intent intent = new Intent(Intent.ACTION_VIEW);

intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);

intent.setDataAndType(path, contentType);

cordova.getActivity().startActivity(intent);
```
Does it need any extra permission from the application or any other way? Thanks in advance!

**Comment by janpio** [comment]
Is this Javascript code?

**Comment by subashdbc** [comment]
No, it is JAVA code. To open file I have written in JavaScript like this,

```
var customPlugin = {
	createEvent : function(success, failure, action,arg1) {
		cordova.exec(success, // success callback function
		failure, // error callback function
		'Utils', // mapped to our native Java class
		action, // with this action name
		[arg1]);
	}
}
```
'Utils' refers to the Java Class that I have written.

**Comment by janpio** [comment]
So you created a custom plugin?

**Comment by subashdbc** [comment]
Yes. But that is working as expected with below android version 7, but android version 7 and above is not working.

I am not sure what went wrong here.

**Comment by janpio** [comment]
(For the record: Such information would be nice if you provided it in the initial post instead of having other people start guessing what is going on)

I would create a super simple native Android app that implements just this and see if it works there or how it behaves in the different Android versions - then you can maybe exclude `cordova-android` as the culprit and just ask on StackOverflow as a normal Android question.

**Comment by subashdbc** [comment]
Yes. It would be great if you give any inputs from your simple app. Thanks

**Comment by janpio** [comment]
Seems I wasn't clear: I won't do that. You can do that to debug, understand and fix your problem.

**Comment by subashdbc** [comment]
I got it fixed over here,

https://github.com/Evolution-36/cordova-plugin-file-opener2
