### ISSUE TITLE
chrome build-in input file upload crash chrome 62.x ?

### ISSUE THREAD

**Issue by crapthings** [apache/cordova-android#480]
we use html5 <input type='file' />, and resumable.js to upload file.

but when we open file explorer(album)

pick some pics format like jpg png etc then cordova crashed

pick some document like txt pdf etc that it doesn't crash cordova but its seems just can't get file into input?

### no working

android 7x jianguopro2

> Mozilla/5.0 (Linux; Android 7.1.1; OS105 Build/NGI77B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36

### these work.

Android 6x google nexus 6
Android 8x google pixel 1
Android 9x google pixel 1

it likes you can list dir(album, file explorer), but can't read certain file.

**Comment by janpio** [comment]
What exactly is the code causing the crash?
Is it reproducible with plain html5 instead of a library?
Does it also happen in the native browser?
What is the `cordova-android` version you are using?

**Comment by crapthings** [comment]
we use meteor as a framework that is cordova-android 6.4.0.
with the crash test phone(android 7x jianguopro2) we can upload file use plain html5 without open cordova app, the chrome core is same, but when upload with cordova, it likes the 1st comment.

**Comment by janpio** [comment]
Please try to answer my questions individually that makes it clear, which answer is to which question. User `>` before my question to repeat and quote it, then your answer. Thanks.

> cordova-android 6.4.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by crapthings** [comment]
> What exactly is the code causing the crash?
Is it reproducible with plain html5 instead of a library?
Does it also happen in the native browser?
What is the cordova-android version you are using?

build a index.html only with input file, pick an image then crashed
```
<input type='file' />
```

**Comment by janpio** [comment]
> build a index.html only with input file, pick an image then crashed

Does this happen only in Cordova or also in the native browser on that device?

> it seems we can only wait until framework upgrade cordova

what do you mean by that? what framework are you using? Usually, Cordova and especially its platform can be updated independently from the rest.

**Comment by crapthings** [comment]
> what do you mean by that? what framework are you using? Usually, Cordova and especially its platform can be updated independently from the rest.

framework is meteor

it can build your app into cordova, the current meteor framework version that we re using which is meteor 1.7.0.4 and its build-in cordova-android version is 6.4.0, we can only use their cli.

but never mind i will try cordova-android  see if it can reproduce.
