### ISSUE TITLE
Angular AOT build is not working, neither --release flag.

### ISSUE THREAD

**Issue by HarelM** [apache/cordova-android#483]
When using an AOT compiled version of a website the application doesn't load.
Might be an issue with cordova-cli, I'm not sure.
Project can be found here:
https://github.com/IsraelHikingMap/Site

Also, When I compile it with `--release` flag android is telling me that the application is invalid and doesn't install it on my device... :-/

**Comment by breautek** [comment]
Sorry for the lack of response, but I'm closing this as this is likely out-dated and missing of information required for assistance.

If you think you've found a bug in cordova, feel free to open a new issue and please fill out all the information requested.

**Comment by HarelM** [comment]
I think this was an issue with angular, not sure, it was long ago. In any case, I managed to make it work.
