### ISSUE TITLE
Cordova generates build.gradle with deprecated "compile" dependencies

### ISSUE THREAD

**Issue by jedrivisser** [apache/cordova-android#485]
When an android cordova plugin has a `framework` dependency, StudioBuilder.js generates a deprecated `compile` dependency instead of a `implementation` dependency:

https://github.com/apache/cordova-android/blob/7.1.x/bin/templates/cordova/lib/builders/StudioBuilder.js#L201

**Comment by janpio** [comment]
This is probably happen in multiple places.

Are you up to creating a PR for that to fix all of those? We would really appreciate it 💯

**Comment by jedrivisser** [comment]
Will do

**Comment by jedrivisser** [comment]
Changes are done
