### ISSUE TITLE
Run command fails if build is skipped

### ISSUE THREAD

**Issue by Menardi** [apache/cordova-android#488]
cordova-android version: v8.0.0-dev

As part of the builders cleanup PR (#461), I removed all the builders except for the StudioBuilder. It turns out that the `none` option is still invoked when the user uses the `cordova run` command in a way that doesn't trigger a build (like if a build has been done just before it). This causes the run command to fail.

cc @erisu

**Comment by erisu** [comment]
To expand on the issue, it appears that `cordova run` actually triggers two builds. The first build uses `studio` and builds successfully. The second build is triggered after the message `deploying to emulator` and tries to use `none` which throws an exception.

[Build Log File](https://github.com/apache/cordova-android/files/2342207/build.log)

Additionally, when using `cordova build android` and installing the app with `adb install` the application closes immediately when trying to launch the app. It might be related to pathing. Using `adb logcat` you will see this error also.

[ADB Log File](https://github.com/apache/cordova-android/files/2342227/adb.log)
