### ISSUE TITLE
Embedding cordova application on Android native application

### ISSUE THREAD

**Issue by StavrosSkourtis** [apache/cordova-android#491]
I'm not sure if this is the correct place to put this, please tell where to ask if it isn't.

What I'm trying to do is embed a cordova application into a native android application.

It seems to me that the documentation is out of date or not clear about the steps that needs to be done.

I'm reading this: https://cordova.apache.org/docs/en/latest/guide/platforms/android/webview.html

I am at the point that I can't create the `.jar` file for the following reasons.

1. I don't have a `/framework` directory in my root project directory or in `platforms/android`
2. Cordova seems to be using `gradle` instead of `ant` for building the android project. I can't find a build.xml anywhere in the android project.

My Cordova version: `8.0.0`

As as followup question, I expect this `.jar` file will also contain the plugins that my cordova project depends on, correct?

**Comment by janpio** [comment]
Yey, those docs are very much out of date. If you figure it out (I think I have seen some StackOverflow answers describing a newer process somewhere), please send a PR to the documentation or at least leave the information here in a comment. We would really appreciate if someone could fix this up.

**Comment by jcesarmobile** [comment]
See my comment on https://github.com/apache/cordova-android/issues/494
