### ISSUE TITLE
File mapUriToFile returns null

### ISSUE THREAD

**Issue by furaiev** [apache/cordova-android#492]
Hi,
It seems like the method below is depricated and should be replaced with [Fileproviders](https://developer.android.com/reference/android/support/v4/content/FileProvider.html)

https://github.com/apache/cordova-android/blob/23b24491c3e2ad5721a2813ec08f80985eca5e64/framework/src/org/apache/cordova/CordovaResourceApi.java#L148

**Comment by dpogue** [comment]
Maybe #468 addresses this? I admit I'm not especially familiar with Android filesystem stuff, so it hasn't gotten the review it deserves yet

**Comment by PabbleDabble** [comment]
I am also curious about this.  I'm using https://github.com/apache/cordova-plugin-media-capture to capture video within my app.  
The plugin returns this from the intent after capturing video: 
`content://com.sec.android.app.camera.files/root/storage/emulated/0/DCIM/Camera/Video-VDO_20210723_130732.mp4`
on Android 11, Galaxy Tab A7, which then `mapUriToFile` returns null
as this line within `mapUriToFile` yields -1
`int columnIndex = cursor.getColumnIndex(LOCAL_FILE_PROJECTION[0]);`
which then crashes the plugin with this error `getAbsolutePath()' on a null object`
So obviously there's probably a null catch missing in the media capture plugin, but I'm wondering if the webview should be able to parse the `com.sec.android.app.camera...` uri?  Or maybe the camera hardware is storing the file in the wrong spot?

I'm looking in to the plugin as well, but I'm wondering if this is correct?

On other Android devices we've tried, it works.  Another Android 11 device yields something like `content://media/0000-0000/video/media/24513`

**Comment by breautek** [comment]
Closing as obsolete / out-dated.

Too many things has changed between now and 2018. If this issue still persists, please create a new ticket with updated information.
