### ISSUE TITLE
Change from CordovaWebView to SystemWebView in latest Cordova not working

### ISSUE THREAD

**Issue by sandeep2244** [apache/cordova-android#494]
I stuck in my old version Android App based on Codova
    I updated My Android App to latest version android@7.0.0

Now where i used CordovaWebView for for Webview in my app as follows

```
<org.apache.cordova.CordovaWebView
         android:id="@+id/cordovaWebCallWebView"
         android:layout_width="match_parent"
         android:layout_height="match_parent" />
```

but it's not present in latest version of Cordova. So I changed to it by below lines

     <org.apache.cordova.engine.SystemWebView
     android:id="@+id/SystemWebView"
     android:layout_width="match_parent"
     android:layout_height="match_parent" />

where i am using WebRtc for my App So I used following method of SystemWebView Class

```
cwv.setWebChromeClient(new WebChromeClient() {

            @Override
            public void onPermissionRequest(final PermissionRequest request) { 
                javaToJavascript.webrtcCallLog("web.java", "permission asked is"+Arrays.deepToString(request.getResources()),0); //This logs the type of permission asked
                Log.i("The list of permission asked is ", Arrays.deepToString(request.getResources())); // this askes for android.webkit.resource.AUDIO_CAPTURE permission

                getActivity().runOnUiThread(new Runnable() {
                    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
                    @Override
                    public void run() {
                        Log.i("Value Of the permission asked is ", request
                                .getOrigin().toString());

                        request.grant(request.getResources());

                    }
                });

            }
        });
```
Now i got runtime error in my Main java file regarding classCastException

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simCard.web/com.simCard.web.WebCall}: java.lang.ClassCastException: com.simCard.web.WebCall$1 cannot be cast to org.apache.cordova.engine.SystemWebChromeClient

How to solve This error ? Please any ones help will be grateful

Thank you

**Comment by janpio** [comment]
> I updated My Android App to latest version android@7.0.0

This is not the latest version. 7.1.1 is.

**Comment by sandeep2244** [comment]
> 
> 
> > I updated My Android App to latest version android@7.0.0
> 
> This is not the latest version. 7.1.1 is.

Its ok ,
But how to solve above issue  

??

**Comment by sandeep2244** [comment]
@brodybits @janpio  
I updated to 7.1.1  And its not working 

Because of CordovaWebView is now Interface not a Class,  we cant use it so,
```
<org.apache.cordova.CordovaWebView
    android:id="@+id/tutorialView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```
Now changing to **SystemWebView Class** 

I replaced it with 
```
<org.apache.cordova.engine.SystemWebView
 android:id="@+id/SystemWebView"
 android:layout_width="match_parent"
 android:layout_height="match_parent" />
```

 Now Problem is ,
 there is function of **SystemWebView.java (class)**
 **setWebChromeClient()**


```
public void setWebChromeClient(WebChromeClient client) {
        chromeClient = (SystemWebChromeClient)client;
        super.setWebChromeClient(client);
    }

```


And I override  setWebChromeClient() in my main class(WebCall.java)

**which  i  defined above in my question** 

And 

I got Error Regarding Class Cast Exception 
Which i defined in my question 

In Previous Version They using CordovaWebView And I checked They Dont Cast It 

below is the function for previous  version

```
 public void setWebChromeClient(CordovaChromeClient client) {
        this.chromeClient = client;
        super.setWebChromeClient(client);
    }
```
    
So How to Solve it

Thank You

**Comment by janpio** [comment]
The webview documentation seems to be outdated in general. If you figure it out, please make sure to create a PR fixing the documentation to match the actual reality. Thank you!

**Comment by jcesarmobile** [comment]
This is not a cordova-android issue, it's a cordova-docs issue.
The embedded workflow has been broken/undocumented for a long time, you can take a look at this two PRs that tried to document it, but in the end were closed. They both helped me to embed the webview long time ago. Also check the comments.
https://github.com/apache/cordova-docs/pull/498
https://github.com/apache/cordova-docs/pull/544

Closing this as there is a cordova-docs issue already linked.

**Comment by brodybits** [comment]
> Closing this as there is a cordova-docs issue already linked.

<https://github.com/apache/cordova-docs/issues/884>

**Comment by martinhorvath** [comment]
I had a hard time with the documentation and tried to reflect my findings in this update: https://github.com/apache/cordova-docs/commit/6dc8836ff669dbd6825093740a3115cb0c08b1c2

Can somebody check if this is useful for others?

**Comment by brodybits** [comment]
> [...] tried to reflect my findings in this update: [apache/cordova-docs@6dc8836](https://github.com/apache/cordova-docs/commit/6dc8836ff669dbd6825093740a3115cb0c08b1c2)

My response is in <https://github.com/apache/cordova-docs/issues/884#issuecomment-438318495>. In short a pull request would be really appreciated.

I would prefer that we keep further discussion in <https://github.com/apache/cordova-docs/issues/884> instead of this closed issue.
