### ISSUE TITLE
Cordova Release Build AAPT2  Exception

### ISSUE THREAD

**Issue by 152hq** [apache/cordova-android#502]
Hi,

I am trying to sign the Cordova app but every time Android Studios throws the below error
`java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details |  
`

I have tried the below ways but no luck so far
-  addding `android.enableAapt2=false` to gradle-wrapper.properties
- reinstalling cordova/android studio

Version Details
- cordova ->` 8.0.0`
- cordova-android -> `7.1.1`
- gradle -> `4.4`
- gradule-plugin -> `3.1`
- android-studio -> `3.1.4`

Please let me know a solution as this is a blocker.
Thanks

**Comment by janpio** [comment]
What do the logs say?
Is `cordova requirements` happy?

**Comment by gokujy** [comment]
I have same issue in Ionic v1, I want to build an android. Is there any solutions?????

**Comment by breautek** [comment]
Closing due to lack of response.

In general, these kind of errors are usually related to a misconfiguration of the android sdk (missing a required version and such).

**Comment by ajaymalik14** [comment]
Found any  solution yet?
