### ISSUE TITLE
several question about cordova plugin

### ISSUE THREAD

**Issue by codenoid** [apache/cordova-android#505]
hi, i can't find any forum about **cordova**, so i put my question right there

1. [Cordova 8 Send Silent SMS](https://stackoverflow.com/questions/52457695/cordova-8-send-silent-sms)
2. [Cordova 8 Screenshot Outside Application](https://stackoverflow.com/questions/52463181/cordova-screenshot-outside-application)

**Comment by janpio** [comment]
There is no forum, and GitHub issues are no replacement.
StackOverflow is the correct place to post something like that, and seems you already found that.
