### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider

### ISSUE THREAD

**Issue by artuska** [apache/cordova-android#511]
Why suddenly GMS started to appear in my Cordova Android build process and throws this error in Android Studio when i run an emulator?

```
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1447)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.balumates.balu, PID: 4409
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:6242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzmn.attachInfo(Unknown Source:17)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(Unknown Source:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        	... 10 more
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'
```

**Comment by rankhispano** [comment]
same problem...

**Comment by krcma96** [comment]
They have updated the AdMob SDK, you have to add your appID in the AndroidManifest

`
<application> .   .   .
       <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-################~##########"/>
    </application>
`

https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html

This fixed the crash but for some reason ads won't load for me, please let me know if you experience the same issue.

**Comment by mattearly** [comment]
hmm still not working for me.

**Comment by ChrisCodes94** [comment]
I have followed the instructions but it is still crashing . Iam using a test unit ID in my activity.main.  Is there an error in my code?



  <application
<activity
            android:name=".MainActivity"
            android:label="@string/app_name">
            <intent-filter>
             ...
            </intent-filter>
        </activity> 
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-###-##############~########"/>
            android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
            android:theme="@android:style/Theme.Translucent" />
    </application>

**Comment by ChrisCodes94** [comment]
Working for me now
I changed my banner from the Ad mob test ID to my personal Banner ID, in both strings.xml and activity main

**Comment by phonetech2000** [comment]
hello i have a problem when i put code admob i have problem  unfortunately my application android studio  please how i can solve this problem

**Comment by ChrisCodes94** [comment]
> hello i have a problem when i put code admob i have problem unfortunately my application android studio please how i can solve this problem


I don't understand.
Please explain your problem better. 
What error message is it giving you?

**Comment by adilthree** [comment]
compile 'com.google.android.gms:play-services-ads:12.0.0'
add this dependency your sdk is low for your dependency. 
I faced this problem now i add this my problem solved

**Comment by Redoyju** [comment]
Follow this answer i hope you will get your solution https://stackoverflow.com/questions/53294162/cannot-import-com-google-android-gmsplay-services-ads17-1-1/53443104#53443104

**Comment by TruptiLondhe** [comment]
> compile 'com.google.android.gms:play-services-ads:12.0.0'
> add this dependency your sdk is low for your dependency.
> I faced this problem now i add this my problem solved

its worked for my app

**Comment by saigor33** [comment]
> Они обновили AdMob SDK, вы должны добавить свой appID в AndroidManifest
> 
> `<application> . . . <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-################~##########"/> </application>`
> 
> https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html
> 
> Это исправило сбой, но по какой-то причине объявления не будут загружаться для меня, пожалуйста, дайте мне знать, если вы испытываете ту же проблему.



> Они обновили AdMob SDK, вы должны добавить свой appID в AndroidManifest
> 
> `<application> . . . <meta-data android:name="com.google.android.gms.ads.APPLICATION_ID" android:value="ca-app-pub-################~##########"/> </application>`
> 
> https://ads-developers.googleblog.com/2018/10/announcing-v1700-of-android-google.html
> 
> Это исправило сбой, но по какой-то причине объявления не будут загружаться для меня, пожалуйста, дайте мне знать, если вы испытываете ту же проблему.

Спасибо, мне помогло

**Comment by spar** [comment]
> compile 'com.google.android.gms:play-services-ads:12.0.0'
> add this dependency your sdk is low for your dependency.
> I faced this problem now i add this my problem solved

newbi here, how do you do this?
