### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/common/internal/zzb;

### ISSUE THREAD

**Issue by artuska** [apache/cordova-android#512]
What is this and what i should do with this?

Cordova CLI — 8.1.2
Cordova Android — 7.1.1
Android SDK Platform-Tools — 27.0.3
Gradle — 4.6-all
com.android.tools.build:gradle — 3.0.1

**Comment by jcesarmobile** [comment]
That happens when different plugins use different google services versions, not really related to cordova-android
