### ISSUE TITLE
BuildHelper provokes ClassNotFoundException when applicationid is not same as manifest package name

### ISSUE THREAD

**Issue by cdmahoney** [apache/cordova-android#513]
Error occurs  when trying to take picture  with camera plugin. Abbreviated stack trace:

~~~~
10-09 13:04:53.164: W/System.err(17950): java.lang.ClassNotFoundException: <application id>.BuildConfig
10-09 13:04:53.164: W/System.err(17950): 	at java.lang.Class.classForName(Native Method)
10-09 13:04:53.164: W/System.err(17950): 	at java.lang.Class.forName(Class.java:453)
10-09 13:04:53.164: W/System.err(17950): 	at java.lang.Class.forName(Class.java:378)
10-09 13:04:53.164: W/System.err(17950): 	at org.apache.cordova.BuildHelper.getBuildConfigValue(BuildHelper.java:54)
10-09 13:04:53.164: W/System.err(17950): 	at org.apache.cordova.camera.CameraLauncher.execute(CameraLauncher.java:140)
~~~~

Error can be reproduced by  defining applicationIdSuffix in build-extras.gradle, for example with
~~~~
		debug {
			applicationIdSuffix ".debug"
			versionNameSuffix ".debug"
		}
~~~~

The problem is caused by BuildHelper calling 'context.getPackageName', which returns the application id, not the package name.

Ironically, the application id is what CameraLauncher is trying to get in the first place, so I've been able to fix the problem modifying code in CameraLauncher:

~~~~
        Context context = cordova.getContext();
        this.applicationId = context.getPackageName();
        // this.applicationId = (String) BuildHelper.getBuildConfigValue(cordova.getActivity(), "APPLICATION_ID");
~~~~

But I think this should really work out of the box... (maybe add a method to CordovaInterface to return BuildConfig, which could be informed optionally from the application's CordovaActivity implementation?)

**Comment by cdmahoney** [comment]
@FreddyCrugger, if you're getting the java.lang.ClassNotFoundException error try manually editing the execute method in CameraLauncher.java (in folder platform\android\app\src\main\java\org\apache\cordova\camera) to use the value returned by `context.getPackageName()` directly, as in the example I gave above. 

If that fixes the problem you might want to set up a hook to copy the patched version of CameraLauncher.java to platform\android\app\src\main\java\org\apache\cordova\camera to prevent losing the changes if the plugin is reinstalled (be careful too if you update the plugin - you may need to update the patched file too.)

**Comment by FreddyCrugger** [comment]
I reverted to 7.0.0 as I was getting too many issues(not just with the camera), thanks anyway.

**Comment by janpio** [comment]
@cdmahoney You seem to have a good grasp of the problem, are you up to submitting a PR fixing this maybe? Thanks.

**Comment by kristianheljas** [comment]
@janpio - New PR: https://github.com/apache/cordova-android/pull/751

Issue is that `context.getPackageName()` return **android** package name which does not have to match **java** package name.

Since `getBuildConfigValue()` tries to load java class `(BuildConfig),` it should use java package name instead using `context.getClass().getPackage().getName()`

**Comment by timbru31** [comment]
Closing as PR #751 has been merged.
