### ISSUE TITLE
Native crash abort on android 8.1

### ISSUE THREAD

**Issue by biji** [apache/cordova-android#518]
Hi,
Any workaround for this issue? My cordova app receives this exception every day

Other similiar issue:

https://stackoverflow.com/questions/48457748/native-crash-in-abort-since-oreo-8-1

https://issuetracker.google.com/issues/70259031

https://stackoverflow.com/questions/51726273/getting-abort-exception-report-from-play-store-on-mi-devices/51761152

https://github.com/mapbox/mapbox-gl-native/issues/12278

**Comment by janpio** [comment]
What crash are you getting? Your issue just contains a few random links, but I have no idea what exactly happens to _you_. Also please include all the relevant versions (Cordova CLI, Cordova platform etc.) that you are using for context.

**Comment by biji** [comment]
The exception is:
```
backtrace:
 
  #00  pc 000000000001db94  /system/lib64/libc.so (abort+120)
 
  #01  pc 0000000000007f84  /system/lib64/liblog.so (__android_log_assert+296)
 
  #02  pc 000000000006c2a0  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::createSurface(ANativeWindow*, bool)+316)
 
  #03  pc 000000000006a018  /system/lib64/libhwui.so (android::uirenderer::renderthread::OpenGLPipeline::setSurface(android::Surface*, android::uirenderer::renderthread::SwapBehavior, android::uirenderer::renderthread::ColorMode)+76)
 
  #04  pc 0000000000066d98  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface*)+144)
 
  #05  pc 000000000006f598  /system/lib64/libhwui.so (android::uirenderer::renderthread::Bridge_initialize(android::uirenderer::renderthread::initializeArgs*)+16)
 
  #06  pc 000000000007189c  /system/lib64/libhwui.so (android::uirenderer::renderthread::MethodInvokeRenderTask::run()+24)
 
  #07  pc 00000000000729f8  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+336)
 
  #08  pc 0000000000011478  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
 
  #09  pc 00000000000aaa5c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
 
  #10  pc 0000000000068470  /system/lib64/libc.so (__pthread_start(void*)+36)
 
  #11  pc 000000000001f024  /system/lib64/libc.so (__start_thread+68)
```

I got 46 exception this week, all from android 8.1

Cordova-android is 7.1.1

Thanks

**Comment by brodybits** [comment]
I gotta say this looks like an issue on the Android platform and not on Cordova. I wouldn't mind a workaround solution, though.

**Comment by bruno-ian** [comment]
`  #00  pc 000000000001db94  /system/lib64/libc.so (abort+120)
  #01  pc 0000000000007f84  /system/lib64/liblog.so (__android_log_assert+296)
  #02  pc 000000000006c300  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::createSurface(ANativeWindow*, bool)+316)
  #03  pc 000000000006a078  /system/lib64/libhwui.so (android::uirenderer::renderthread::OpenGLPipeline::setSurface(android::Surface*, android::uirenderer::renderthread::SwapBehavior, android::uirenderer::renderthread::ColorMode)+76)
  #04  pc 0000000000066df8  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface*)+144)
  #05  pc 000000000006f5f8  /system/lib64/libhwui.so (android::uirenderer::renderthread::Bridge_initialize(android::uirenderer::renderthread::initializeArgs*)+16)
  #06  pc 00000000000718fc  /system/lib64/libhwui.so (android::uirenderer::renderthread::MethodInvokeRenderTask::run()+24)
  #07  pc 0000000000072a58  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+336)
  #08  pc 0000000000011478  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+280)
  #09  pc 00000000000aaa04  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+140)
  #10  pc 0000000000068470  /system/lib64/libc.so (__pthread_start(void*)+36)
  #11  pc 000000000001f024  /system/lib64/libc.so (__start_thread+68)`

Not using cordova, always happening on android 8.1 mostly Nokia 5... 
Is something related to canvas... i think... I would mind a workaround solution too!

**Comment by breautek** [comment]
Closing because the issue doesn't appear to be an issue with cordova.

If you think you've found a bug with cordova, feel free to open a new issue and please fill out all the information in the form.
