### ISSUE TITLE
cordova build android : Could not find intellij-core.jar

### ISSUE THREAD

**Issue by mccob** [apache/cordova-android#521]
```
cordova -v
8.1.2 (cordova-lib@8.1.1)

 cordova platform list
Installed platforms:
  android 7.1.1


cordova build android

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

thank you

see also another recent report of same issue : https://forum.ionicframework.com/t/ionic-pro-package-failed-after-successful-deploy/145355

**Comment by KristoferGoransson** [comment]
I also got the same issue today

**Comment by vicenteaige** [comment]
I got the same error but with the support-v4-27.1.1.jar. I was able to build a few days ago.

**Comment by arnoldsi** [comment]
Hi,
The issue happened due the removal of jar file from the repository:
https://bintray.com/bintray/jcenter/com.android.tools.external.com-intellij:intellij-core/26.0.1#files/com%2Fandroid%2Ftools%2Fexternal%2Fcom-intellij%2Fintellij-core%2F26.0.1

There is a fix for it that should be implemented in cordovalib:
open:
platforms\android\CordovaLib\build.gradle

Replace the order of repositories from:
`
repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
`

to:
`
repositories {
        maven {
            url "https://maven.google.com"
        }
		jcenter()
    }
`

I think this fix should be also implemented in cordova

**Comment by mccob** [comment]
seems I already get that :

```
buildscript {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
        maven { url 'https://maven.fabric.io/public' } // Fabrics Maven repository from cordova-plugin-firebase
    }
    dependencies {

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:4.1.0' // google-services dependency from cordova-plugin-firebase
        classpath 'io.fabric.tools:gradle:1.25.4' // fabric dependency from cordova-plugin-firebase
    }
}

allprojects {
    repositories {
        maven {
            url "https://maven.google.com"
        }
        jcenter()
        google() // Google's Maven repository from cordova-plugin-firebase
    }
    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="27.0.1" //String
      defaultMinSdkVersion=19 //Integer - Minimum requirement is Android 4.4
      defaultTargetSdkVersion=27 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=27 //Integer - We ALWAYS compile with the latest by default
    }
}

```

**Comment by arnoldsi** [comment]
@mccob make sure you changing the file in 
platforms\android\CordovaLib\build.gradle
and not app\build.gradle

**Comment by mccob** [comment]
android target : cordova default

cordova -v
8.1.2 (cordova-lib@8.1.1)

 cordova platform list
Installed platforms:
  android 7.1.1

**Comment by arnoldsi** [comment]
@mccob there is nothing changed in version 7.1.1 regarding this issue. You currently have cached gradle, therfore it working for you. On clean server or environment it won't work because the file doesn't exist (it was removed today, probably by mistake)

**Comment by mccob** [comment]
I have updated build.gradle as you explain (after platform rm / add)

**Comment by arnoldsi** [comment]
@mccob this is temporary solution. Usually you shouldn't save the platform as part of you project and add it according to environment you running on.
Cordova guys should fix the issue :)

**Comment by dpogue** [comment]
Part of the proposed change to move the Google Maven repo ahead of jcentre has already been made and released in cordova-android 7.1.1. However, the build.gradle file in the CordovaLib project did not get updated.

We'll be doing further gradle updates in the next major version for compatibility with updated Android SDKs, so I'll make sure it gets fixed there.

**Comment by arnoldsi** [comment]
@dpogue can't it be a hotfix for current major version? I think it's very important to fix this issue

**Comment by dpogue** [comment]
It sounds like the root issue here is that stuff got published to bintray with broken dependencies. Changing the Cordova dependencies is working around the problem, but not actually fixing it (because it's entirely outside the scope of anything we can control).

We can make the gradle file change and try to do a 7.1.2 release, but it's going to take at least a few days before that can be published. Speaking for myself, I won't be able to even start the release process and submit it to the list for voting until mid-next week at the earliest.
