### ISSUE TITLE
org.apache.cordova.engine.SystemWebView.mContext leak !

### ISSUE THREAD

**Issue by winnerliu** [apache/cordova-android#529]
SystemWebView memory leak

**Comment by janpio** [comment]
Can you please provide some more information?

**Comment by winnerliu** [comment]
[use leakcanary found](https://i.imgur.com/6gBzMoT.png)

**Comment by winnerliu** [comment]
@janpio

**Comment by brodybits** [comment]
Reopening for now. @winnerliu a better explanation to walk us through the issue would be really appreciated since not all of us are familiar with Leakcanary.

**Comment by pengbs** [comment]
same issue

**Comment by YauhenPaplauski** [comment]
I think I have the similar(or the same) issue. 
You can reproduce it after implementing LeakCanary([link](https://square.github.io/leakcanary/getting_started/)) into your "test" project([link](https://github.com/apache/cordova-android/tree/master/test)). 
![Screenshot_2019-11-05-23-57-38-980_org apache cordova unittests](https://user-images.githubusercontent.com/22295221/68285734-e0800b80-0090-11ea-8d44-f8eb27fc9f00.png)

Also, you can enable StrictMode([link](https://developer.android.com/reference/android/os/StrictMode)) and check TestActivity(for example) on InstanceCountViolation
 - I have this error in my app and also in your "test" project. To reproduce - reenter in the activity a few times.
       ```
 StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .setClassInstanceLimit(TestActivity.class, 1)
                .penaltyLog()
//                    .penaltyDeath()
                .build());
```

**Comment by breautek** [comment]
I'm unable to reproduce this (but could be using LeakCanary wrong...), but following their get started link, the logcat only produces `org.apache.cordova.unittests D/LeakCanary: Installing AppWatcher`, and nothing else. I also tried the StrictMode, but that didn't produce any output either.

Can someone confirm if this is still an issue on the current master?

**Comment by breautek** [comment]
Closing due to staleness.
