### ISSUE TITLE
Could not find intellij-core.jar 

### ISSUE THREAD

**Issue by videmort** [apache/cordova-android#530]
I know that the issue is fixed in version --> 7.1.2 
     Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar

But when will be released the version 7.1.2?

**Comment by dpogue** [comment]
When someone has time to start the release process, and it goes to the list for voting. Hopefully that process can start next week.

**Comment by videmort** [comment]
@dpogue  thanks for your quick answer!

I think that it is a blocking issue.
