### ISSUE TITLE
Build failing @7.1.1 Could not find intellij-core.jar

### ISSUE THREAD

**Issue by TimStopfer** [apache/cordova-android#533]
When I try to build my cordova android app I get the following build error:

`* What went wrong:
A problem occurred configuring project ':CordovaLib'.
> Could not resolve all files for configuration ':CordovaLib:classpath'.
   > Could not find intellij-core.jar (com.android.tools.external.com-intellij:intellij-core:26.0.1).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/external/com-intellij/intellij-core/26.0.1/intellij-core-26.0.1.jar`

The problem was supposedly fixed in :
https://cordova.apache.org/announcements/2018/07/18/cordova-android-7.1.1.html
but the build still fails.

I tracked it down to "/platforms/android/CordovaLib/build.gradle", where the jcenter repository is still in front of the maven repository.

When I change this manualy the build works just fine.

**Comment by dpogue** [comment]
This is fixed on master, and will be backported in a 7.1.2 patch release.

**Comment by mccob** [comment]
@dpogue 

```
cordova platform add android@https://github.com/apache/cordova-android.git
Using cordova-fetch for cordova-android@https://github.com/apache/cordova-android.git
Warning: using prerelease platform android@7.2.0-dev.
Use 'cordova platform add android@latest' to add the latest published version instead.
Adding android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: io.cordova.hellocordova
    Name: HelloCordova
    Activity: MainActivity
    Android target: android-27
cp: no such file or directory: /project/node_modules/cordova-android/node_modules
```

master is broken ?

with android@latest, intellij core error

**Comment by dpogue** [comment]
The master branch is being worked on in preparation for a new major version release, so it might have incompatibilities with existing tooling.

The `7.1.x` branch is probably what you're looking for.
