### ISSUE TITLE
com-intel-security-cordova-plugin incompatible with Cordova Android 7.x

### ISSUE THREAD

**Issue by ehorodyski** [apache/cordova-android#537]
This plugin from Intel was never upgraded for the 7+ line of Cordova Android. I've been trying to get in touch with their support team to update it, but heard nothing back.

Since the plugin is published and still available to install, I was wondering if there was a way I could help upgrade the plugin to be in-line for Android and submit it for the community, but haven't found any tutorials on how to upgrade Cordova Plugins for Cordova Android 7. It looks like all the old docs that were up are now tough to find searching on Google.

**Comment by janpio** [comment]
Can you link to the plugin?
What exactly is broken and not working?

**Comment by ehorodyski** [comment]
@janpio - Thanks for the swift response! 

The error I get is when I try to install `cordova-android@7.x` -- it just says the plugin `com-intel-security-cordova-plugin` is not compatible. 

As for the plugin's site, all that's left that I can find is their [npm repo](https://www.npmjs.com/package/com-intel-security-cordova-plugin). The Github repository has been taken down.

**Comment by janpio** [comment]
Hm, first, make sure to get a copy from the npm package that you can later use to create a new repository for the plugin: `npm pack com-intel-security-cordova-plugin`

Then I would suggest you create a new Cordova project with the newest CLI, add the newest Cordova-Android (7.1.2) and try to add the plugin. If it doesn't work, post the complete output of the `cordova plugin add ...` command here and we can take a look.

**Comment by ehorodyski** [comment]
Holy moley it worked. I just tried the other day too, removing Android from my project and re-adding it, then being told that the plugin didn't support the 7.x version of Cordova-Android. And now it works. 

I feel like I'm going crazy! Is it `7.1.2` helping out w/ older plugins?

**Comment by dpogue** [comment]
> Is it `7.1.2` helping out w/ older plugins?

Yes, glad to hear it's working :smile:

**Comment by janpio** [comment]
(Still make sure to create a copy of the plugin though - could be gone from npm any day)

**Comment by ehorodyski** [comment]
> (Still make sure to create a copy of the plugin though - could be gone from npm any day)

Totally did...we plan on moving away from it to use encrypted sqlite...but no time right now -- deadlines and such!

**Comment by ehorodyski** [comment]
Actually, I think we need to _unclose_ this. Now my app crashes when it starts...

Here are the logs: https://gist.github.com/ehorodyski/8da66177b56c524c920539a5dab98fd2

**Comment by brodybits** [comment]
> Actually, I think we need to _unclose_ this.

You should be able to click the Reopen button since you are the one who closed it. But I wonder if it is even worth the time and effort to troubleshoot a plugin with no GitHub repo together with cordova-android@7. Maybe easier for one of us to make a cordova-android@6 update, if needed.

> Here are the logs: https://gist.github.com/ehorodyski/8da66177b56c524c920539a5dab98fd2

I cannot tell anything from the logs.

**Comment by ehorodyski** [comment]
We started using that plugin to encrypt session tokens 3 years back, and with a tight deadline I don't know if we have the capacity to redo our encrypted storage technique.

It's definitely the Intel security plugin, if I remove it app runs fine...

⁣Sent from TypeApp ​

**Comment by brodybits** [comment]
Understood. Considering that the plugin is no longer supported, I think it would be easiest if you would stick with cordova-android@6 until you can redo your encrypted storage to use another plugin. I think it would be easier for one of us to make a special patch on cordova-android@6 than to debug the issue with cordova-android@7.

Considering that the plugin is no longer supported and the GitHub repo is gone, I would like to propose that we close this one as invalid. Any objections?

**Comment by ehorodyski** [comment]
Nope, that's what we're talking about internally as well. Thanks again for all the help everyone!

⁣Sent from TypeApp ​

**Comment by brodybits** [comment]
Wishing you guys the best of luck, please don't hesitate to ask if you have any other questions.
