### ISSUE TITLE
Cordova Platform add Android command failure

### ISSUE THREAD

**Issue by somnathkhamaru** [apache/cordova-android#543]
Unable to add android platform in Cordova
after recent update in cordova libraries
Last successfully completed the above mentioned command on 7th Nov 2018.
Node version:  10.13.0
npm version: 6.4.1
cordova version : 8.1.2 (cordova-lib@8.1.1)
I am able to build old codes. new app is failing

**Logs:

C:\Android_APP\cordova-ibeacon>cordova platform add android
Using cordova-fetch for cordova-android@~7.1.1
Failed to fetch platform cordova-android@~7.1.1
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 4294963248 Error output:
npm WARN com.evothings.cordovaibeacon@1.0.0 No repository field.

npm ERR! path C:\Android_APP\cordova-ibeacon\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Android_APP\cordova-ibeacon\node_modules\.staging'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Android_APP\cordova-ibeacon\node_modules\.staging']
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Android_APP\\cordova-ibeacon\\node_modules\\.staging\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Android_APP\\cordova-ibeacon\\node_modules\\.staging' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\somna\AppData\Roaming\npm-cache\_logs\2018-11-10T05_02_24_226Z-debug.log**

**Comment by dpogue** [comment]
Can you provide details of what version of cordova you're using, what version of cordova-android you're trying to install, and any error messages?

**Comment by somnathkhamaru** [comment]
@dpogue  cordova version : 8.1.2 (cordova-lib@8.1.1) 
cordova-android@~7.1.1

**Comment by somnathkhamaru** [comment]
I found a workaround to the problem,
Workaround:
 After the **_cordova add_** command  or  **_cordava plugin_** command command failure, a .staging folder is getting create in **_node_modules_** folder. This folder is stopping further commands to work. 
So I found that we can only delete this **_.staging_** folder after restarting the system.
So every time I am facing the command failure  issue . I am restarting the system and then deleting the .staging folder . Then other commands work.

**_### This workaround is time taking and annoying_**

**Comment by dpogue** [comment]
This sounds like an npm issue rather than specifically a Cordova issue. It's normal to have the `node_modules/.staging` folder during an npm install, but it should be removed automatically when the install finishes.

Other people facing this issue suggested checking that you have enough available disk space and memory.
