### ISSUE TITLE
Inconsistent installation of NDK .so files

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#557]
For JAR files I can think of the following options:
* `source-file` element with `libs` or `app/libs` target dir
* `lib-file` element

AFAIK for NDK `.so` the plugin has to use a `source-file` element, with target-dir in `app/src/main/jniLibs` for it to work (may be changed by PR #550).

I would like to see the following fixes:
* possible to use `lib-file` for both JAR and `.so`
* `.so` files should work from a subdirectory of `libs` or `app/libs` (`.so` files should **not** have to be installed in subdirectory of `app/src`)

**Comment by breautek** [comment]
Closing as obsolete / out-dated.

Too many things has changed between now and 2018. If this issue still persists, please create a new ticket with updated information.
