### ISSUE TITLE
Specifying a directory of .java files as source-file src no longer works

### ISSUE THREAD

**Issue by ippeiukai** [apache/cordova-android#564]
From https://github.com/apache/cordova/issues/47
And originally https://github.com/apache/cordova-android/issues/547#issuecomment-439331477

Specifying a directory with many .java files as source-file src works with cordova-android@6, but not with cordova-android@7. (Source files would be put into incorrect subdirectory on cordova-android@latest.)

This has affected at least one plugin, as shown in following PR:
https://github.com/vaenow/cordova-plugin-app-update/pull/119

This behaviour is undocumented, but has been already know on the web.
As discussed in https://github.com/apache/cordova/issues/47#issuecomment-439435990, we are keeping this behaviour.

**Comment by brodybits** [comment]
Thanks @ippeiukai for reporting. I cannot promise when I or anyone else will get a chance to fix this. PR would be welcome for review.

**Comment by dpogue** [comment]
I'm not really a fan of this and don't really think we should support this. It was always intended to to operate on files (hence the `source-file` name). We need to know what types of files are being installed in order to know where they need to go in the project structure.

Of course, now it's basically impossible to drop support for this without breaking an unknown number of plugins :disappointed:

**Comment by brodybits** [comment]
I am also not in love with this feature, for reasons I gave in the description of <https://github.com/apache/cordova/issues/47>. But yes the idea of breaking an unknown number of plugins without proper investigation and advance warning is pretty bad.

Assuming that this undocumented feature was broken in cordova-android 7.0.0, and we did not hear much until recently, I would now expect the number of plugins broken by this issue to be pretty minimal. I would favor deprecating this feature in the upcoming major release, with a warning message, and removing it at some point in the future. This should be part of the discussion in <https://github.com/apache/cordova/issues/47>.

**Comment by ippeiukai** [comment]
I’m not fun of the whole source-file element situation to be honest.
I feel it is already compromised when it allowed any file to be copied into the target dir inside Cordova project. It’s not just directory as src feature.
To me, specifying a directory of .java files is far more aligned with the purpose of source-file element than specifying individual .so or .a files. But that’s matter of personal opinion. My point is that it’s not just the directory that should be deprecated.

The documentation on the target-dir attribute reads as follows:

> A directory into which the files should be copied, relative to the root of the Cordova project. 

(https://cordova.apache.org/docs/en/8.x/plugin_ref/spec.html#source-file)

Note that cordova-android has diverged from the above documented behaviour in 7.x by replacing parts of specified path for backward compatibility. In fact, the undocumented feature described in this issue is broken (more like left behind) in that process.

As @brodybits says discussion should be continued on https://github.com/apache/cordova/issues/47.
