### ISSUE TITLE
SDK versions are resolved after plugins gradle extensions

### ISSUE THREAD

**Issue by tombell** [apache/cordova-android#569]
I also noticed that gradle extensions get injected before these versions are determined, meaning any plugin relying on these sees them as `null`.

```
// ...

// PLUGIN GRADLE EXTENSIONS START
apply from: "../cordova-plugin-browsertab/mobile-BrowserTab.gradle"
// PLUGIN GRADLE EXTENSIONS END

def hasBuildExtras = file('build-extras.gradle').exists()
if (hasBuildExtras) {
    apply from: 'build-extras.gradle'
}

// Set property defaults after extension .gradle files.
if (ext.cdvCompileSdkVersion == null) {
    ext.cdvCompileSdkVersion = privateHelpers.getProjectTarget()
    //ext.cdvCompileSdkVersion = project.ext.defaultCompileSdkVersion
}
if (ext.cdvBuildToolsVersion == null) {
    ext.cdvBuildToolsVersion = privateHelpers.findLatestInstalledBuildTools()
    //ext.cdvBuildToolsVersion = project.ext.defaultBuildToolsVersion
}
if (ext.cdvDebugSigningPropertiesFile == null && file('../debug-signing.properties').exists()) {
    ext.cdvDebugSigningPropertiesFile = '../debug-signing.properties'
}
if (ext.cdvReleaseSigningPropertiesFile == null && file('../release-signing.properties').exists()) {
    ext.cdvReleaseSigningPropertiesFile = '../release-signing.properties'
}

// Cast to appropriate types.
ext.cdvBuildMultipleApks = cdvBuildMultipleApks == null ? false : cdvBuildMultipleApks.toBoolean();
ext.cdvVersionCodeForceAbiDigit = cdvVersionCodeForceAbiDigit == null ? false : cdvVersionCodeForceAbiDigit.toBoolean();
ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? defaultMinSdkVersion : cdvMinSdkVersion
ext.cdvVersionCode = cdvVersionCode == null ? null : Integer.parseInt('' + cdvVersionCode)

//...
```

**Comment by brodybits** [comment]
I just labeled this as a bug, maybe similar to #599.

As I said in <https://github.com/apache/cordova-android/pull/568#issuecomment-444179258> the standard way for a plugin to specify minimum SDK version is in `sdk-element` (<https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config>), but it seems to be ignored if the value is also specified in Gradle (<https://github.com/apache/cordova-android/issues/599#issuecomment-444283762>).

As discussed in #599 there is an issue if both a plugin and user config specify SDK version. The suggestion in #599 to move the `PLUGIN GRADLE EXTENSIONS` comments is good but could prove to be a breaking change in some cases.

I think the best solution would be to move the plugin gradle extensions into a separate Gradle file. I think this should be done in a major release, with plenty of advance warning with documentation.

**Comment by brodybits** [comment]
@tombell any particular reason to close this?

Do you think this issue was fixed somehow?

**Comment by tombell** [comment]
From what I remember, I didn't have to work around it anymore.
