### ISSUE TITLE
Plugin is not correctly installed if the package contains "app"

### ISSUE THREAD

**Issue by jcesarmobile** [apache/cordova-android#571]
Example from `cordova-plugin-local-notifications` https://github.com/katzer/cordova-plugin-local-notifications
`src/de/appplant/cordova/plugin/localnotification`

We should probably check for `"app/"`, but might still affect others. Maybe use `startsWith` instead of `includes`?

**Comment by brodybits** [comment]
`cordova-plugin-inappbrowser` is also affected, thanks to @kamilbrk for pointing it out in <https://github.com/apache/cordova-android/pull/572#issuecomment-441018515>

**Comment by brodybits** [comment]
Will be in cordova-android@nightly (nightly build from master branch, with bleeding-edge updates for Cordova 9) in 12-24 hours or so, patch release coming in the next few days.

**Comment by brodybits** [comment]
7.1.4 patch release is now published to resolve the issue.
