### ISSUE TITLE
Target directory generation in source-file for legacy plugin is not enough restrictive

### ISSUE THREAD

**Issue by Jule-** [apache/cordova-android#575]
This line :
https://github.com/apache/cordova-android/blob/a68f9fd752a25bb680da96414a3b956357c2dfcb/bin/templates/cordova/lib/pluginHandlers.js#L323

Should be written like this :
```js
if (obj.targetDir.startsWith('app/')) {
```

Or maybe you should treat paths as directory arrays and check the first one.

Current released version is :
https://github.com/apache/cordova-android/blob/e1befaca5a0c52ebc62cbb94870558d428d92fc4/bin/templates/cordova/lib/pluginHandlers.js#L323

Which is leading plugin with package names containing somewhere `app` to be wrongly installed in `platforms/android/src/`.
This is the case for : [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) (`de.appplant.cordova.plugin.localnotification.LocalNotification`).

And with the actual form packages like `applause.fun.example` should get trapped in that issue.

**Comment by Jule-** [comment]
Oh maybe I am wrong, since directory should start with `src/applause/fun/example`... Need confirmation!

**Comment by Jule-** [comment]
But I think it doesn't hurt to put the `/` no? ;)

**Comment by brodybits** [comment]
My comments coming in PR #576

**Comment by brodybits** [comment]
Resolved by #589
