### ISSUE TITLE
AppVeyor/Windows CI builds are broken

### ISSUE THREAD

**Issue by janpio** [apache/cordova-android#579]
See latest commits in https://github.com/apache/cordova-android/commits/7.1.x

https://ci.appveyor.com/project/Humbedooh/cordova-android/builds/20501293/job/3xd5auvkdf2d301l/messages
https://ci.appveyor.com/project/Humbedooh/cordova-android/builds/20501493/job/23ba35450icc9anc/messages

Should be investigated and fixed.

**Comment by breautek** [comment]
Closing because this is out-dated.
