### ISSUE TITLE
it should be checked if `studioPathRemap(obj);` is undefined, because `target-dir` starts with `app/src/main/` will become undefined.

### ISSUE THREAD

**Issue by janpio** [apache/cordova-android#583]
Just noticed this comment on the 7.1.2 release:
https://cordova.apache.org/announcements/2018/11/07/cordova-android-7.1.2.html#comment-4197687730

**Comment by dpogue** [comment]
This was fixed in 7.1.3: https://github.com/apache/cordova-android/pull/539
