### ISSUE TITLE
plugin.xml with platform version filters

### ISSUE THREAD

**Issue by j3k0** [apache/cordova-android#585]
About #580, I have a higher level concern about handling deprecation as a plugin author.

It's ok to allow breaking changes in Cordova for the sake of progress, but the following small change in `plugin.xml` structure would give plugin authors flexibility to support multiple cordova versions.

Has it been ever considered to allow multiple `<platform>` tags with version filters?

Short demo of what I mean in a plugin description file:

```xml
<plugin ...>
  <platform type="android" version="<8.0.0">
    ...
    <source-file src="src/android/ILib.aidl" target-dir="src/com/android/vending/billing" />
    ...
  </platform>
  <platform type="android" version=">=8.0.0">
    ...
    <lib-file src="src/android/ILib.aidl" />
    ...
  </platform>
  <platform type="android" version="*">
    ... common stuff ...
  </platform>
</plugin>
```

It's probably not specific to `cordova-android` though, where should such an idea be discussed?

**Comment by janpio** [comment]
Interesting suggestion!

A good way to get this in front of more people would be to send an email to the dev mailing list: https://cordova.apache.org/contact/ (Best mention that discussion should happen here in the issue)

**Comment by Jule-** [comment]
@j3k0 is that what you are looking for?
https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#specifying-cordova-dependencies

I think this is how to handle platform version with plugin version and maybe you will have to maintain separate branches/tags for that purpose. I did not have tested it myself.

**Comment by brodybits** [comment]
I just raised <https://github.com/apache/cordova/issues/58>, with some edits to the plugin demo, for discussion.

> https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/index.html#specifying-cordova-dependencies
>
> maybe you will have to maintain separate branches/tags for that purpose

"Maybe" should be "definitely"; I would not favor making plugins do this. I just updated <https://github.com/apache/cordova/issues/58> with this info.

**Comment by j3k0** [comment]
Thanks @Jule-  This can do the job, but it might not be really to manage plugins version numbers.

This suggest, for example that the plugin has branches with version 1 that supports cordova-android@7 and version 2 that supports cordova-android@latest.

Then the plugin introduces an API change, it has to change major version. In order to keep supporting both cordova-android@7 and cordova-android@8 with the new plugin API, the plugin author has to create 2 new major releases. Like version 3 for cordova-android@7 and version 4 for cordova-android@8... What if the problem is multiplied with more different platforms?

It might be a little confusing, with different versions meaning either a change in supported platforms or a change in the plugin itself.

**Comment by erisu** [comment]
I am closing this ticket as previous comment said it would in favor for the other ticket.

I will also migrate this ticket to the `apache/cordova` repo as this request is more of a generic feature request for all platforms.
