### ISSUE TITLE
CordovaPlugin method name onRequestPermissionResult inconsistent with Android onRequestPermissionsResult

### ISSUE THREAD

**Issue by shader** [apache/cordova-android#592]
The name used for the permission request callback in the Android class [ActivityCompat.OnRequestPermissionsResultCallback](https://developer.android.com/reference/androidx/core/app/ActivityCompat.OnRequestPermissionsResultCallback) is onRequestPermissionsResult, not onRequestPermissionResult.

This is quite confusing, and should probably be fixed.

**Comment by dpogue** [comment]
We can't rename this without breaking a bunch of existing plugins :(

**Comment by brodybits** [comment]
Couldn't Cordova trigger both `onRequestPermissionResult` and `onRequestPermissionsResult` on the plugin, and deprecate the first one?
