### ISSUE TITLE
Support gradle 4.9+

### ISSUE THREAD

**Issue by theunreal** [apache/cordova-android#596]
Since Gradle 4.9, it is possible to create app Bundle instead of managing and signing an APK.

I use app bundle for my Cordova app and I need to change the gradle version and manifest manually each build in order to build app bundle in Android Studio from my Cordova application.

Is there any plan to support gradle 4.9 (or latest - 5) in the near future?

**Comment by dpogue** [comment]
We were having a discussion about minimum vs latest gradle versions in https://github.com/apache/cordova-android/pull/507. This is probably a compelling reason to go for the latest rather than the minimum.
