### ISSUE TITLE
darryncampbell-cordova-plugin-intent crashed 

### ISSUE THREAD

**Issue by viacheslavvbogdanov** [apache/cordova-android#597]
android engine 7.1.4
cordova 8.1.2
ionic 4.5.0

error:
```
Fatal Exception: java.lang.NoSuchMethodError
No virtual method put(Ljava/lang/String;Ljava/util/Collection;)Lorg/json/JSONObject; in class Lorg/json/JSONObject; or its super classes (declaration of 'org.json.JSONObject' appears in /system/framework/core-libart.jar)
```

P.S. in cordova-android 7.1.0 it works with no exceptions

**Comment by janpio** [comment]
In the linked issue it seems the plugin author can't reproduce the problem in 7.1.4. Can you in a newly created Cordova app (`cordova create`)?

**Comment by viacheslavvbogdanov** [comment]
I've changed android engine to 7.1.4 and recompiled my project again and for now it works fine.
Sorry, looks like it was some build issue in my project. May be some files was not downloaded correctly...
Thank you for your time and great software you develop!
