### ISSUE TITLE
Reload app with backup url if first fails

### ISSUE THREAD

**Issue by eXpliCo** [apache/cordova-android#601]
I want to be able to catch when the page fails to load in Cordova, fails to load in "CordovaWebViewImpl.loadUrl(String url)" function. I've noticed if I implemented the 
`
WebViewClient.onReceivedHttpError(WebView view, WebResourceRequest request, WebResourceResponse errorResponse)
`
to notify all plugins that the error has happened then I'm able to fetch the error. But that requires me to change the base cordova code. Is there a way to do this and not change the base cordova code and extend some class a simple way.

What I want to do is that if the page that is trying to be loaded returns a 500 error then I want to try to load another url that is fetched from the configuration. Is this possible with current cordova impl?

**Comment by jcesarmobile** [comment]
Cordova has an errorUrl preference
https://cordova.apache.org/docs/en/latest/config_ref/index.html
