### ISSUE TITLE
App crashes on Android when HTTP plugin and Launch Navigator are installed

### ISSUE THREAD

**Issue by Genarito** [apache/cordova-android#602]
Hi! 
As [this issue](https://github.com/ionic-team/ionic/issues/15583) says, app crashes when trying to use [HTTP plugin](https://github.com/silkimen/cordova-plugin-advanced-http) in a project with [Launch Navigator plugin](https://github.com/dpa99c/phonegap-launch-navigator) installed too. Apparently there is a problem in cordova.js, that's why I'm reporting here (I've also reported in the plugin repo).

Thanks in advance and sorry about inconvenients.
Great job!

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by Genarito** [comment]
Sure! [Here It is](https://bitbucket.org/GenaroCamele/demo_bug_http_advanced/src)

Note that when you remove the Launch Navigator plugin function `demoBug()` in `index.js` executes successfully and app does not crash.

Thanks in advance!

**Comment by Genarito** [comment]
Ok, It's a problem with the fixed version of OKHTTP in Advanced HTTP Plugin. The solution for the problem is to set the library version in the Launch Navigator Plugin's variable as they say [in this issue](https://github.com/dpa99c/phonegap-launch-navigator/issues/207)
