### ISSUE TITLE
black screen after build success with cocoon ads android admob plugin

### ISSUE THREAD

**Issue by krestia** [apache/cordova-android#603]
Hi, 
after i update to cordova 8.1.2 and add platforms android 7.1.4, my app build has success but it run but only show black screen.
I made with construct 2, export to cordova and add plugin 
-  install plugin cocoon ads android admob 2.0.1, (latest version of cocoon ads plugin)
- add plugin android support gradle release, 
- add plugin cordova crosswalk webview.
I build it with cordova cli. Build success but it shown black screen.

why it happen?

**Comment by janpio** [comment]
Did this work with an earlier version of `cordova-android`?

**Comment by krestia** [comment]
> Did this work with an earlier version of `cordova-android`?

yes, i was build with cordova 8.0.0, android 6.3.0 and all worked fine...

**Comment by janpio** [comment]
`cordova-android` moved a lot of stuff around, plugins have to support that.
Did it work with `cordova-android` 7.x?

**Comment by krestia** [comment]
> `cordova-android` moved a lot of stuff around, plugins have to support that.
> Did it work with `cordova-android` 7.x?

i used android@7.0.0 and get this error ;
       BUILD FAILED in 26s
cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find builder.jar (com.android.tools.build:builder:3.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/builder/3.0.0/build
er-3.0.0.jar
   > Could not find lint-checks.jar (com.android.tools.lint:lint-checks:26.0.0).

     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-checks/26.0.0/l
int-checks-26.0.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s

**Comment by janpio** [comment]
That sounds like a problem with the plugin then - please report it to their GitHub repo. Feel free to open another issue here if they say it is actually a problem of cordova-android in general.
