### ISSUE TITLE
Deviceready has not fired after 5 seconds - Android 7.1.4

### ISSUE THREAD

**Issue by FreddyCrugger** [apache/cordova-android#604]
Hello,

I would like to know if there is a problem with this 7.1.4 android version as I keep having this issue in my chrome://inspect console:

```
deviceready has not fired after 5 seconds. cordova.js:1219
Channel not fired: onPluginsReady cordova.js:1212
Channel not fired: onCordovaReady 
```

I have disabled all the plugins, same problem.

I am using vue.js with Cordova:

```
import 'babel-polyfill';
import Vue from "vue";
import App from "./App.vue";
import Vuetify from "vuetify";
import router from "./router";
import { store } from "./store";
import "./registerServiceWorker";
import "vuetify/dist/vuetify.min.css";
import "material-design-icons-iconfont/dist/material-design-icons.css";
Vue.use(Vuetify);

Vue.config.productionTip = false;

if (
navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|IEMobile)/)
) {
document.addEventListener("deviceready", onDeviceReady, false);
} else {
onDeviceReady(); //this is the browser
}

function onDeviceReady() {
new Vue({
router,
store,
render: h => h(App)
}).$mount("#app");
}
```

I have also tried directly without condition
`document.addEventListener("deviceready", onDeviceReady, false);`

Same issue.

Any idea why can cause this please?

Thank you.

**Comment by alexlopezit** [comment]
+1

**Comment by shijunti19** [comment]
+1

**Comment by brodybits** [comment]
Please [create a minimal reproduction example](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) based on recent version of Cordova, as we do not support old Cordova releases. See also [this minimal reproducible example on StackOverflow](https://stackoverflow.com/help/minimal-reproducible-example).

Followup questions are fine, but no “+1” comments please. To upvote the issue, please do the following:

1: Click on the smiley thing on the description, like you can see in this mini-screenshot:

<img width="184" alt="Screen Shot 2019-07-18 at 9 31 11 PM" src="https://user-images.githubusercontent.com/1559888/61502875-9e2ca480-a9a3-11e9-9bb9-2352f94ad11a.png">

2: Then click on your desired reaction, like one of these:

<img width="234" alt="Screen Shot 2019-07-18 at 9 33 43 PM" src="https://user-images.githubusercontent.com/1559888/61502932-dc29c880-a9a3-11e9-96b0-e27fc4046170.png">

**Comment by jcesarmobile** [comment]
Closing as the requested information was not provided.
