### ISSUE TITLE
Strange Google requests crashes

### ISSUE THREAD

**Issue by QuipHop** [apache/cordova-android#605]
Hi!
I've already googled the issue but found nothing
Maybe You know how to fix the error
Some of users with different phones/android versions got error in the android builds

![image](https://user-images.githubusercontent.com/3627368/49999353-3f332700-ff9f-11e8-8177-68bd6075fa02.png)

I used Your default configs for config.xml and meta tag in the index.html
Whitelist plugin works properly (seems like)
All my files are static and the app doesn't make any external requests at all
The most users are don't facing this issue.
Cordova and plugins/platforms are up to date.
Web builds works properly for any device.
I really can't understand where this request comes from and can't wrap it in try/catch or handle somehow.

My configs:

```<?xml version='1.0' encoding='utf-8'?>
<widget id="com.quiphop.bumgineer" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Bumgineer</name>
    <description>
    </description>
    <author email="quiphop@gmail.com" href="">
        Konstantin Vasilkovsky
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="Fullscreen" value="true" />
    <preference name="orientation" value="portrait" />
    <plugin name="cordova-plugin-browsersync" spec="~0.1.7" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <engine name="ios" spec="^4.5.1" />
    <engine name="browser" spec="^5.0.2" />
    <engine name="android" spec="^7.0.0" />
</widget>
```

```<meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *; img-src 'self' data: content:;">```

Thanks for Your attention!

**Comment by janpio** [comment]
As I said in the Cordova Slack, this is a Doubleclick (Google Ad network) URL, possibly being blocked by something on the client, Ad Blocker or similar. Then later `gbar` is not defined which would be loaded via that file.

What plugins are you using?
Are you using any Google products or scripts in your app?
Who sent you this screenshot and how did they get it?

**Comment by QuipHop** [comment]
> As I said in the Cordova Slack, this is a Doubleclick (Google Ad network) URL, possibly being blocked by something on the client, Ad Blocker or similar. Then later `gbar` is not defined which would be loaded via that file.
> 
> What plugins are you using?
> Are you using any Google products or scripts in your app?
> Who sent you this screenshot and how did they get it?

It's not adblocker/vpn/network issue, i've tested it

**Comment by QuipHop** [comment]
> > It's not adblocker/vpn/network issue, i've tested it
I checked with user his apps/plugins, nothing special
> How? Can you reliably reproduce the error yourself?
 I can't reproduce it. But 3 users got this error. Rest ~30 are ok.
> > The user got app hang and I provided him an instructions how to inspect device within chrome inspector tool.
> 
> Best ask him to send the whole content of the `index` that is throwing the error - if you are not using `gbar` in your code, I would be curious where it is coming from.
 Ok, We will try that
> Do your users install your app from Google Play Store or some other locations?
The user installed app from Play store, other build with potential fixes I've sent him as debug versions without signing

Maybe there is something wrong with allows in config?

**Comment by janpio** [comment]
A configuration error can not make requests to domains that are not part of your appear out of nothing. You could possibly add the domain to the whitelist so it doesn't get blocked, but I don't know enough about that to give any advise here.

The more interesting question here is: Why does your app request stuff you didn't program it do do? That will possibly be answered by the `index` content.

**Comment by QuipHop** [comment]
> A configuration error can not make requests to domains that are not part of your appear out of nothing. You could possibly add the domain to the whitelist so it doesn't get blocked, but I don't know enough about that to give any advise here.
> 
> The more interesting question here is: Why does your app request stuff you didn't program it do do? That will possibly be answered by the `index` content.

Yes, I'm curious as well. Will provide more info when will be ready. 
Thanks for attention

**Comment by janpio** [comment]
What was the solution and explanation?

**Comment by QuipHop** [comment]
> What was the solution and explanation?

After deeper investigation I've found the major error
There is something with sound on Meizu Phones only on cordova build, same build in browser working well.
Original error: `Failed to execute 'start' on 'AudioBufferSourceNode' The provided double value is non-finite`
