### ISSUE TITLE
There are no `android.home` system property on Linux

### ISSUE THREAD

**Issue by dkotrada** [apache/cordova-android#614]
Hello,
you guys use in `/platforms/CordovaLib/cordova.gradle` 
This codeline `String systemProperty = System.getProperty("android.home")`

There is no such property. :) So you get nothing in `systemProperty`

See for Documentation: https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

This is related to not found Android Build Tools
```bash
* What went wrong:
A problem occurred evaluating project ':CordovaLib'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.
```
What do you intended to do with `android.home` ?

**Comment by breautek** [comment]
`android.home` is set by the android sdk, which you appear to be missing as stated by the error.

See https://cordova.apache.org/docs/en/9.x/guide/platforms/android/index.html#installing-the-requirements

**Comment by dkotrada** [comment]
$ echo $ANDROID_HOME
/Users/****/Library/Android/sdk

is `ANDROID_HOME` != `android.home`  ?
