### ISSUE TITLE
Cordova application considerably slower than mobile browser version of application

### ISSUE THREAD

**Issue by FarhadG** [apache/cordova-android#615]
We have a web application that we've recently wrapped with Cordova. That being said, the overall experience is considerably slower from the web equivalent. What are the reasons for this?

Some examples include transitions, animations, touch interactions, etc.

I haven't been able to get `--prod` to work just yet, but I've only read that this feature improves build/start time of the application. Not sure about UI/UX interactions.

**Comment by dpogue** [comment]
Closing in favour of the discussion at https://github.com/apache/cordova-ios/issues/495
