### ISSUE TITLE
<input type="file" multiple> not working

### ISSUE THREAD

**Issue by StarStep** [apache/cordova-android#621]
Hi, 
I just noticed that on android is impossibile to get multiple files trought file choser.
Code used: `<input type="file" name="attachment[]" multiple="multiple"/>`

Tested on iOS and works as should. Work on Google Chrome too.
Searched on the web for any solution... but found only this:
https://stackoverflow.com/questions/5907369/file-upload-in-webview

Maybe you know how to deal with it? I tried other filechoisers but none of them supports misc files.
It would be great to be able to select files just like on the other platforms.
Thanks you very much!

**Comment by artuska** [comment]
+1

**Comment by StarStep** [comment]
Work for me on Android 8.1.0. 
@MatusFiala, thanks!

**Comment by gabriele-sacchi** [comment]
@MatusFiala please note that the lack fo the intent type and category prevents this to work using ng-file-upload.

These 2 lines fix the problem as reported on [this new issue](https://github.com/apache/cordova-android/issues/695).

Thanks!!

**Comment by shubhamtakode** [comment]
I'm facing same issue tried name="files[]" but still not working on android

**Comment by marcusdiy** [comment]
Currently on android browser, using multiple attribute, allows the direct selection of multiple files. On cordova is required to hold an element to enter multiple selection mode. Would it be possibile to do the same? As its more user friendly actually...

**Comment by jcesarmobile** [comment]
multiple is working fine in cordova-android 9, as marcusdiy said, you have to hold a file and then you can pick more.

And no, that behavior can't be changed, is provided by the webview picker.
