### ISSUE TITLE
Java version check does not print detected version to console

### ISSUE THREAD

**Issue by FabianTe** [apache/cordova-android#623]
Hi!

Disclaimer: I am unsure if this is the correct repository, feel free to guide me to the correct spot if I am lost 😉 

So, When using Cordova and having Java 11 and Java 8 installed on my Windows machine, running `cordova emulate android` will output this error many people know: 

```
ANDROID_HOME=C:\Users\fabit\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_202
Requirements check failed for JDK 1.8
```

I then thought "hmm, but my `JAVA_HOME` is pointing to the correct JDK, version 8.
Running the command with `--verbose` showed my that in fact Cordova checks not the ENV variable but some other. This happens in this function:

This can be found here: https://github.com/apache/cordova-android/blob/d9c08f12a7bceb47ee97ca8ca0e75548e78f999d/bin/templates/cordova/lib/check_reqs.js#L355-L369

As you can see, the check is happening on `values[0]`, not the `JAVA_HOME` ENV variable.

This is misleading and caused me (and propably others) to uninstall the correct Java version and still getting the error since I didn't suspect Cordova picking up Java 11.

**Comment by FabianTe** [comment]
I added a `console.log` command in the linked PR.

**Comment by janpio** [comment]
Ugh, why does it output that ENV var there then at all? Do you have a suggestion for better output here that would actually help users to understand what is going on? (besides just outputting the compared value like in your PR?)

**Comment by FabianTe** [comment]
Well, I could rewrite it to display "Checking your Java and Android SDK version". Printing the ENV variable isn't correct.

Looks like in my case, there was more to it, i fixed my error:

As mentioned above I have Java 11 and 8 installed. What I just now found was, that I hat a `PATH` ENV entry pointing to my Java 11 installation. In some way this ended up in the called function, not my `JAVA_HOME` ENV variable. Figuring this out will take a while, but isn't related to this issue.

**Comment by brodybits** [comment]
I think it is good to log both the JAVA_HOME setting and the result of `javac -version` to help the user figure out what is going wrong.

**Comment by FabianTe** [comment]
@brodybits Theoretically it is. But what I have discovered is that these may not correspond to what Cordova checks. Both my ENV variables and the javac --version showed the 1.8 installation. Yet somehow Cordova used my OpenJDK 11 installation.

**Comment by brodybits** [comment]
> Both my ENV variables and the javac --version showed the 1.8 installation. Yet somehow Cordova used my OpenJDK 11 installation.

Got it now. I think that comment belongs on PR #624 where we are reviewing the actual changes.

**Comment by FabianTe** [comment]
Thank you for your feedback!
I'd be happy to clean up the `check_req.js` once Cordova 9 is out. But that should be another issue & PR I think 😉
