### ISSUE TITLE
It is a question about the version of gradle used

### ISSUE THREAD

**Issue by nrikiji** [apache/cordova-android#627]
It is the question

```
cordova build
cordova run
```
When building with this command, where is the gradle used?
When building a project with android studio, I think that you use gradlle that android studio has.
Does it happen that the version of gradle used before and after opening a project in android studio changes?

**Comment by brodybits** [comment]
> When building with this command, where is the gradle used?

Should be run from the PATH setting in the environment.

You should be able to get some more specific info from `cordova requirements`.

> When building a project with android studio, I think that you use gradlle that android studio has.

I think so too.

> Does it happen that the version of gradle used before and after opening a project in android studio changes?

I am leaving that question up to someone more experienced with Gradle.

I hope another Cordova member can help explain this information more clearly, don't have much time to research it right now.

I think this should be documented better.

**Comment by breautek** [comment]
The project defines the gradle version to use, and downloads a "gradle wrapper" (`gradlew`) that is installed locally to the android project.

In normal android projects, the gradle version is defined in a gradle config like in https://github.com/apache/cordova-android/blob/master/test/android/wrapper.gradle

Cordova does some manually stuff manually, but will generate a file similar to the one I linked above for your android project.

The main gradle executable (`gradle`) will be searched for in the `PATH` system variable, and if missing, it may search for locations in the android studio/sdk directory. But Google tends to move things around frequently so relying on the fallback isn't very reliable.

Hope this helps. If you have further questions, I invite you to ask on our [slack](http://slack.cordova.io/)

@brodybits I'm not sure what exactly should be documented. Most of this I don't think is relevant to most users, maybe only to plugin developers? But if you think something should be documented, then perhaps raise an issue on [cordova-docs](https://github.com/apache/cordova-docs)?
