### ISSUE TITLE
Missing cordova_plugins.js after platform add/prepare

### ISSUE THREAD

**Issue by bramk** [apache/cordova-android#636]
When adding android platform 7.0.0/7.1.4 on an existing project I can build/install the app, but it is non-functional because `cordova_plugins.js` is missing. All is fine using android platform 6.3.0/6.4.0.

I did some debugging and what I can see when I do `cordova platform add android@7.1.4`:

1. `PluginManager#` writes `www` and not `platform_www` because `options.usePlatformWww` is not truthy? On platform 6.3.0/6.4.0 it does.
2. During merging the `cordova_plugins.js` version in `www` is deleted, because it does not exist in `platform_www`.
```
Merging and updating files from [www, platforms/android/platform_www] to platforms/android/app/src/main/assets/www
...
  delete platforms/android/app/src/main/assets/www/cordova_plugins.js (no source)
 ```
When I subsequently add a plugin using `cordova plugin add` the  `cordova_plugins.js` is being created in both `www` and `platform_www` and everything is fine again.

From CB-11022 I got that the `usePlatformWww` was added as an optimization, but Iḿ not clear how this should work here (or why it breaks).

version disclosures:
node@v6.9.5
npm@3.10.10
cordova@8.1.2 (cordova-lib@8.1.1)

**edit1:**
Adding a plugin using `cordova plugin add` does not solve it. The resulting apk does now contain a full `cordova_plugins.js `, but the plugin resources themselves actually have not been added. So now I get these messages:
```
019-01-23 15:25:23.767 6710-6788/com.equestic E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/plugins/cordova-plugin-appminimize/www/AppMinimize.js
2019-01-23 15:25:23.773 6710-6788/com.equestic E/AndroidProtocolHandler: Unable to open asset URL: file:///android_asset/www/plugins/cordova-plugin-background-mode/www/background-mode.js
```

**edit2**
The plugin resources are missing for the same reason. They are being deleted during the merge.
```
  rmdir  platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera (no source)
  rmdir  platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera/www (no source)
  delete platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera/www/Camera.js (no source)
  delete platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera/www/CameraConstants.js (no source)
  delete platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera/www/CameraPopoverHandle.js (no source)
  delete platforms/android/app/src/main/assets/www/plugins/cordova-plugin-camera/www/CameraPopoverOptions.js (no source)
```

**Comment by bramk** [comment]
Took another look and found what seems to be the source of my problem, but still not sure how to proceed and/or solve this in the correct way.

**Cordova Lib** during `prepare#restoreMissingPluginsForPlatform` calls `removePlugin` followed by `addPlugin` for each plugin to be installed  on the platform api. It sets `pluginOptions.usePlatformWww` to `true`, but **notice how it reuses that object for both calls**! This code has not changed in the last couple of releases.

https://github.com/apache/cordova-lib/blob/a478ce39b44a957ba1f960f380c75b6353213aa4/src/cordova/prepare.js#L162-L170

**Cordova Android** during `removePlugin` conditionally sets `uninstallOptions.usePlatformWww` to `false` and if it does during prepare the subsequent call to `addPlugin` will have that also receive that value. That particular logic has changed a lot over the last couple of releases.

In `6.4.0` it seems the condition was never met due to a broken  `AndroidStudio.isAndroidStudioProject` check and therefore `uninstallOptions.usePlatformWww` was left thruthy.

In `7.0.0` and beyond the `AndroidStudio.isAndroidStudioProject` was modified several times, in `7.1.4` it just defaults to `true` and in master it has been removed. In all these case it means that the condition is met and `uninstallOptions.usePlatformWww` is set to `false` for `removePlugin` and, in the prepare case, also the subsequent `addPlugin` call.

https://github.com/apache/cordova-android/blob/a68f9fd752a25bb680da96414a3b956357c2dfcb/bin/templates/cordova/Api.js#L274-L277

I think there is some code smell here? One could argue that Cordova lib should make a defensive copy, but tbh I also simply do not understand why  `usePlatformWww` is set to `false` at all in the `removePlugin` code.

**Comment by brodybits** [comment]
Thanks @bramk for reporting.

Unfortunately it is still not quite clear to me what exactly would trigger this issue and how we may be able to reproduce it. A reproduction demo project would be especially helpful.

I could imagine that changing the Cordova CLI version after adding and removing plugins could lead to this kind of an issue. I would say that the workaround would be to simply regenerate the Android project (Android platform) whenever you change to a different major Cordova CLI version or remove several plugins.

The code analysis sounds right. I cannot promise when I or any other Apache Cordova member would have a chance to take a closer look. Contributions of improvements or some kind of bug fix would be really appreciated, especially with reproduction and testing instructions.

I am not sure whether or not we should use the **bug** label. I would really like to get a better understanding of reproduction, if possible.

**Comment by bramk** [comment]
Hey @brodybits, thanks for looking at this!

Please note that this also consistently happens when I regenerate the android. platform. I can not share my affected project, but will look into creating a small reproduction when I find the time. 

I think the obvious fix would be to ensure that a) `Api#removePlugin` simply respects `uninstallOptions.usePlatformWww`, and b) does not modify it so the side-effect to a subsequent `Api#addPlugin` goes away?

My hesitation is that I am new to this stack and I simply do not understand why it was put there in the first place. It seems intentional, but I can find a rationale in the history..

**Comment by PowerP** [comment]
Hi,

have the same problem and can not fix it. 
Are there any updates on this?

Cheers

**Comment by kalex375** [comment]
if you add platform with version ```cordova platform add android@9.0.0``` and platform exists in package.json, cordova won't update/add 'cordova_plugins.js'.  As workaround remove platform from packge.json and use key '--nosave'
 ```cordova platform add android@9.0.0 --nosave```

**Comment by breautek** [comment]
Closing as stale.

**Comment by erophames** [comment]
> if you add platform with version `cordova platform add android@9.0.0` and platform exists in package.json, cordova won't update/add 'cordova_plugins.js'. As workaround remove platform from packge.json and use key '--nosave' `cordova platform add android@9.0.0 --nosave`

This is not a fix and it is now happening with cordova-android@13.0.0
