### ISSUE TITLE
Release notes for 7.1.x are missing

### ISSUE THREAD

**Issue by janpio** [apache/cordova-android#639]
7.1.1, 7.1.2, 7.1.3 and 7.1.4 were released, but the release notes in master were not updated.

The release note exist in the release branch: https://github.com/apache/cordova-android/blob/7.1.x/RELEASENOTES.md

**Comment by brodybits** [comment]
That is because 7.1.1, 7.1.2, 7.1.3, and 7.1.4 are not part of master.

If we release 8.0.0 according to <https://github.com/apache/cordova-coho/blob/master/docs/platforms-release-process.md> then we should see all changes for 8.0.0 in RELEASENOTES.md.

I hope this makes sense.

**Comment by janpio** [comment]
Does that make sense to you? It feels like a missing thing in the release docs to me.

How do e.g. bugfixes from the release branch make its way back to `master`? Only on the next major or minor release that also merges back the release notes?

**Comment by erisu** [comment]
Per documentation:

>## Special Case 1: Release notes in release branch for patch release
> If you have prepared the release notes in your release branch for a patch release, **you will have to cherry-pick the RELEASENOTES only into your master branch as well (stage only the appropriate chunk).**
> 
> ```
> git checkout master
> git checkout -p RELEASENOTES_COMMIT_SHA_HASH
> ```
> For iOS, you may have to cherry-pick the commit for Added X.Y.Z to CDVAvailability.h (via coho) into the master branch as well.

Especially note the bolded line. Master should contain the release notes as well. It need to be cherry picked from the release branch.

https://github.com/apache/cordova-coho/blob/master/docs/platforms-release-process.md#special-case-1-release-notes-in-release-branch-for-patch-release

**Comment by janpio** [comment]
Yeah, I think the way @brodybits reads this is that this should happen when you do the next release from `master` - which I agree is one possible interpretation of how it is written. 

But I think it was probably meant like you interpret it: After having added the release notes to the release branch, also cherry pick them over to `master` and then continue with the release in the release bracnh.

Does this make sense? If so, we should probably clarify this section to make this clearer.

I think in general, users would expect the release notes in `master` to always contain all releases, because this is where you go to learn more about the releases - not in the release branch (which 95% of users probably don't even know about - which is totally fine).
