### ISSUE TITLE
cordova-plugin-browsertab conflict with cordova android@7.1.3 and 7.1.4

### ISSUE THREAD

**Issue by cjohn001** [apache/cordova-android#640]
The title says everything. 

Replicate by creating a new project and adding 

```
 <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
  <plugin name="cordova-plugin-browsertab" spec="^0.2.0" />
```

I get the following error. Maybe someone has an idea for a workaround. I tried setting the min version to 19 as mentioned in the error message. But without success.

--------------------------------------
This did not work:
```
    <platform name="android">
        <preference name="android-minSdkVersion" value="19" />
        <preference name="android-targetSdkVersion" value="27" />
    </platform>

```

--------------------------------------
Error message:
```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:CordovaLib] /Users/cjohn/Entwicklung/IMS/CordovaLogin/platforms/android/CordovaLib/build/intermediates/manifests/full/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
c

**Comment by cjohn001** [comment]
Hello Brody,
thanks for the analysis. However, the decision not to fix it, is somehow a pitty. Seems like this plugin is required to enable SSO in Cordova, like described here 

https://www.youtube.com/watch?v=HKulxXDYJSs&feature=youtu.be

I do not have the java background to maintain the plugin. So you say it is a bug in the plugin? The BrowserTab.gradle file which you reference says in the checkin comment, that it was a workaround regarding  a gradle issue with cordova. To me it is not clear what would have to be done to fix the issue here. 
As far as I understood the discussion in #508, even though it shows not the resulting decision, the min version should be set via config.xml. In that case, would the fix than be simple as removing the BrowserTab.gradle file from the plugin? I assume, this would require, that the fix the file made in the past was previously in the meantime fixed in Cordova. Would be great if you could give me a hint on that, as I am currently stuck with Cordova 7.1.2 due to the issue.

Best regards
 Christoph

**Comment by brodybits** [comment]
Workaround is given by @ashvinmay in <https://github.com/google/cordova-plugin-browsertab/issues/17#issuecomment-344198360>, I just tested it myself:

> For quick fix, create build-extras.gradle with following
> def minSdkVersion = 21
> cdvMinSdkVersion = minSdkVersion
> ext.cdvMinSdkVersion = minSdkVersion
> 
> Copy this file to /platforms/android/ folder. You can either do it manually or can write a hook

I really hope someone will update and fix [`cordova-plugin-browsertab`](https://www.npmjs.com/package/cordova-plugin-browsertab).

**Comment by cjohn001** [comment]
Hello Brody,
thanks, the fix did work.

Best regards,
 Christoph

**Comment by brodybits** [comment]
Thanks. As I said before I really hope someone will fix the problem in [`cordova-plugin-browsertab`](https://www.npmjs.com/package/cordova-plugin-browsertab). It is not so good that any of us Cordova maintainers have to provide support due to this kind of abandoned projects.

**Comment by Icety** [comment]
When you need the fix to be applied automatically the following hook will fix it for you:

Add to config.xml: 
``` 
<platform name="android">
<hook src="scripts/afterAddBrowserTabPlugin.js" type="after_plugin_add" />
</platform> 
```

create file: cordova/scripts/afterAddBrowserTabPlugin.js
```nodejs
const fs = require('fs');

module.exports = function(ctx) {
    var Q = ctx.requireCordovaModule('q');
    var deferral = new Q.defer();

    if (ctx.opts.plugins.includes('cordova-plugin-browsertab')) {

        let file = ctx.opts.projectRoot + '/plugins/cordova-plugin-browsertab/src/android/BrowserTab.gradle';
        console.log(file);

        checkForFix(file);
    }

    return deferral.promise;
};

function checkForFix(file) {
    fs.readFile(file, function read(err, data) {
        if (err) {
            throw err;
        }

        if (!data.includes('minSdkFix')) {
            writeFix(file);
        }
    });
}

function writeFix(file) {
    fs.appendFile(file, '\n\n// minSdkFix\nminSdkVersion = 21;\ncdvMinSdkVersion = minSdkVersion;\n' +
        'ext.cdvMinSdkVersion = minSdkVersion;', function(err) {
        if (err) {
            console.log('Adding minSdkFix failed: ' + err);
        }
        console.log("Writing success!");
    });
} 
```

**Comment by cjohn001** [comment]
Hello Icety, 
thanks for your help. The fix from brodybits did the trick for me already, but the solution you described is probably the better one as it does not need changes in the platform folder.

Best regards,
 Christoph
