### ISSUE TITLE
input=file camera photo

### ISSUE THREAD

**Issue by superainovacoes** [apache/cordova-android#643]
Hi guys, I don't is this is the right place or is related to "cordova-plugin-inappbrowser" ( https://github.com/apache/cordova-plugin-inappbrowser/issues/328#issuecomment-456472870 ).

I have a website that uses:
```
<input type="file" accept="image/*" capture="camera" />
```
Compiling the cordova app to android/ios the code works when using direct from the html hosted at the cordova app, but when i open an popup (using inappbrowser) the same input doesn't open the camera on android, ios works fine.

**Comment by Aarbel** [comment]
Same issue there, @superainovacoes have you found a workaround ?

**Comment by jcesarmobile** [comment]
if it only happens in InAppBrowser, should be fixed in InAppBrowser
