### ISSUE TITLE
Not working svg in background-image

### ISSUE THREAD

**Issue by maxxam11** [apache/cordova-android#645]
Hello.
After updated webview to Chrome 72 (android 9) in cordova app stopped working svg in background-image (css):

`.my-class { background-image: url('data:image/svg+xml;utf8,<svg fill="#00bcd4" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M14 17H4v2h10v-2zm6-8H4v2h16V9zM4 15h16v-2H4v2zM4 5v2h16V5H4z"></path><path d="M0 0h24v24H0z" fill="none"></path></svg>'); }`

But it working in browser itself.

**Comment by dpogue** [comment]
Try replacing `fill="#00bcd4"` with `fill="%2300bcd4"`.

This is not a Cordova bug, but an intentional change to Chrome:
https://www.chromestatus.com/features/5656049583390720
https://bugs.chromium.org/p/chromium/issues/detail?id=911973

**Comment by maxxam11** [comment]
Thank you!
