### ISSUE TITLE
Is Cordova Android 64-bit?

### ISSUE THREAD

**Issue by jacobweber** [apache/cordova-android#647]
Google is [warning developers](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) that starting Aug 1 2019, all apps must be 64-bit.

Does Cordova already support this? If so, in what version?

**Comment by brodybits** [comment]
> Google is [warning developers](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) that starting Aug 1 2019, all apps must be 64-bit.

<https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html>

Cordova itself fulfills the requirement since it include any NDK ("native") *.so library files, NDK jar files, or dependencies using NDK libraries in any form.

From a quick scan of all plugins maintained by Apache Cordova I could not find any plugins using NDK libraries in any form.

Thanks for asking.

**Comment by ASHBAW** [comment]
Hi I am using cordova-sqlite-storage in one of my applications.  After building my application (using ionic) I see the following associated .so libraries:
```
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/armeabi-v7a/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/x86/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/arm64-v8a/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/armeabi/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/release/0/lib/x86_64/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi-v7a/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/x86/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/arm64-v8a/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libsqlc-native-driver.so
/platforms/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/x86_64/libsqlc-native-driver.so
```
I also use the cordova-plugin-globalization in another app and I see the following:

```
/plugins/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
/plugins/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
/node_modules/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
/node_modules/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
```
I know these are blackberry but still .so.

Should these .so be removed from each plugin?

Thanks

**Comment by rodrigograca31** [comment]
> Cordova itself fulfills the requirement since it include any NDK ("native") *.so library files, NDK jar files, or dependencies using NDK libraries in any form.

`it include` ? I think you meant `it doesn't include` am I right?
Please fix your reply...

**Comment by brodybits** [comment]
> I think you meant `it doesn't include` am I right?

Yes

> Please fix your reply...

Done. My bad. Thanks!

**Comment by brodybits** [comment]
To address a couple other questions:

> Hi I am using `cordova-sqlite-storage` in one of my applications. After building my application (using ionic) I see the following associated .so libraries:
> [...]

`cordova-sqlite-storage` is an external plugin, so let's please keep the discussion there.

> I also use the cordova-plugin-globalization in another app and I see the following:
> 
> ```
> /plugins/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
> /plugins/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
> /node_modules/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
> /node_modules/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
> ```
> I know these are blackberry but still .so.

Since that is on a different platform, it would not be an issue on Android.

**Comment by suhail339** [comment]
https://www.npmjs.com/package/cordova-plugin-build-architecture solved my problem

**Comment by pratikq23** [comment]
> https://www.npmjs.com/package/cordova-plugin-build-architecture solved my problem
I use this plugin in my project and created the apk, But when i unzip it, i can't see the lib/arm64-v8a &  lib/x86_64. 
Because according to this https://developer.android.com/distribute/best-practices/develop/64-bit on apk unzip it show these foloders.

**Comment by whoamien** [comment]
After build, I found that there is still one so file 
./cordova/node_modules/cordova-android/spec/fixtures/org.test.plugins.dummyplugin/src/android/jniLibs/x86/libnative.so

where this file come from?

**Comment by dpogue** [comment]
That file is for unit tests within the cordova-android project. It is not part of your app's project.

**Comment by jcesarmobile** [comment]
Closing as it’s been explained.
