### ISSUE TITLE
Google Play Console targetSdkVersion requirement

### ISSUE THREAD

**Issue by EiyuuZack** [apache/cordova-android#649]
Greetings,

According to this [blog post](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html) Google will require Android apps to target newer SDK versions:

> In order to provide users with the best Android experience possible, the Google Play Console will require that apps target a recent API level:
> 
> - **August 2018**: New apps required to target API level 26 (Android 8.0) or higher.
> - **November 2018**: Updates to existing apps required to target API level 26 or higher.
> - **2019 onwards**: Each year the `targetSdkVersion` requirement will advance. Within one year following each Android dessert release, new apps and app updates will need to target the corresponding API level or higher.

Regarding the advancing requirement part, I have an Android app built using Cordova targeting API 26 (Android 8.1). My question is: **must I target API 28 (Android 9.0) this year or will API 27 (Android 8.1) suffice?**

I could not find anything on this Cordova-wise (forgive me if I missed some obvious place) and given that Cordova **only supports up to API 27 (Android 8.1)** as of today, I would like to know if I should be concerned in order to make the proper adjustments to my team's roadmap.

Much appreciated.

**Comment by JPAlfa** [comment]
Based on what I read you will have to upgrade to API 28 until November 1st, or will get an error at Play Console and will be forbidden to releasing your app. You can solve this by updating your cordova-android to version 8.0.0, as this version supports Gradle 4.10.3, which supports Android SDK 28. 

[Instructions to update cordova-android](https://cordova.apache.org/announcements/2019/02/16/cordova-android-release-8.0.0.html)

**Comment by breautek** [comment]
Closing this issue cause I think @JPAlfa has answered this clearly. If there are any other questions, feel free to raise a new issue.

**Comment by leandrocastro** [comment]
~/Library/Android/sdk/tools/bin
./sdkmanager --licenses

just this
