### ISSUE TITLE
prepare.js considers ic_launcher_background.xml,ic_launcher_foreground.xml in mipmap but android studio puts it in drawable

### ISSUE THREAD

**Issue by guylando** [apache/cordova-android#652]
https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/prepare.js
considers ic_launcher_background.xml and ic_launcher_foreground.xml in mipmap
but android studio images assets studio puts them in:
drawable-v24\ic_launcher_background.xml
drawable\ic_launcher_foreground.xml

**Comment by breautek** [comment]
Please use the issue template. It's not clear what the issue is, or why this is an issue.
