### ISSUE TITLE
Gradle default values ignored

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#658]
From the default values in <https://github.com/apache/cordova-android/blob/a6f30b6977156df4bb2e3a488178ac05a96f0671/bin/templates/project/build.gradle#L43-L46>

the following default values seem to be ignored:

- `defaultBuildToolsVersion`
- `defaultTargetSdkVersion`
- `defaultCompileSdkVersion`

The default values were introduced in f790aeb8f677eb047ce6e82fceaeb814cfc9d4fc (part of PR #389), where `defaultTargetSdkVersion` was introduced but never used.

The code that uses `defaultBuildToolsVersion` and `defaultCompileSdkVersion` was commented out in c74192d578e647a8386ac8663d6c99521f28b110 (also part of PR #389).

I discovered this issue through investigation of code related to issue #657 & PR #655.

**Comment by erisu** [comment]
Closing ticket as the code in question had been removed in Cordova-Android 10.
