### ISSUE TITLE
Does not seem to enforce the default build tools version

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#659]
Related to issue #658: in case the user does not explicitly configure `cdvBuildToolsVersion`, no default build tools version such as `defaultBuildToolsVersion` (`"28.0.3"`) is enforced in the following lines: <https://github.com/apache/cordova-android/blob/a6f30b6977156df4bb2e3a488178ac05a96f0671/bin/templates/project/app/build.gradle#L110-L113>

**Comment by erisu** [comment]
I am closing this ticket as resolved in Cordova-Android 10.

The referenced code was removed.

During the refactoring of the Gradle scripts, the default build tools version is set first. Next, it will attempt to find the latest installed build tools while using the default as the minimum required version. If the latest installed version is lower than the minimum, the build process will halt and the user is notified that they must install the correct version.
