### ISSUE TITLE
Remove old Eclipse project artifacts

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#661]
as suggested by @dpogue in <https://github.com/dpogue/cordova-android/commit/d5f888b81c947e984cc0101862770a8113bc38fb> (comes before <https://github.com/dpogue/cordova-android/commit/d18f8d18a10a50084130300d5edbb84901b59707> as suggested by @dpogue in review of PR #655)

this includes removing project.properties files (issue #660)

**Comment by breautek** [comment]
I think this issue might have been resolved by https://github.com/apache/cordova-android/pull/831

**Comment by erisu** [comment]
Closing as resolved in: https://github.com/apache/cordova-android/pull/1272
