### ISSUE TITLE
Android build failes looking from common.jar

### ISSUE THREAD

**Issue by newuser44** [apache/cordova-android#665]
Not really sure what is causing this. I try to build a dev android version

ionic cordova build android 

I expect that to build an android version

I’m getting this error.

> FAILURE:
> Build failed with an exception.
> 
> What went wrong:
> A problem occurred configuring root project ‘android’.
> 
> Could not find common.jar (android.arch.lifecycle:common:1.1.0).
> 
> Searched in the following locations:
> 
>   https://jcenter.bintray.com/android/arch/lifecycle/common/1.1.0/common-1.1.0.jar

The only thing I have tried it remove android and add android back (Android 6.3.0).
Same thing. 
I try to go to that path that its looking for that file and it doesn't exist anymore.   

I don't really feel this is a Cordova problem, but not sure what is wrong.

**Comment by newuser44** [comment]
ionic info dump. 

cli packages: (/home/dev/.npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.16.0
    npm               : 3.10.10
    OS                : Linux 3.13

Environment Variables:

    ANDROID_HOME : /home/dev/Android/Sdk

Misc:

    backend : legacy

**Comment by janpio** [comment]
> Cordova Platforms  : android 6.3.0

Your Cordova tooling seems to be out of date, which might be causing all kinds of problems. 
You can read about how to figure out the current Cordova versions and how to update CLI, platforms and plugins here: https://ionic.zone/cordova/update

**Comment by newuser44** [comment]
Thanks for the response.  Yes I know my android version is behind.  This worked yesterday.  
I can't seem to get Android 6.4.0 to work with the Firebase plugin for our analytics.  it won't build.  (Could be android sdk side).  
Have not tried going up to Android 7, because it seems like it does not support versions of android less then 4.4  which we have customers still on that.

**Comment by breautek** [comment]
Closing as this is likely an out-dated issue. We no longer support anything older than `cordova-android@8.x` due to the google requirement of supporting target SDK >= 28.

My advice is to ensure that all your cordova & android SDK tooling is up to date. If the issue persists, I invite you to our [slack](http://slack.cordova.io/) which is a more appropriate place for support-style questions.
