### ISSUE TITLE
Android 8.0.0 SystemCookieManager.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-android#674]
# Bug Report

## Problem
```
Error: D:\[PROJECT_NAME]\platforms\android\gradlew: Command failed with exit code 1 Error output:
Note: D:\[PROJECT_NAME]\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java uses or overrides a deprecated API.
```

Also getting this
```
Task :app:fabricGenerateResourcesDebug FAILED
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null.
Check the Crashlytics plugin to make sure that the application has been added successfully!
```

It all disappears doing
`cordova platform rm android`
`cordova platform add android@7.1.4`

### Version information
Cordova 7.1
Cordova Android 8.0.0

**Comment by janpio** [comment]
> Task :app:fabricGenerateResourcesDebug FAILED
> ERROR - Crashlytics Developer Tools error.
> java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null.
> Check the Crashlytics plugin to make sure that the application has been added successfully!

This is an implementation error on your side. It seems you are using a plugin for Crashlytics and the plugin is not properly configured. If this is not the case, please direct your question at the author of this plugin.

> Error: D:\[PROJECT_NAME]\platforms\android\gradlew: Command failed with exit code 1 Error output:
> Note: D:\[PROJECT_NAME]\platforms\android\CordovaLib\src\org\apache\cordova\engine\SystemCookieManager.java uses or overrides a deprecated API.

Are those two things related? It's not really possible to tell from what you posted. Using a deprecated API is by itself not a problem. It just means that the API has the flag "deprecated" and might be going away in the future. It is perfectly fine to use right now.

Is your build problem reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by globules-io** [comment]
I do not use the Crashlytics, so I don't know why it shows.
Like I said, it works perfectly with 7.1.4.

**Comment by globules-io** [comment]
Ok it seems like this comes from cordova-plugin-firebase, closing

**Comment by GuiF007** [comment]
How did you solve it ?

**Comment by globules-io** [comment]
@GuiF007 cordova platform add android@7.1.4

**Comment by GuiF007** [comment]
Ok, just downgrading the android cordova plugin, as I did too...
