### ISSUE TITLE
Would like to be able to filter files copied from www directory.

### ISSUE THREAD

**Issue by wifisher** [apache/cordova-android#684]
# Feature Request

## Motivation Behind Feature

Currently, Cordova will copy all files from the project www folder to the assets folder during the prepare process. However, the project www folder may contain files that should not be part of the built application and as such, they should not be copied.

## Feature Description

It would be nice if Cordova could use a list of excludes to avoid copying unneeded files. I would suggest using a preference such as wwwExcludes. This preference would contain a list of glob strings that would be used to filter the list of files copied to the assets folder during the prepare process.

## Alternatives or Workarounds

The only current alternative is to use an after_prepare hook to remove the unneeded files. 

In my case, Cordova is copying VCS files (ie from .git or .hg) which can be quite large.

**Comment by wifisher** [comment]
Here is an example of the wwwExclude preference usage:

`<preference name="wwwExcludes" value=".git*, .hg*, artwork, */*.orig" />`

**Comment by jcesarmobile** [comment]
Android has its own mechanism to not copy those files to the resulting app

ignoreAssetsPattern

https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.AaptOptions.html

Those are the ones ignored by default

 "!.svn:!.git:!.ds_store:!*.scc:.*:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"

https://android.googlesource.com/platform/frameworks/base/+/b41af58f49d371cedf041443d20a1893f7f6c840/tools/aapt/AaptAssets.cpp#60
