### ISSUE TITLE
Web Worker in cordova

### ISSUE THREAD

**Issue by josiahbryan** [apache/cordova-android#688]
# Bug Report

## Problem

I can't seem to get my cordova app to execute even a simple web worker, even though the same web worker works in the Chrome browser on the same device. 

(Android device, Google Pixel 3, running Android 9, latest patch level. The app was built in PhoneGap build with `cli-8.0.0`)

Setup in the main thread:
```
const worker = new Worker('/fake.worker.js');
worker.postMessage(1337);
worker.addEventListener('message', event => console.log("[myWorker] received event from myWorker:", event));
```

And the `/fake.worker.js` file is just this, no transpilation:
```
/* eslint-disable no-restricted-globals */
console.log("fake.worker booted");
self.addEventListener("message", startCounter);

function startCounter(event) {
    console.log(event.data, self)
	let initial = event.data;
	console.log("fake.worker counter started:", initial);
	
    setInterval(() => this.postMessage(initial++), 1000);
}
```

Bottom line, the console never shows anything from the worker, either from the main thread or from the worker thread's `console.log` statements. 

While attached to the device and remote debugging, I can see that `('Worker' in window) === true` and that the Network tab of the remote console that the `fake.worker.js` file is indeed loaded. (Serving the file via `ngrok` from my development laptop - after connecting to the remote console, I changed the location of the web view with `window.location.href = 'https://....ngrok...'`.) 

_Note_: I also tried including the Web Worker via an inline blob (`worker-loader` for webpack automated this for me, but the concept is shown at https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Embedded_workers) - and when "embedded", the worker never booted.

### What is expected to happen?

Web Worker should boot and at minimum, console should show: `fake.worker booted`

### What does actually happen?

Nothing, no errors, nothing. Valid Worker object is created, but no events and no console output happens.

## Information

* N/A

### Command or Code

* Code above

### Environment, Platform, Device

* Android 9.0, latest patch (March 5)
* PhoneGap `cli-8.0.0`
* Built with PhoneGap build

### Version information

* PhoneGap `cli-8.0.0` (android ver 7.0.0)
* Android 9.0
* No plugins relevant

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version **NB cannot use >`cli-8.0.0` due to plugin compat**
- [x] I included all the necessary information above

**Comment by d410** [comment]
I suspect your issue may just be the simple issue of security restrictions on web workers. Connect your Cordova Application to your USB cable to your computer and Open Chrome for Desktop. Go to DevTools in Desktop Chrome and select Remote Devices. Find the webview running on your Android device and select > Inspect. 

Tell us what the console is saying.

Here is the solution.

Firstly, ensure that your worker is not being blocked by CORS. Chrome Mobile does not allow workers to execute if they are accessed through the file:// protocol or the origin of the request to the file is of origin null. You can bypass this by using a Blob URL encoding scheme. These are called inline workers.

See here:

https://stackoverflow.com/questions/5408406/web-workers-without-a-separate-javascript-file

Create an inline function version of your worker script. 

> function() inlineWorker()
> {
>  /* eslint-disable no-restricted-globals */
> console.log("fake.worker booted");
> self.addEventListener("message", startCounter);
> 
> function startCounter(event) {
>     console.log(event.data, self)
> 	let initial = event.data;
> 	console.log("fake.worker counter started:", initial);
> 	
>     setInterval(() => this.postMessage(initial++), 1000);
> }
> }

Add this to your main Javascript file and call it as a Blob URL when you create the worker within that same file. This will bypass the security restrictions with using external files and will let you use only one file for a worker.

`   const worker = new Worker(URL.createObjectURL(new Blob(["("+inlineWorker.toString()+")()"], {type: 'text/javascript'})));`
 

After you've reconstructed your worker to work inline, you should add response logic for your worker within the worker itself using the onmessage event callback.

Try adding an onmessage function callback to your inline worker function.

> onmessage = function(e) {
> console.log('Message received from main script ' + JSON.stringify(e.data));
> }

Now lets see the final code.

> function() inlineWorker()
> {
>  /* eslint-disable no-restricted-globals */
> console.log("fake.worker booted");
> self.addEventListener("message", startCounter);
> 
> function startCounter(event) {
>     console.log(event.data, self)
> 	let initial = event.data;
> 	console.log("fake.worker counter started:", initial);
> 	
>     setInterval(() => this.postMessage(initial++), 1000);
> }
> onmessage = function(e) {
> console.log('Message received from main script ' + JSON.stringify(e.data));
> }
> }

Good luck!

**Comment by tryhardest** [comment]
@d410 you are the bomb thanks best explanation ever. Quick follow up have you ever got service workers going on Cordova cross platform? Localhost forbids it on Android but maybe there a hack to run localhost plugin or something. Want to see if you ever did it as I've never seen anyone who has on Cordova.

**Comment by tudordumitriu** [comment]
Great solution, thanks @d410  I can confirm it works on iOS, Android and web as well.

**Comment by breautek** [comment]
Closing this due to lack of response from the OP. Solution is posted above.

**Comment by PreciousBiscuit** [comment]
Hi, I had the same issue as OP and I tried for a week to get it working with different solutions without success. However I was able to find out the reason for it.
The worker did not work when I was inspecting the application through chrome devtools. When I closed chrome the worker started working again.
