### ISSUE TITLE
Snyk report: High severity vulnerability found in shelljs -> Command Injection

### ISSUE THREAD

**Issue by gabriele-sacchi** [apache/cordova-android#696]
# Bug Report

## Problem

Snyk (https://www.npmjs.com/package/snyk) querying a database of known vulnerabilities revealed this critical security vulnerability:

```
✗ High severity vulnerability found in shelljs
  Description: Command Injection
  Info: https://snyk.io/vuln/npm:shelljs:20140723
  Introduced through: cordova-android@8.0.0, cordova-ios@5.0.0, cordova-custom-config@5.0.3
  From: cordova-android@8.0.0 > shelljs@0.5.3
  From: cordova-ios@5.0.0 > shelljs@0.5.3
  From: cordova-custom-config@5.0.3 > shelljs@0.7.8
```

### What is expected to happen?
No security vulnerabilities should be found by Snyk

### What does actually happen?
High severity security vulnerability found by Snyk

## Information

**Steps to reproduce:**
- Add latest version of cordova-ios to a package.json file
- Install `npm snyk`
- Run `snyk test`

### Command or Code
See above

### Environment, Platform, Device
Any

### Version information

This is the case both for
`"cordova-android": "^7.0.0",`
and
`"cordova-android": "^8.0.0",`.

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Shelljs was removed by https://github.com/apache/cordova-android/pull/842
