### ISSUE TITLE
Cordova build android error ocurred 7.1.4

### ISSUE THREAD

**Issue by adriansaenz** [apache/cordova-android#700]
# Bug Report

## Problem
When you run 'cordova build android' the console output build succesful but the process finish with error code 1, so the build is finish correctly but the error code returns that build fail.

### What is expected to happen?
cordova build process will not return any error code when build is succesful

### What does actually happen?
cordova build returns an error code even the build is succesful

## Information
Running 'cordova build android --verbose' with cordova-android 7.1.4. The output is the following.

![error-verbose](https://user-images.githubusercontent.com/22059052/55074393-7762ff00-5090-11e9-8e45-5be8387e92d0.PNG)

### Command or Code
cordova-android version 7.1.4 run 'cordova build android'

### Environment, Platform, Device
Using windows and build to android device.

### Version information
Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\asaenz\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : not available

System:

   NodeJS : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.1.0
   OS     : Windows 10

## Checklist

- [X] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by janpio** [comment]
The screenshot you posted is not the ouput of running `cordova build android --verbose` but probably something from Ionic CLI?

Your "Version information" also tells us:

> cordova (Cordova CLI) : not installed

Huh?

**Comment by adriansaenz** [comment]
For cordova-android 6.3.0, the same process and steps, the build is succesful and the process does not return any error code. On the other hand, for any reason cordova cli is not displayed but I'm using cordova 8.0.0.

**Comment by breautek** [comment]
Closing because 7.1.4 is no longer supported. If this issue occurs on cordova-android@8.1.0, please do open a new issue. If ionic provides a way to pass down the `--verbose` flag down to the cordova command, that verbose output would be helpful.

FYI, the no scripts found messages are not part of the error. They are simply stating that it found no hook scripts.
