### ISSUE TITLE
Project cannot name cannot start with a number

### ISSUE THREAD

**Issue by fknbwdwn** [apache/cordova-android#701]
Hello everyone,

I already commented here: https://github.com/apache/cordova-android/issues/584, however I was instructed to open a new issue to ask for support - so here we are.

I've adopted this project from someone else, so my knowledge of Cordova isn't all that great, although I have spent considerable amounts of time in the documentation to understand what I am supporting. Anyway, as described in my other comment, here is my issue:

> I am really struggling with this currently. I need to build some apps whose names begin with a number - however when I run the Cordova build command it seems to try and name my project after whatever is in the name field in my config.xml. If I change this to not be a string beginning with a number, it also renames the app this as well which I need to figure out how to avoid.
> 
> I should mention I am using this in a pipeline so manual intervention isn't necessarily ideal. Is there anything I can change in config.xml or anywhere else that will allow me to specify a project name that doesn't begin with a number, but an app name that does? I tried using "<name short=..." to set the name as one beginning with a number - am I on the right track? Am I missing something?
> 
> Please help me!

Thanks in advance!

**Comment by rrlevy** [comment]
We are having the same problem here. Our app name at config.xml has always started with a number, but now we can't use it anymore and it requires manual intervention at the pipeline

**Comment by jjvillavicencio** [comment]
I have the same problem, any solution?

**Comment by MrHakala** [comment]
For anyone stuck in Ionic's Appflow build environment (or otherwise) try to downgrade to cordova@8.0.0 (not 8.1.2 as mention [here](https://ionic.zendesk.com/hc/en-us/articles/360021400494-Package-build-fails-with-error-CordovaError-Using-requireCordovaModule-))

Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.4

**Comment by fknbwdwn** [comment]
I provided detailed instructions on my workaround here in the comments:

https://github.com/apache/cordova-android/issues/584

**Comment by pflausino** [comment]
same problem yet ...

**Comment by crabbydavis** [comment]
Problem still exists with cordova-android 8.1.0
