### ISSUE TITLE
Build is broken when using edit-config for "android:" attribute

### ISSUE THREAD

**Issue by distinctdan** [apache/cordova-android#702]
# Bug Report

I'm using an `edit-config` block to set the orientation of my app. It looks like this:
```
<edit-config file="AndroidManifest.xml"
             target="/manifest/application/activity[@android:name='MainActivity']"
             mode="merge">
    <activity android:screenOrientation="landscape"></activity>
</edit-config>
```
It edits `AndroidManifest` correctly, but building produces the error:
```
Android resource compilation failed
/orbs/cordova/platforms/android/app/src/main/res/xml/config.xml:51: error: unbound prefix.
```

The issue is that cordova or something isn't adding the android namespace to the outputted widget, so the `android:` prefix is causing it to error. I've even tried adding the namespace to the widget manually, but it gets overwritten. It's the same problem described in this thread on the custom-config plugin: https://github.com/dpa99c/cordova-custom-config/issues/24. 

### Version information
Cordova CLI: 9.0.0
Cordova-android: 8.0.0
Cordova-ios: 5.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
You'll need to add `xmlns:android` to the`widget` tag in your project's top-level config.xml

**Comment by distinctdan** [comment]
Thanks for the help, I hadn't realized the widget in `cordova/config.xml` got copied to the android output. For future readers, the full attribute to add is `xmlns:android="http://schemas.android.com/apk/res/android"`

**Comment by FreddyCrugger** [comment]
> Thanks for the help, I hadn't realized the widget in `cordova/config.xml` got copied to the android output. For future readers, the full attribute to add is `xmlns:android="http://schemas.android.com/apk/res/android"`

Thank you so much! Very helpful.

**Comment by gregor-srdic** [comment]
> xmlns:android

omg, thanks :)
