### ISSUE TITLE
Crash navigating to chrome-error://webdata

### ISSUE THREAD

**Issue by zznidar** [apache/cordova-android#703]
# Bug Report

## Problem
A Cordova Android app, built with PhoneGap, crashes when it is navigated to `chrome-error://webdata` either inside an iFrame or directly.

### What is expected to happen?
App should not crash.
This is held up by the fact that Chrome on Windows throws an exception: `Not allowed to load local resource: chrome-error://webdata/`. Same exception is thrown when debugging an app made in Android Studio with WebView.  

### What does actually happen?
App crashes when navigating to url chrome-error://webdata either inside an iFrame or directly.

## Information

Apparently it only crashes on Android 8 or newer.
### Steps to reproduce
1. Download [the .apk file](https://github.com/zznidar/bugreports/raw/master/Cordova/Crash%20on%20visiting%20chrome-error%20webdata/apk/iFramecrasher-debug.3519194.1.apk) and install it.
2. Open the app.
3. Press one of the "*Will this crash it?*" links.

### Command or Code

The sample .apk – you can also build it manually, here are [Source files](https://github.com/zznidar/bugreports/tree/master/Cordova/Crash%20on%20visiting%20chrome-error%20webdata/www)

### Environment, Platform, Device

- Pocophone f1, Android 8.1.0
- Samsung Galaxy S8+, Android 9
The tested devices running Android 7 or lower did not crash.
- Phonegap `cli-6.5.0`, `cli-8.1.1`

### Version information

- Phonegap `cli-6.5.0` (Android ver 6.1.2), `cli-8.1.1` (Android ver 7.1.2)
- Android 8.1.0, Android 9
- No plugins needed

[Full list of tested devices](https://github.com/zznidar/bugreports/tree/master/Cordova/Crash%20on%20visiting%20chrome-error%20webdata#tested-devices-affected-written-in-bold)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version *(The highest supported by PhoneGap)*
- [x] I included all the necessary information above

**Comment by breautek** [comment]
In your `config.xml` you appear to be missing the whitelist tags to allow `chrome-error:`


https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#navigation-whitelist

**Comment by breautek** [comment]
Closing due to lack of response. Most likely solution posted above.
