### ISSUE TITLE
edit-config isn't working when setting "android:screenOrientation"

### ISSUE THREAD

**Issue by distinctdan** [apache/cordova-android#704]
# Bug Report
I'm trying to set the orientation of my tilt-based app to be only landscape (and not reverse-landscape. Cordova unfortunately doesn't support this out of the box, so I'm using an edit config to edit the AndroidManifest.xml. However, it isn't working. It adds an `edit-config` entry under `res/xml/config.xml`, but it doesn't actually change `AndroidManifest.xml`. I'm not sure if it's supposed to or not. Regardless, when I run my app, it's still in portrait mode.

Here is my main config.xml for the edit-config:
```
<platform name="android">
        
    <edit-config file="AndroidManifest.xml"
                 target="/manifest/application/activity[@android:name='MainActivity']"
                 mode="merge">
        <activity android:screenOrientation="landscape"></activity>
    </edit-config>
</platform>
```

### Version information

Cordova CLI: 9.0.0
Cordova-android: 8.0.0
Cordova-ios: 5.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
It's on my list to look into what's going on here, since this is affecting one of my projects as well, but it's not clear when I'll get to it.

Of note, the edit-config contents are not ending up in the platforms/android/android.json file

**Comment by distinctdan** [comment]
Great, thanks for looking into it.

**Comment by dpogue** [comment]
This seems to be caused by changed made in https://github.com/apache/cordova-common/pull/24

The `config-file`/`edit-config` directives from config.xml are being considered `unusedConfigMunge` when other plugins are installed with their own `config-file`/`edit-config` directives, and then it's removed from the resulting files.
