### ISSUE TITLE
cordova.gradle does not compare versions properly.

### ISSUE THREAD

**Issue by wmramazan** [apache/cordova-android#708]
# Bug Report

## Problem
Some of Android SDK Build-Tools versions have a tag of the release life cycle like "29.0.0-rc1". But cordova.gradle cannot compare these versions. This might be a problem for beginner developers because Android Studio can recommend the SDK version which is the release candidate.

### What is expected to happen?
Cordova-Android should compare all SDK Build-Tools versions without any problem.

### What does actually happen?
It throws RuntimeException when there is only one installed SDK Build-Tools whose version has a tag of the release life cycle.

### Version information
cordova-android: 8.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
What is the status of this issue?
