### ISSUE TITLE
The HTML <datalist> element isn't working on Android 8 or higher 

### ISSUE THREAD

**Issue by gengns** [apache/cordova-android#711]
# Bug Report
HTML **datalist** element is not working since Android 8. However, it's working with previous versions.
 
## Problem
If I try to open or type in an HTML **datalist** nothing happens. It behaves like an HTML input. So, you cannot list your options, search or autocomplete.

### What is expected to happen?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

## Information
If you open any web with an HTML **datalist** on your phone's browser, it behaves as expected.
HTML **datalist** has been working for a long time. 
At first we thought about an Android issue but it's working outside of Cordova.

### Command or Code
Add this to the default Cordova example and open it on Android 8 or higher.
```
<div class="app">
  <datalist id="ice-cream-flavors">
    <option value="Chocolate">
    <option value="Coconut">
    <option value="Vanilla">
  </datalist>
</div>
```
### Environment, Platform, Device
Android version: 8.0.0
WebView implementation: Chrome 73.0.3683.90

### Version information
cordova-lib@9.0.0 with:
  cordova-common@3.1.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: linux
  Node: v11.9.0
  npm: 6.5.0

Plugins:
  cordova-plugin-whitelist

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
Your example code shouldn't render anything.
```html
<div class="app">
  <datalist id="ice-cream-flavors">
    <option value="Chocolate">
    <option value="Coconut">
    <option value="Vanilla">
  </datalist>
</div>
```

You need to attach the datalist to an input element like this:
```html
<input type="text" list="ice-cream-flavors">
<datalist id="ice-cream-flavors">
    <option value="Chocolate">
    <option value="Coconut">
    <option value="Vanilla">
</datalist>
```

In any case, this is handled by the browser engine, not by Cordova.

**Comment by gengns** [comment]
Sorry, I don't know why I didn't completely copy the **datalist** example from MDN, I pasted it again in my post. If Cordova is not responsible, why it's working on the browser and not when I use Cordova?

**Comment by dpogue** [comment]
Chrome on Android and the Chrome-powered System WebView have slightly different features enabled :(

It's possible that you're running into this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=662828
Is your System WebView up to date?

**Comment by breautek** [comment]
I ran a quick test on my device and the datalist popup doesn't show, but it does show on the Chrome Browser app.

I used:
cordova-cli 8.1.2
cordova-android@8

My device is Samsung Galaxy Note 9
Android 9
System webview 71.0.3578.99

Not blocked by this but I thought to share some details. The system webview is a couple of versions behind Chromium but my device has no available updates currently.

**Comment by gengns** [comment]
My System WebView is up to date. Version 73.0.3683.90
![image](https://user-images.githubusercontent.com/13253926/55444808-7cf0a580-55b8-11e9-893b-554d3cc24c9b.png)

I'm testing in:
1. BQ Aquaris C with Android 7 (working)
2. Samsung Galaxy A5 2017 with Android 8 (not working)
3. Xiaomi Mi with Android 8 and with Android 9 (not working)

In all of them works on the browser and with Cordova for Android < 8

I tested with:
* cordova-cli 8.1.2
* cordova-android@8
* cordova-cli 9.0.0
* cordova-android@8
 
Thank you @dpogue and @breautek

**Comment by gengns** [comment]
Thank you @dpogue and @breautek :) this issue has been confirmed as a new Chromium bug and now they are working on it: https://bugs.chromium.org/p/chromium/issues/detail?id=949555
