### ISSUE TITLE
Running Cordova Webview with flags set.

### ISSUE THREAD

**Issue by d410** [apache/cordova-android#715]
# Feature Request

## Motivation Behind Feature
https://stackoverflow.com/questions/20994625/enable-experimental-features-in-android-chrome-webview-aim-css-regions-suppor/21009181#21009181

Running Cordova Webview with flags set would allow the enabling of experimental Javascript and experimental Chromium related features.

Possible other issues this would solve
Issue #712 https://github.com/apache/cordova-android/issues/712

https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode

Issue #714 https://github.com/apache/cordova-android/issues/714
https://stackoverflow.com/questions/55668046/offscreencanvas-works-on-chrome-mobile-but-refuses-to-work-in-mobile-application

## Feature Description
This feature could possibly be easily enabled through the config.xml, by appending the flag to an area of the configuration for the cordova project.

## Alternatives or Workarounds
There is currently as of my knowledge no way to do this.

**Comment by dpogue** [comment]
As stated in the StackOverflow post you linked, it is not possible to pass flags to the Android WebView to control experimental features. There's nothing Cordova can do here.

If you feel this is a bug with the Android WebView, please report it to Chromium.
