### ISSUE TITLE
cordova's configured gradle version unsupported in Android Studio 3.4

### ISSUE THREAD

**Issue by jacobg** [apache/cordova-android#718]
# Bug Report

Android Studio 3.4 (just released) require a minimum Gradle version of 5.1.1, and so Gradle sync fails:
```
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in /Users/jacob/workspace/f-tc/src-cordova/platforms/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip
```

## Problem

See above

### What is expected to happen?

cordova android automatically configured for Gradle 5.1.

### What does actually happen?

uses Gradle 4.10

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by codinronan** [comment]
Hmmm I am using Gradle 5.1 in Android Studio 3.4 without any issues.

*However* I should note that when I am provided the opportunity to upgrade the Gradle plugin, I do so - the *first* time Android Studio is opened after doing `cordova prepare`. If you do not take that opportunity, for some reason if you do it later the upgrade doesn't occur correctly and I get other errors and end up having to start over.

The NDK setting is also no longer accepted, NDK is removed in Android Studio 3.4, I end up needing to manually edit `gradle.properties` to remove it.

Getting `cordova-android` 8.1 released would be incredibly helpful, the build conflicts are mounting up.

**Comment by blondie63** [comment]
8.1 ? when ?

**Comment by dpogue** [comment]
Releasing an 8.1.0 release right now wouldn't do anything about this, because nothing has been done yet to address this.

One problem is that upgrading to a new major version of gradle might be a breaking change, which we can't do until cordova-android@9.0.0. A larger problem is that currently nobody has time to look into this.

**Comment by nhhockeyplayer** [comment]
this is not fun
if you cant build you cant do anything
im seeing corrupted up maven repo's being made too for the gradle dist
what a disaster
f you try to fix it cordova resets it back
their configuration is secret... probably hardwired by intent

**Comment by benitogf** [comment]
I faced a similar issue and was able to solve it updating cordova:
```
npm i -g cordova
```
then removing and adding back the android platform:
```
cordova platform remove android
cordova plarform add android
```
And finally adding the minSdk preference to config.xml:
```
<preference name="android-minSdkVersion" value="19"/>
```

but now I get a different error on graddle sync inside android studio:
```
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
```

**Comment by benitogf** [comment]
> but now I get a different error on graddle sync inside android studio:

I'm able to run the project from android studio following the steps above and them removing 

```
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
```

both from the application and CordovaLib `AndroidManifest.xml`

but this breaks rebuilding with cordova-cli without removing and adding back the platform

**Comment by brodybits** [comment]
A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would really help us confirm this as a bug.

I did raise #780 to update for Gradle 5, as a MAJOR BREAKING update.

**Comment by jsbreezy** [comment]
Je ne m'en sors pas là, en tous cas du tout du tout !

**Comment by Darren777** [comment]
if you run the following it will fix the problem building APKs from the command line
```
ionic cordova platform remove android
ionic cordova platform add android 
```
however, after you run/build it in android studio the version mismatch error returns...

instead to fix this, in android studio you should NOT update the project gradle versioning but instead go to 
file > project structure > SDK location > Gradle settings...
and then tell it to use Gradle from a specified location which should be
C:/Gradle/gradle-7.4.2 or whatever version you have.

By doing this you will be able to build APKs from the command line using ionic as well as from within android studio.
