### ISSUE TITLE
Execution failed for task ':app:packageDebug'. > value (89854) > 0x0000ffff

### ISSUE THREAD

**Issue by tkutlic** [apache/cordova-android#720]
Can someone please help:

I'm using cordova-android@7.1.0 and sdk target version is 25.

FAILURE: Build failed with an exception.
.../platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
' > value (89854) > 0x0000ffff

**Comment by breautek** [comment]
Please provide a full stacktrace for assistance.

All I can tell you is that there is a number (89854) that is larger than 0x0000FFFF (numerically 65535)

**Comment by breautek** [comment]
Closing due to lack of response.
