### ISSUE TITLE
Android9 open remote HTTP error

### ISSUE THREAD

**Issue by WinterWoods** [apache/cordova-android#721]
I expect to open it properly.

BUT Open remote links to display errors.
net::ERR_CLEARTEXT_NOT_PERMITTED

My Cordova version is 9.0.0

**Comment by dominic-simplan** [comment]
Since Android 9 access via http is not permitted by default (only https is allowed). See [this answer](https://stackoverflow.com/a/55445650/3049015) for a solution.

**Comment by facundofarias** [comment]
Using always SSL (HTTPS) solved the issue. 
You should try it @WinterWoods

**Comment by Livideakoto** [comment]
@WinterWoods. If you didn't still get a solution to solve this problem. Here is one
In your config.xml platform tag add this first
<edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/application">
        <application android:usesCleartextTraffic="true" />
</edit-config>

And second add this to your widget tag
xmlns:android="http://schemas.android.com/apk/res/android"
like that
<widget id="com.yourapp.id" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" ...

**Comment by jcesarmobile** [comment]
This is not really a cordova-android issue, but an Android 9 feature.
There are a few ways of allowing HTTP calls and even plugins, but not really recommended, you should switch to https

**Comment by pcwSlide** [comment]
Yes thanks all.. I included a link to the appropriate code and had solved the issue. 

My query was more  is Cordova going to add some code to include the clear text directive -  without this the links  break in the normal use cases.  Say test for Android and Protocol, insert code and perhaps put up a message - more from a user side really - seems like a much reported issue/problem and may not reflect well on Cordova - even though it is Google - as usual.

Anyway - thanks for your replies..
