### ISSUE TITLE
Android emulator not  worked

### ISSUE THREAD

**Issue by BDAinc** [apache/cordova-android#723]
I install android emulator in android studio

I run command cordova -d emulate android

But see error

```
/media/anonim/01D4C6F2C6169120/PROJECTS/PLANSTER/PRODUCTIONS/MOBILE/project/platforms/android/app/build/outputs/apk/debug/app-debug.apk
No scripts found for hook "before_deploy".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/usr/lib/android-sdk (DEPRECATED)
Running command: adb devices
Command finished with error code 0: adb devices
Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?
CordovaError: Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?
    at /media/anonim/01D4C6F2C6169120/PROJECTS/PLANSTER/PRODUCTIONS/MOBILE/Planster31/platforms/android/cordova/lib/emulator.js:176:35
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

in my .bashrc I add next string

```
export ANDROID_SDK=/home/anonim/Android/Sdk:@PATH
export PATH=/opt/gradle/gradle-5.4/bin:$PATH
```

but this is not solution

How solve problem?

**Comment by janpio** [comment]
Try to set `ANDROID_HOME` to something else as well, seems to be `/usr/lib/android-sdk` right now.

**Comment by breautek** [comment]
Also don't forget to restart your terminal session after changing .bashrc

**Comment by BDAinc** [comment]
> Try to set `ANDROID_HOME` to something else as well, seems to be `/usr/lib/android-sdk` right now.

I try. Now my .bashrc 

```
setenv JAVA_HOME /usr/lib/jvm/java-8-oracle/jre/
setenv PATH $JAVA_HOME/bin:$PATH

export ANDROID_SDK=/home/anonim/Android/Sdk:@PATH
export ANDROID_HOME=/usr/lib/android-sdk:@PATH
```

But this is not work

**Comment by janpio** [comment]
Can you execute `android` or `avdmanager` manager manually on your command line?

**Comment by BDAinc** [comment]
> Можете ли вы выполнить `android`или `avdmanager`управлять вручную в командной строке?
>>>avdmanager
avdmanager: command not found

I don't know what I'm doing wrong. I feel stupid.

**Comment by BDAinc** [comment]
by the way when I start the console that I see the following error every time

setenv: command not found
setenv: command not found

**Comment by breautek** [comment]
The path of `/usr/lib/android-sdk`

should be a directory of several directories, more importantly it should have build-tools, platforms, tools, and platform-tools. See below 

```
$ ls
build-tools  extras    ndk-bundle  platforms       sources        tools
emulator     licenses  patcher     platform-tools  system-images
```
If `/usr/lib/android-sdk` doesn't look anything like above, then you may have the wrong directory!

Note that some of the command line tools are in these sub-directories. To address that, I have the following inside my .bashrc. While `ANDROID_HOME` should be the only thing that is required for cordova, the other paths may be helpful to debug the android sdk installation.

```bash
# ANDROID_HOME should be a directory that looks above
export ANDROID_HOME="/usr/lib/android-sdk"

# ANDROID_HOME is deprecated and being replaced by ANDROID_SDK_ROOT, but many tools
# still relies on ANDROID_HOME
export ANDROID_SDK_ROOT=$ANDROID_HOME

export PATH="$PATH:$ANDROID_HOME/tools" # Required for the android binary
# export PATH="$PATH:$ANDROID_HOME/tools/bin" # Some android installations have their binaries located in tools/bin instead of tools/

export PATH="$PATH:$ANDROID_HOME/platform-tools" # Required for using adb (Android debug bridge) from command line

# This should be set to the installed build-tools installation, which may be different. 
# Look inside the build-tools folder to see which build tools versions you have installed, and 
# use one of them.
# Required for accessing build and deployment tools such as zipalign
export PATH="$PATH:$ANDROID_HOME/build-tools/28.0.3"
```

Of course after modifying the .bashrc you'll need to restart the terminal for the changes to take effect.

After you restart your terminal if you run `avdmanager --help` then you should see:

```
Usage:
      avdmanager [global options] [action] [action options]
      Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

Valid actions are composed of a verb and an optional direct object:
-   list              : Lists existing targets or virtual devices.
-   list avd          : Lists existing Android Virtual Devices.
-   list target       : Lists existing targets.
-   list device       : Lists existing devices.
- create avd          : Creates a new Android Virtual Device.
-   move avd          : Moves or renames an Android Virtual Device.
- delete avd          : Deletes an Android Virtual Device.
```

Then it looks like your environment is configured properly and you can try running cordova again. Hope this helps.

**Comment by BDAinc** [comment]
> The path of `/usr/lib/android-sdk`
> 
> should be a directory of several directories, more importantly it should have build-tools, platforms, tools, and platform-tools. See below
> 
> ```
> $ ls
> build-tools  extras    ndk-bundle  platforms       sources        tools
> emulator     licenses  patcher     platform-tools  system-images
> ```
> 
> If `/usr/lib/android-sdk` doesn't look anything like above, then you may have the wrong directory!
> 
> Note that some of the command line tools are in these sub-directories. To address that, I have the following inside my .bashrc. While `ANDROID_HOME` should be the only thing that is required for cordova, the other paths may be helpful to debug the android sdk installation.
> 
> ```shell
> # ANDROID_HOME should be a directory that looks above
> export ANDROID_HOME="/usr/lib/android-sdk"
> 
> # ANDROID_HOME is deprecated and being replaced by ANDROID_SDK_ROOT, but many tools
> # still relies on ANDROID_HOME
> export ANDROID_SDK_ROOT=$ANDROID_HOME
> 
> export PATH="$PATH:$ANDROID_HOME/tools" # Required for the android binary
> # export PATH="$PATH:$ANDROID_HOME/tools/bin" # Some android installations have their binaries located in tools/bin instead of tools/
> 
> export PATH="$PATH:$ANDROID_HOME/platform-tools" # Required for using adb (Android debug bridge) from command line
> 
> # This should be set to the installed build-tools installation, which may be different. 
> # Look inside the build-tools folder to see which build tools versions you have installed, and 
> # use one of them.
> # Required for accessing build and deployment tools such as zipalign
> export PATH="$PATH:$ANDROID_HOME/build-tools/28.0.3"
> ```
> 
> Of course after modifying the .bashrc you'll need to restart the terminal for the changes to take effect.
> 
> After you restart your terminal if you run `avdmanager --help` then you should see:
> 
> ```
> Usage:
>       avdmanager [global options] [action] [action options]
>       Global options:
>   -s --silent     : Silent mode, shows errors only.
>   -v --verbose    : Verbose mode, shows errors, warnings and all messages.
>      --clear-cache: Clear the SDK Manager repository manifest cache.
>   -h --help       : Help on a specific command.
> 
> Valid actions are composed of a verb and an optional direct object:
> -   list              : Lists existing targets or virtual devices.
> -   list avd          : Lists existing Android Virtual Devices.
> -   list target       : Lists existing targets.
> -   list device       : Lists existing devices.
> - create avd          : Creates a new Android Virtual Device.
> -   move avd          : Moves or renames an Android Virtual Device.
> - delete avd          : Deletes an Android Virtual Device.
> ```
> 
> Then it looks like your environment is configured properly and you can try running cordova again. Hope this helps.

Thank you so much for wasting your time and giving so many detailed answers. Recently, this is a great rarity! Thanks again.

despite the fact that I installed the emulator from adnroid studio my 

> /usr/lib/android-sdk

 directory, looks like that
`build-tools  licenses  platforms  platform-tools  tools`

I think that you were right when you said that I had a problem with the ways, but I don’t know how to fix it (

**Comment by BDAinc** [comment]
содержимое папки /home/anonim/Android/Sdk выглядит примерно так как вы описали

```
build-tools  extras    patcher    platform-tools  tools
emulator     licenses  platforms  sources
```

now my .bashrc 

```
setenv JAVA_HOME /usr/lib/jvm/java-8-oracle/jre/
setenv PATH $JAVA_HOME/bin:$PATH
export PATH=$JAVA_HOME/bin:$PATH

export PATH=/opt/gradle/gradle-5.4/bin:$PATH

export ANDROID_HOME="/home/anonim/Android/Sdk"
export ANDROID_SDK_ROOT=$ANDROID_HOME

export PATH="$PATH:$ANDROID_HOME/tools"

export PATH="$PATH:$ANDROID_HOME/platform-tools"
export PATH="$PATH:$ANDROID_HOME/build-tools/28.0.3"
```
I restart my terminal and run command avdmanager but see

`avdmanager: command not found`

i run cordova build and see

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/anonim/Android/Sdk (recommended setting)
ANDROID_HOME=/home/anonim/Android/Sdk (DEPRECATED)
Running command: adb devices
Command finished with error code 0: adb devices
Running command: avdmanager list avd
Command finished with error code 0: avdmanager list,avd
No emulator images (avds) found.
1. Download desired System Image by running: /home/anonim/Android/Sdk/tools/android sdk
2. Create an AVD by running: /home/anonim/Android/Sdk/tools/android avd
HINT: For a faster emulator, use an Intel System Image and install the HAXM device driver

```

**Comment by breautek** [comment]
Some android installations can have binaries including the avdmanager binary located at `$ANDROID_HOME/tools/bin/`. I suspect this is the case for you.

To confirm try running:

ls $ANDROID_HOME/tools/bin/avdmanager

If it outputs something like

`/home/totalpave/Android/Sdk/tools/bin/avdmanager`

Then edit your .bashrc and add

`export PATH="$PATH:$ANDROID_HOME/tools/bin"`

Then restart your terminal and try the cordova command again.

**Comment by BDAinc** [comment]
> Some android installations can have binaries including the avdmanager binary located at `$ANDROID_HOME/tools/bin/`. I suspect this is the case for you.
> 
> To confirm try running:
> 
> ls $ANDROID_HOME/tools/bin/avdmanager
> 
> If it outputs something like
> 
> `/home/totalpave/Android/Sdk/tools/bin/avdmanager`
> 
> Then edit your .bashrc and add
> 
> `export PATH="$PATH:$ANDROID_HOME/tools/bin"`
> 
> Then restart your terminal and try the cordova command again.

I try it but see error again

No emulator images (avds) found.
1. Download desired System Image by running: /home/anonim/Android/Sdk/tools/android sdk
2. Create an AVD by running: /home/anonim/Android/Sdk/tools/android avd
HINT: For a faster emulator, use an Intel System Image and install the HAXM device driver

**Comment by breautek** [comment]
At least the error changed! This error suggests its finally using the avdmanager but suggests you don't have any emulators configured.

I personally don't use android emulators so this is where my help may end. This is something I haven't done before,  but like the error states, you can try running `android sdk` to download the images to run an emulator and `android avd` to create an emulator.

**Comment by BDAinc** [comment]
> At least the error changed! This error suggests its finally using the avdmanager but suggests you don't have any emulators configured.
> 
> I personally don't use android emulators so this is where my help may end. This is something I haven't done before, but like the error states, you can try running `android sdk` to download the images to run an emulator and `android avd` to create an emulator.

I think what I'll do.

Thank you very much for your time to help! I appreciate that!

**Comment by breautek** [comment]
This issue looks to be resolved. If you have any other questions/issues please feel free to raise a new issue.
