### ISSUE TITLE
Android emulator app run error

### ISSUE THREAD

**Issue by BDAinc** [apache/cordova-android#727]
Hi all! I am setup android emulator and its work. But, if I run command cordova -d emaulator android

i see error
```
Failed to execute shell command "getprop,dev.bootcomplete"" on device: Error: adb: Command failed with exit code 1 Error output:
error: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.

```

the emulator started, but there is no application in it

whats problem?

**Comment by breautek** [comment]
Something appears to be wrong with your ADB tooling/android sdk.

- You can try the the suggested:
```
adb kill-server
adb start-server
```

- Also in the emulator, ensure that developer tools is indeed on.
- You can also try revoking USB debugging and restarting the emulator.
- Ensuring all your SDK tools is up to date by using the SDK Manager

There are likely more tips you can try on https://stackoverflow.com/questions/23081263/adb-android-device-unauthorized

For more support, I invite you to Cordova's [slack](http://slack.cordova.io/)
