### ISSUE TITLE
failed to install "cordova-plugin-whitelist" for android 

### ISSUE THREAD

**Issue by MaryemZOBI** [apache/cordova-android#731]
hello,
I have some problems while adding android platform to myApp project, someone could help me to solve that.
cordova v : 6.5.0
node js v :10.15.3
npm v : 6.4.1
![image](https://user-images.githubusercontent.com/38964877/57485240-04889e80-7260-11e9-85b8-e5b14a35c634.png)

**Comment by janpio** [comment]
>  cordova v : 6.5.0

Current version of Cordova CLI is 9.x, current version of Cordova Android is 8.x. You are trying to use software here that is multiple years out of date - it'S not very surprising this doesn't work. (Building an actual Android project would probably also not work.)

You should use current versions of everything, then you won't have these problems.

**Comment by MaryemZOBI** [comment]
thanks for replaying,
Using the Latest version of Cordova v9.0.0 shows these errors: 
Node.js (v:10.15.3 latest version)
npm(v6.4.1 latest version)
![image](https://user-images.githubusercontent.com/38964877/57493592-7bcb2c00-727a-11e9-8e75-3b0abb611bba.png)
could you suggest any solution

**Comment by janpio** [comment]
This one has nothing to do with Cordova Android. Please create a new issue at https://github.com/apache/cordova-cli Thanks.
