### ISSUE TITLE
How to use startActivity in cordovaActivity?

### ISSUE THREAD

**Issue by czweb2017** [apache/cordova-android#732]
Help!
My project was created by ionc and cordova CLI. I want to open a new activity in my app.But when i use startActivity in main class CordovaActivity, it doesn't work! I'm new to cordova.I don't know how to do

**Comment by erisu** [comment]
I am going to close this ticket as it appears to be more of a usage support question and not a feature or bug request.

> Apache Cordova uses GitHub Issues as a feature request and bug tracker.
> For usage and support questions, please check out the resources below. Thanks!
>
> You can get answers to your usage and support questions about **Apache Cordova** on:
> * Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
> * StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`
> If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

From a quick Google search maybe this will give you an idea, but it is talking from a Cordova plugin's view. 

https://stackoverflow.com/a/14321849

I would recommend asking support and usage request on StackOverflow as you might get replies faster.
