### ISSUE TITLE
App not scaling correctly on android (Honor 8x)

### ISSUE THREAD

**Issue by RaZ0r1994** [apache/cordova-android#734]
Btw. this issue was copied over from the other apache-cordave repository since they directed me here.

### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Information
I cant get the app to use the full height of the device. The only topics i found were referring to ios.

### Environment, Platform, Device
Android version 8.1.0
Phone is Honor 8x

Apache Cordova toolset version: 6.3.1
![cordova](https://user-images.githubusercontent.com/39921982/56023411-0e28f000-5d0e-11e9-8ea6-56647e83cb1e.jpeg)

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
> Apache Cordova toolset version: 6.3.1

What does this refer to?

What is your Cordova CLI version?
What is your Cordova Android version?

**Comment by RaZ0r1994** [comment]
running npm info cordova returns version (assuming thats the cordova cli version): cordova@9.0.0

cordova platform ls: Installad platform android 5.2.1

**Comment by janpio** [comment]
> cordova platform ls: Installad platform android 5.2.1

This is suuuuper old. You should upgrade this to a recent release of Cordova Android and try again.

**Comment by RaZ0r1994** [comment]
Ok just to give you a little update. Iam trying to update right now (kinda hard because visual studio dropped support for Cordova) i will check whether the App will scale correctly or not after the update is done

**Comment by RaZ0r1994** [comment]
This can be closed since Visual Studio dropped support and i have no longer time to try to get this to work. I´ve written my own HTML/JS based framework instead.

Anyways, thank you for your help :)
