### ISSUE TITLE
ionic cordova build android with prod flag fails unexpectedly

### ISSUE THREAD

**Issue by LaurentiuGabriel** [apache/cordova-android#735]
# Bug Report

When running ionic cordova build android --prod on my project it fails unexpectedly with the following issue:
typescript error 
            Unexpected value 'null' declared by the module 'AppModule in app/app.module.ts'
The following is the complete log with --verbose flag:

ionic cordova build android --prod --verbose
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'build', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, prod: true, project: null, '--': [] } +11ms
  ionic:lib:project Project type from config: Ionic 2/3 (ionic-angular) +0ms
  ionic:lib:project Project details: { configPath: '/media/laur/project/ionic.config.json', errors: [], context: 'app', type: 'ionic-angular' } +1ms
  ionic Context: { binPath: '/home/laur/.config/versions/node/v8.3.0/lib/node_modules/ionic/bin/ionic', libPath: '/home/laur/.config/versions/node/v8.3.0/lib/node_modules/ionic', execPath: '/media/laur/project/', version: '4.10.3' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /media/laur/project/config.xml +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova build' [ 'android', '--prod', '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:hooks Looking for ionic:build:before npm script. +0ms
  ionic:lib:project:ionic-angular:build Looking for ionic:build npm script. +0ms
  ionic:lib:project:ionic-angular:build Found ionic:build, but it is the default. Not running. +7ms
> ionic-app-scripts build --prod --target cordova --platform android
[22:09:26]  ionic-app-scripts 3.2.1 
[22:09:26]  build prod started ... 
[22:09:26]  clean started ... 
[22:09:26]  clean finished in 3 ms 
[22:09:26]  copy started ... 
[22:09:27]  deeplinks started ... 
[22:09:27]  deeplinks finished in 270 ms 
[22:09:27]  ngc started ... 
[22:09:41]  typescript error 
            Unexpected value 'null' declared by the module 'AppModule

When running the same command using --release flag, it works and it generates the .apk file. 

### What is expected to happen?

I expect to get the .apk file after running the command.

### What does actually happen?

The .apk isn't generated as it is when using the release flag. Also, no detailed information is displayed about the issue even when using the verbose flag. I have found some info on some stackoverflow threads about using ionic serve before running this command. I tried this as well but with no luck. 

## Information

Here is the app.module.ts file that I use: 

import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { HttpModule, JsonpModule } from '@angular/http';
import { StatusBar } from '@ionic-native/status-bar';
import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';
import { HelpPage } from "../pages/help/help";
import { IngredientsPage } from '../pages/ingredients/ingredients';
import RecipesPage from '../pages/recipes/recipes';
import { EdamamApiProvider } from '../providers/edamam-api/edamam-api';
import { File } from '@ionic-native/file';
import { IonicStorageModule } from '@ionic/storage';
import { PreferencesPage } from '../pages/preferences/preferences';
import { SQLite } from '@ionic-native/sqlite';
import { NutritionCalculatorComponent } from '../components/nutrition-calculator/nutrition-calculator';
import { RecipesSingleton } from '../pages/recipes/recipesSingleton';

@NgModule({
  declarations: [
    MyApp,
    HomePage,
    IngredientsPage,
    RecipesPage,
    HelpPage,
    PreferencesPage,
    NutritionCalculatorComponent
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    HttpModule,
    JsonpModule,
    IonicStorageModule.forRoot()
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage,
    IngredientsPage,
    RecipesPage,
    HelpPage,
    PreferencesPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    EdamamApiProvider,
    File,
    {provide: ErrorHandler, useClass: IonicErrorHandler},
    SQLite,
    RecipesSingleton
  ]
})
export class AppModule {}

### Command or Code

ionic cordova build android --prod

### Environment, Platform, Device

Command was performed from my Ubuntu machine v.18.04. Issue reproducible only on Android. 

### Version information

I'm using ionic cli 4.10.3, android studio 24.4, cordova 8.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
> ```
> typescript error
> Unexpected value 'null' declared by the module 'AppModule in app/app.module.ts'
> ```

This is due to a TypeScript error in your application code, and is not related to Cordova.

**Comment by LaurentiuGabriel** [comment]
I can see that, but with release flag it works as expected. Also, the file mentioned above doesnt have any error whatsoever.

**Comment by breautek** [comment]
> I can see that, but with release flag it works as expected. Also, the file mentioned above doesnt have any error whatsoever.

The --prod flag is an ionic construct, not cordova's. So you should raise an issue with Ionic.

**Comment by janpio** [comment]
And if they are talking about `--release` this is indeed a Cordova thing - which Ionic re-uses to change the way they build the app. As the error message is about TypeScript, which Cordova contains exactly none of, we are very confident this has nothing to do with Cordova but is all Ionic.
