### ISSUE TITLE
Android Gradle cannot compile

### ISSUE THREAD

**Issue by noxsener** [apache/cordova-android#736]
# Bug Report
Android Gradle cannot compile
## Problem
Gradle cannot compile at last version of android. It's giving an error "testImplementation is not found"

## Information
Problem caused by from Turkish letter problem from gradle. I had same error from a native android project, solved by;

"testImplementation" changed to "testİmplementation"

(for more info in Turkish letters; 
"i".upperCase()="İ",
"ı".upperCase()="I"
)

I was searched "testImplementation" line in gradle build. But i cannot find. Anyone can tell me where is it?

### Environment, Platform, Device
Android device connected via usb.

### Version information
Cordova 9.0.0
Installed platforms
android ^8.0.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Can you post the output of `cordova platform list` to show what android platform version you're using?

**Comment by noxsener** [comment]
Cordova 9.0.0
Installed platforms
android ^8.0.0
....other available platforms (I dont need)

**Comment by noxsener** [comment]
android ^7.1.4 hasn't this problem.

**Comment by janpio** [comment]
Please post the complete output of the command that is giving you problems. Run it with `--verbose` to get maximum output.

**Comment by dpogue** [comment]
This is a bug in Gradle, tracked upstream at https://issuetracker.google.com/issues/126874329

I don't think there's anything Cordova can easily/realistically do to work around it :disappointed:

**Comment by janpio** [comment]
There seems to be a workaround now:
https://stackoverflow.com/questions/55601018/how-to-fix-build-gradle-problem-in-a-cordova-project/55778295#55778295

**Comment by noxsener** [comment]
Thanks for all. I solved my problem and Issue is closed.
This is a bug in Gradle.
Solution;
https://stackoverflow.com/questions/55601018/how-to-fix-build-gradle-problem-in-a-cordova-project/55778295#55778295
