### ISSUE TITLE
Apache Cordova repository seems to be deleted on github

### ISSUE THREAD

**Issue by hugetiny** [apache/cordova-android#738]
I can't find the original Apache/Cordova repository,why?

**Comment by breautek** [comment]
You mean this repository https://github.com/apache/cordova ?

**Comment by hugetiny** [comment]
@breaku
Yes，but why this repository only got 96 starts？

**Comment by janpio** [comment]
Because historically there was no "Apache Cordova" repository, Cordova didn't even use GitHub for a long time, the code was only mirrored here for convenience.
