### ISSUE TITLE
Warning to fix: android.bat shouldn't be recommended anymore

### ISSUE THREAD

**Issue by Songbird0** [apache/cordova-android#741]
Hi,

When `cordova requirements` command is typed and any Android target hasn't been assigned, cordova recommends to use `android.bat` to install a fresh Android target. However, sdkmanager.bat should be used instead of android.bat.

I would be very happy to fix it myself, but I don't know the location of this warning.

**Comment by erisu** [comment]
Closing this issue as PR #1083 mentions that it closes this ticket.
