### ISSUE TITLE
bug: deploying installs & launches app but doesn’t create launcher on android

### ISSUE THREAD

**Issue by SanduCuragau** [apache/cordova-android#742]
# Bug Report

## Problem
when I deploy ionic app it installs and opens up but it doesn't create a launcher on my phone, so after closing the app I can literally never open it up again

### What is expected to happen?
Behaviour I used to have for the past month and a half developing in ionic 4 native:
-> Plug my phone to the PC
-> Make sure it’s connected and working using adb devices
-> Start developing something
-> Deciding it’s time to test it
-> Deploy the app to the phone by using: ionic cordova run android --target
-> If the app was installed, it would update, if it wasn’t, it would be installed, and stay installed even after closing it, I could open it up again using the launcher if I ever wanted to, it would be literally installed as any other app
-> Whenever I made big alterations to the sqlite local database such as creating new tables I’d completely wipe it's data and uninstall the app, since updating it created conflicts, and deployed again clean
-> Everything worked, happy dev

### What does actually happen?
Behaviour starting couple days ago:
-> I deploy using: ionic cordova run android --target
-> I’m watching the terminal
-> I see app building logs
-> I see app deployment logs
-> app opens up on my phone
-> app works PERFECTLY
-> going to settings -> installed apps, app is there
-> when I go to my home menu, app is no where to be found, I go and even search for it by name, nothing, apparently it is installed but something is going on and not creating the launcher

## Steps to reproduce
I don't know what caused this to start happening, but it is happening and I don't know how to reproduce it, or how to stop it from happening to me, it's driving me crazy, I close the app by mistake and then I have to deploy again just to open it up.

Any ideas what could be causing this bug? This is somewhat tolerable when I’m on my pc working since I can open the app by deploying it again, but when I’m not near my computer I literally have no way to open up the app
Here's the app installed
![image](https://user-images.githubusercontent.com/18098208/57709776-86fbce80-7663-11e9-837a-049781b14a82.png)

### Command or Code

ionic cordova run android --target

### Environment, Platform, Device

I'm on windows 10, using IONIC 4 and deploying directly to my android device which requires android studio and sdk installed

### Version information

Environment:
  OS: win32
  Node: v10.15.3
  npm: 6.9.0

>cordova info
  cordova-lib@9.0.0 with:
  cordova-common@3.1.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Plugins:
  cordova-plugin-app-version
  cordova-plugin-camera
  cordova-plugin-device
  cordova-plugin-ionic-keyboard
  cordova-plugin-ionic-webview
  cordova-plugin-screen-orientation
  cordova-plugin-splashscreen
  cordova-plugin-statusbar
  cordova-plugin-telerik-imagepicker
  cordova-plugin-whitelist
  cordova-sqlite-storage
  es6-promise-plugin

>ionic info
   ionic (Ionic CLI)             : 4.12.0 (C:\Users\SCuragau\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.3.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1```

![image](https://user-images.githubusercontent.com/18098208/57914522-ae7eb100-7886-11e9-9835-646ab4ce2824.png)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

Edit: 
I also tired deploying it directly from android studio to my phone by executing the project
![image](https://user-images.githubusercontent.com/18098208/57915400-9f006780-7888-11e9-9514-ebee6170c16e.png)
It builds, it installs because it appears in the installed apps, but it doesn't open up the app.

**Comment by breautek** [comment]
Thank you for your detailed report and I apologise for the lack of response here.

At some point (I forget when) but apps don't get installed to the home screen on android anymore. On most android versions, while on the home screen you have to swipe up or down to get to the app list screen, your app should appear here. You can then create a "shortcut" by holding down on the app to add it to your home screen. This may vary by device/emulator/android version.

Closing this because this is not a cordova issue. Cordova has the capability to build and install to the device, but from what the Android OS does from there is not really in Cordova's control.

If you think you've found a big, please do open a new issue with the relevant information. If you require further assistance on this, I invite you to join our [slack](http://slack.cordova.io/).
