### ISSUE TITLE
cordova run android gives "Failed to execute shell command cat,/proc/cpuinfo" error

### ISSUE THREAD

**Issue by sirdas** [apache/cordova-android#743]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
I'm having problem running an ionic project using "(ionic) cordova run android" and "(ionic) cordova emulate android". I get the same error with both:

> Failed to execute shell command "cat,/proc/cpuinfo"" on device: Error: D:\Android\Sdk\platform-tools\adb.exe: Command failed with exit code 3221226356

Any help is appreciated.

### Command or Code

cordova run android

### Version information

I've tried the latest versions of both cordova (9) and ionic (5) cli. I also tried downgrading and I am currently using:
ionic: 4.12.0
cordova: 8.1.2
node: v10.16.0 (LTS)

Using VS Code. I use the Android SDK from Android Studio.

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by yhajjaji** [comment]
I have the same problem, and it starts to irritate me frankly, two days lost, for a stupidity certainly, I tried all possible combinations, but nothing works (change version of android, simulated AVD, cordova-android version, I have everything uninstalled and reinstalled, but the problem persists), can anyone have a solution to this problem?
In addition there is another problem that I had was "Failed to execute command shell" getprop, dev.bootcomplete "" on device: Error "

**Comment by breautek** [comment]
First I'd suggest to check to see if ADB even sees your device. Try running `adb devices -l` (l is an lowercase L)

The output should look something like:

```
totalpave@norman-ThinkPad:~$ adb devices -l
List of devices attached
2791d7743d1c7ece       device usb:1-3 product:crownqltecs model:SM_N960W device:crownqltecs transport_id:1
```

Please post the results.

**Comment by yhajjaji** [comment]
Thank you for your response
A result of the command is : 

emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:23

**Comment by breautek** [comment]
Also, knowing the ADB version might be helpful... Quick google search on the error code suggests the problem is related to specific ADB versions. 

```
totalpave@norman-ThinkPad:~$ adb --version
Android Debug Bridge version 1.0.40
Version 4986621
```

**Comment by yhajjaji** [comment]
My adb version is : 

Android Debug Bridge version 1.0.41
Version 29.0.0-5611747

**Comment by breautek** [comment]
In the SDK Manager, do you have Platform 28 or Platform 29 installed?

**Comment by yhajjaji** [comment]
I have Platform 29 installed ( Android 9.+ (Q)),  you think version Android 9.+ is not stable?

**Comment by breautek** [comment]
> I have Platform 29 installed ( Android 9.+ (Q)), you think version Android 9.+ is not stable?

Just trying to figure out potential differences... I'm updating my environment to the latest to see if it breaks for me.

For the record, my current versions are:
- Platform 28
- SDK Platform Tools 28.0.1
- SDK Build Tools 28.0.3

**Comment by yhajjaji** [comment]
Ok, I'm going to align with your configuration and check if it works, I'll let you know

**Comment by breautek** [comment]
I've updated my android tooling to the latest and still failing to reproduce the issue unfortunately. I am on Linux however, not a windows platform. Not sure if that would be significant.

Ideas of mine is reaching thin.

**Comment by sirdas** [comment]
I can see my device and I can also run "adb shell cat /proc/cpuinfo" for my device and get:

> Processor       : AArch64 Processor rev 4 (aarch64)
> processor       : 0
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 1
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 2
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 3
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 4
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 5
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 6
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4
> 
> processor       : 7
> BogoMIPS        : 3.84
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant     : 0x0
> CPU part        : 0xd03
> CPU revision    : 4

I might later try downgrading adb. Recently, I also saw the "CordovaError: Failed to execute shell command "getprop,dev.bootcomplete"" error (I don't quite remember how I got it) and the error was occuring somewhere in the Adb.js file in the Cordova lib. I figured it was more of a Cordova issue than an adb issue but I'm new to this so I'm not sure.

**Comment by breautek** [comment]
> he error was occuring somewhere in the Adb.js file in the Cordova lib. I figured it was more of a Cordova issue than an adb issue but I'm new to this so I'm not sure.

Useful information thanks @sirdas . Adb.js looks like is just a wrapper to call on the ADB executable. The errors shown so far appears to come from the ADB executable itself, which Cordova is simply just propagating.

**Comment by dpogue** [comment]
> I have Platform 29 installed ( Android 9.+ (Q)), you think version Android 9.+ is not stable?

Just noting that Cordova does not claim any level of support for pre-release versions of tools. Cordova-Android 8 supports the Android SDK v28.

**Comment by yhajjaji** [comment]
@breautek and @sirdas : 
Finally I managed to make it work by following the procedure of @breautek (thank you)[https://stackoverflow.com/a/56474669/4685664], by copying that the file adb.exe, by copying the other two it does not work, @sirdas is what can you test and keep me informed? Thank you

**Comment by sirdas** [comment]
Thank you @breautek. Downgrading Android SDK platform-tools works! I should note that it's not possible to downgrade the version of platform-tools via Android Studio or the sdkmanager cli (only the most recent version is available). I uninstalled platform-tools and then I used a link to download platform-tools v28 ([http://dl.google.com/android/repository/platform-tools_r28.0.0-windows.zip](http://dl.google.com/android/repository/platform-tools_r28.0.0-windows.zip)) and copy platform-tools over to the Sdk folder. You can pretty much just edit the version number in the URL to get whatever version you want from Google's repo. Cheers

**Comment by thyagocl** [comment]
I think it's worth mentioning, for future visitors, that Google has updated the platform-tools and fixed the bug in adb. It works fine on version 29.0.1.
