### ISSUE TITLE
bug / trivial programming error -- crash in fresh build 'Cannot read property 'length' of undefined'

### ISSUE THREAD

**Issue by alschytte** [apache/cordova-android#745]
# Bug Report

## Problem
a javascript file in cordova has a trivial and very-very old problem - this problems har been around for long, and you cannot build on windows unless you modify the check_reqs.js file in the  'platforms/android/cordova/lib' directory

### What is expected to happen?
The build call 'get_gradle_wrapper'  to find an path to gradle but it fails, because the javascript that locates gradle-dir has a flaw

### What does actually happen?
crash in build 'Cannot read property 'length' of undefined'

## Information
 line 116 your version
-----------------------
      if (dirs[0].split('-')[0] === 'gradle') {
          console.log( dirs[0])
            return path.join(androidStudioPath, dirs[0], 'bin', 'gradle');
        }

line 116 my version
-----------------------
       var gradledir;
        dirs.forEach((dir) => {
          if (dir.split('-')[0] === 'gradle')
              gradledir = path.join(androidStudioPath, dir, 'bin', 'gradle');
        });
       if (!gradledir)  
          throw new CordovaError('Could not find a version of gradle in Android Studio');
       return gradledir;

The problems is that 'dirs' is an array and the gradle directory is (no more ?) the only sub-directory in 'androidstudiopath'. It's a simple error.

### Command or Code
Fresh install 

     cordova build android --debug (or release)

### Environment, Platform, Device
Windows 10, android app

### Version information
cordova -v = 9.0.0 (cordova-lib@9.0.1)
"cordova-android": "^8.0.0", (exists in 6 and 7 versions also )

android studio 3.4.1 (but exists in android 2.1, 3.0, and 3.2 also)
gradle 5.1.1 (also in 4.6)

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by janpio** [comment]
I can build Cordova Android apps on Windows just fine.

**Comment by alschytte** [comment]
Hello Jan, 
Thanks for your swift reply.

I have seen this error several times. It may be caused by a change in android studio as regards to gradle integration.

Several ppl on the internet has complained of this issue too (but not on GitHub).

And if you check the code I have supplied you can’t miss the error, and my program change solves the issue.

The subroutine is locating the gradle exec, which is in <android studio>\gradle\gradle-x.x.x\bin.

When Android studio installs now it makes  a number of sub-directories  in the <android studio>\gradle directory. 

The code makes a directory list, and then only handles the first ( dirs[0 ] )  (I believe earlier versions of studio might have made only 1 subdirectory – therefore the bug).

Following is a dump of a fresh install <android studio>\gradle directory




Sendt fra Mail til Windows 10

Fra: Jan Piotrowski
Sendt: 13. juni 2019 10:30
Til: apache/cordova-android
Cc: Allan Steen Schytt; Author
Emne: Re: [apache/cordova-android] bug / trivial programming error -- crashin fresh build 'Cannot read property 'length' of undefined' (#745)

I can build Cordova Android apps on Windows just fine.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Denne mail er kontrolleret for vira af AVG.
http://www.avg.com

**Comment by breautek** [comment]
It looks like you created a PR against your own fork.

**Comment by breautek** [comment]
Closing as stale.
