### ISSUE TITLE
Dark Mode Support Android Q

### ISSUE THREAD

**Issue by Ebrahim-Merchant** [apache/cordova-android#747]
I was wondering if Cordova would support the new Android Q System wide dark mode? If it does how do we currently know that the system has dark mode activated?

**Comment by dpogue** [comment]
You should be able to do this entirely in CSS using `@media (prefers-color-scheme: dark)`.
For more information, see https://webkit.org/blog/8840/dark-mode-support-in-webkit/ (There's a Chrome blog coming out about it soon, but it's not published yet)

**Comment by m-s-morgan** [comment]
@dpogue as far as I can tell the `prefers-color-scheme` media query seems to exist but it always matches as `no-preference` no matter what the OS is set to. Is there a possible workaround for this at the moment or are we forced to wait for an android update?

**Comment by dpogue** [comment]
This might only work when building against API 29

**Comment by m-s-morgan** [comment]
Unfortunately, I am building with API 29. Prefers-color-scheme is supported, it just always matches `no-preference`. It may simply not yet be honored in the Android WebView.

**Comment by m-s-morgan** [comment]
If I `setForceDark` in the WebSettings of the `SystemWebViewEngine` and `FORCE_DARK_ON` it will honor the `dark` color-scheme. But obviously then it's always dark which isn't what I want. If you think there may be a workaround of some kind, I'm more than interested. Otherwise, I'll likely write a plugin to listen for UI config updates in the meantime. Thanks.

**Comment by jcesarmobile** [comment]
You can check if the device has dark mode enabled and only force the WebView into dark mode in that case, something like

```
    int nightModeFlags = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
    if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
      if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
        webSettings.setForceDark(WebSettings.FORCE_DARK_ON);
      }
    }
```

But doesn't seem to be possible to get light media query.

Looks like an Android bug to me.

**Comment by acpnayak** [comment]
Is this issue still open? I just tried and experiencing the same behavior. prefers-color-scheme media query always matches as no-preference no matter what the OS is set to.

**Comment by jpike88** [comment]
Insanity. Android does it again.

**Comment by MittereggerMartin** [comment]
I have the same issue - dark mode seems to be enabled since the following if statement evaluates to true.
```
if (window.matchMedia('(prefers-color-scheme)').media !== 'not all') {
    console.log('Dark mode is supported');
}
```

But the css media query always returns no-preference - no matter if dark mode is enabled or not.

**Comment by onaty** [comment]
> You can check if the device has dark mode enabled and only force the WebView into dark mode in that case, something like
> 
> ```
>     int nightModeFlags = getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
>     if (nightModeFlags == Configuration.UI_MODE_NIGHT_YES) {
>       if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q) {
>         webSettings.setForceDark(WebSettings.FORCE_DARK_ON);
>       }
>     }
> ```
> 
> But doesn't seem to be possible to get light media query.
> 
> Looks like an Android bug to me.

Please, which file will I edit this
