### ISSUE TITLE
cordova-android@8.0.0 not work with cordova-plugin-whitelist@1.3.3

### ISSUE THREAD

**Issue by alighasemzadeh** [apache/cordova-android#748]
Hello 
This is my repo:http://github.com/alighasemzadeh/srssms-mobile
I am try to use cordova-android@8.0.0 with whitelist plugin but I get network error.
When I downgrade my cordova-android to 6.4.0 it works well.
I think there is bug with cordova-android@8.0.0

**Comment by janpio** [comment]
You already created an issue with the plugin: https://github.com/apache/cordova-plugin-whitelist/issues/43
