### ISSUE TITLE
How to enable notifications on lock screen & led light by default ?

### ISSUE THREAD

**Issue by arcaweb** [apache/cordova-android#749]
Hi,

My app work well, and notifications with FCM too. But, notifications only show in status bar, and not on lock screen and no led light is blinking.

I can do this working, but I have to enable lock screen notification, led, ... in my device application parameters.

How can my app have theses parameters enabled by default ? I did not found any permission to do that :(

On iOS it works well.

Best regards

**Comment by breautek** [comment]
>  ... in my device application parameters.

Not exactly sure what you mean by this, please do clarify. If you mean you need to modify the `AndroidManifest.xml` file then you can use the `<edit-config>` tags in your `config.xml` to target and modify the `AndroidManifest.xml`. The documentation for `<edit-config>` can be found [here](https://cordova.apache.org/docs/en/latest/plugin_ref/spec.html#edit-config). Note that it's in the plugin documentation, but it can be used in your config.xml as well.

If you mean you want to programmatically modify/set default notification settings in your app, I'm afraid this isn't possible and defeats the purpose of giving user control over their notification settings. Only the user can choose the notification mode of an app. At most you can probably find a third-party plugin that allows you to launch the android settings programmatically so you can provide a "Notification Settings" button in your app. A quick plugin search I found [cordova-open-native-settings](https://github.com/guyromb/Cordova-open-native-settings), but I don't vouch for the plugin nor have I ever used it.

**Comment by arcaweb** [comment]
Thanks @breautek for your anwer.

When I install Whats App or Facebook application, I do not have to enable manually lock screen notifications, how can they do that ?

Is there a limit of cross platform app ? Or something else ?

**Comment by breautek** [comment]
I apologize, I didn't recognize FCM... I knew it as the old and I guess now deprecated GCM. I thought you were trying to do local notifications. 

I had a quick look at the FCM documentation... In order to receive FCM messages you'll likely will require a plugin as it requires changes to the AndroidManifest, Gradle configuration as well as a native implementation to respond to messaging events. Cordova doesn't provide an FCM implementation out of the box.

**Comment by arcaweb** [comment]
@breautek Yes but I thought I can change permissions of my cordova app. Because if app is closed, an FCM plugin for cordova will do nothing :/ I already have one for catching incoming notifications when app is in foreground. When in background / close the notification is threatened by FCM.

**Comment by breautek** [comment]
I'm not too familiar with FCM, but I'll bounce some information at you. The old GCM API did have a priority setting for android that controlled some behaviour that you are describing. A normal priority message will only immediately be sent to apps in the foreground. While the app is in the background, the notification may be delayed and if it is sent, it will only appear in the system tray/statusbar.

They used to have a high priority option when sending notification messages... which is intended to be used for apps that require immediate/urgent attention from the user (which things like instant messaging usually requires). 

I found [this](https://firebase.googleblog.com/2018/09/handle-fcm-messages-on-android.html) and it looks like FCM is a little bit different in that they have two message types.

A notification message which will go to the system tray while the app is in the background.

Then they have a "Data message"

> You should use data messages if you need to handle the notification in the client app, whether to customize the notification or to decrypt the received payload data.

So it sounds like you need to use a data message if you want to control how to display the notification.

**Comment by arcaweb** [comment]
@breautek yes that's right, I already use a data message for this (and it works), but not options found to display it on lock screen :(

**Comment by breautek** [comment]
Ok, so again this would be the responsibility of your FCM plugin.

The plugin would receive the message and would have to use the android's notification builder APIs to build a notification as documented [here](https://developer.android.com/training/notify-user/build-notification.html)

Specifically lock screen visibility settings can be found [here](https://developer.android.com/training/notify-user/build-notification.html#lockscreenNotification)

You should raise an issue with the authors of your FCM plugin. There is nothing that Cordova can do about this issue.

**Comment by arcaweb** [comment]
@breautek Ok thanks you so much for your answers :)

**Comment by breautek** [comment]
This issue looks to be resolved, at least as far as Cordova is capable of. Closing this issue. If you have more questions that is cordova related, feel free to raise a new issue.
