### ISSUE TITLE
BUILD FAILURE: Manifest Merger Failed

### ISSUE THREAD

**Issue by willnix86** [apache/cordova-android#752]
# Bug Report

## Problem
Can't build Android project.

### What is expected to happen?
Setting 'minSdkVersion' to 19 in the root config.xml should set the minSdk to 19 in the app.

### What does actually happen?

Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 19 declared in library [:CordovaLib] myProject/platforms/android/CordovaLib/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 14
	Suggestion: use a compatible library with a minSdk of at most 14,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

## Information
I have checked every single file in my project (including all plugins) and nowhere is the sdk version being overwritten. I have checked in all the Android projects folder after build and all I can see is references to sdk 19.

I do however, see cdvMinSdkVersion=14 in gradle.properties (Project Properties), so I guess the question is, where's that being set and why is it not overwritten?

### Environment, Platform, Device
Using Cordova Android 8.0.0
Using Cordova 9.0.0
Using global Gradle 4.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Cordova's config xml doesn't have a `minSdkVersion` option, I think you might mean `android-minSdkVersion`?

[Documentation Reference](https://cordova.apache.org/docs/en/latest/config_ref/#preference)

Also worth noting that Cordova doesn't support API levels < 19 when using Android platform 8. More info [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support)

**Comment by willnix86** [comment]
Yeah sorry I just didn’t write the full thing out  in the bug report - it’s all written as in the documentation. I’ve even upped it to 21 but still same error unless I add a build-extras.gradle specifying a min-sdk after build.

**Comment by breautek** [comment]
Interesting...

so `<preference name="android-minSdkVersion" value="21"/>` doesn't work but...

> In a build-extras.gradle, i have:
ext.cdvMinSdkVersion = 21

does?

**Comment by willnix86** [comment]
Yeah, it’s very odd!

I cannot find anywhere that’s making any reference to setting the minSdk to 14, yet without the build-extras overwrite, cdvMinSdkVersion in gradle.properties kills everything because it’s locked at 14 🤷🏻‍♂️

**Comment by breautek** [comment]
> I cannot find anywhere that’s making any reference to setting the minSdk to 14

A plugin could be doing this. If possible, I'd make a minimal reproducible project including only what is necessary to reproduce this issue. I'm willing to bet it will isolate the issue to a specific plugin.

**Comment by breautek** [comment]
This issue may be related to https://github.com/apache/cordova-android/issues/599

**Comment by willnix86** [comment]
I tentatively say that the sdk issue is fixed now, but let me run a few more builds to make sure.

Another issue has arisen now, in that I get the following errors once the app has installed:

Failed to load resource: net::ERR_FILE_NOT_FOUND: cordova_plugins.js:1

Any thoughts on that one?!

**Comment by breautek** [comment]
Nope... Never seen that one before. I'd recommend creating a new issue to keep things organised if the issue persists.

**Comment by willnix86** [comment]
This issue seems to have resolved itself too. Unsure if it was the fault of one or more plugins but, either way, we're all good. Thanks for the help @breautek
