### ISSUE TITLE
File Not Found: cordova_plugins.js

### ISSUE THREAD

**Issue by willnix86** [apache/cordova-android#753]
# Bug Report

## Problem
When I (successfully) build a project on the Android Platform and launch it on an Emulated device, it fails.

### What is expected to happen?
The app should work properly.

### What does actually happen?
I get a white screen and the following error in the console:

Failed to load resource: net::ERR_FILE_NOT_FOUND: cordova_plugins.js:1

## Information
It's a pretty basic project. The only plugins installed are:

     "cordova-android": "^8.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^5.0.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "2.1.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "3.2.0",
    "cordova.plugins.diagnostic": "4.0.12"

### Environment, Platform, Device
Cordova CLI Version 9.0.0
Others, see above.
Mac OS X 10.14.5

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

Can you also post the _complete_ output you get during the build? What command are you using to build?

**Comment by breautek** [comment]
Are you able to share the project or can create a minimal reproducible project that can be shared?

**Comment by willnix86** [comment]
It's all good - I figured out the issue. I was deleting the platform folder before every 'cordova run android' which would rebuild the platform folder but miss the 'installing plugins' step, so plugins weren't being installed correctly (hence the missing cordova_plugin file). Silly me!

**Comment by peiyumo** [comment]
> It's all good - I figured out the issue. I was deleting the platform folder before every 'cordova run android' which would rebuild the platform folder but miss the 'installing plugins' step, so plugins weren't being installed correctly (hence the missing cordova_plugin file). Silly me!

so may I know how did you solve it in the end @willnix86 ...

**Comment by peiyumo** [comment]
I sloved it by close my hooks in config.xml, which was added by my coworkers.
It misled the build procedure. So, when I deleted the hook lines in the config file then it started to add cordova plugins one by one.
Hope someone find this, and it's helpful for you.
