### ISSUE TITLE
Trigger "backbutton" event for gesture navigation in Android 9

### ISSUE THREAD

**Issue by gabrielrbarbosa** [apache/cordova-android#759]
# Feature Request

## Motivation Behind Feature
In Android Pie, there is a new way to navigate using gestures instead of buttons to get more screen space, but I couldn't use theses gestures in a Cordova app.

## Feature Description
Trigger "backbutton" event for gesture navigation in Android 9

**Comment by breautek** [comment]
Just adding information relevant to this feature request.

The android documentation for gesture navigation can be found [here](https://developer.android.com/preview/features/gesturalnav)

**Comment by jcesarmobile** [comment]
I've verified that the gesture navigation triggers backbutton event, there is nothing to do in Cordova's part.

Note that I wasn't able to test gesture navigation on Android 9 as the title said, only on Android 10+, it's not that it didn't work on Android 9, I wasn't able to enable gesture navigation on Android 9 emulators (didn't find the option)

**Comment by breautek** [comment]
> it's not that it didn't work on Android 9, I wasn't able to enable gesture navigation on Android 9 emulators (didn't find the option)

The android docs also does say:

> Beginning with Android 10 (API level 29), the Android system supports fully gesture-based navigation.

So gesture navigation in Android 9 might be non-standard or incomplete feature.
