### ISSUE TITLE
npm test fails on Node 12

### ISSUE THREAD

**Issue by breautek** [apache/cordova-android#767]
# Bug Report

## Problem
running `npm test` currently has 1 test failling.

### What is expected to happen?
- The test to pass.

### What does actually happen?
```
Failures:
1) ProjectBuilder apkSorter should sort APKs from most recent to oldest, deprioritising unsigned arch-specific builds
  Message:
    Expected $[3] = 'app-debug-x86.apk' to equal 'app-release-arm.apk'.
    Expected $[4] = 'app-release-x86.apk' to equal 'app-debug-arm.apk'.
    Expected $[5] = 'app-debug-arm.apk' to equal 'app-release-x86.apk'.
    Expected $[6] = 'app-release-arm.apk' to equal 'app-debug-x86.apk'.
  Stack:
    Error: Expected $[3] = 'app-debug-x86.apk' to equal 'app-release-arm.apk'.
    Expected $[4] = 'app-release-x86.apk' to equal 'app-debug-arm.apk'.
    Expected $[5] = 'app-debug-arm.apk' to equal 'app-release-x86.apk'.
    Expected $[6] = 'app-release-arm.apk' to equal 'app-debug-x86.apk'.
        at <Jasmine>
        at UserContext.<anonymous> (/home/norman/development/cordova-android/spec/unit/builders/ProjectBuilder.spec.js:262:32)
        at <Jasmine>

292 specs, 1 failure
Finished in 5.982 seconds
```

## Information
This currently only happens when running Node 12. Running Node 10 works ok.

### Command or Code
`npm test`

### Environment, Platform, Device & Versions
Node 12.4.0
Node 12.6.0
Linux Ubuntu 18.04
cordova-android@8.1.0-dev (master at the time of writing)
9.0.0 (cordova-lib@9.0.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
The explanation is that the following lines will lead to different results depending on what order `Array.prototype.sort()` follows when comparing the elements: https://github.com/apache/cordova-android/blob/rel/8.0.0/bin/templates/cordova/lib/builders/ProjectBuilder.js#L304-L318

I just raised PR #779 which gives consistent order on Node.js versions 6, 8, 10, and 12.

Thanks to @breautek for reporting this one.
