### ISSUE TITLE
Gradle  - << was deprecated in 4.x and removed in 5.0

### ISSUE THREAD

**Issue by frontenddeveloping** [apache/cordova-android#775]
# Bug Report
ERROR: Could not find method leftShift() for arguments

## Problem
Can't sync project in Android Studio

### What is expected to happen?
Project Synced

### What does actually happen?
Got error `ERROR: Could not find method leftShift() for arguments`

## Information
`task cdvPrintProps << { ... } ` should be changed to:
```
task cdvPrintProps {
    doLast {
      ...
    }
}
```

### Version information
Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by breautek** [comment]
Can you please provide your `cordova-android` version?

You can find your installed version by using `cordova platform ls`

Thanks

**Comment by frontenddeveloping** [comment]
@breautek android 7.1.4

**Comment by breautek** [comment]
Latest release is 8.0, which includes refactoring a `<< { ... }` to `doLast { ... }`. Please update and let me know if this solves your issue.

**Comment by brodybits** [comment]
I am marking this issue as invalid for now. I would vote to close this issue unless someone can show that this is an issue on cordova-android@8.

**Comment by frontenddeveloping** [comment]
Sounds good. Closed it.
