### ISSUE TITLE
Angular navigation issues

### ISSUE THREAD

**Issue by MrShakes** [apache/cordova-android#776]
# Bug Report

## Problem
Angular application is working well, only issue seems to be the navigation in Cordova(works well on web), using `chrome://inspect` I'm monitoring the issue and whenever navigation occurs `this.router.navigate` the callback from Angular confirms that the navigation was successful and most times(not all) the page will navigate however the url in Cordova remains constant(changes in web), this then goes on to affect other things such as navigating back which doesn't work, weird thing is Angular callback once again confirms that the page has navigated back but the page itself never changes in Cordova(does so on web)

### What is expected to happen?
Navigation is supposed to work as well as it does on Web

### Command or Code

`this.Router.navigate()` and `this.Location.back()`

### Environment, Platform, Device

Android device (Pie)

### Version information
"@angular/core": "^6.0.3",
"@angular/router": "^6.0.3",
cordova-lib@9.0.1
android 8.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by MrShakes** [comment]
@janpio I've created a minimal repo with this issue, you'll be able to see that the url does not change on navigation(please click Signin button) https://github.com/MrShakes/cordovaBugFix

**Comment by janpio** [comment]
This is not a Cordova project.

**Comment by MrShakes** [comment]
It is, please `cd` into `mobile` directory, the root directory is an Angular dir

**Comment by janpio** [comment]
Had to manually copy `dist` into `mobile/www` as the symlink doesn't work on Windows.

Works on Android 6.0.1 for me (assuming that clicking "Signin", getting an alert "Success!", then a page "Hello!", hitting the Back button to go to the "Signin" page again is the indended behavior.)

**Comment by MrShakes** [comment]
Yes, the issue I'm pointing to is the url never changes from login(if you inspect the device chrome://inspect) unlike web where it does, I believe this may be causing the issues I'm experiencing in my much larger App.

**Comment by janpio** [comment]
Isn't the URL changing just a visual thing in this case?

When I have the DevTools inspect window open, I don't see a changing URL. But if I close it, then click the button, then reload the chrome://inspect/#devices list I see the other URL. 

Also `this.location.href` outputs the correct URL in the console of the dev tools.

**Comment by MrShakes** [comment]
You're correct, thanks
