### ISSUE TITLE
[MAJOR] Update for Gradle version 5

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#780]
From discussion in #718 it sounds like we should update cordova-android to use Gradle 5.

I think this should be considered a MAJOR BREAKING CHANGE, for a new major release.

Any contributions would be much appreciated.

This may also be related to #754.

**Comment by janpio** [comment]
> I think this should be considered a MAJOR BREAKING CHANGE, for a new major release.

Why?

**Comment by breautek** [comment]
Just leaving this here for notes on potential breaking changes

https://docs.gradle.org/5.0/userguide/upgrading_version_4.html

**Comment by dpogue** [comment]
We’re likely going to need to do a major version bump to drop node 6 and 8 support in the next few months. We’re also going to have to look at what’s required to support Android Q.

We should put together a list of the things we need to get into the next major version so that everyone’s aligned, rather than just opening issues that will get lost in the noise.

**Comment by brodybits** [comment]
I just put this on the [9.0.0 milestone](https://github.com/apache/cordova-android/milestone/2), which seems to have a few other items already. I would suggest we put other items on that milestone, for the sake of good tracking.

**Comment by deleayuba** [comment]
kindly fix this quickly. Thank you

**Comment by brodybits** [comment]
Thank you for your interest in our work. Please keep in mind that this project is maintained by a bunch of overworked volunteers since a couple major companies have pulled their resources out of the maintenance. This makes it hard for us to compete with alternatives such as Capacitor and React Native which seem to have some stronger corporate backing.

Contributions are always appreciated, see the proposal by @breautek in PR #792 for example.

The other blocker is that we are reluctant to merge major changes like this until we are really ready to move forward with a new major release.

Given these two factors, we are not in a position to promise any timeline for fixing issues like this one.

**Comment by breautek** [comment]
> kindly fix this quickly. Thank you

If you need PR #792 asap, I'll provide instructions on how you can install `cordova-android` with the gradle 5 update.

First, fork the Apache's `cordova-android` repository, then clone it, then you can use the following git commands to merge in my PR. I assume your current working directory is inside the root of your `cordova-android` repository.

```bash
# The following commands branches off of version 8.0.0, the current stable release
git checkout rel/8.0.0
git branch gradle-patch
git checkout gradle-patch

# The following commands adds my repository so you can merge in my gradle-5.x branch into your repository
git remote add breautek https://github.com/breautek/cordova-android.git
git fetch breautek
git merge breautek/gradle-5.x

# Then push everything to a new branch on your repository
git push -u origin gradle-patch

# Now install your copy of cordova-android to your project
cd /to/your/cordova/project

cordova platform remove android
cordova platform add https://github.com/<your_github_account>/cordova-android.git#gradle-patch
```

Alternatively, you can simply install my copy of `cordova-android` doing:

```bash
cordova platform remove android
cordova platform add https://github.com/breautek/cordova-android.git#gradle-5.x
```

But you'll be using a development version of `cordova-android` and you'll be subject to any future changes I may do to my branch, which may unexpectedly break your build.

**Comment by piotr-cz** [comment]
After upgrading Android Studio to 3.5 and cordova-android to 8.1 builds via CLI doesn't work anymore:

```
FAILURE: Build failed with an exception.                                                                                                                                                                                   
                                                                                                                                                                                                                           
* Where:                                                                                                                                                                                                                   
Build file 'D:\x\platforms\android\app\build.gradle' line: 20                                                                                                                           
                                                                                                                                                                                                                           
* What went wrong:                                                                                                                                                                                                         
A problem occurred evaluating project ':app'.                                                                                                                                                                              
> Failed to apply plugin [id 'com.android.application']                                                                                                                                                                    
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in C:\Users\y\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip 
```

My workardound is to run
```sh
set CORDOVA_ANDROID_GRADLE_DISTRIBUTION_URL=https://services.gradle.org/distributions/gradle-5.6.2-all.zip
```

**Comment by breautek** [comment]
Removed the help wanted label as the work is already done in this PR https://github.com/apache/cordova-android/pull/792
