### ISSUE TITLE
[MAJOR] Migrate from shelljs to fs-extra

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-android#781]
As discussed during review of PR #764 (aab support). This idea originally comes from [Apache CB-14140 (jira)](https://issues.apache.org/jira/browse/CB-14140) which was done on the common/library packages. Here are some PRs to check out as examples:

- apache/cordova-common#21
- apache/cordova-lib#613
- https://github.com/apache/cordova-fetch/pull/23
- https://github.com/apache/cordova-create/pull/19

One thing to watch out for: We did encounter apache/cordova#121 on Windows, which was eventually solved by a workaround on fs-extra@8.

A few more pointers:

For spawning external processes, we migrated from Node.js “child_process” to cross-spawn in apache/cordova-common#50, started discussing further work in apache/cordova#16.

From @erisu (quoted from <https://github.com/apache/cordova-android/pull/764#discussion_r302806133>; see apache/cordova#79 for larger discussion on deprecating at least Node.js 6):

> Additionally, the next major will deprecates deprecates node 6 and 8 which allows us to leverage modern JS to cleanly write a recursive directory scan.
>
> Example: https://stackoverflow.com/a/45130990/1644129

**Comment by janpio** [comment]
Re the included comment: I don't think Cordova Android 9.0.0 was planned to drop Node 8.

**Comment by dpogue** [comment]
Yes, node 8 EOL is in December, so the thinking was that by dropping both 6 and 8 at the same time (targeting a release roughly somewhere in the fall) we’d avoid needing to do two major version bumps and go through all the release work again so soon.

**Comment by breautek** [comment]
If no one has already started working on this, this is something I'm willing to tackle over my available weekends.

**Comment by timbru31** [comment]
Go for it, any contribution is much appreciated :)

**Comment by breautek** [comment]
> Yes, node 8 EOL is in December, so the thinking was that by dropping both 6 and 8 at the same time (targeting a release roughly somewhere in the fall) we’d avoid needing to do two major version bumps and go through all the release work again so soon.
> 
> EDIT: This hasn’t been _decided_ yet, and should probably be brought up on the list for discussion.

There was a rejection to drop Node 8 at the same time as 6, in the sense that Node 8 should only be dropped in December.

https://lists.apache.org/thread.html/735c5ebc78fea19dd3f86067f7d330d5f3c0c660c6ed7c9b538540ac@%3Cdev.cordova.apache.org%3E

If the 9.0 milestone is only going to be release after December, then I can continue with this ticket with the assumption that node 8 support will be dropped.

**Comment by breautek** [comment]
```js
// checks if file exists and then deletes. Error if doesn't exist
function removeFile (project_dir, src) {
    var file = path.resolve(project_dir, src);
    shell.rm('-Rf', file);
}

// deletes file/directory without checking
function removeFileF (file) {
    shell.rm('-Rf', file);
}
```
@brodybits 

Do you think these two functions could be merged into one? They both appear to be doing essentially the same thing, and I believe the comments are also out-dated... as `removeFile` doesn't do anything special about checking for existence, and if it does throw an error, so would `removeFileF`.

**Comment by breautek** [comment]
https://github.com/apache/cordova-android/blob/c35a990c09f1ab278873754eb7f81e52250893a3/bin/lib/create.js#L75-L95

These snippet of contains a lot of shell usages, and where it uses `ls` I've replaced the implementation using `readdirsSync` where necessary, but in this instance I think this is legacy code that can simply be removed. The code appears to be looking for old jar files that must of existed 6+ years ago but is no longer required. The commit that adds this check & jar removal can be found [here](https://github.com/apache/cordova-android/commit/7c446b222d0c66dd9d2a23ef695a09d42669a9d3). It is referencing a JIRA id that doesn't appear to exist anymore. I think anybody today won't have these old jar files to begin with.

**Comment by brodybits** [comment]
Hi @breautek, I wonder if you should raise a *draft* PR with your ongoing work on this?

I think a draft PR with your ideas would be much easier for us to discuss than random pointers to the old code.

Thanks for all of your work on this so far!

**Comment by breautek** [comment]
Think that might be a good idea, but I'll at least refactor everything that is simple enough to refactor. Then if there is any edge cases, I may skip over them until I can point them out in the draft for discussion.

**Comment by breautek** [comment]
I should a draft PR for this sometime next week.

Just finished refactoring, and fixing all the errors and messes I've made in doing so, at least back to the point where the unit tests is all green. Next week I'll be manually testing my branch and if I'm happy with it, a PR will soon follow.
