### ISSUE TITLE
Could not resolve all files for configuration ':CordovaLib:classpath'.

### ISSUE THREAD

**Issue by psw0714** [apache/cordova-android#785]
report an error  when i build android 
￼
￼
![image](https://user-images.githubusercontent.com/26177875/61344374-9f66b000-a883-11e9-8abd-4b6e1b3a9b5f.png)

**Comment by breautek** [comment]
Please do not delete the issue template. The screenshot is helpful to describe what you're seeing, but we still need to know your environment details and other information the issue template asks in order to provide help or suggestions.

Thanks.

**Comment by brodybits** [comment]
Please fill in the fields from the issue template, and [create a reproduction for us](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md).

**Comment by breautek** [comment]
Closing due to lack of response.
