### ISSUE TITLE
Google Play Console targetSdkVersion 28

### ISSUE THREAD

**Issue by khoabuidev** [apache/cordova-android#791]
Hi all,

I have just published my app to google play, I see this warning as below:

> Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.
> 
> From August 2019, new apps must target at least Android 9.0 (API level 28).
> From November 2019, app updates must target Android 9.0 (API level 28).

This is  informations about my app
<img width="755" alt="Screen Shot 2019-07-23 at 20 46 42" src="https://user-images.githubusercontent.com/12908326/61717374-22f43580-ad8b-11e9-9b4d-b2423746e278.png">

Could you please give me any suggest?

Regards,
Khoa

**Comment by timbru31** [comment]
Have you recently upgraded from an older cordova-android version? With v8.0.0 the new default targetSdkVersion is set to 28.
Can you try to remove and re-add the platform?

**Comment by khoabuidev** [comment]
> Have you recently upgraded from an older cordova-android version? With v8.0.0 the new default targetSdkVersion is set to 28.
> Can you try to remove and re-add the platform?

That problem happen when I use Android Studio to Generate Sign Bundle, but when I using command line to Build release app that problem not happen.
Thanks @timbru31

**Comment by ahmedaniss25** [comment]
problem fixed here : https://youtu.be/o4iDJWjfUHs
