### ISSUE TITLE
Cordova-Android 6.3.0 support for androidTargetSDK 28?

### ISSUE THREAD

**Issue by hungtranpg** [apache/cordova-android#793]
Hi all, 
My current project is cordova-android 6.3.0. Then I change android:targetSdkVersion=28 and build successful. But in the cordova document, cordova-android 6.X.X is only Supported Android API-Levels 16 - 26.
So I'm confused that my app meets Google Play's target API level requirement?
Do I need to remove platform android and add the new one (cordova 8.x)?

> "Starting August 1, 2019, Google Play requires that new apps target at least Android 9.0 (API level 28), and that app updates target Android 9.0 from November 1, 2019."

Thank you for your help!

**Comment by breautek** [comment]
> Do I need to remove platform android and add the new one (cordova 8.x)?

Yes, this is exactly it. Use...

```
cordova platform remove android
cordova platform add android
```

This should update `cordova-android` to `8.0.0`. When you update to version `8.0.0`, these settings will be used.

https://github.com/apache/cordova-android/blob/d5069b1030cb8cb7713157362584877718d10819/bin/templates/project/build.gradle#L42-L46

You may also have to update your android SDK and install the android build tools `28.0.3` using the `SDKManager`

**Comment by brodybits** [comment]
I would also recommend you consider using recent Cordova CLI, try updating plugins, update any other Cordova platforms, use recent Node.js version, etc.

**Comment by hungtranpg** [comment]
Thank you much!
Unfortunately, some plugins are currently not supported for Cordova-Android 8.0. 
So I will upgrade my app on later with your suggestion. 👍
