### ISSUE TITLE
The method remapUri  of PluginManager crash, java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by coderloveryan** [apache/cordova-android#794]
Uri remapUri(Uri uri) {
        Iterator var2 = this.pluginMap.values().iterator();
        while(var2.hasNext()) {
            CordovaPlugin plugin = (CordovaPlugin)var2.next();
            if (plugin != null) {
                Uri ret = plugin.remapUri(uri);
                if (ret != null) {
                    return ret;
                }
            }
        }
        return null;
    }
This problem occurs when testers perform monkey tests,When you frequently go in and out of a web page.synchronization lock should be added to this method or the pluginMap or use ConcurrentHashMap

**Comment by breautek** [comment]
You'll need to fill out the issue form properly. I did a search for `this.pluginMap.values()` across the latest version of `cordova-android` and found several results, but no results that used the `iterator()`. So I'm not sure where you are seeing this code. We need to know everything that the issue form asks you.

Thanks.

**Comment by coderloveryan** [comment]
Thank you for your answer. The reason for this is that the version I used hasn't been updated for a long time. The new version has been solved.
