### ISSUE TITLE
document.removeEventListener is invalid

### ISSUE THREAD

**Issue by nanasheng** [apache/cordova-android#795]
I wanted to remove the android physical return key after adding it to the listener, but this method didn't work.I wrote listening on the vue page，remove listener when page destroyed.
Adding listeners is fine, but removing them is not work.
document.addEventListener("backbutton", () => {
      console.log("addEventListener backbutton ############");     
 });

document.removeEventListener("backbutton", () => {
      console.log("removeEventListener backbutton ############");
 });

**Comment by breautek** [comment]
```javascript
document.addEventListener("backbutton", () => {
    console.log("addEventListener backbutton ############");
});

document.removeEventListener("backbutton", () => {
    console.log("removeEventListener backbutton ############");
});
```

In javascript, you are creating two different functions here, if you want to remove a listener, you need to keep a reference to it.

```javascript
var listener =  () => {
    console.log("addEventListener backbutton ############");
};

document.addEventListener("backbutton", listener);

// ... sometime later?

document.removeEventListener("backButton", listener);
```

**Comment by nanasheng** [comment]
That's the question. Thank you very much
