### ISSUE TITLE
Unable to build/run cordova android 8.0.0

### ISSUE THREAD

**Issue by CleatonPais** [apache/cordova-android#797]
# Bug Report

### What is expected to happen?
the basic application should be built and run, irrespective if an android phone is connected to the computer

### What does actually happen?
This error is encountered when the application is built or run

E:\cordova\plugin\teller>cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Cleaton\AppData\Local\Android\Sdk (DEPRECATED)
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

BUILD SUCCESSFUL in 19s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)
E:\cordova\plugin\teller\platforms\android\gradlew: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)

## Information

Steps to reproduce
1) Create new Cordova application
2) Add android platform version 8.0.0
3) Run/Build application

### Version information

Cordova - 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms - android 8.0.0
OS - Windows 10
Android Studio 3.4.2 

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by Wallethub** [comment]
This was the same problem here since day one - we are using 8.1.0-dev (the version that is on git) to be able to build against latest android api. Question is, when are you guys going to make this one available as a stable version so we can all feel comfortable - it looks pretty good to us. We tested from android 6 to Q, after updating all plugins related to deprecated APIs, things are fine.

**Comment by breautek** [comment]
Inside the `platforms/android/` directory you should see a `gradlew` command line executable. 

Can you run `gradlew --version` and post its output here please.

**Comment by CleatonPais** [comment]
this is what i got the commend

E:\cordova\plugin\teller\platforms\android>gradlew --version
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:38)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:26)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62)

**Comment by breautek** [comment]
@CleatonPais Well that's interesting. Something about your `gradlew` is really messed up. You should be seeing something similar to below:

```
------------------------------------------------------------
Gradle 4.10.3
------------------------------------------------------------

Build time:   2018-12-05 00:50:54 UTC
Revision:     e76905e3a1034e6f724566aeb985621347ff43bc

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_222 (Private Build 25.222-b10)
OS:           Linux 4.15.0-55-generic amd64
```

This is part of the Android SDK environment, so I think you're going to have to double check that your environment is installed properly. After you double check everything, you may have to unininstall & reinstall the `cordova-android` platform. I'll post some details about my Android SDK environment below, just in case they are helpful.

```
Android Studio 3.4.2
Android SDK Platform 28 (Note that platform 29 is not officially supported by Cordova yet, but it will **probably** still work)
Android SDK Build-Tools 28.0.3 (Cordova-android@8 will be looking for this version specifically)
Android SDK Platform-Tools 29.0.1
Android SDK Tools 26.1.1
openjdk version "1.8.0_222" (I'm using openjdk because I'm on linux, but Oracle Java should work just fine as well, as long as it is Java 8)
```

Note that if you use the Android Studio SDK Manager GUI, you may have to uncheck `Hide Obsolete Packages` and check `Show Package Details` to see older versions.

**Comment by CleatonPais** [comment]
> @CleatonPais Well that's interesting. Something about your `gradlew` is really messed up. You should be seeing something similar to below:
> 
> ```
> ------------------------------------------------------------
> Gradle 4.10.3
> ------------------------------------------------------------
> 
> Build time:   2018-12-05 00:50:54 UTC
> Revision:     e76905e3a1034e6f724566aeb985621347ff43bc
> 
> Kotlin DSL:   1.0-rc-6
> Kotlin:       1.2.61
> Groovy:       2.4.15
> Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
> JVM:          1.8.0_222 (Private Build 25.222-b10)
> OS:           Linux 4.15.0-55-generic amd64
> ```
> 
> This is part of the Android SDK environment, so I think you're going to have to double check that your environment is installed properly. After you double check everything, you may have to unininstall & reinstall the `cordova-android` platform. I'll post some details about my Android SDK environment below, just in case they are helpful.
> 
> ```
> Android Studio 3.4.2
> Android SDK Platform 28 (Note that platform 29 is not officially supported by Cordova yet, but it will **probably** still work)
> Android SDK Build-Tools 28.0.3 (Cordova-android@8 will be looking for this version specifically)
> Android SDK Platform-Tools 29.0.1
> Android SDK Tools 26.1.1
> openjdk version "1.8.0_222" (I'm using openjdk because I'm on linux, but Oracle Java should work just fine as well, as long as it is Java 8)
> ```
> 
> Note that if you use the Android Studio SDK Manager GUI, you may have to uncheck `Hide Obsolete Packages` and check `Show Package Details` to see older versions.

I have tried matching all the versions to what you recommended but still, get the same result at Gradle

**Comment by breautek** [comment]
Glad you found a solution that works for you.

I'll leave this year in case someone else has an issue where a specific version of gradle simply isn't working for some reason.

> If you want to use gradle wrapper - delete anything under:
`.gradle/wrapper/dists/`
and refresh gradle. The gradle wrapper will download from scratch and everything should work fine.

https://stackoverflow.com/a/45548105/4685664

In otherwords,

`rm -r ~/.gradle/wrapper/dists/gradle-4.10.3-all` may allow you to use `4.10.3` again as it will allow version `4.10.3` to be downloaded again from scratch.

**Comment by CleatonPais** [comment]
> I have tried matching all the versions to what you recommended but still, get the same result at Gradle
> 
> I tried this and it worked
> 
> I changed distributionUrl FROM `https\\://services.gradle.org/distributions/gradle-4.10.3-all.zip;` TO `https\\://services.gradle.org/distributions/gradle-4.10.2-all.zip;`
> in file `platforms\android\cordova\lib\builders\ProjectBuilder.js`
> 
> Also, the minimum version that can be used is 4.10.1

was able to build an application that works perfectly fine after the above change was made

**Comment by kayembechris** [comment]
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/pc/Library/Android/sdk (recommended setting)
ANDROID_HOME=/home/pc/Android/Sdk (DEPRECATED)
Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.6
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.

**Comment by CleatonPais** [comment]
In the command prompt run this command `java -version`, you should get the following result
`
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
`
If shows version 1.11 then you will need to uninstall that version of java and remove the path in environment variable of 1.11.
then download version 1.8 (can get his from the oracle site), install and set the path in environment variable for 1.8

**Comment by zhangv** [comment]
In cordova 9.0.1, when I run : 

`cordova build android --status`

I got this:

`
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in /Users/xxx/Develop/sites/biasura-diy/src-cordova/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip
`

**Comment by breautek** [comment]
>Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/home/pc/Library/Android/sdk (recommended setting)
ANDROID_HOME=/home/pc/Android/Sdk (DEPRECATED)
Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.6
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.

You path for java points to Java11. Android requires Java8. You'll need to install and point your `JAVA_HOME`/`PATH` variables to a java8 installation.

> A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.internal.version-check']
   > Minimum supported Gradle version is 5.6.4. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in /Users/xxx/src-cordova/gradle/wrapper/gradle-wrapper.properties to gradle-5.6.4-all.zip

This is caused by updating your android studio to a newer version. 8.x only supports gradle 4.x, but the latest version of android studio requires 5.6.x. Unfortunately 9.x is still in the works, but it supports the latest version of gradle. You can try using `cordova-android@nightly` or install from git directly as a quick workaround.

There's been a lot of comments that isn't actually related to the original post, so I'll be locking this thread. If you have found a bug, please do open a new ticket so that we can track the issues. If you have a support issue, then I would encourage you to use our [slack](http://slack.cordova.io/)
