### ISSUE TITLE
Setting different icon for push notification and launcher

### ISSUE THREAD

**Issue by felipe0silva** [apache/cordova-android#798]
# Bug Report

## Problem

Push notification icon to look nice have to be transparent and foreground white but launcher app icon need to be colorfull.

### What is expected to happen?

You must have an way to set different kind of icons to push notification and launcher.

### What does actually happen?

You use the same icon for both and this is looking horrible

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by dpogue** [comment]
The easiest way to accomplish this is to use `resource-file` in your config.xml to copy additional icons into the Android project, and tell your notification plugin to use the other icon resource.

**Comment by jcesarmobile** [comment]
As dpogue said, you can do it already, not a bug.
