### ISSUE TITLE
App is restarted on split-screen

### ISSUE THREAD

**Issue by ttencate** [apache/cordova-android#799]
# Bug Report

### What is expected to happen?

App keeps running in split screen, just resized.

### What does actually happen?

Activity is restarted.

### Command or Code

Press and hold the "square" button on any modern Android device to trigger split screen mode. Notice how the Cordova app is restarted.

This is fixed if I add the following to my `config.xml`:

    <edit-config file="AndroidManifest.xml" target="/manifest/application/activity[@android:name='MainActivity']" mode="merge">
      <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" />
    </edit-config>

This is the default list of `configChanges` with `|smallestScreenSize|screenLayout|uiMode` appended. See docs: https://developer.android.com/guide/topics/manifest/activity-element#config

I propose that at least `smallestScreenSize|screenLayout` are added to the default `AndroidManifest.xml`. `uiMode` is not necessary to fix this issue, but should maybe be in the default list as well.

### Environment, Platform, Device

Android 7.1.2

### Version information

Cordova 9.0.0  
Cordova Android 8.0.0

## Checklist

- [x] I searched for existing GitHub issues (#744 is a duplicate, but folks explicitly requested a new issue)
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Thank you for filling out completely, and it's awesome you even provided a possible solution.

We will welcome a PR, or if you prefer I  can test this out and do a PR.

**Comment by ttencate** [comment]
The code change is [tri](https://github.com/apache/cordova-android/blob/485e6e0e4d4ae4521c590fbd999c2c575940d593/bin/templates/project/AndroidManifest.xml#L40)[vial](https://github.com/apache/cordova-android/blob/485e6e0e4d4ae4521c590fbd999c2c575940d593/spec/unit/AndroidManifest.spec.js#L41) but indeed it's the testing where I'd prefer someone more experienced to take over.

**Comment by breautek** [comment]
I'd also like to add the ability to disable the resize activity altogether as discussed in #744 just to have a more complete resize activity support feature. I'll start one right now, but not sure if I'll have time to publish a PR today.
