### ISSUE TITLE
Can't tap to edit on input text on Android 9

### ISSUE THREAD

**Issue by BJR7** [apache/cordova-android#804]
# Bug Report
Can't tap to edit on input text on Android 9

## Problem

Can't tap to edit on input text on Android 9

### What is expected to happen?

Tap the edit input, so i can enter my username or password.

### What does actually happen?

After making a manual action like tap a button to remember password, only then i'm able to tap the edit input to enter my username or password.

## Information

After generate the .apk and install it on my device with OS Android 9,  i try to tap the username or password input but i does not work until i tap other component like a slider to remember the password, or tap the button to enter my fingerprint.

### Command or Code

ionic cordova build android --prod

### Environment, Platform, Device

Devices with Android 9 installed.

### Version information

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 1.2.1, (and 18 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v8.11.2 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS
   Xcode      : Xcode 10.2.1 Build version 10E1001

## Checklist

- [x] I searched for existing GitHub issues
- [] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Generally speaking, Cordova is pretty un-opinionated of what happens inside the webview so this is likely an issue with HTML, CSS, or JavaScript code. 

Are you able to provide a [sample app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) that reproduces this issue with the minimal amount of setup? I'd be happy to take a look.

**Comment by nascarjake** [comment]
I have the same issue with ion-inputs in ionic 3 - only for Android 9. Perhaps its an ionic issue that surfaced due to the android 9 update.

**Comment by StefanRein** [comment]
@breautek I was just about to verify with real devices (Samsung / Android One) and the simulator and at least with my setup it worked fine with the pure HTMLInputElement all of the time.

But it was not working with the Ionic Inputs, until some elements had focus. Especially document.hasFocus() returned all the time false when it did not work. When it returned true (after setting some focus with interaction and not code), it worked.

I poked a little around and if I remove ALL of: *.preventDefault() and *.stopPropagation() calls in the `ionic-angular package (version 3)` repository, it **is** working.

So the next day my time I will figure out what exactly breaks and will keep you guys updated. 

If someone is also down this road figuring out what is happening and is done before me, please share this.

**Comment by StefanRein** [comment]
**It works** by commenting exactly out this line of code:
https://github.com/ionic-team/ionic-v3/blob/master/src/components/input/input.ts#L614

Try it out in your installed package:
`node_modules/ionic-angular/components/input/input.js`

**Comment by breautek** [comment]
Sounds like you should raise an issue with the ionic-team :smile: 

Feel free to provide a link to the ionic-team issue here if you create one, it might help other people track this issue as we do get a lot of ionic related questions here.

**Comment by alex-steinberg** [comment]
ionic-team/ionic-v3#1056

**Comment by dpogue** [comment]
It seems like this is an Ionic problem (see https://github.com/ionic-team/ionic-v3/issues/1056) so I'm going to mark this issue as closed because it's outside the scope of cordova-android.

**Comment by BJR7** [comment]
Thank you guys for your help, @StefanRein your solution worked for me.

**Comment by suryakvm** [comment]
Thanks alot for your help @StefanRein. it worked
