### ISSUE TITLE
When is the official release of 8.0.0?

### ISSUE THREAD

**Issue by sandhyachowdary** [apache/cordova-android#806]
Hi, wanted to know when you are planning to release 8.0.0.
Also wanted to know whether the car file is available at bintary: https://bintray.com/cordova/maven/cordova-android/8.0.0 is the final version or could uses expect any changes when the release is official.

**Comment by breautek** [comment]
`cordova-android` 8.0.0 is released, and has been released for some time now. Do you mean 8.1.0?

**Comment by sandhyachowdary** [comment]
Thanks @breautek,
But the same is not released in the tags(8.0.0). Is there any probable date of the same.

**Comment by breautek** [comment]
It is tagged...

https://github.com/apache/cordova-android/tree/rel/8.0.0

`cordova platform add https://github.com/apache/cordova-android.git#rel/8.0.0`
`cordova platform add cordova-android@8.0.0`

https://www.npmjs.com/package/cordova-android/v/8.0.0

**Comment by brodybits** [comment]
Thanks @breautek!

Closing as invalid.

I recommend sending this kind of question to the mailing list, see contact info here:  https://cordova.apache.org/contact/
