### ISSUE TITLE
<config-file> blocks in config.xml overwrites those in plugin.xml

### ISSUE THREAD

**Issue by dpa99c** [apache/cordova-android#809]
# Bug Report

## Problem
`<config-file target="AndroidManifest.xml">` blocks in `config.xml` seems to overwrite similar blocks added via the `plugin.xml` of plugins.
This seems to be a regression bug in `cordova@9` / `cordova-lib@9)` since the same issue does not occur using `cordova@8` / `cordova-lib@8)`.

### What is expected to happen?
On adding the Android platform, the contents of `<config-file>` blocks from both `config.xml` and `plugin.xml` appear in `AndroidManifest.xml`.

### What does actually happen?
On adding the Android platform, only the contents of `<config-file>` blocks from both `config.xml` appear in `AndroidManifest.xml`. Those from `plugin.xml` are missing.

## Information

I've created a [test project](http://ge.tt/3FYiuXx2) to illustrate the issue.

It contains a dummy plugin with the following `<config-file>` blocks in its `plugin.xml`:

    <config-file target="AndroidManifest.xml" parent="/*">
      <meta-data android:name="manifest_block" android:value="from_plugin_xml" />
    </config-file>

    <config-file target="AndroidManifest.xml" parent="application">
      <meta-data android:name="application_block" android:value="from_plugin_xml" />
    </config-file>

And the following blocks in `config.xml`:

    <config-file target="AndroidManifest.xml" parent="/*">
        <meta-data android:name="manifest_block" android:value="from_config_xml" />
    </config-file>
    <config-file target="AndroidManifest.xml" parent="application">
        <meta-data android:name="application_block" android:value="from_config_xml" />
    </config-file>

On running `cordova platform add android@8.0.0` with `cordova@9.0.0 (cordova-lib@9.0.1)`, the resulting `AndroidManifest.xml` is:

    <manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="io.cordova.hellocordova" xmlns:android="http://schemas.android.com/apk/res/android">
        <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
            <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
                <intent-filter android:label="@string/launcher_name">
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            <meta-data android:name="application_block" android:value="from_config_xml" />
        </application>
        <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
        <meta-data android:name="manifest_block" android:value="from_config_xml" />
    </manifest>

As can be seen, it contains the entries for `config.xml` but not from the plugin's `plugin.xml`.

On running `cordova platform add android@8.0.0` with `8.1.2 (cordova-lib@8.1.1)`, the resulting `AndroidManifest.xml` is:

    <?xml version='1.0' encoding='utf-8'?>
    <manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="io.cordova.hellocordova" xmlns:android="http://schemas.android.com/apk/res/android">
        <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
            <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
                <intent-filter android:label="@string/launcher_name">
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            <meta-data android:name="application_block" android:value="from_config_xml" />
            <meta-data android:name="application_block" android:value="from_plugin_xml" />
        </application>
        <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
        <meta-data android:name="manifest_block" android:value="from_config_xml" />
        <meta-data android:name="manifest_block" android:value="from_plugin_xml" />
    </manifest>

i.e. the entries from `plugin.xml` are not missing and the result is as expected.

If I remove the `<config-file>` blocks from `config.xml` and run `cordova platform add android@8.0.0` with `cordova@9.0.0 (cordova-lib@9.0.1)`, the resulting `AndroidManifest.xml` is:

    <?xml version='1.0' encoding='utf-8'?>
    <manifest android:hardwareAccelerated="true" android:versionCode="10000" android:versionName="1.0.0" package="io.cordova.hellocordova" xmlns:android="http://schemas.android.com/apk/res/android">
        <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application android:hardwareAccelerated="true" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:supportsRtl="true">
            <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
                <intent-filter android:label="@string/launcher_name">
                    <action android:name="android.intent.action.MAIN" />
                    <category android:name="android.intent.category.LAUNCHER" />
                </intent-filter>
            </activity>
            <meta-data android:name="application_block" android:value="from_plugin_xml" />
        </application>
        <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="28" />
        <meta-data android:name="manifest_block" android:value="from_plugin_xml" />
    </manifest>

Now the `<config-file>` blocks from `plugin.xml` are present, indicated a conflict with those in `config.xml` is causing the issue.

For now I have worked around this issue by installing [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) in my projects and using `<custom-config-file>` blocks in the `config.xml`.

### Command or Code

To reproduce the issue:
- Download and unzip the [test project](http://ge.tt/3FYiuXx2)
- Using `cordova@9` / `cordova-lib@9)`, run `cordova platform add android@8.0.0`
- Observe that `platforms/android/app/src/main/AndroidManifest.xml` doesn't contain the contents of `<config-file>` blocks from the `plugin.xml`

### Environment, Platform, Device

Android platform

### Version information

$ cordova -v
9.0.0 (cordova-lib@9.0.1)

$ node -v
v10.15.3

$ nvm version
1.1.6

OS: Windows 10 1809

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by erisu** [comment]
@dpa99c I think this is the same as these tickets:

* https://github.com/apache/cordova/issues/95
* https://github.com/apache/cordova-cli/issues/389
* https://github.com/apache/cordova-android/issues/704

**Comment by dpa99c** [comment]
@erisu Maybe but those seem to focus on `<edit-config>` as opposed to `<config-file>`.

At least here is a reproducible test case which clearly illustrates the issue so hopefully should be easy to identify & fix.

**Comment by dpa99c** [comment]
> What seems to have been described as the solution when user's need to define additional parameters that uses `edit-config` and `config-file`, or modify those that `plugins.xml` defines, the user must redefine all plugins as well in `config.xml`
> 
> Quote from ticket with regards to permissions:
> 
> > the user must describe all permissions in config.xml if the user want to use additional permission which conflict to plugin.xml.

This seems to suggest that if you want to define `edit-config` or `config-file` blocks in `config.xml` that target the same elements (so cause conflict in `AndroidManifest.xml`) as `edit-config` and `config-file` blocks in `plugin.xml, you need to duplicate all the relevant `edit-config` or `config-file` blocks from the various `plugin.xml` into the `config.xml`?

**Comment by erisu** [comment]
Yes, from how I interpreted that [post's reply](https://github.com/apache/cordova/issues/95#issuecomment-502529643), it suggests that you will need to duplicate all the relevant blocks.

**Comment by dpa99c** [comment]
Not sure I like that idea - what if the `edit-config` or `config-file` blocks in `plugin.xml` use plugin variables to set the values?

	<preference name="SOME_PLUGIN_VAR" default="some_default_value" />
	<config-file target="AndroidManifest.xml" parent="application">
		<foo>$SOME_PLUGIN_VAR</foo>
	</config-file>

I think I'll stick with my own workaround which is installing [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) in my projects and using `<custom-config-file>` blocks in the `config.xml`.
That means the `edit-config` or `config-file` blocks in `plugin.xml` will function correctly and `cordova-custom-config` will add the additional config blocks I need.
If I needed to use `<edit-config>` in `config.xml`, `cordova-custom-config` has an equivalent `<custom-preference>` e.g. to modify element attributes.

**Comment by breautek** [comment]
#801 may be related as well. Describes the same behaviour, but again, with the use of `<edit-config>`...

**Comment by nero120** [comment]
@erisu I'm experiencing a similar issue when using cordova-plugin-snackbar, as I also have `edit-config` and `config-file` sections in my config.xml.

However in addition to the conflict error I'm experiencing plugin files being deleted from cordova\platforms\android\app\src\main\assets\www\plugins when I attempt to `cordova run`, so when the app runs it's unable to find the plugin js files.

Is this issue also fixed by your merge?

**Comment by ollydixon** [comment]
Was there a solution for this? We are doing research into Ionic and so far nothing works as written in the docs. Our config.xml under the ios/App/App directory.. gets overwritten each time.

**Comment by sithwarrior** [comment]
> os/App/App directory.. gets overwritten each time.

you should never manually edit the config files inside the platform folders, you should only edit the root config.xml.
Everything inside the platform folders, are generated when adding platforms or building your app.

**Comment by ollydixon** [comment]
@sithwarrior turns out the documentation is completly wrong / doesn't exist when using Capacitor. Tbh the platform is a mess, there's conflicting documetetion all over the offical pages; doesn't mean I won't continue to research; still looking like a good solutions reguardless.
