### ISSUE TITLE
cordova-plugin-splashscreen BUG

### ISSUE THREAD

**Issue by abcd498936590** [apache/cordova-android#811]
I used the (cordova-plugin-splashscreen) plugin, which conflicts with the app's backButton event. When I enter the app, click the back button. backButton does not prevent the application from exiting.
When I enter the app, I need to click on document.body and this bug won't appear.
I removed the plugin and everything is fine.

how to solve this problem

**Comment by janpio** [comment]
Discussion and possible solution (for the plugin) in https://github.com/apache/cordova-plugin-splashscreen/pull/225
