### ISSUE TITLE
Task 'undefined' not found in root project 'android'. master branch

### ISSUE THREAD

**Issue by tehmaestro** [apache/cordova-android#813]
# Bug Report

## Problem
I get the following error when running `cordova clean`
```
Task 'undefined' not found in root project 'android'.
```

### What is expected to happen?
It should just work and clean the project

### What does actually happen?
I get the error I mentioned above.

## Information

I was trying to update cordova-android on an existing project, from version 7.1.4 to using the master branch, as I wanted to build my project with SDK 28. However, the issue is present in a newly created project too. 

The reason I am using the master branch is because 8.0.0 still injects minSdkVersion in AndroidManifest file, and this makes the build fail.

### Command or Code

```
cordova create my-app
cd my-app
cordova platform add https://github.com/apache/cordova-android.git
cordova clean
```

This will produce the above mentioned error.

### Environment, Platform, Device

Windows PC

### Version information

Cordova CLI -> 8.1.2
Cordova Android -> Master branch
Node -> 6.11.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Thank you for raising this issue. I was able to reproduce this on the following environment:

```
cordova -v
9.0.0 (cordova-lib@9.0.1)

node -v
v10.16.0

cordova-android
8.1.0-dev (current master)

OS
Ubuntu 18.04

javac -version
javac 1.8.0_222
```

Also important to note that the clean command does work on `cordova-android@8.0.0`

**Comment by tehmaestro** [comment]
Thank you for looking into  this.
