### ISSUE TITLE
Android Studio. The minSdk version should not be declared in the manifest file.

### ISSUE THREAD

**Issue by exxbrain** [apache/cordova-android#818]
# Bug Report
When I build my project in Android Studio after update to Cordova-Android 8.0.0 I see next error:
```
ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Move minSdkVersion to build files and sync project
Affected Modules: CordovaLib, app
```

**Comment by timbru31** [comment]
Please use the search before randomly open issues that completely ignore the issue template. It's already fixed in master, but not yet releases: https://github.com/apache/cordova-android/issues/629#issuecomment-480475051
