### ISSUE TITLE
"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found." on Android 5 and lower versions

### ISSUE THREAD

**Issue by nam-bash** [apache/cordova-android#819]
## Problem
Hi.
My app is working fine on Android >= 6 version but it throws exception **"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."** on Android <= 5 version when any plugin try's to access my server using https.

for example, I'm using cordova-plugin-file-transfer@1.5.1 to upload files on my server but it throws exception **"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found."** while uploading using https  but it works fine if I pass parameter **trustAllHosts = true.**

### Environment, Platform, Device
Environment:
  OS: win32
  Node: v11.7.0
  npm: 6.5.0

Installed platforms:
  android 7.0.0

Java JDK: installed 1.8.0
Android SDK: installed true
Android target: installed android-28,android-27,android-26,android-25
Gradle: installed C:\Program Files\Android\Android Studio\gradle\gradle-4.6\bin\gradle

### Version information

cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

## Plugins
    "com.xmartlabs.cordova.market": "https://github.com/xmartlabs/cordova-plugin-market",
    "cordova-android": "^7.0.0",
    "cordova-ios": "4.2.0",
    "cordova-plugin-app-event": "1.2.0",
    "cordova-plugin-badge": "~0.8.8",
    "cordova-plugin-camera": "4.1.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-console": "1.0.3",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-dialogs": "https://github.com/apache/cordova-plugin-dialogs.git",
    "cordova-plugin-file": "4.2.0",
    "cordova-plugin-file-transfer": "1.5.1",
    "cordova-plugin-geolocation": "2.2.0",
    "cordova-plugin-inappbrowser": "1.4.0",
    "cordova-plugin-mauron85-background-geolocation": "https://github.com/mauron85/cordova-plugin-background-geolocation",
    "cordova-plugin-network-information": "1.3.0",
    "cordova-plugin-splashscreen": "4.0.0",
    "cordova-plugin-whitelist": "1",
    "cordova-support-google-services": "^1.1.0",
    "cordova-windows": "4.4.2",
    "cordova.plugins.diagnostic": "https://github.com/dpa99c/cordova-diagnostic-plugin",
    "phonegap-plugin-multidex": "~1.0.0",
    "phonegap-plugin-push": "^2.1.2",
    "polarcape-cordova-plugin-document-handler": "^1.0.14"

**Comment by nam-bash** [comment]
Thank you @breautek for your response! 
my same app is working fine with other 2 different https urls one is deployed on same server (where original is deployed ) and second one is on other server.

SSL cert for Original and other 2 urls  are from different provides as shown in below images.

### SSL provider for original url
![orignalUrl](https://user-images.githubusercontent.com/38281747/63772781-40b93b00-c8f3-11e9-9d2f-986ac4ffc702.JPG)
### SSL provider for other urls
![otherUrls](https://user-images.githubusercontent.com/38281747/63772825-562e6500-c8f3-11e9-81c4-6d49e1681f9f.JPG)

if this is TLS 1.0  issue then is there any way to enable TLS 1.1/1.2 on older android versions or any cordova-plugin for that purpose ?

**Comment by nam-bash** [comment]
**Solved** by reconfiguration of SSL Certificate  on my server.
**the problem was due to chain certificate**  so I contact my SSL provider they issue me a new  SSL certificate and my problem is resolved.

**Comment by pradipvadher** [comment]
can you please tell me where to write "trustAllHosts = true."?

**Comment by breautek** [comment]
> **Solved** by reconfiguration of SSL Certificate on my server.
> **the problem was due to chain certificate** so I contact my SSL provider they issue me a new SSL certificate and my problem is resolved.

Glad you've found your solution. I'll be closing this issue now.
