### ISSUE TITLE
The connection to the server was unsuccessful.

### ISSUE THREAD

**Issue by theLMGN** [apache/cordova-android#826]
# Bug Report

## Problem

App does not launch on Android.

### What is expected to happen?

App launches like it should on Android

### What does actually happen?

A white screen shows for a few seconds, before erroring out with `The connection to the server was unsuccessful.` error

## Information

This happens on both my main project and a freshly created Cordova project with no files modified.

### Command or Code

`cordova run android`

### Environment, Platform, Device

Google Nexus 6P, Android 9 (16.0-20181001-UNOFFICIAL-angler)

WebView implementation: Chrome 76.0.3809.132

### Version information

Cordova CLI: 9.0.0 (cordova-lib@9.0.1)
cordova-android: 8.0.0
cordova-common: 3.2.0
cordova-plugin-whitelist: 1.3.4

macOS: 10.14.6 (18G87)

Gradle: 5.5.1
JDK: 1.8.0
![image](https://user-images.githubusercontent.com/12257112/64370184-d3ee2100-d015-11e9-97f6-f4d4ef1e2cc8.png)

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
This error is triggered by

https://github.com/apache/cordova-android/blob/c93e3e9f6fc91e268d51bc06e6ee70621523351f/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L147-L166

Which occurs after sometime has passed while attempting to load the html file.

Following the steps I failed to reproduce this issue, but this could be device specific. The reproduction steps works fine on Samsung Galaxy Note 9, running Android 9, on Chrome 76.0.3809.132 webview.

Running `adb logcat CordovaWebViewImpl *:S CordovaWebViewImpl` may provide more hints on why it is failing to load.

**Comment by theLMGN** [comment]
@breautek Not much

```09-05 20:13:53.701 29497 29497 D CordovaWebViewImpl: >>> loadUrl(file:///android_asset/www/index.html)
09-05 20:14:13.707 29497 29497 E CordovaWebViewImpl: CordovaWebView: TIMEOUT ERROR!
09-05 20:14:20.612 29497 29497 D CordovaWebViewImpl: >>> loadUrl(about:blank)

```

**Comment by theLMGN** [comment]
After a device wipe, the same issue occures. Trying the stock rom.

**Comment by theLMGN** [comment]
Okay, it seems this was an issue with the build of LineageOS I was using.

**Comment by timbru31** [comment]
I’m closing this as resolved then :)
