### ISSUE TITLE
Gradle Sync Issues: "NdkCompile is no longer supported"

### ISSUE THREAD

**Issue by JunlingQin** [apache/cordova-android#834]
# Bug Report
INFO: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported
Affected Modules: CordovaLib, app

### environment：
Android Studio3.5
cordova  version 9.0.0 (cordova-lib@9.0.1)
classpath 'com.android.tools.build:gradle:3.5.0'
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

**Comment by breautek** [comment]
Please also provide your `cordova-android` version you are using. You can find this by running

`cordova platform ls`

In your cordova project folder.

Thanks

**Comment by JunlingQin** [comment]
Installed platforms:
  android 8.1.0

**Comment by almothafar** [comment]
I can see the issue here:

```console
> Configure project :app
WARNING: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported


WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
FCM PLUGIN GRADLE TOOLS VERSION: 3.5.0registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Configure project :CordovaLib
....
```


```
almothafar$ cordova platform ls
Installed platforms:
  android 8.1.0
  ios 5.0.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

```

**Comment by breautek** [comment]
This must be the offending line:

https://github.com/apache/cordova-android/blob/c35a990c09f1ab278873754eb7f81e52250893a3/bin/templates/cordova/lib/config/GradlePropertiesParser.js#L40

Someone will have to do research if it is safe to simply remove this line. Considering it's there to support deprecated NDK, it probably is safe to do so, but will require a major version bump.

**Comment by rajashekaranugu** [comment]
facing the same issue
WARNING: The following project options are deprecated and have been removed: 
android.useDeprecatedNdk
NdkCompile is no longer supported
Affected Modules: CordovaLib, app
<img width="852" alt="Screen Shot 2019-10-16 at 11 55 22 AM" src="https://user-images.githubusercontent.com/52263762/67035075-8669d700-f0de-11e9-8fda-15eddd58f5e6.png">

**Comment by breautek** [comment]
I'm unable reproduce this with a fresh simple app. I think this might be triggered by a plugin.

**Comment by helzgate** [comment]
This may not be 100% relevant to original post but I am sharing some important findings:

I ran the following commands and nothing else:
```
cordova create deleteme com.delete.me deleteme
cd deleteme
cordova platform add android
```
I search the deleteme folder for all `GradlePropertiesParser.js` files and it finds 2 (and one test file)

They both contain the following:
```
// allow NDK to be used - required by Gradle 1.5 plugin
            'android.useDeprecatedNdk': 'true'
```

I'm using:
```
cordova-android@8.1.0
9.0.0 (cordova-lib@9.0.1)
```

cordova build runs file with no errors.

If I delete the above project and recreate it from scratch using the same steps them open it in Android Studio I get the following message:

![clickok](https://user-images.githubusercontent.com/7506982/68872323-76381e00-06c3-11ea-9b9d-7170daeceb8e.png)

I click "OK".

I can build the apk with no errors.

But, if I update the Gradle plugin using the following prompt:

![plugin2](https://user-images.githubusercontent.com/7506982/68872623-f494c000-06c3-11ea-9ca6-7049e63f69e6.png)


I now get the Gradle sync error mentioned in this post.

Here is what Android Studio shows for the project gradle versions:

![projectStructure](https://user-images.githubusercontent.com/7506982/68872991-84d30500-06c4-11ea-8d85-be23c34283b2.png)

**Comment by breautek** [comment]
@helzgate 

Interesting. `cordova-android` 8.1.0 technically only supports gradle 4.x. Gradle upgrade will happen on the next major (https://github.com/apache/cordova-android/pull/792) however when I wrote that PR I had no problem upgrading to the latest gradle version. It just worked with the current cordova-android codebase.

So this leads me to believe something in the android gradle plugin is what is triggering the problem? Do you know what version this was before you did the plugin update?

**Comment by helzgate** [comment]
@breautek 

Plugin: 3.3.0
Gradle Version: 5.4.1

**Comment by breautek** [comment]
Thanks. Upgrading the plugin version makes 5.x required, and 5.x appears to what triggers the problem.

Like I said though earlier, cordova-android 8 does not and will not support 5. Gradle 5 support will come with cordova-android 9.

**Comment by almothafar** [comment]
I do use Gradle 5.6.4 now so yes I get some warnings, but I don't see any issues that stops the build process, and btw, Gradle 6 is out :)
