### ISSUE TITLE
Is there a way Cordova Build Android can work without installing gradle? I just want to use gradlewrapper instead.

### ISSUE THREAD

**Issue by rnandy** [apache/cordova-android#838]
**Our build machines do not have gradle installation. We just use ./gradlew (gradle wrapper) to build android projects. Is there a way to run "cordova build android" command with gradlewrapper only?**

Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by breautek** [comment]
> Our build machines do not have gradle installation.

Huh? Cordova's build command for android should install the gradle wrapper for you if it's missing.

**Comment by rnandy** [comment]
Thanks @breautek for your quick response! 
So, I have gradle/wrapper inside my platforms/android folder but everytime I try to execute "cordova build android" it gives me the following error 
"**Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio**"

Once I install gradle this error goes away. Is there any specific settings need to be enabled for gradlewrapper?

**Comment by rnandy** [comment]
Thanks you @breautek for your response! So, looks like gradle installation is mandatory in order to "cordova build android" to work? Is there any workaround without installing gradle in the system?

**Comment by breautek** [comment]
> Thanks you @breautek for your response! So, looks like gradle installation is mandatory in order to "cordova build android" to work? Is there any workaround without installing gradle in the system?

No, this is a requirement of the android SDK, not Cordova.
