### ISSUE TITLE
Back Button after Full Screen Mode

### ISSUE THREAD

**Issue by josephlodero** [apache/cordova-android#839]
# Bug Report

## Problem
Back Button will exit the app after the full screen mode it only happens in API 28 but in API 27 to down is working properly

### What is expected to happen?
back button should be go back to main page after the full screen mode

### What does actually happen?
after the full screen mode and use the back button it will crash/exit the app

### Environment, Platform, Device
Android Device

### Version information
cordova 9
cordova-android 8.1.0

**Comment by breautek** [comment]
Is it possible that you can provide a sample reproduction app that I can use as a test app?

https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

This would help me focus on debugging. Thanks.

**Comment by josephlodero** [comment]
@breautek 
https://github.com/josephlodero/cordova-fullscreen

steps:
1: clone
2: npm install
3: cordova platform add android
4 cordova emulate android

Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0

note: the video is not working due to cross origin but i think it doesnt matter. ther problem is the after the fullscreen mode and then use the platform backbutton

thank you for your help!

**Comment by breautek** [comment]
Thanks, I'll try to take a look sometime this week.

**Comment by breautek** [comment]
@josephlodero Sorry, can you create me a *non* ionic reproduction app? I've never used ionic before nor am I very experienced in the angular framework. Additionally having a pure cordova reproduction app will also help prove that the issue is indeed coming from Cordova and nothing that the ionic frameworks adds/overrides.

**Comment by josephlodero** [comment]
@breautek 
Hi! try this one : https://github.com/josephlodero/cordovaapp
i just wrapped my angular app to cordova i hope this one will do.
thanks!

**Comment by breautek** [comment]
Thanks, if I don't make a comment within a week, don't hesitate to ping me, but I'll try to take a look over the weekend.

**Comment by breautek** [comment]
This is actually the same issue as https://github.com/apache/cordova-android/issues/822
