### ISSUE TITLE
When is Android X support coming?

### ISSUE THREAD

**Issue by semerda** [apache/cordova-android#840]
When is Android X support coming?

**Comment by brodybits** [comment]
Unfortunately we cannot make any promises due to lack of resources, see apache/cordova#163

**Comment by breautek** [comment]
In the meantime, as a workaround there are 2 plugins available to enable androidx

https://github.com/dpa99c/cordova-plugin-androidx
https://github.com/dpa99c/cordova-plugin-androidx-adapter

**Comment by jcesarmobile** [comment]
closing as duplicate of https://github.com/apache/cordova-android/issues/565
