### ISSUE TITLE
Bridge access attempt with wrong secret token

### ISSUE THREAD

**Issue by pjc0247** [apache/cordova-android#843]
# Bug Report

### What is expected to happen?
Every plugin native call does not work.

### What does actually happen?
All native call does not work after using `cordova-plugin-geolocation`. 
But, it seems that this issue is not related with the plugin, so i posted here.
(the plugin didn't changed since June)
https://github.com/apache/cordova-plugin-geolocation/releases

## Information

```
10-14 10:04:46.830  3924  4072 E CordovaBridge: Bridge access attempt with wrong secret token, possibly from malicious code. Disabling exec() bridge!: 
10-14 10:04:46.830  3924  4072 W System.err: java.lang.IllegalAccessException: 
10-14 10:04:46.830  3924  4072 W System.err: 	at org.apache.cordova.CordovaBridge.verifySecret(CordovaBridge.java:100): 
10-14 10:04:46.830  3924  4072 W System.err: 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:45): 
10-14 10:04:46.830  3924  4072 W System.err: 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41): 
10-14 10:04:46.830  3924  4072 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method): 
10-14 10:04:46.830  3924  4072 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:326): 
10-14 10:04:46.830  3924  4072 W System.err: 	at android.os.Looper.loop(Looper.java:181): 
10-14 10:04:46.830  3924  4072 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65): 
10-14 10:04:46.834  3924  3924 D SystemWebChromeClient: http://localhost/tab1-tab1-module-es2015.js: Line 124 : Error: Java exception was raised during method invocation: 
10-14 10:04:46.834  3924  3924 I chromium: [INFO:CONSOLE(124)] "Error: Java exception was raised during method invocation", source: http://localhost/tab1-tab1-module-es2015.js (124): 
10-14 10:04:47.007  3924  3924 D SystemWebChromeClient: http://call.ittonion.com/web_view/js/main.js: Line 20 : Uncaught TypeError: $(...).button is not a function: 
10-14 10:04:47.007  3924  3924 I chromium: [INFO:CONSOLE(20)] "Uncaught TypeError: $(...).button is not a function", source: http://call.ittonion.com/web_view/js/main.js (20): 

```

### Command or Code

The code is pretty simple, no setup required. it may not help you.
```ts
await this.gps.getCurrentPosition();
```

### Environment, Platform, Device

Samsung Galaxy S10

### Version information

```
9.0.0 (cordova-lib@9.0.1)
```
```
"cordova-android": "8.1.0",
    "cordova-clipboard": "^1.3.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-device": "2.0.2",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-qrscanner": "^3.0.1",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "2.4.2",
    "cordova-plugin-whitelist": "1.3.3",
```

## Checklist

- [x ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by breautek** [comment]
>"Uncaught TypeError: $(...).button is not a function", source: http://call.ittonion.com/web_view/js/main.js (20):

Whatever what is triggering this error is likely disrupting the javascript call routine preventing everything from being setup properly.

**Comment by pjc0247** [comment]
@breautek That error occurs inside `iframe`. it doest not affect the app

**Comment by pjc0247** [comment]
it suddenly happened to me. (works fine before)

**Comment by pjc0247** [comment]
@breautek The problem was mine. `iframe` loads `http://localhost/null` for some reason. this requests `cordova.js` again breaks everything.

I know there is an error message that warns duplicated loading in the __same page__. but it would be great to add additional error message to help out some people like me.
