### ISSUE TITLE
Broken app icon with cordova android 8.0.0/8.0.1

### ISSUE THREAD

**Issue by gambarle** [apache/cordova-android#847]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
After updating Cordova Android to version 8.0.0/8.0.1, newer Android phones show generic Android icon for the app on the home screen of the phone, instead of the app icon generated in the resource folder of the project.

## Information

The issue might only be present for phones that can show adaptive icons
### Environment, Platform, Device

Ionic 3.20
Cordova Android 8.0.0

### Version information

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1) 

local packages:

    @ionic/app-scripts : 3.2.4
    Cordova Platforms  : android 8.0.0 browser 5.0.4 ios 5.0.1
    Ionic Framework    : ionic-angular 3.9.8

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.1.3 
    Node       : v8.11.1
    npm        : 5.6.0 
    OS         : macOS
    Xcode      : Xcode 11.0 Build version 11A420a 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by cmgustavo** [comment]
Same issue here.

**Comment by gambarle** [comment]
The icon not showing is triggered when I build with --release flag

**Comment by gambarle** [comment]
Is there any news on this issue?

**Comment by breautek** [comment]
Sorry for the lack of responses here...

You'll likely missing the icon with the proper resolution for those newer phones (though I'm not sure why the problem only appears with the `--release` flag...)

Are you using adaptive icons or traditional?

**Comment by gambarle** [comment]
Hi,

I'm using traditional icons, but I have tried them both.
The icons are generated by ionic cordova resources, from an icon.png 1024x1024, and a splashscreen.png 2732x2732.
If I downgrade Cordova Android to below 8, the issue does not occur, so my initial assessment is that the issue is with Cordova Android >= 8

Thank you for your time :-)

**Comment by breautek** [comment]
> The icons are generated by ionic cordova resources, from an icon.png 1024x1024

I'm assuming when you generate your icons from your `1024x1024` image, you're different sizes as listed in the Launcher Icon section in https://iconhandbook.co.uk/reference/chart/android/ correct?

**Comment by gambarle** [comment]
I found out that I need to use cordova-res, too generate the icons and splash screens instead of Ionic resources.
[https://github.com/ionic-team/cordova-res]

Thank you for your time.

**Comment by gambarle** [comment]
The fix was a fluke, since the problem only occurs after a build with the --release flag.

Apparently I hadn't verified it properly.

The issue persists even after using Cordova Android 9.0.0

**Comment by gambarle** [comment]
@breautek 
Realised i didn't answer your question.
The cordova-res generates the needed icon sizes in the appropriate resources/android/icon folder.

I'm currently running Cordova Android 9.0.0 with Cordova-CLI 10.0.0, 
but it does not work with Cordova Android 8 with Cordova-CLI 9, either

**Comment by filipefreitas82** [comment]
I have the same problem doing a release build.

Using:
Cordova CLI 10
Cordova android 9
cordova-res (to generate the assets)

**Comment by filipefreitas82** [comment]
On a windows pc the icons were added correctly.

**Comment by breautek** [comment]
Closing as obsolete. cordova android 8.x is no longer supported.
