### ISSUE TITLE
Error Build com.google.firebase:firebase-common:19.2.0/androidmanifest.xml 

### ISSUE THREAD

**Issue by wongjow0** [apache/cordova-android#852]
Error Build :
Execution Failed for task ':processReleaseManifest'
[com.google.firebase:firebase-common:19.2.0]
AndroidManifest.xml : Error: invalid instuction 'targetApi', valid instructions are : REMOVE,REPLACE,STRICT

**Comment by breautek** [comment]
Please fill out the bug report form properly. It tells us important details that we need to know in order to help you out.
