### ISSUE TITLE
Cordova Android 8.0.0 app crashes after signing

### ISSUE THREAD

**Issue by Muveefreak** [apache/cordova-android#853]
After signing my Cordova Android 8.0.0 application and deploying it to a device, the app crashes. The crashes occur on Android 9 and Android 10 devices in most cases Samsung devices. This is my ionic info

    Ionic:
    
       Ionic CLI         : 5.4.1 (/usr/local/lib/node_modules/ionic)
       Ionic Framework   : ionic1 1.3.3
       @ionic/v1-toolkit : 1.0.14
    
    Cordova:
    
       Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
       Cordova Platforms : android 8.0.0
       Cordova Plugins   : no whitelisted plugins (19 plugins total)
    
    Utility:
    
       cordova-res : 0.6.0 
       native-run  : 0.2.8 
    
    System:
    
       Android SDK Tools : 26.1.1 (/Users/******/Library/Android/sdk/)
       ios-deploy        : 2.0.0
       NodeJS            : v11.10.1 (/usr/local/bin/node)
       npm               : 6.7.0
       OS                : macOS Mojave

Here is a list of my installed Cordova plugins

    cordova-plugin-android-fingerprint-auth 1.5.0 "FingerprintAuth"
    cordova-plugin-android-permissions 0.11.0 "Permissions"
    cordova-plugin-apple-watch 0.11.5 "Apple Watch"
    cordova-plugin-camera 2.3.1 "Camera"
    cordova-plugin-compat 1.2.0 "Compat"
    cordova-plugin-contacts 2.3.1 "Contacts"
    cordova-plugin-device 1.1.3 "Device"
    cordova-plugin-dialogs 1.2.0 "Notification"
    cordova-plugin-email-composer 0.8.3 "EmailComposer"
    cordova-plugin-file 6.0.2 "File"
    cordova-plugin-file-opener2 2.1.3 "File Opener2"
    cordova-plugin-file-transfer 1.4.0 "File Transfer"
    cordova-plugin-geolocation 1.0.1 "Geolocation"
    cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
    cordova-plugin-media 5.0.3 "Media"
    cordova-plugin-media-capture 3.0.3 "Capture"
    cordova-plugin-splashscreen 5.0.3 "Splashscreen"
    cordova-plugin-statusbar 2.0.0 "StatusBar"
    cordova-plugin-vibration 2.0.0 "Vibration"
    cordova-plugin-whitelist 1.3.4 "Whitelist"
    cordova-plugin-x-socialsharing 5.4.3 "SocialSharing"
    cordova.plugins.diagnostic 2.3.11 "Diagnostic"
    es6-promise-plugin 4.2.2 "Promise"
    ionic-plugin-deploy 0.6.7 "IonicDeploy"

Logs from LogCat is this, but I am unable to deduce what the issue is. Please help

> 2019-10-02 16:13:19.603 1403-16289/? E/ANDR-PERF-JNI:
> com_qualcomm_qtiperformance_native_perf_io_prefetch_start 2019-10-02
> 16:13:19.604 808-808/? E/ANDR-IOP: IOP HAL: Received pkg_name =
> com.****** pid = -1 2019-10-02 16:13:19.606 808-834/?
> E/ANDR-IOP: io prefetch is disabled 2019-10-02 16:13:19.677 651-651/?
> E/audit: avc:  denied  { find } for service=gpu pid=2045 uid=10299
> scontext=u:r:untrusted_app:s0:c43,c257,c512,c768
> tcontext=u:object_r:gpu_service:s0 tclass=service_manager permissive=0
> 2019-10-02 16:13:19.678 2045-2526/? E/GraphicsEnv: Failed to get gpu
> service 2019-10-02 16:13:19.718 1403-16289/? E/PackageManager: Failed
> to find package; permName: android.permission.INTERNET, uid: 99255,
> caller: 1000 2019-10-02 16:13:19.731 2541-2541/? E/Zygote: accessInfo
> : 0 2019-10-02 16:13:19.747 2541-2541/? E/dboxed_process: Not starting
> debugger since process cannot load the jdwp agent. 2019-10-02
> 16:13:19.823 2045-2045/? E/StatusBar: Invalid hexString argument, use
> f.i. '#999999' 2019-10-02 16:13:19.840 596-596/? E/audit: avc:  denied
> { find } for interface=vendor.display.config::IDisplayConfig
> sid=u:r:hal_configstore_default:s0 pid=787
> scontext=u:r:hal_configstore_default:s0
> tcontext=u:object_r:hal_display_config_hwservice:s0
> tclass=hwservice_manager permissive=0 2019-10-02 16:13:19.841
> 703-703/? E/audit: type=1400 audit(1570029199.829:6977): avc:  denied 
> { getattr } for  pid=596 comm="hwservicemanage" name="avc_msg"
> dev="proc" ino=4026533870 scontext=u:r:hwservicemanager:s0
> tcontext=u:object_r:proc_avc_msg:s0 tclass=file permissive=0
> SEPF_SM-N970U1_9_0009 audit_filtered 2019-10-02 16:13:19.841 703-703/?
> E/audit: type=1300 audit(1570029199.829:6977): arch=c00000b7
> syscall=56 success=yes exit=8 a0=ffffff9c a1=7984923880 a2=1 a3=0
> items=0 ppid=1 pid=596 auid=4294967295 uid=1000 gid=1000 euid=1000
> suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none)
> ses=4294967295 comm="hwservicemanage"
> exe="/system/bin/hwservicemanager" subj=u:r:hwservicemanager:s0
> key=(null) 2019-10-02 16:13:19.841 703-703/? E/audit: type=1327
> audit(1570029199.829:6977): proctitle="/system/bin/hwservicemanager"
> 2019-10-02 16:13:19.842 596-596/? E/audit: avc:  denied  { find } for
> interface=vendor.display.config::IDisplayConfig
> sid=u:r:hal_configstore_default:s0 pid=787
> scontext=u:r:hal_configstore_default:s0
> tcontext=u:object_r:hal_display_config_hwservice:s0
> tclass=hwservice_manager permissive=0 2019-10-02 16:13:19.842
> 703-703/? E/audit: type=1400 audit(1570029199.829:6978): avc:  denied 
> { getattr } for  pid=596 comm="hwservicemanage" name="avc_msg"
> dev="proc" ino=4026533870 scontext=u:r:hwservicemanager:s0
> tcontext=u:object_r:proc_avc_msg:s0 tclass=file permissive=0
> SEPF_SM-N970U1_9_0009 audit_filtered 2019-10-02 16:13:19.842 703-703/?
> E/audit: type=1300 audit(1570029199.829:6978): arch=c00000b7
> syscall=56 success=yes exit=8 a0=ffffff9c a1=7984923880 a2=1 a3=0
> items=0 ppid=1 pid=596 auid=4294967295 uid=1000 gid=1000 euid=1000
> suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none)
> ses=4294967295 comm="hwservicemanage"
> exe="/system/bin/hwservicemanager" subj=u:r:hwservicemanager:s0
> key=(null) 2019-10-02 16:13:19.842 703-703/? E/audit: type=1327
> audit(1570029199.829:6978): proctitle="/system/bin/hwservicemanager"
> 2019-10-02 16:13:19.924 14964-14964/? E/pageboostd: Received HALT
> command code 2 2019-10-02 16:13:20.026 1403-3224/? E/WindowManager:
> win=Window{4649360 u0 Splash Screen com.******* EXITING}
> destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true
> win.mRemoveOnExit=true win.mViewVisibility=0
> caller=com.android.server.wm.AppWindowToken.destroySurfaces:896
> com.android.server.wm.AppWindowToken.destroySurfaces:877
> com.android.server.wm.WindowState.onExitAnimationDone:5496
> com.android.server.wm.WindowStateAnimator.onAnimationFinished:320
> com.android.server.wm.WindowState.onAnimationFinished:5920
> com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2
> com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:100
> 2019-10-02 16:13:20.033 1403-14496/? E/WindowManager:
> win=Window{242c03a u0
> com.sec.android.app.launcher/com.sec.android.app.launcher.activities.LauncherActivity}
> destroySurfaces: appStopped=false win.mWindowRemovalAllowed=false
> win.mRemoveOnExit=false win.mViewVisibility=8
> caller=com.android.server.wm.WindowManagerService.tryStartExitingAnimation:2769
> com.android.server.wm.WindowManagerService.relayoutWindow:2466
> com.android.server.wm.Session.relayoutForTranslate:308
> android.view.IWindowSession$Stub.onTransact:518
> com.android.server.wm.Session.onTransact:192
> android.os.Binder.execTransact:739 <bottom of call stack>  2019-10-02
> 16:13:20.439 716-736/? E/Netd: getNetworkForDns: getNetId from
> enterpriseCtrl is netid 0 2019-10-02 16:13:21.070 2045-2573/? A/libc:
> Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x54 in
> tid 2573 (Chrome_InProcGp), pid 2045 (****) 2019-10-02
> 16:13:21.108 2604-2604/? E/crash_dump64: unknown process state: t
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG: *** *** *** *** *** ***
> *** *** *** *** *** *** *** *** *** *** 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG: Build fingerprint:
> 'samsung/d1que/d1q:9/PPR1.180610.011/N970U1UEU1ASHE:user/release-keys'
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG: Revision: '9' 2019-10-02
> 16:13:21.139 2604-2604/? A/DEBUG: ABI: 'arm64' 2019-10-02 16:13:21.139
> 2604-2604/? A/DEBUG: pid: 2045, tid: 2573, name: Chrome_InProcGp  >>>
> com.***** <<< 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x54 2019-10-02
> 16:13:21.139 2604-2604/? A/DEBUG: Cause: null pointer dereference
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x0  000000769b035900 
> x1  000000769becb080  x2  0000000000000001  x3  000000769aa5d000
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x4  000000769d538f80 
> x5  000000000000000b  x6  0000000000000000  x7  0000000031465451
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x8  0000000000000001 
> x9  000000000000001c  x10 0000000000000017  x11 000000000000000f
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x12 0000000000000001 
> x13 0000000000000000  x14 000000769b035900  x15 00000000fffffe24
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x16 000000769a36d080 
> x17 0000000000000002  x18 0000000000000010  x19 000000769becb080
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     x20 000000769f340180 
> x21 000000769b111480  x22 0000000000000001  x23 000000000000000b
> 2019-10-02 16:13:21.139 716-736/? E/Netd: getNetworkForDns: getNetId
> from enterpriseCtrl is netid 0 2019-10-02 16:13:21.139 2604-2604/?
> A/DEBUG:     x24 0000000000000001  x25 0000000000000001  x26
> 0000000000000000  x27 0000000000000000 2019-10-02 16:13:21.139
> 2604-2604/? A/DEBUG:     x28 000000769b035900  x29 000000769c5f8060
> 2019-10-02 16:13:21.139 2604-2604/? A/DEBUG:     sp  000000769c5f7f60 
> lr  00000076a2af23f0  pc  00000076a2af2114 2019-10-02 16:13:21.152
> 2604-2604/? A/DEBUG: backtrace: 2019-10-02 16:13:21.152 2604-2604/?
> A/DEBUG:     #00 pc 000000000024c114 
> /vendor/lib64/egl/libGLESv2_adreno.so
> (!!!0000!dfb810a28748fbd0016a54d68a3dd2!2eb03ad!+1636) 2019-10-02
> 16:13:21.152 2604-2604/? A/DEBUG:     apache/cordova-cli#1 pc 00000000001884c0 
> /vendor/lib64/egl/libGLESv2_adreno.so
> (!!!0000!15b3af84d7aa3d905632f0b31859d6!2eb03ad!+1128) 2019-10-02
> 16:13:21.152 2604-2604/? A/DEBUG:     apache/cordova-cli#2 pc 00000000002f63a4 
> /vendor/lib64/egl/libGLESv2_adreno.so
> (!!!0000!f56be09eb88f86833124f1df42e945!2eb03ad!+17068) 2019-10-02
> 16:13:21.152 2604-2604/? A/DEBUG:     apache/cordova-cli#3 pc 0000000000195c80 
> /vendor/lib64/egl/libGLESv2_adreno.so
> (!!!0000!6b200851123c7898055fe62ff9f71f!2eb03ad!+576) 2019-10-02
> 16:13:21.152 2604-2604/? A/DEBUG:     apache/cordova-cli#4 pc 00000000001ea830 
> /vendor/lib64/egl/libGLESv2_adreno.so
> (!!!0000!28254c066fd778faffa7894b1bd8b1!2eb03ad!+192) 2019-10-02
> 16:13:21.152 2604-2604/? A/DEBUG:     apache/cordova-cli#5 pc 000000000224a9e8 
> /data/app/com.android.chrome-w5PSFWHisBndmMsNT47NcA==/base.apk (offset
> 0xc19000) 2019-10-02 16:13:21.399 1091-1091/?
> E//system/bin/tombstoned: Tombstone written to:
> /data/tombstones/tombstone_08 2019-10-02 16:13:21.404 703-703/?
> E/audit: type=1701 audit(1570029201.389:6979): auid=4294967295
> uid=10299 gid=10299 ses=4294967295
> subj=u:r:untrusted_app:s0:c43,c257,c512,c768 pid=2045
> comm="Chrome_InProcGp" exe="/system/bin/app_process64" sig=11 res=1
> 2019-10-02 16:13:21.420 1403-3293/? E/InputDispatcher: channel
> 'b90761c com.*****/com.*****.MainActivity
> (server)' ~ Channel is unrecoverably broken and will be disposed!
> 2019-10-02 16:13:21.420 1403-3293/? E/InputDispatcher: channel
> 'e5a5a84 com.*****/com.*****.MainActivity
> (server)' ~ Channel is unrecoverably broken and will be disposed!
> 2019-10-02 16:13:21.433 1403-1434/? E/WindowManager: RemoteException
> occurs on reporting focusChanged, w=Window{e5a5a84 u0
> com.*****/com.*****.MainActivity EXITING}
>     android.os.DeadObjectException
>         at android.os.BinderProxy.transactNative(Native Method)
>         at android.os.BinderProxy.transact(Binder.java:1145)
>         at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
>         at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3986)
>         at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5535)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:216)
>         at android.os.HandlerThread.run(HandlerThread.java:65)
>         at com.android.server.ServiceThread.run(ServiceThread.java:44) 2019-10-02 16:13:21.449 861-861/? E/lmkd: Error opening
> /proc/2541/oom_score_adj; errno=2 2019-10-02 16:13:21.449 861-861/?
> E/lmkd: Error opening /proc/2045/oom_score_adj; errno=2 2019-10-02
> 16:13:21.458 1403-1425/? E/libprocessgroup: Error encountered killing
> process cgroup uid 99255 pid 2541: No such file or directory
> 2019-10-02 16:13:21.467 1403-1426/? E/KernelCpuUidUserSysTimeReader:
> Negative user/sys time delta for UID=10120
>     Prev times: u=215346000 s=56770000 Curr times: u=208410000 s=53002000 2019-10-02 16:13:21.569 1403-1413/? E/WindowManager:
> win=Window{b90761c u0
> com.*****/com.*****.MainActivity EXITING}
> destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true
> win.mRemoveOnExit=true win.mViewVisibility=0
> caller=com.android.server.wm.AppWindowToken.destroySurfaces:896
> com.android.server.wm.AppWindowToken.destroySurfaces:877
> com.android.server.wm.WindowState.onExitAnimationDone:5496
> com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2
> java.util.ArrayList.forEach:1262
> com.android.server.wm.AppWindowToken.onAnimationFinished:2479
> com.android.server.wm.AppWindowToken.setVisibility:560  2019-10-02
> 16:13:21.573 1403-1413/? E/WindowManager: win=Window{e5a5a84 u0
> com.*****/com.*****.MainActivity EXITING}
> destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true
> win.mRemoveOnExit=true win.mViewVisibility=0
> caller=com.android.server.wm.AppWindowToken.destroySurfaces:896
> com.android.server.wm.AppWindowToken.destroySurfaces:877
> com.android.server.wm.WindowState.onExitAnimationDone:5496
> com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2
> java.util.ArrayList.forEach:1262
> com.android.server.wm.AppWindowToken.onAnimationFinished:2479
> com.android.server.wm.AppWindowToken.setVisibility:560

**Comment by breautek** [comment]
This looks more of a `cordova-android` issue so transferring...

**Comment by breautek** [comment]
Are you able to reproduce this with a basic cordova app? If not, then chances are it's one of your plugins that is causing the crash.

You can try adding each plugin one at a time until the problem comes back.

**Comment by jcesarmobile** [comment]
It was also reported here. Closing as duplicate
https://github.com/apache/cordova-android/issues/836
