### ISSUE TITLE
Creating bundle package with 8.1.0 not working

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-android#855]
# Bug Report
I tried with 8.1.0:

```
cordova build android --release
cd platforms/android
./gradlew bundleRelease
```

## Problem

After the command
./gradlew bundleRelease
I get an error.

### What is expected to happen?
Creating .aab bundle package.

### What does actually happen?
Adding platform is working
Build Process ist working as well
If I try to create bundle package, I get this error:

    > Configure project :app
    WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
    It will be removed at the end of 2018. For more information see:     http://d.android.com/r/tools/update-dependency-configurations.html
    An exception occurred while trying to find the Android build tools.
    Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

    FAILURE: Build failed with an exception.

    * Where:
    Script '/XXX/platforms/android/CordovaLib/cordova.gradle' line: 121

    * What went wrong:
    A problem occurred evaluating project ':app'.
    > Unable to determine Android SDK directory.

## Information

Cordova 9.0.0
Cordova Android 8.1.0

### Command or Code

./gradlew bundleRelease

### Environment, Platform, Device

Terminal

### Version information

Cordova CLI

## Checklist

- [X ] I searched for existing GitHub issues
- [X ] I updated all Cordova tooling to most recent version
- [ X] I included all the necessary information above

**Comment by breautek** [comment]
Can you run `cordova requirements android` and tell me the output? Thanks.

**Comment by breautek** [comment]
Sorry, just noticed

>Unable to determine Android SDK directory.

This means you don't have the android SDK installed, or it's not in a path findable by cordova.

To install the android SDK, it's recommended to install the android studio (this will give you GUI tools to install everything that you need). https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#android-sdk

If you already do have the android sdk installed, then you may need to set your environment variables. https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#setting-environment-variables

Also note that `cordova-android` 8.0.0 or later requires android API 28 at minimum.

**Comment by desmeit** [comment]
Android Studio is installed. I wil try the environment variables. Thank you.
You mean I have to define minSdkVersion to 28 in the config? I did that.

**Comment by breautek** [comment]
> You mean I have to define minSdkVersion to 28 in the config

No, you must open up the `SDK Manager` (tool provided by android) and you must have at least API 28 installed. I'll provide a sceenshot of the `SDK Manager` ui.

![sdkmanager](https://user-images.githubusercontent.com/11200662/67231939-aec33f80-f416-11e9-9ecd-cbd39a139812.png)

While you're there, you should also click on the `SDK Tools` tab and ensure `Android SDK Build-Tools`, `Android SDK Platform-Tools`, and `Android SDK Tools` are all up to date.

**Comment by desmeit** [comment]
Okay thanks. I will try tomorrow morning and let you know.

**Comment by desmeit** [comment]
Okay, my feedback:

I have updated and installed everything as recommended by you.
I also created a ~/.bash_profile with the following content:

```
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/${version}
```
Before it was:

```
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/XXX/Library/Android/sdk (DEPRECATED)
```

Now it is:

```
ANDROID_SDK_ROOT=/XXX/Library/Android/sdk (recommended setting)
ANDROID_HOME=/XXX/Library/Android/sdk (DEPRECATED)
```

The problem still exists. I'm not able to create a bundle package.

**Comment by desmeit** [comment]
Okay, now it is working.
As in this answer described (https://stackoverflow.com/a/33631853/3037763), you to do the following:

`open ~/.bash_profile`

if bash_profile is not in your homefolder, you can create by the following:
`touch ~/.bash_profile`

Then type in this file:

```
export ANDROID_HOME=/Users/XXX/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
```

Then you can check, if it is working:

```
source ~/.bash_profile
echo $ANDROID_HOME
```

**Comment by zimejin** [comment]
I tried everything here and on the link to no avail until finally opening the Android folder under platforms in Android Studio. Somehow this got everything working again.
