### ISSUE TITLE
Hardware Back Button ISSUE

### ISSUE THREAD

**Issue by 08Thug** [apache/cordova-android#864]
# Bug Report

## Problem
I am currently working in IONIC with CORDOVA plugins and platforms ,i am facing an issue in hardware back button 

### What is expected to happen?
when the user opens the application,once the application is opened when the hardware button is pressed its should pop up the alert message like do you wanna exit yes or no when yes is pressed app should terminate.

### What does actually happen?
Once the app is opened  when the hardware button is pressed the app terminates without alert but when a click is made inside or any other navigation is made then afterwards coming back to the same home page when pressing the hardware back button the exitapp() alert is shown...

## Information

I've used android version (OREO)8 in this application on degrading the version to (LOLLIPOP) 5 its working perfectly.

### Environment, Platform, Device

PLATFORM-ANDROID
DEVICE-NEXUS

### Version information
 Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.2.0
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-webview 3.1.2, (and 28 other plugins)

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.15.3 
   npm               : 6.4.1
   OS                : Linux 4.4

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by LifeIsStrange** [comment]
Related:
https://github.com/ionic-team/ionic/issues/16611

**Comment by breautek** [comment]
Unable to reproduce using the latest platform/tooling.

I'm able to utilize the [backbutton](https://cordova.apache.org/docs/en/11.x/cordova/events/events.html#backbutton) event to hook into the back button and produce wanted behaviour.

If this issue persists on cordova-android@10, I'd recommend creating a new issue. Please include code samples that are expected to work, or a minimal sample application that reproduces the issue. Please note that any application that uses third-party frameworks will make it difficult to pinpoint any issues, so using such frameworks in the sample application should be avoided.

**Comment by NiklasMerz** [comment]
Please check https://github.com/apache/cordova-android/issues/1106
