### ISSUE TITLE
Issues when accessing android assets through browser

### ISSUE THREAD

**Issue by DimitrisRK** [apache/cordova-android#865]
# Bug Report
Using 'cordova serve' command, I start cordova static page server.
This server should give me access to any platform www assets using a url with 'http://HOST_IP:PORT/PLATFORM/www' format, just as mentioned in the command docs.
The thing is that in the case of android, some weird prompts appear in browser and if you click ok to all of them, browser will start loading to the point it hangs forever.

First prompt message: gap_init:3
Second prompt message: gap:[0,"CoreAndroid","messageChannel","CoreAndroid914833860"]
Third prompt message: gap:[0,"CoreAndroid","show","CoreAndroid47601542"]

**After couple of tests, I noticed that on browser tab change prompts are gone and page is loaded successfully.

### What is expected to happen?
Load page without issues.

### What does actually happen?
First prompt message: gap_init:3
Second prompt message: gap:[0,"CoreAndroid","messageChannel","CoreAndroid914833860"]
Third prompt message: gap:[0,"CoreAndroid","show","CoreAndroid47601542"]

### Command or Code
cordova serve

### Environment, Platform, Device
Windows 10

### Version information
Cordova 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
You're not suppose to load the android platform in the browser. You're suppose to set your content tag to the local webserver (via your private ip) and deploy an android app I believe.

**Comment by DimitrisRK** [comment]
When started with 'cordova serve' command, cordova local server gives access to all installed platform assets when entering localhost:8000 page.
Also, Cordova documentation states that upon using this command, developers can access the assets of a platform of their choice by using the corresponding URL in 'http://HOST_IP:PORT/PLATFORM/www' format.

**Comment by breautek** [comment]
Perhaps the documentation requires more clear text, you cannot run an "android" platform in the browser. You can serve the assets to any platform via cordova serve, but you still must build and deploy the android platform to an android device or emulator.

You can then set the content src attribute to your cordova serve address. https://cordova.apache.org/docs/en/latest/config_ref/index.html#content

And android app will use the cordova serve to obtain its assets, which is useful for development.
