### ISSUE TITLE
Gradle home for cordova only - to be able to have multiple gradle installtions on the pc

### ISSUE THREAD

**Issue by bys92** [apache/cordova-android#866]
# Feature Request

## Motivation Behind Feature
My company is working with multiple applications. One of them is Java where we already use several different gradle version. It must be able to have some gradle binaries which will be used from cordova only.

## Feature Description
Cordova shall check a new env var if there is a value set it should be used from cordova as gradle home. 
or
Cordova shall check if there is gradle path defined in the project (in conifg.xml or package.json?) and if it's set it should use this as gradle home. 

If not the default logic can be performed, to keep the software backward compatible

## Alternatives or Workarounds
No known for me

Remarkds / Ideas / Suggestions? 

Regards

**Comment by breautek** [comment]
Cordova just needs any gradle version installed.

Gradle has a concept of wrappers, which installs a gradle version local to the project. Gradle itself will download the specific version that a project requires. So I don't see the need for this feature. Am I missing something?

**Comment by erisu** [comment]
Closing this ticket as an invalid request and no response from the original ticket author.

As previously pointed out, Cordova uses a Gradle wrapper.

It will download and use the version of Gradle it needs to perform the build. 

The system's Gradle, IMO, should be updated regularly. The system Gradle is for setting up the wrapper while the projects should use the wrapper.
