### ISSUE TITLE
Upgrading Cordova Android version cause INSTALL_FAILED_UPDATE_INCOMPATIBLE

### ISSUE THREAD

**Issue by ash67** [apache/cordova-android#869]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description

I had to upgrade the Cordova Android version to 8.1.0 from 7.1.1 in order to support targetSdkVersion to 28.

After upgrade to the latest version of Cordova Android, I add the below entry in the config file.

```   <preference name="android-targetSdkVersion" value="28" />```

With the above changes, my app builds and generates APK successfully. However, when I try to deploy(cordova run android) this newly generated APK to my device(which has already installed the app from play store), I get the following error.

“INSTALL_FAILED_UPDATE_INCOMPATIBLE signatures do not match the previously installed version”

To resolve this issue, I have to uninstall the current version from my phone and clean reinstall. It would work but it is not ideal behavior as uninstalling the previous version and installing a brand new version would loss existing user settings and etc. Please help!

## Information

1. Upgrade Cordova platform version from 7.1.1 to 8.1.0
2. In Config.xml add a new flag `android-targetSdkVersion` with value 28
3. run cordova build android --release
4. run corodva run android --release

### Command or Code

cordova run android

### Environment, Platform, Device

Cordova Platform Android
Device: Samsung S9 running Android version 9

### Version information

Cordova Android 8.1.0

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> “INSTALL_FAILED_UPDATE_INCOMPATIBLE signatures do not match the previously installed version”

This means that you have used a different keystore to sign your APK compared to the APK that is already installed on the device. 

A common error where this occurs is that you had a debug copy installed on your device (signed with the android sdk provided keystore) while trying to install a production copy of your APK (signed with your own keystore), or vice versa.

**Comment by breautek** [comment]
@ash67 Did my above comment help you, can this issue be closed?
