### ISSUE TITLE
I solved one issue( its a solution)

### ISSUE THREAD

**Issue by SirmaXX** [apache/cordova-android#872]
# Bug Report

## Problem
> Configure project :CordovaLib
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/deniz/Masaüstü/masaüstü/mobile/MyApp/platforms/android/CordovaLib/build.gradle' line: 48

### What is expected to happen?
when ı type cordova build android ,it should build app

### What does actually happen?
it show this error 
A problem occurred evaluating project ':CordovaLib'.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Configuration with name 'testImplementation' not found.

### Environment, Platform, Device

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_222 (Private Build 25.222-b10)
OS:           Linux 4.15.0-70-generic amd64

### Version information

java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

cordova -v
9.0.0 (cordova-lib@9.0.1)

node -v
v12.9.0

## Solution 
go to the MyApp/platforms/android/CordovaLib/build.gradle' line: 35
change to classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1' to classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'

**Comment by breautek** [comment]
What version of `cordova-android` does this trigger on?

**Comment by SirmaXX** [comment]
cordova platform version android

Installed platforms:
  android 7.1.4
  browser 5.0.4
Available platforms: 
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

**Comment by breautek** [comment]
This should have been fix as of cordova-android@8. If the issue persists in the current latest version, please open a new issue. Thanks.

**Comment by SirmaXX** [comment]
Sorry for Late and reopen this issue .First of All thanks for feedback ,I have upgraded all things
cordova platform version android
Installed platforms:
  android 8.1.0
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
node -v
v12.9.0
java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
npm -v
6.11.3
cordova -v
9.0.0 (cordova-lib@9.0.1)
