### ISSUE TITLE
Android App Bundle: --versionCode ignored with --packageType=bundle

### ISSUE THREAD

**Issue by anatoly-spb** [apache/cordova-android#873]
# Bug Report

## Problem

The following command ignore versionCode parameter when use --packageType=bundle

    cordova build android -- --packageType=bundle --versionCode=500000

### What is expected to happen?

    cordova build android -- --packageType=bundle --versionCode=500000

versionCode must not ignored when  --packageType=bundle is used

### What does actually happen?

Now cordova uses version from config.xml and generates version instead of using the specified in --versionCode parameters

## Information

cordova --version                                                                                                                                                                                             9.0.0 (cordova-lib@9.0.1)         

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Thanks for the report, I'll try to take a look at this tonight.

**Comment by breautek** [comment]
I have reproduced this issue and confirmed this as a bug.

**Comment by breautek** [comment]
I do not know why `--versionCode` or `--gradleArgs=-PcdvVersionCode` is being ignored during bundle generation, but using the `<widget android-versionCode="123">` attribute in `config.xml` could be a workaround as that does appear to work.

It's getting late for me so I have to pick this back up another time.

**Comment by tklaas** [comment]
@breautek 
came across this problem today, did you already do something or is the workaround through config.xml still the way to go? This is unfortunately not the best option since we are adding the version code within our CI build via command line :(

**Comment by breautek** [comment]
> @breautek
> I came across this problem today, did you already do something or is the workaround through config.xml still the way to go? This is unfortunately not the best option since we are adding the version code within our CI build via command line :(

No sorry, I haven't had a chance to relook at this. Afaik, the above workaround is the only way to properly set the versionCode :sob:

**Comment by breautek** [comment]
And the issue all along was... I omitted passing down the flags if the package type was bundle in the original bundle implementation :man_facepalming: 

Amazing what kind of work can do when you ignore the issue for 3 months.
