### ISSUE TITLE
Handling android back button?

### ISSUE THREAD

**Issue by UmarBilanov** [apache/cordova-android#876]
I try to navigate from Example.vue to Example2.vue by android back button my code works for os under android 8.0. On devices android upper 8.0 the back button works by history.Do you have any idea to do it?

onClickBackButton() {
this.$router.replace({'path': '/example2'});
}

mounted() {
if (this.$q.platform.is.cordova) {
document.addEventListener("backbutton", this.onClickBackButton, false)
}
}

Platform:
Android:

**Comment by jcesarmobile** [comment]
Can you provide a sample app?

**Comment by jcesarmobile** [comment]
Closing since the requested information was not provided
