### ISSUE TITLE
App not launching, no issue with building apk file.

### ISSUE THREAD

**Issue by sreerajr137** [apache/cordova-android#882]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ X] Support Question

## Description
Building a cordova app with Quasar cordova build --release android does not throw errors.
## Information

k :app:compileReleaseSources UP-TO-DATE

> Task :app:lintVitalRelease

Portal/src-cordova/platforms/android/app/src/main/res/drawable-land-xhdpi/screen.png: Error: The drawable "screen" in drawable-land-xhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
Portal/src-cordova/platforms/android/app/src/main/res/drawable-land-xxhdpi/screen.png: Error: The drawable "screen" in drawable-land-xxhdpi has no declaration in the base drawable folder or in a drawable-densitydpi folder; this can lead to crashes when the drawable is queried in a configuration that does not match this qualifier [MissingDefaultResource]
...........................
..............................
.............................
   Explanation for issues of type "MissingDefaultResource":
   If a resource is only defined in folders with qualifiers like -land or -en,
   and there is no default declaration in the base folder (layout or values
   etc), then the app will crash if that resource is accessed on a device
   where the device is in a configuration missing the given qualifier.

   As a special case, drawables do not have to be specified in the base
   folder; if there is a match in a density folder (such as drawable-mdpi)
   that image will be used and scaled. Note however that if you  only specify
   a drawable in a folder like drawable-en-hdpi, the app will crash in
   non-English locales.

   There may be scenarios where you have a resource, such as a -fr drawable,
   which is only referenced from some other resource with the same qualifiers
   (such as a -fr style), which itself has safe fallbacks. However, this still
   makes it possible for somebody to accidentally reference the drawable and
   crash, so it is safer to create a default dummy fallback in the base
   folder. Alternatively, you can suppress the issue by adding
   tools:ignore="MissingDefaultResource" on the element.

   (This scenario frequently happens with string translations, where you might
   delete code and the corresponding resources, but forget to delete a
   translation. There is a dedicated issue id for that scenario, with the id
   ExtraTranslation.)

12 errors, 0 warnings
.............................
.......................
...........................
BUILD SUCCESSFUL in 6s
44 actionable tasks: 4 executed, 40 up-to-date
Built the following apk(s): 
	Portal/src-cordova/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

 Build succeeded

## Checklist

- [ ] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
Please fill in the version numbers.

You can find this by doing `cordova -v` and `cordova platform list`

Thanks.

**Comment by breautek** [comment]
Closing due to lack of response. If you think you've found a bug, please do open a new issue with all the details filled out.

If you require support, a more appropriate place to ask is on our [slack](http://slack.cordova.io/).
