### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by bhandaribhumin** [apache/cordova-android#887]
# Bug Report
I try to add android but got some error 

### Command or Code
**project.property**

```
target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=cordova-plugin-background-fetch/campus-build.gradle
cordova.system.library.1=com.google.android.gms:play-services-location:16.+
cordova.system.library.2=com.android.support:appcompat-v7:28.+
cordova.system.library.3=com.squareup.okhttp3:okhttp:3.12.+
cordova.system.library.4=org.greenrobot:eventbus:3.0.0
cordova.system.library.5=com.intentfilter:android-permissions:0.1.8
cordova.system.library.6=org.slf4j:slf4j-api:1.7.25
cordova.system.library.7=com.github.tony19:logback-android:1.3.0-2
cordova.gradle.include.2=cordova-background-geolocation-lt/campus-build.gradle
cordova.system.library.8=com.android.support:support-annotations:27.+
cordova.gradle.include.3=cordova-plugin-ms-adal/campus-adal.gradle
cordova.gradle.include.4=cordova-support-google-services/campus-build.gradle
cordova.gradle.include.5=phonegap-plugin-multidex/campus-multidex.gradle
cordova.system.library.9=com.android.support:support-v13:27.+
cordova.system.library.10=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.11=com.google.firebase:firebase-messaging:17.0.+
cordova.system.library.12=io.sentry:sentry-android:1+
```

### Environment, Platform, Device

Ionic:

   Ionic CLI                     : 5.4.13 (/Users/bhumin3imac/.npm-global/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.3
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/bhumin3imac/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v12.13.0 (/usr/local/bin/node)
   npm               : 6.12.0
   OS                : macOS Mojave
   Xcode             : Xcode 11.2 Build version 11B52

### Version information

cordova-background-geolocation-lt 3.2.0 "BackgroundGeolocation"
cordova-plugin-background-fetch 5.5.0 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-ms-adal 0.10.1 "ADAL for Cordova"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
phonegap-plugin-multidex 1.0.0 "Multidex"
phonegap-plugin-push 2.3.0 "PushPlugin"
sentry-cordova 0.17.0 "Sentry"

## Error log

```
ANDROID_SDK_ROOT=/Users/bhumin3imac/Library/Android/sdk (recommended setting)
ANDROID_HOME=/Users/bhumin3imac/Library/Android/sdk (DEPRECATED)
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 18s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Downloading https://services.gradle.org/distributions/gradle-4.10.3-all.zip
...........10%...........20%...........30%...........40%............50%...........60%...........70%...........80%...........90%............100%

Welcome to Gradle 4.10.3!

Here are the highlights of this release:
 - Incremental Java compilation by default
 - Periodic Gradle caches cleanup
 - Gradle Kotlin DSL 1.0-RC6
 - Nested included builds
 - SNAPSHOT plugin versions in the `plugins {}` block

For more details see https://docs.gradle.org/4.10.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest
> Task :CordovaLib:processDebugManifest
> Task :app:preDebugBuild
Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.nimbusds, artifactId=nimbus-jose-jwt, version=5.7), toArtifact=Artifact(groupId=net.minidev, artifactId=json-smart), toArtifactVersionString=[1.3.1,2.3])

> Task :app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.7 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto net.minidev:json-smart@2.3
  -- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@5.7
  -- Project 'app' depends onto com.microsoft.aad:adal@1.15.0
  -- Project 'app' depends onto com.microsoft.identity:common@0.0.3
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 53s
3 actionable tasks: 3 executed
/Users/bhumin3imac/Desktop/git/mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
  ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
  
  Dependency failing: com.nimbusds:nimbus-jose-jwt:5.7 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2
  .3.
  
  The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
  ifact with the issue.
  -- Project 'app' depends onto net.minidev:json-smart@2.3
  -- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@5.7
  -- Project 'app' depends onto com.microsoft.aad:adal@1.15.0
  -- Project 'app' depends onto com.microsoft.identity:common@0.0.3
  
  For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
  endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
  github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
  uild.gradle file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10m 53s
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
```

**Comment by breautek** [comment]
You have plugins that has clashing dependencies. Given I see microsoft dependencies, I'm going to assume `cordova-plugin-ms-adal 0.10.1 "ADAL for Cordova"` is one of the plugins that isn't playing nicely with another.

**Comment by bhandaribhumin** [comment]
@breautek  thanks for reply but in my old device same plugins works but i setup new system and clone repo after adding android it's fail to build android. if you have any clue or idea please help me on this.

**Comment by breautek** [comment]
> @breautek thanks for reply but in my old device same plugins works but i setup new system and clone repo after adding android it's fail to build android. if you have any clue or idea please help me on this.

In my experience, some plugins do a poor job at defining their dependencies and usually use a very loose pinning strategy, such as allowing any (latest) version to be used a dependency. This means it may have worked in the past, but since then a breaking update may have been release, which and the plugin is no longer compatible. If I would take a wild guess, this is what I would suspect first.

It can be hard pinpointing the faulty plugin because the issue may not be with the plugin itself, but a subdependency of that plugin. An easy way to pinpoint the faulty plugin is to remove each plugin one at a time, and attempt build after each plugin. This will at least point you to the right direction.

**Comment by bhandaribhumin** [comment]
@breautek i found  ionic cordova plugin add phonegap-plugin-push plugin may cause for build error.

**Comment by timbru31** [comment]
@bhandaribhumin can we close this issue given the fact you identified the culprit plugin?

**Comment by tryhardest** [comment]
@brianleroux @dpogue @breautek that is one of the absolute top Cordova issues all these years articulated so we'll. There should be a simple plugin repo master page where plugins can check and update comparability issues. It's long since been an issue. Version related issues either plugin or Gradle and CocoaPod related turned so many people away. I feel like actually there are people returning as Capacitor isn't quite ready and advanced web APIs and the recent efforts of all the good people working on Cordova has been a boost. Nothing complex, maybe even a repo thread people can point plugin maintainers too, that says in a way as clear as @bhandaribhumin did filing this issue, what versions things are at and the min version they support. Just 2cents. This tiny thread says it all.

**Comment by tryhardest** [comment]
Maybe even a hook that on build would send their plugin, npm, node, CLI, platform version information to a consolidated place? Not sure how to do it best but if there was a more concise way and 'standard' to know the plugin version were  up to date or that someone else found success on some specific version setup it would be amazing.

**Comment by bhandaribhumin** [comment]
i resolve this issue using some tweaks, @tryhardest thanks for your advice and help. cheers 🍺 brooooo 😉
