### ISSUE TITLE
How to get app working on samsung dex?

### ISSUE THREAD

**Issue by steffanhalv** [apache/cordova-android#888]
How do I get my cordova app to work on samsung dex?

Samsung dex only says:

`can't run in Samsung Dex. It's designed for phone touch screens`

**Edit:**

I think I found a way to do it by adding this to the `config.xml` file but havent tested yet:

```xml
<edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
   <uses-configuration android:reqTouchScreen="finger">
   <uses-feature android:name="android.hardware.touchscreen">
   <android:required="false">
</edit-config>
```

**Ref:**
https://stackoverflow.com/questions/50233000/app-not-cant-run-in-samsung-dex
https://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by breautek** [comment]
Closing due to lack of response. If you still require assistance, I invite you to ask support-style questions on our [slack](http://slack.cordova.io/)
