### ISSUE TITLE
App don't work with Android SDK 28 emulator

### ISSUE THREAD

**Issue by DeltaFox0018** [apache/cordova-android#889]
Hi, after installing cordova I have created a new project.
The contents of the www folder are generated by building an Angular project
As a platform I added android@8.1.0 with target SDK at 28 and min SDK at 19, after doing the build of the project, I open the emulator with SDK 28 launch the command cordova emulate android and on the device the white screen opens, instead if using an emulator with SDK 29 the app opens and shows the correct contents of the www folder.
Anyone know how I can fix it?

**Comment by jcesarmobile** [comment]
Make sure your angular build is not adding module and nomodule scripts, they don’t work when served from file protocol, which cordova uses by default.
If you want to serve from http or https then you can try ionic webview plugin.
