### ISSUE TITLE
Dark Mode Android 

### ISSUE THREAD

**Issue by acpnayak** [apache/cordova-android#897]
# Bug Report
prefers-color-scheme media query seems to exist but it always matches as no-preference no matter what the OS is set.

## Problem
prefers-color-scheme media query seems to exist but it always matches as no-preference no matter what the OS is set to

### What is expected to happen?
prefers-color-scheme media query should matches to dark, light or no-preference on the basis of user device

### What does actually happen?
prefers-color-scheme media query always match  no-preference

### Environment, Platform, Device
Android, S9

### Version information
Cordova Android 6.3.0 and Iconic 1.2.4

**Comment by jpike88** [comment]
@erisu do you have any recommendations RE workarounds here? Is this something Cordova-android can easily compensate for?

**Comment by dpogue** [comment]
This is an Android WebView issue, not something that Cordova can fix.

**Comment by jpike88** [comment]
https://joebirch.co/2020/01/24/enabling-dark-theme-in-android-webviews/

@dpogue This article describes a way of giving it in application context. Are you sure it's not something that can be handled?

**Comment by dpogue** [comment]
That is forcing dark web content, which is different than supporting the media query.

**Comment by jpike88** [comment]
I see. What a pain!

**Comment by MichaelPote** [comment]
I've found something which fixed it for me!

From https://developer.android.com/guide/webapps/dark-theme

"WebView can't differentiate based solely on the presence of the media query, so it needs a color-scheme meta tag with dark value as indication that a web page has its own dark theme. To prevent double-darkening (that is, applying color inversion on top of media query customization) WebView evaluates @media (prefers-color-scheme: dark) to false in this mode."

So I added `<meta name="color-scheme" content="dark">` to my html and presto - it now detects my prefers-color-scheme: dark query.

**Comment by timbru31** [comment]
You might want to check out this plugin, too:

> While Android supports a dark mode since API level 29 (Android 10), Android WebView's need explicit support for this. This plugin changes the used Cordova WebView, no matter if the default from cordova-android or a custom one such as the cordova-plugin-ionic-webview to enable or disable the dark mode. This results in a correct usage of the (prefers-color-scheme: dark) media query.
Additionally, when the native configuration changes, it is re-evaluated whether the dark mode is currently active.
Under the hood, the Configuration.UI_MODE_NIGHT_YES, WebSettingsCompat.setForceDark and WebSettingsCompat.setForceDarkStrategy are used. You can read more here: developer.android.com/guide/webapps/dark-theme

https://github.com/timbru31/cordova-plugin-android-dark-mode-support

**Comment by nielsjakob** [comment]
> You might want to check out this plugin, too:
> 
> > While Android supports a dark mode since API level 29 (Android 10), Android WebView's need explicit support for this. This plugin changes the used Cordova WebView, no matter if the default from cordova-android or a custom one such as the cordova-plugin-ionic-webview to enable or disable the dark mode. This results in a correct usage of the (prefers-color-scheme: dark) media query.
> > Additionally, when the native configuration changes, it is re-evaluated whether the dark mode is currently active.
> > Under the hood, the Configuration.UI_MODE_NIGHT_YES, WebSettingsCompat.setForceDark and WebSettingsCompat.setForceDarkStrategy are used. You can read more here: developer.android.com/guide/webapps/dark-theme
> 
> https://github.com/timbru31/cordova-plugin-android-dark-mode-support

omg thank you, can't believe that is burried like that - took me an hour researching before finding your comment!
