### ISSUE TITLE
Phonegap APK - jarsigner -verify throwing an error - invalid SHA-256 signature file digest for res/layout/notification_action.xml

### ISSUE THREAD

**Issue by bhavika84** [apache/cordova-android#903]
I have created the keystore using

`keytool -genkey -v -keystore xx_yy_zz.keystore -alias xx_yy_zz_alias_name -keyalg RSA -keysize 2048 -validity 10000`

Uploaded to Phonegap and generated a APK file

The signed the APK using the below command

`jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore xx_yy_zz.keystore xx_yy_zz.78.apk xx_yy_zz_alias_name`

But when I verify the APK it throws the below error

`jarsigner -verify xx_yy_zz.78.apk`

**jarsigner: java.lang.SecurityException: invalid SHA-256 signature file digest for res/layout/notification_action.xml**

Any insight would be greatly appreciated. Seem to be stuck on it for days.

Thanks

**Comment by aymenbahroun** [comment]
Did you find the solution ?
i have the same problem : **invalid SHA-256 signature file digest for res/layout/crop__activity_crop.xml
** 
if you found how to solve that it would be really great

**Comment by breautek** [comment]
You'll get this error if the jar/apk was already signed.

Unclear if this the OP's issue or not but I'm closing this issue since it appears to be more related to PhoneGap's APK generation, which is now an obsolete service.
