### ISSUE TITLE
Button partially visible with input type=time 

### ISSUE THREAD

**Issue by marcosvega91** [apache/cordova-android#906]
### Issue Type

- [ X] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
Hi i have developed an application with cordova and angular. I'm facing a problem with input type=time.
The buttons are displayed in a wrong way  in particularly the button Set is partially visible.
## Information

I attach a screen with the issue 

![image](https://user-images.githubusercontent.com/5365582/72794326-208c6e80-3c3c-11ea-81b0-e4d02074426b.png)

### Command or Code

The code is very simple 
` <input class="form-control"  type="time">`
### Environment, Platform, Device
The device is Samsung Galaxy Tab A SM-T295

### Version information

Cordova CLI 8.0.0
Cordova Platforms 8.0.0
Operation System Android 

## Checklist

- [ X] I searched for already existing GitHub issues about this
- [ X] I updated all Cordova tooling to their most recent version
- [ X] I included all the necessary information above

**Comment by timbru31** [comment]
This is probably an Android bug itself. Is the time picker cut off when you use, e.g., Chrome or Samsung Internet and visit, for instance, this demo site https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time ?

**Comment by marcosvega91** [comment]
Yes you are right. I have the same error with the browser.

**Comment by timbru31** [comment]
Then, unfortunately, we can't fix this issue. You should report it to Samsung, if possible.
