### ISSUE TITLE
Issues with video quality in Cordova

### ISSUE THREAD

**Issue by mrcatman** [apache/cordova-android#907]
I want to play a HLS stream in a Android TV Cordova-based app. The source is a live HLS FullHD stream (1920x1080). But when it's played on Android TV box, the video looks pixelated, like it's not even in HD. In the browser (Chrome on Android TV) the quality is also the same.
Tried different web video players, but nothing changed. But if I use the native Android player, the quality is much better. What can this be related to?

**Comment by jcesarmobile** [comment]
If it happens also in chrome then it’s probably a chrome bug. Cordova uses a webview which is also affected by the same bug, so report it to google.
