### ISSUE TITLE
Support newer JDK versions

### ISSUE THREAD

**Issue by SchnWalter** [apache/cordova-android#908]
# Feature Request

Cordova should support newer JDK versions. In pull request #446 a check was introduced to enforce the JDK version but no real reasoning was provided.

## Motivation Behind Feature

Oracle has announced that the [End of Public Updates of Java SE 8](https://www.oracle.com/technetwork/java/java-se-support-roadmap.html) is on `December 2020`.

## Feature Description

Now that the JAVA 8 EOL is near, I think that all the issues in newer JDKs should be documented and a new tag should be added just for issues that prevent JDK updates.

**Comment by erisu** [comment]
Some other information to know is that Android Studio (AS) still uses OpenJDK 8 (`openjdk version "1.8.0_202-release"`). It does not use/bundle the Oracle's version.

If any changes were made, I suspect it would only be supporting OpenJDK 8 and to be in line with what Android Studio uses.

**Comment by breautek** [comment]
The current version of Gradle that cordova-android requires also depends on java 8. Although in cordova-android@9, it will be using gradle 6.x, and they added support for up to JDK13.

Android Studio expects you to use Java 8. They don't officially support higher versions of java. So I believe this makes android studio the only blocker for a JDK upgrade. It doesn't mean android studio won't work in a higher JDK version, but it won't be guaranteed.

Android's docs where they talk about this can be found [here](https://developer.android.com/studio/write/java8-support)

**Comment by jcesarmobile** [comment]
Android doesn’t use oracles java but their own implementation, which at the moment is like java 8. So this is an android limitation, not something cordova can fix.
