### ISSUE TITLE
Not able to generate APK file

### ISSUE THREAD

**Issue by BjoernKorioth** [apache/cordova-android#913]
# Bug Report

## Problem

I am trying to build and android version of my ionic application. Sadly I am not able to generate an APK file.

I am running the command "ionic cordova build android". The sub task "cordova.cmd build android" stops with:

```
config file undefined requested for changes not found at C:\Users\d060445\university\Team Project\Tracktivity\moveit\platforms\android\undefined, ignoring
config file undefined requested for changes not found at C:\Users\d060445\university\Team Project\Tracktivity\moveit\platforms\android\undefined, ignoring
The "path" argument must be of type string. Received type undefined
```

running "cordova.cmd build android --verbose" shows:

```
Updating resource files at platforms\android
  copy  resources/android/xml/network_security_config.xml platforms\android\app\src\main\res\xml\network_security_config.xml (updated file)
Prepared android project successfully
The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at ConfigKeeper_get [as get] (C:\Users\d060445\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\ConfigChanges\ConfigKeeper.js:45:26)
    at C:\Users\d060445\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:346:51
    at Array.forEach (<anonymous>)
    at is_conflicting (C:\Users\d060445\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:339:17)
    at PlatformMunger.add_config_changes (C:\Users\d060445\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-common\src\ConfigChanges\ConfigChanges.js:190:33)
    at C:\Users\d060445\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\prepare.js:112:32
    at _fulfilled (C:\Users\d060445\university\Team Project\Tracktivity\moveit\node_modules\q\q.js:854:54)
    at C:\Users\d060445\university\Team Project\Tracktivity\moveit\node_modules\q\q.js:883:30
```

________

I have already tried several times to remove the android platform and add it again to my project, but the issue still persists.

Version of cordova:
$ cordova -v
9.0.0 (cordova-lib@9.0.1)

## Checklist

- [ x] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment]
Can you provide the `cordova-android` platform version? You can find this out by running `cordova platform ls`

**Comment by josehector** [comment]
I have the similar issue but I am not using ionic.
When I try "cordova run android --verbose" I get this error:

```
BUILD SUCCESSFUL in 3s
41 actionable tasks: 41 up-to-date
The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:168:7)
    at fs.readdirSync.map.entry (C:\Dev\workspace\ITV\platforms\android\cordova\lib\builders\ProjectBuilder.js:79:31)
    at Array.map (<anonymous>)
    at recursivelyFindFiles (C:\Dev\workspace\ITV\platforms\android\cordova\lib\builders\ProjectBuilder.js:78:10)
    at findOutputFilesHelper (C:\Dev\workspace\ITV\platforms\android\cordova\lib\builders\ProjectBuilder.js:97:17)
    at ProjectBuilder.findOutputApks (C:\Dev\workspace\ITV\platforms\android\cordova\lib\builders\ProjectBuilder.js:365:16)
    at C:\Dev\workspace\ITV\platforms\android\cordova\lib\build.js:181:33
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
In my case, APK file is generated but it is not installed on the device.

Version of cordova:
$ cordova -v
9.0.0 (cordova-lib@9.0.1)

$ cordova platform ls
Installed platforms:
  android 9.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

**Comment by josehector** [comment]
I tried that fix and it didn't work.

**Comment by josehector** [comment]
I found the error. 
The problem is with Node version. 
this piece of code is where error occurs

```
function recursivelyFindFiles (dir, extension) {
    if (!fs.existsSync(dir) || !extension) return [];

    const files = fs.readdirSync(dir, { withFileTypes: true })
        .map(entry => {
            const item = path.resolve(dir, entry.name);

            if (entry.isDirectory()) return recursivelyFindFiles(item, extension);
            if (path.extname(entry.name) === `.${extension}`) return item;
            return false;
        });

    return Array.prototype.concat(...files)
        .filter(file => file !== false);
}
```
_withFileTypes_ parameter is only available in Node 10.10.0 version (https://nodejs.org/api/fs.html#fs_fs_readdirsync_path_options)
In my case I am using 10.4.0 Node version so this parameter is not available, and for that _entry_ is a string value (_entry.name_ is undefined).

Therefore, updating Node version to 10.10.0 we solve the problem.

I don't know if this Node version dependency is normal or not, but I didn't find which Node version dependency is needed with this plugin version.

**Comment by breautek** [comment]
I've tried reproducing several of these kind of issues and this may explain why I couldn't reproduce any of them. I've always tested using the latest version of a particular major...

Generally speaking we say we support Node 10+. But what I think we really mean is we support the latest patch of Node 10... because our test environments always use the latest patch of a major version. It's also always a good idea to use the latest patch available for security fixes.

In what file was `recursivelyFindFiles` located in? Perhaps we should update the `package.json` engines entry to reflect that >= `10.10.0` is required...

**Comment by josehector** [comment]
`recursivelyFindFiles` is located in `ProjectBuilder.js` (\platforms\android\cordova\lib\builders\ProjectBuilder.js), line 74.

I think it would be a good idea to reflect that required version in `package.json`
