### ISSUE TITLE
Unsupported API's from google play report

### ISSUE THREAD

**Issue by vignesh-balakrishnan** [apache/cordova-android#920]
The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK.

Kindly suggest me solution. Thanks in advance.

![google-report](https://user-images.githubusercontent.com/55088712/75317134-34577000-588d-11ea-8359-c31252d9e0ac.png)

**Comment by jcesarmobile** [comment]
See https://github.com/apache/cordova-android/issues/737
