### ISSUE TITLE
I developed an Android app using cordova, but there was a problem updating the app version.

### ISSUE THREAD

**Issue by chary2060** [apache/cordova-android#921]
I developed an Android app using cordova, but there was a problem updating the app version.The
 content of the www in the old app has been modified, and then I install the new app directly on the old 
app. I hope that the www of the APP should be the www in the new app, but the fact is that the www 
content  has not been replaced, it is still the content in the old 
version.I know that uninstalling and reloading will solve this problem, but can you solve it without 
uninstalling the older app? tks.

**Comment by breautek** [comment]
All APK assets are installed in a read-only application directory. They cannot be modified (outside of installing the apk).

If the APK has:
1. it's versionCode increased (cordova by default, creates a versionCode based on your app version)
2. the app id remains the same
3. the apk was signed using the same keystore

Then android will do an application upgrade (replacing the contents of the application directory with the assets in the new APK). If any of the above conditions fails, the upgrade will fail (or if the app id has changed, it will treat the apk has a new app).

Hope this answers your question. If it does not, I invite you to cordova's [slack](http://slack.cordova.io/), which is a more appropriate for support questions such as this one.
