### ISSUE TITLE
Cordova cannot find correct path to ANDROID_HOME

### ISSUE THREAD

**Issue by SamToorchi** [apache/cordova-android#922]
# Bug Report

## Problem
Cordova cannot find correct path to ANDROID_HOME

by tring to build I become this message:
```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=home/sam/Android/Sdk (recommended setting)
ANDROID_HOME=/usr/lib/android-sdk (DEPRECATED)
Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio
```

The problem is, that Cordova read always a wrong path to my ANDROID_HOME

the write path to my ANDROID_HOME after adding `echo $ANDROID_HOME` to console is: `home/sam/Android/Sdk`

I restarted my system and tried also `cordova platform remove android
` and after that with `cordova platform add android`, but it doesn't help.

**Comment by brodybits** [comment]
ANDROID_SDK_ROOT has precedence over ANDROID_HOME. I highly recommend that you set ANDROID_SDK_ROOT to the correct path and try again. To be extra safe, I would set both ANDROID_SDK_ROOT and ANDROID_HOME to the correct path and try again.

There is a known *cosmetic* issue with the console log output. I cannot promise when we will get this fixed.

In case of further troubles, I would highly recommend that you open a new terminal window, show both settings in that window, try build again, and show *all* output to help pinpoint the cause.

Note that I transferred this issue to cordova-android where I think it belongs.

**Comment by SamToorchi** [comment]
now I tried this paths and it worked.

```
export ANDROID_HOME=$HOME/Android/Sdk
export ANDROID_SDK_ROOT=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

Thank you for you help!
