### ISSUE TITLE
Debugging with Android Emulator and Chrome 80 

### ISSUE THREAD

**Issue by gonzalovinas** [apache/cordova-android#925]
Using Chrome latest version 80 or above devtools starts blank. It cannot be debugged. Should also be Android emulated Chrome be upgraded to 80?

**Comment by breautek** [comment]
Cordova doesn't control what version of chrome it uses. It simply just uses the android webview, which as of android 4.4, it happens to be chrome (on all devices that I know of).

Modern devices the webview can be updated independently, so the version of the chrome webview that is available really depends on whether the user decides to update their device. This is unfortunately something completely out of Cordova's control.

If there is truely a problem with chrome 80 unable to remote debug android webviews, I'd consider opening a bug ticket in the chromium project. 

Downgrading, an [archived chromium](https://www.chromium.org/getting-involved/download-chromium) version for using the devtools may also be a workaround in the meantime. See "Downloading old builds of Chrome/Chromium".
