### ISSUE TITLE
Android emulator does not work

### ISSUE THREAD

**Issue by Mehditeranee** [apache/cordova-android#926]
**Prerequisite**

 - Android SDK is well installed (directory : /Users/gamecube/Library/Android/sdk)

**How to reproduce :** 

 1. Run this command : `cordova build android`
 2. Run this command to launch android emulator : `cordova emulate android --verbose`

**Expected result**

The emulator is launched.

**Obtained result**

```
Command finished with error code 0: /Users/gamecube/Desktop/geocars/platforms/android/gradlew cdvBuildDebug,-b,/Users/gamecube/Desktop/geocars/platforms/android/build.gradle
Built the following apk(s): 
	/Users/gamecube/Desktop/geocars/platforms/android/app/build/outputs/apk/debug/app-debug.apk
No scripts found for hook "before_deploy".
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/Users/gamecube/Library/Android/sdk (DEPRECATED)
Running command: adb devices
Command finished with error code 0: adb devices
Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?
CordovaError: Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?
    at /Users/gamecube/Desktop/geocars/platforms/android/cordova/lib/emulator.js:176:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**My questions** 

*Why Android Emulator does not work?* 

and 

*Why is there this error? :* 

    CordovaError: Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?

**Comment by breautek** [comment]
Cordova tries to guess some directories, but perhaps the directories it tries is out-dated.

The quick work around is to update your `PATH` environment variable to include the directory of `avdmanager`

I'm not sure if it is the same on windows, but on my system `android` is located
`<android-sdk>/tools/`

And `avdmanager`...
`<android-sdk>tools/bin/`

Ensure those paths are in your path (and remember to restart your terminal) and that should get you by. I'll leave this ticket open though so that cordova can maybe be smarter when looking for these executables.

**Comment by Mehditeranee** [comment]
@breautek In my android-sdk folder (/<user>/Library/Android/sdk), I have these folders : 

`build-tools	extras		patcher		platforms	sources
emulator	licenses	platform-tools	skins		system-images`

There is not the `tools` folder to which you are referring.

**Comment by Mehditeranee** [comment]
I solved my problem.

**How did I do it?**

- I opened Android Studio, and went to the SDK Manager.

![image](https://user-images.githubusercontent.com/38721898/76468458-49cfac80-63ec-11ea-975b-fa133d5be778.png)

- I clicked on the SDK Tools tab, and in the list displayed, I checked: Android SDK Command-line Tools (latest)

![image](https://user-images.githubusercontent.com/38721898/76468468-518f5100-63ec-11ea-8370-0046553cc536.png)

- I then clicked on Apply (then OK on the pop-up) to download the package in question.

- I added the path of avdmanager to PATH in my .bash_profile as you explained @breautek 

- I have run `source ~ / .bash_profile` to refresh

- And I launched my command: `cordova emulate android --verbose` successfully since the emulator has opened well.

**Comment by breautek** [comment]
Interesting, Android SDK Command-line Tools appears to be new... I'll create a docs issue for this.

Since you've found your solution I'll close this issue but I'll link your comment in the docs issue.

**Comment by jamesjsewell** [comment]
https://user-images.githubusercontent.com/38721898/76468468-518f5100-63ec-11ea-8370-0046553cc536.png  when i was at this view, i had to click the "hide obsolete packages" checkbox, the i was able to see SDK Tools. I installed SDK tools which is obsolete. Now the /tools folder appears in my Sdk folder. This solved the issue of "CordovaError: Could not find either `android` or `avdmanager` on your $PATH! Are you sure the Android SDK is installed and available?" for me

**Comment by adhuliya** [comment]
Please update this in the cordova tutorial/docs as well. This is the only place, that I could find on the web, that has the correct solution. All other places assume android sdk folder to have `tools/` directory when that seems to be deprecated in recent releases. This will save hours of futile search.

**Comment by joaaogui** [comment]
In my case the avdmanager was in C:\Users\<user>\AppData\Local\Android\Sdk\cmdline-tools\latest\bin

**Comment by partharoy-digicert** [comment]
Thanks @Mehditerranee & @joaaogui , 

After combining both your steps it worked in MacOS Sequoia,

Here's what I followed,

- Installed the **Android SDK Command-line Tools** in Android Studio
- The _avdmanager_ is inside `Library/Android/sdk/cmdline-tools/latest/bin`, accordingly I updated my `.zshrc` file,

```
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/build-tools
```

One important thing is you must have `JAVA_HOME` configured as well, I used sdkman for that,

```
# Show the list of jdks available
sdk list java 

# Install the specific JDK
 sdk install java 17.0.14-jbr

```

Then updated the `.zshrc` file with,
`export JAVA_HOME=$HOME/.sdkman/candidates/java/17.0.14-jbr/`

_For posterity.._
