### ISSUE TITLE
[bug] resource integer/google_play_services_version not found

### ISSUE THREAD

**Issue by indraraj26** [apache/cordova-android#927]
# Bug Report

### What is expected to happen?
I should able to build apk

### What does actually happen?
It is crashing with below error. It was working fine 1 week ago i have changed nothing in source file.
```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
 D:\project\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:107: AAPT: error: resource integer/google_play_services_version (aka com.project.projectName:integer/google_play_services_version) not found.
```

### Command or Code

ionic cordova build android

### Version information

```
ionic info

Ionic:

   Ionic CLI          : 5.4.4 (C:\Users\HP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 25 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   Android SDK Tools : 26.1.1 (C:\Users\HP\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.10.2
   OS                : Windows 10
```

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
I don't believe this is related to `cordova-android`. I think this is caused a plugin that depends on google play services.

Can you provide the full list of your plugins?

**Comment by indraraj26** [comment]
Thank you @breautek, It resolved by making an build in android studio.
closing as this is not related to cordova android
