### ISSUE TITLE
Pressing back button leads to "Webpage not available" error page

### ISSUE THREAD

**Issue by IustinMicu** [apache/cordova-android#931]
# Bug Report

## Problem

Pressing native back button on android leads to "Webpage not available" error page

### What is expected to happen?

I expect the back button to either close the application, or to redirect the user to the last visited url, which means opening the in-app browser and load the login page.

### What does actually happen?

The Webpage not available error page is displayed, with this message:
"The webpage at **file:///android_asset/www/#/dashboard** could not be loaded because: net::ERR_INVALID_RESPONSE"

## Information

I have an Angular application wrapped in cordova.
I use the cordova-plugin-safariviewcontroller plugin to open an in-app browser and navigate to an external login page.
After finishing the login process, I use the cordova-plugin-customurlscheme plugin to close the in-app browser and return back to the application (on a landingpage route, which loads a certain Angular component).
The problem occurs when I am on this landingpage and I press the native back button.

### Environment, Platform, Device

android 8 and android 9

### Version information

cordova: 9.0.0
cordova-android: 8.1.0
cordova-ios: 5.1.1
cordova-plugin-customurlscheme: 4.4.0
cordova-plugin-safariviewcontroller: 1.6.0
cordova-plugin-whitelist: 1.3.4

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
This isn't a bug. This would be a misconfiguration on the app. `file:///android_asset/www/#/dashboard` is not a valid URL. Maybe you meant `file:///android_asset/www/index.html#/dashboard`? 

URLs should always point to an index file. Do note that there is no webserver here to automatically serve out a default index file when accessing the directory.

If you require further assistance, I'd invite you to join our [slack](http://slack.cordova.io/), which is a more appropriate place for support.

**Comment by IustinMicu** [comment]
I know that's not a valid url.
The valid url in my case is `file:///android_asset/www/index.cordova.html/#/dashboard` and works fine when I navigate through the application, even when I press the native back button.
The issue is with the flow described above (returning from the in-app browser and then press the back button), when the native back button wants to access that invalid url (that doesn't contain the "index.cordova.html" part in the path).
I haven't configured anything related to the navigation history or the target of the back button, that's why I think this is a cordova issue.

**Comment by mohamedHassanKa** [comment]
i just had this problem recently did u find any solution for it

**Comment by BagpipesJohnson** [comment]
@breautek the link to join slack is broken. I am also having the same issue. For us, it's when you leave the app and watch a youtube video and then hit the native back button. I don't understand this could be a misconfiguration of the app...there was never any opportunity to decide what happens when the back button is used outside of our app.
