### ISSUE TITLE
`cordova build android` destroy jks and p12 keystore files

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-android#934]
Hallo guys, I have strange bug in my build process...

what I do:
1. create *.jks file
1. convert *.jks file into *.p12 by using same password
1. build app.. sometimes doesn't matter which version debug or release...
    ```
    cordova build android --buildConfig "<config_path>" --debug
    # or
    cordova build android --buildConfig "<config_path>" --release
    ```
1. then the build is failed with error: 
    ```
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:packageDebug'.
    > Failed to read key myapp-debug from store "../myapp-debug-key.p12": keystore password was incorrect 
    ```

Then I try to check my keystore file
```bash
$ keytool -list -v -keystore myapp-debug-key.p12
```
and got an error:
```
java.io.IOException: keystore password was incorrect
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
```

then I try to check *.p12 file with "KeyStore Explorer" App... same error...

how can it be possible?

*.jks and *.p12 files was generated with my script and additionally I saved generated passwords into file. Before I did `cordova build android` I added this files in GIT... After cordova destroyed this files GIT doesn't show any changes in this files...

----

PS: maybe this can help more:

**buildConfig.json**:
```
{
    "android": {
        "debug": {
            "keystore": "myapp-debug-key.p12",
            "storePassword": "bbbbb",
            "alias": "myapp-debug",
            "password": "",
            "keystoreType": "pkcs12"
        },
        "release": {
            "keystore": "myapp-release-key.p12",
            "storePassword": "aaaaaaa",
            "alias": "myapp-release",
            "password": "",
            "keystoreType": "pkcs12"
        }
    }
}
```

I try to use storePassword in password, but this doesn't helped me...

Anyone has the same problem? Or maybe can give me some tips, what I do wrong?

----

maybe related to 
- https://github.com/apache/cordova-android/issues/761
- https://stackoverflow.com/questions/13535424/android-keystore-stopped-working

**Comment by breautek** [comment]
> keytool -list -v -keystore myapp-debug-key.p12

If you're using a `p12` file, you should also add the `-storetype PKCS12` flag.

https://stackoverflow.com/questions/14375185/how-to-create-a-certificate-into-a-pkcs12-keystore-with-keytool might be relevant.

**Comment by WuglyakBolgoink** [comment]
Hallo @breautek!

I use my script to generate certificates:
https://gist.github.com/WuglyakBolgoink/e10533849dc2e8fb50596c1da3f8142c

and `PKCS12` was already used  https://gist.github.com/WuglyakBolgoink/e10533849dc2e8fb50596c1da3f8142c#file-generate_android_signing_certificate-js-L189

**Comment by breautek** [comment]
Cordova doesn't delete files except for potentially files inside `plugins/` or `platforms/`. 

Closing as this doesn't appear to be a bug with cordova-android.
