### ISSUE TITLE
Tests are broken on NodeJS 12.16.0+

### ISSUE THREAD

**Issue by breautek** [apache/cordova-android#938]
Tests that try to `rewire` any module with a shebang declaration are broken starting NodeJS 12.16.0.

The issue is being tracked at https://github.com/jhnns/rewire/issues/178
I've created a PR for rewire at https://github.com/jhnns/rewire/pull/179

This ticket is for us to keep track if/when rewire is updated or maybe to discuss alternative solutions, depending how long it will take for rewire to update. Their last update was 20 days ago, so could be some hope available.

**Comment by timbru31** [comment]
/cc @erisu - we've had this discussion yesterday on Slack.
The underlying bug is IMO https://github.com/nodejs/modules/issues/464

**Comment by breautek** [comment]
I acknowledge that the issue should be really fixed at the NodeJS level. The PR is just a quick workaround for the time being.

In https://github.com/jhnns/rewire/issues/178 they reference https://github.com/nodejs/node/commit/bcd27f7300 & https://github.com/nodejs/node/commit/1c50714729

I don't think moving away from `rewire` is a realistic approach as our repos are quite heavily invested in rewire. Without rewire a lot of code I think will need to be rewritten and exposed in a way so that the unit tests can have access to attach spies and such. It would be considerable amount of work to do, especially to maintain the same level of unit testing that we have.

If it takes a long time to see a fix from either NodeJS, or have my PR merged into rewire, would using my [fork](https://github.com/breautek/rewire/tree/shebang-fix) be acceptable?
