### ISSUE TITLE
adaptive icons broken

### ISSUE THREAD

**Issue by whyameye** [apache/cordova-android#942]
# Bug Report

## Problem
adaptive icons as explained in the docs prevent compilation

### What is expected to happen?
a successful build

### What does actually happen?
when using `foreground` and `background` as explained in the docs:
https://cordova.apache.org/docs/en/latest/config_ref/images.html#android
I get:
```ENOENT: no such file or directory, open '/platforms/android/app/src/main/res/mipmap-port-hdpi-v26/ic_launcher.xml'```

### Command or Code

```
<platform name="android">
  <icon background="res/icon/android/ldpi-background.png" density="ldpi" foreground="res/icon/android/ldpi-foreground.png" />
  <icon background="res/icon/android/mdpi-background.png" density="mdpi" foreground="res/icon/android/mdpi-foreground.png" />
  <icon background="res/icon/android/hdpi-background.png" density="hdpi" foreground="res/icon/android/hdpi-foreground.png" />
  <icon background="res/icon/android/xhdpi-background.png" density="xhdpi" foreground="res/icon/android/xhdpi-foreground.png" />
  <icon background="res/icon/android/xxhdpi-background.png" density="xxhdpi" foreground="res/icon/android/xxhdpi-foreground.png" />
  <icon background="res/icon/android/xxxhdpi-background.png" density="xxxhdpi" foreground="res/icon/android/xxxhdpi-foreground.png" />
</platform>
```

### Environment, Platform, Device
Linux x64 (kubuntu 18.04)
Cordova 9.0.0 (Cordova lib 9.0.1)

### Version information

Cordova 9.0.0 (Cordova lib 9.0.1)

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
I'm unable to reproduce this.

Here's what I did:
I create a new cordova project, pasted your config inside the `config.xml` file. I grabbed some random icon pngs from another app of mine and pasted them into the proper directory and renaming them so the filenames match. Finally, then I ran `cordova build android`, which produced a successful build (no errors)

Here is my environment

Cordova:
```
cordova -v
9.0.0 (cordova-lib@9.0.1)

cordova platform list
Installed platforms:
  android 8.1.0
```

Android SDK

```
Android SDK Platform 28 (Android 9.0)
Android SDK Build-Tools 29.0.2
Android SDK Platform-Tools 29.0.6
Android SDK Tools 26.1.1
```

Are you able to provide a [minimal reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md)?

**Comment by jptrainor** [comment]
I experienced this error. It was a simple matter of an incorrect filename (one of the foreground or background images did not exist). In my case I included the 'src' attribute and that file did not exist. Perhaps an improved error message would help.

**Comment by EmilJunker** [comment]
Here's the config.xml:


When I run `cordova prepare android`, I get:
```
ENOENT: no such file or directory, open '/waistline/app/platforms/android/app/src/main/res/mipmap-ldpi-v26/ic_launcher.xml'
```

If I change the setup in `config.xml` to:
```xml
<icon density="ldpi" background="res/icon/android/ldpi-background.png" foreground="res/icon/android/ldpi-foreground.png" src="res/android/ldpi.png" />
<icon density="mdpi" background="res/icon/android/mdpi-background.png" foreground="res/icon/android/mdpi-foreground.png" src="res/android/mdpi.png" />
<icon density="hdpi" background="res/icon/android/hdpi-background.png" foreground="res/icon/android/hdpi-foreground.png" src="res/android/hdpi.png" />
<icon density="xhdpi" background="res/icon/android/xhdpi-background.png" foreground="res/icon/android/xhdpi-foreground.png" src="res/android/xhdpi.png" />
<icon density="xxhdpi" background="res/icon/android/xxhdpi-background.png" foreground="res/icon/android/xxhdpi-foreground.png" src="res/android/xxhdpi.png" />
<icon density="xxxhdpi" background="res/icon/android/xxxhdpi-background.png" foreground="res/icon/android/xxxhdpi-foreground.png" src="res/android/xxxhdpi.png" />
```

**Comment by EmilJunker** [comment]
I'm running into the same problem with a Cordova project I'm working on.

You can find the source code here: https://github.com/EmilJunker/waistline/tree/android-icons (on branch `android-icons`). You should be able to reproduce it with this code.

Note that this isn't my app, I'm just contributing to it.

This is the setup in `config.xml`:
```xml
<icon density="ldpi" background="res/icon/android/ldpi-background.png" foreground="res/icon/android/ldpi-foreground.png" src="res/android/ldpi.png" />
<icon density="mdpi" background="res/icon/android/mdpi-background.png" foreground="res/icon/android/mdpi-foreground.png" src="res/android/mdpi.png" />
<icon density="hdpi" background="res/icon/android/hdpi-background.png" foreground="res/icon/android/hdpi-foreground.png" src="res/android/hdpi.png" />
<icon density="xhdpi" background="res/icon/android/xhdpi-background.png" foreground="res/icon/android/xhdpi-foreground.png" src="res/android/xhdpi.png" />
<icon density="xxhdpi" background="res/icon/android/xxhdpi-background.png" foreground="res/icon/android/xxhdpi-foreground.png" src="res/android/xxhdpi.png" />
<icon density="xxxhdpi" background="res/icon/android/xxxhdpi-background.png" foreground="res/icon/android/xxxhdpi-foreground.png" src="res/android/xxxhdpi.png" />
```

When I run `cordova prepare android`, I get this error:
```
ENOENT: no such file or directory, open '/waistline/app/platforms/android/app/src/main/res/mipmap-ldpi-v26/ic_launcher.xml'
```

If I change the setup in `config.xml` to ...
```xml
<icon density="ldpi" src="res/android/ldpi.png" />
<icon density="mdpi" src="res/android/mdpi.png" />
<icon density="hdpi" src="res/android/hdpi.png" />
<icon density="xhdpi" src="res/android/xhdpi.png" />
<icon density="xxhdpi" src="res/android/xxhdpi.png" />
<icon density="xxxhdpi" src="res/android/xxxhdpi.png" />
```
i.e. remove the `background` and `foreground` attributes then I don't get the error. So it must have something to do with the adaptive icons.

**Comment by EmilJunker** [comment]
I was able to fix the issue by upgrading to the latest Android SDK. Apparently, this is required for the adaptive icons to work.

> Perhaps an improved error message would help.

Yes, indeed!
