### ISSUE TITLE
ANDROID_HOME is deprecated

### ISSUE THREAD

**Issue by zdm** [apache/cordova-android#949]
# Feature Request

## Motivation Behind Feature
Keep environment clean

## Feature Description
ANDROID_HOME is deprecated and replaced with ANDROID_SDK_ROOT by android SDK.
It would be nice, if cordova also support ANDROID_SDK_ROOT variable to make it consistent with the SDK.

**Comment by zdm** [comment]
https://developer.android.com/studio/command-line/variables

**Comment by breautek** [comment]
cordova-android does support `ANDROID_SDK_ROOT`, however if you have `ANDROID_HOME` also defined, I think it current takes precedence... not 100% sure. If that is the case though, I think `ANDROID_SDK_ROOT` should be the dominant environment variable, falling back to the deprecated variable.

**Comment by zdm** [comment]
I am unable to build on android platform if ANDROID_SDK_ROOT is set but ANDROID_HOME is NOT set.
```
d:\gdrive\projects\workspace\smartcnc-app>cordova build android
Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
Detected 'avdmanager' command at d:\devel\android\cmdline-tools\latest\bin but no 'tools\bin' directory found near.
Try reinstall Android SDK or update your PATH to include valid path to SDK\tools\bin directory.

```

**Comment by breautek** [comment]
I've actually reproduced this as well... the tooling prints out that `ANDROID_SDK_ROOT` is recommended but it definitely does not use it properly.. even on `9.0.0-dev`.

**Comment by fortuna** [comment]
As of April 27, 2022, the page at https://developer.android.com/studio/command-line/variables says:

> ANDROID_HOME: Sets the path to the SDK installation directory. Once set, the value does not typically change, and can be shared by multiple users on the same machine. ANDROID_SDK_ROOT, which also points to the SDK installation directory, is deprecated. If you continue to use it, Android Studio and the Android Gradle plugin will check that the old and new variables are consistent.

So Cordova is saying the opposite of what the Android team is saying.

**Comment by breautek** [comment]
> As of April 27, 2022, the page at https://developer.android.com/studio/command-line/variables says:
> 
> > ANDROID_HOME: Sets the path to the SDK installation directory. Once set, the value does not typically change, and can be shared by multiple users on the same machine. ANDROID_SDK_ROOT, which also points to the SDK installation directory, is deprecated. If you continue to use it, Android Studio and the Android Gradle plugin will check that the old and new variables are consistent.
> 
> So Cordova is saying the opposite of what the Android team is saying.

You can open a new issue for this.

For context, Google can't seem to make up their mind. e.g: back in 2018 https://web.archive.org/web/20181121202227/https://developer.android.com/studio/command-line/variables

> Sets the path to the SDK installation directory. Once set, the value does not typically change, and can be shared by multiple users on the same machine. ANDROID_HOME, which also points to the SDK installation directory, is deprecated. 

![Screenshot from 2022-04-27 17-04-21](https://user-images.githubusercontent.com/11200662/165621907-8b17c67c-505a-4cfb-a086-da14b5aa413c.png)
