### ISSUE TITLE
Update to shelljs@0.6.1

### ISSUE THREAD

**Issue by wzijden** [apache/cordova-android#952]
# Feature Request

## Motivation Behind Feature

I'm an SDE at Amazon and we are building a Cordova Android app. Right now our build is failing because shelljs@0.5.3 is blacklisted in our internal build system.

## Feature Description

I realize shelljs was already removed from the 9.0 version, but while this is not released, can we migrate to shelljs@0.6.1, which is the maintenance version of shelljs?

When updating this locally, `npm test` fails on the following:
```
  android project handler

    installation

      of <lib-file> elements
        ✓ Test#001 : should copy files for Android Studio projects (0.001 sec)

      of <resource-file> elements
        ✓ Test#002 : should copy files to the correct location on an Android Studio project (0.001 sec)

shell.js: internal error
Error: ENOENT: no such file or directory, stat '<project-dir>/spec/fixtures/android_studio_project/*'
    at Object.statSync (fs.js:915:3)
    at <project-dir>/node_modules/shelljs/src/cp.js:148:21
```

## Alternatives or Workarounds

Wait until version 9? Do we know when it will be released?

**Comment by timbru31** [comment]
We are working hard on the next major platform releases and they should be ready soonish. I doubt we will do a patch/minor release just for the shelljs bump because the master already removed shelljs.
