### ISSUE TITLE
Android detectArchitecture timeout is too short

### ISSUE THREAD

**Issue by GimpArm** [apache/cordova-android#963]
# Bug Report

### What is expected to happen?

Android debugging to connect

### What does actually happen?

Android debugging fails to connect

## Information

The timeout for detechArchitecture() is sometimes too low when devices are on wifi network connections and even sometimes over USB. The command can take up to 3 seconds to execute and return. Currently the timeout is set to 1000 ms and setting it to 5000 ms seems to be a good compromise.

[/bin/templates/cordova/lib/build.js line213](https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/build.js#L213)

`Command finished with error code 0: adb devices
Running adb shell command "cat /proc/cpuinfo" on target ce071827f219c13701...

Command finished with error code ENOENT: killall adb
Device communication timed out. Try unplugging & replugging the device.
CordovaError: Device communication timed out. Try unplugging & replugging the device.
    at Object.module.exports.detectArchitecture (D:\workspace\Git\store-logistics-app\build-tmp\cordova\cordova\platforms\android\cordova\lib\build.js:209:35)
    at D:\workspace\Git\store-logistics-app\build-tmp\cordova\cordova\platforms\android\cordova\lib\device.js:64:22
    at _fulfilled (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:854:54)
    at D:\workspace\Git\store-logistics-app\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:816:13)
    at D:\workspace\Git\store-logistics-app\node_modules\q\q.js:624:44
    at runSingle (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:137:13)
    at flush (D:\workspace\Git\store-logistics-app\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Command finished with error code 0: adb -s,ce071827f219c13701,shell,cat,/proc/cpuinfo
'cordova.cmd run android --device --verbose --no-update-notifier' failed with exit code 1`

### Command or Code

`cordova.cmd run android --device --verbose --no-update-notifier`

### Environment, Platform, Device

Windows 10 building Android

### Version information

VS Code: 1.44.2
Cordova: 9.0.0
Cordova-Android: 8.1.0

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by tbl0605** [comment]
I have exactly same problem, patch #965 solves it, thank you! :)
Hopefully it will be merged...

**Comment by breautek** [comment]
Closing as the PR for this issue has been merged.
