### ISSUE TITLE
Ionic 5 cordova android chrome debug console not removed in release 

### ISSUE THREAD

**Issue by iot-dev01** [apache/cordova-android#968]
# Bug Report

## Problem
After a android cordova release build and signing the chrome debugger console is not removed like expected.

### What is expected to happen?
Like the docs say the chrome debugging console should not appear in the release build.

### What does actually happen?
Chrome web debug console appear in release build.

### Command or Code

create the ionic sample tabs app -> build in release and sign -> install on a device
`ionic cordova build android --prod --release` - for build
`jarsigner` - for signing

### Environment, Platform, Device

Windows 10 Device for build
Android 5.1 Tablet
Android 8 Tablet

### Version information

```
Ionic:
   Ionic CLI                     : 5.4.9
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 4 other plugins)
Utility:
   cordova-res : 0.9.0
   native-run  : 0.2.8 (update available: 0.3.0)
System:
   NodeJS : v10.16.0 
   npm    : 6.9.0
   OS     : Windows 10
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
Is this reproducible with a basic cordova app without frameworks like Ionic?

**Comment by iot-dev01** [comment]
Thanks for the fast reply.
Yes its reproducible with the follwing steps:

1. run `cordova create MyApp`
2. run `cd MyApp`
3. run `cordova platform add android`
4. run `cordova build --prod --release`
5. run `jarsigner` command

**Comment by breautek** [comment]
That does not reproduce the issue for me.

I've tried:
- cordova-android@8.1
- with & without cordova-plugin-ionic-webview
- signing apk manually via jarsigner
- Letting cordova sign app automatically via `build.json`

None of which allowed me to connect to the web inspector while the released version was installed. For reassurance, I've confirmed that the web inspector did work when a debug variant of the apk was installed.

**Comment by iot-dev01** [comment]
@breautek  Thanks for the response
Can you maybe provide your sample build.json?
I will try to make a full clean setup on a new machine to make clear that my system is not the problem

**Comment by breautek** [comment]
```json
{
        "android": {
                "debug": {
                        "keystore": "./tp.keystore",
                        "storePassword": "<password>",
                        "alias": "<alias>",
                        "password": "<passphrase>"
                },
                "release": {
                        "keystore": "./tp.keystore",
                        "storePassword": "<password>",
                        "alias": "<alias>",
                        "password": "<passphrase>"
                }
        }
}
```

If you don't like storing passwords in text fields, you can omit them and use the CLI arguments to supply them, as shown in the [docs](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#using-flags)

**Comment by breautek** [comment]
I'm not sure if windows have any equivalent to `grep`, I'll let that be an exercise for you, but you can also use the `aapt` tool to quickly determine if the debuggable flag is set. You'll find it's executable in the android sdk (eg: `Android/Sdk/build-tools/29.0.2/aapt`).

`aapt l -a app-debug.apk | grep debuggable`

If the ouput is `A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff`. The apk is debuggable, (which means the web inspector is enabled, cause cordova uses this flag to decide to enable the inspector).

If output shows `A: android:debuggable(0x0101000f)=(type 0x12)0x0` OR shows no output (which means the flag is not explicitly set, and `debuggable` will default to `false`), then the apk is not debuggable and you won't be able to open the chrome dev tools.

**Comment by AndrWeisR** [comment]
I have built an Ionic 5 prod release APK with cordova-android nightly (9.0.0-nightly.2020.5.28.a830145f), and I too am seeing debug output in Chrome dev tools, and also in Android Studio. I listed the APK as above and I see no "debuggable" at all.

**Comment by breautek** [comment]
> I have built an Ionic 5 prod release APK with cordova-android nightly (9.0.0-nightly.2020.5.28.a830145f), and I too am seeing debug output in Chrome dev tools, and also in Android Studio. I listed the APK as above and I see no "debuggable" at all.

This leads me to believe this is an issue with Ionic, not Cordova. Cordova does not enable the webview dev tools unless if the `debuggable` flag is set. If you see no debuggable, this means it's not set and it is defaulting to false.

Please let me know if you can reproduce this in raw vanilla cordova project (no frameworks such as Ionic). If you can please let me know of the steps you took and details about your environment as I failed to reproduce this before.

**Comment by LHLK** [comment]
Google just release a new Android System WebView version 85.0.4183.83. chrome://inspect/#devices show the device but you can no longer target any HTML element using this method, ie you can target any HTML tags inside the console.

**Comment by breautek** [comment]
> Google just release a new Android System WebView version 85.0.4183.83. chrome://inspect/#devices shows the device OK, but you can no longer target any HTML elements using this method, ie you cannot target or hightlight any HTML tags (device view) inside the console.

This is unrelated to this issue, which describes that the web inspector is still being accessible in a release build. The issue you're describing sounds like a web inspector issue and should be reported to Google.

**Comment by LHLK** [comment]
Oh, I see and thanks.Louie
    Norman Breau (<notifications@github.com>) 在 2020年8月31日星期一 下午09:46:20 [GMT+8] 寫道：  
 
 



Google just release a new Android System WebView version 85.0.4183.83. chrome://inspect/#devices shows the device OK, but you can no longer target any HTML elements using this method, ie you cannot target or hightlight any HTML tags (device view) inside the console.


This is unrelated to this issue, which describes that the web inspector is still being accessible in a release build. The issue you're describing sounds like a web inspector issue and should be reported to Google.

**Comment by breautek** [comment]
Closing as stale.
