### ISSUE TITLE
After language change , App pause to resume splash screen is not showing and white screen is showing.

### ISSUE THREAD

**Issue by rajiramamoorthi** [apache/cordova-android#977]
1. Cordova app is working fine and showing splash screen when kill and open in android device
2. After language change , App pause mode to resume splash screen is not showing and white screen is showing.

**My Build Details**
Ionic:

   Ionic CLI                     : 6.1.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.1.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/apple/Library/Android/sdk)
   ios-sim           : 8.0.2
   NodeJS            : v12.16.0 (/usr/local/bin/node)
   npm               : 6.13.7
   OS                : macOS Catalina
   Xcode             : Xcode 10.3 Build version 10G8

**Plugin list**
cordova-plugin-advanced-http 2.4.0 "Advanced HTTP plugin"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-dbcopy 2.1.2 "sqlDB"
cordova-plugin-decimal-keyboard 1.0.0 "Decimal Keyboard"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-plugin-youtube-video-player 2.4.0 "CordovaYoutubeVideoPlayer"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

**Comment by aam-antonio** [comment]
Hi, I was having the same issue.

I updated `cordova-plugin-x-socialsharing` to the lastest version (6.0.0) and then it worked.

**Comment by rajiramamoorthi** [comment]
Any update on this white screen issue?

**Comment by timbru31** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by jcesarmobile** [comment]
closing since there was no response and it's not possible to reproduce with the provided information
