### ISSUE TITLE
Ionic 5 function "handleOpenForRead" not being called

### ISSUE THREAD

**Issue by mjacques-notur** [apache/cordova-android#980]
# Bug Report
After overriding the function on a plugin it is not being called.
This happens on ionic 5 with webview 4.1.3
## Problem
The first line of the override should be seen on logcat
### What is expected to happen?
Logcat should show feedback of the executed function

### What does actually happen?
The function "handleOpenForRead" is not being executed

## Information

the problem is with the plugin integration of webview 4.1.3 and crypto-file

### Command or Code

@Override
  public CordovaResourceApi.OpenForReadResult handleOpenForRead(Uri uri) throws IOException {
    CordovaResourceApi.OpenForReadResult  res = super.handleOpenForRead(uri);
    LOG.d(TAG, "decrypt: " + uri);
    return res;
}

### Environment, Platform, Device

Android from api 22 and above, haven't tested lower versions

### Version information

  cordova platform: android 8.1.0
  plugins: webview 4.1.3, crypto-file
  

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x} I included all the necessary information above

**Comment by breautek** [comment]
Are you able to paste a sample uri that you're receiving when expecting for it to be invoked?

It should look something like `cdvplugin://pluginId/` for the `CordovaPlugin.handleOpenForRead` to be invoked.

See https://github.com/apache/cordova-android/blob/a830145f36c8bba2ecdf7910f3699116d4c2f018/framework/src/org/apache/cordova/CordovaResourceApi.java#L298-L304

If it's not being invoked, and you're not seeing `Invalid plugin ID in URI`, then it's probably not in the proper uri scheme and it's being handled by another case block.

**Comment by mjacques-notur** [comment]
The uri is "localhost/index.html" so that is probably the case, despite  "public Uri remapUri(Uri uri)" being overriden.
I tried the same plugins on another app that has no plugins and it has the same issue, also "handleOpenForRead" works with webview 1.x

**Comment by timbru31** [comment]
Could you also specify „webview“? If you mean cordova-plugin-ionic-webview then unfortunately we can’t help with that as it’s not maintained by Apache.

**Comment by mjacques-notur** [comment]
The uri is "localhost/index.html" so that is probably the case, despite  "public Uri remapUri(Uri uri)" being overriden.
I tried the same plugins on another app that has no plugins and it has the same issue, also "handleOpenForRead" works with webview 1.x
