### ISSUE TITLE
Cordova net::ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by nevstas** [apache/cordova-android#991]
Try load external website (google.com) in Cordova.

My config.xml:

```
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.test" version="1.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Invest 2020</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="https://google.com" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="*" />
    <preference name="loadUrlTimeoutValue" value="99999999" />
    <platform name="android">

    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <icon src="www/img/icon.png" />
</widget>
```

I get an error when trying to run app:

net::ERR_INVALID_RESPONSE

![n9eYdw55TeU](https://user-images.githubusercontent.com/22144214/84137604-9c554f00-aa55-11ea-97ae-923a34e84364.jpg)

### Version information
Cordova version 9.0.0
Cordova Platform android version 8.1.0
Windows 10, Xiaomi Redmi 4

**Comment by breautek** [comment]
`ERR_INVALID_RESPONSE` means the client (the webview) received something that it doesn't understand or know how to handle.

I don't believe this is a bug with Cordova.

**Comment by nevstas** [comment]
I found a solution:
`cordova platform rm android
cordova platform add android
`

**Comment by breautek** [comment]
Happy to hear that re-adding the platform appears to resolve it for you. Perhaps there was a hiccup and something didn't install right the first time.

Because there is no real evidence suggesting a bug I'll be closing this issue. If the issue comes back, don't hesitate to open a new issue with the issue form filled out. :grinning:

**Comment by meablelee2013** [comment]
I needed to add a few lines of code to the config.xml - these are...

 

<access origin="*"/>

<allow-intent href="http://*/*"/>

<allow-intent href="https://*/*"/>

<allow-intent href="tel:*"/>

<allow-intent href="sms:*"/>

<allow-intent href="mailto:*"/>

<allow-intent href="geo:*"/>

 

and 

<plugin name="cordova-plugin-whitelist" spec="1.2.0"/>

OR 
add this to your config.xml

  <feature name="Whitelist">
        <param
            name="android-package"
            value="org.apache.cordova.whitelist.WhitelistPlugin" />
    </feature>
